### ISSUE TITLE
[Issue]: CUDA out of memory.

### ISSUE THREAD

**Issue by sonicjhon1** [vladmandic/automatic#1354]
### Issue Description

The error: `CUDA out of memory. Tried to allocate 6.12 GiB (GPU 0; 6.00 GiB total capacity; 635.39 MiB already allocated; 4.27 GiB free; 698.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

I am able to use it just fine on 6th June (on the latest version avaliable that on that date), but today (8th June, on the latest version) I keep on getting CUDA OOM errors (when reaching Highres Fix) with the same settings used:
![image](https://github.com/vladmandic/automatic/assets/41381685/ebd2af2d-f87b-450d-ba1a-77bc9bd36e88)

When I set the **Upscale By** to 1.5x it kinda works and fully generated the image without OOM, although the System Info extensions reports that it keeps on retrying (rapidly incrementing):
![image](https://github.com/vladmandic/automatic/assets/41381685/5d82cb38-58b3-46ee-b77a-cfcfc59dab43)

I've tried:
- Changing `--medvram` to `--lowvram`. Nothing changes, OOM.
- Adding `--safe`, nothing changes, OOM.

Normally I could easily upscale to 2x achieving from 896x1024 to 1792x2048.

### Version Platform Description

- Server arguments: `['--medvram', '--upgrade', '--listen', '--experimental', '--insecure',
                         '--allow-code', '--ckpt',
                         'models\\Stable-diffusion\\Counterfeit-V2.5\\Counterfeit-V2.5_fp16.safetensors', '--safe']`
- Python 3.10.11 on Windows
- Version: 276fb6a0 Wed Jun 7 17:45:39 2023 -0400
- Torch 2.0.0+cu118
- Torch backend: nVidia CUDA 11.8 cuDNN 8700
- Torch detected GPU: NVIDIA GeForce RTX 3060 Laptop GPU VRAM 6144 Arch (8, 6) Cores 30
- Enabled extensions-builtin: `['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']`
- Game Ready Driver: 532.03
- Browser: Firefox 115.0b2

**Comment by sonicjhon1** [comment]
Nvm, restarted the computer and it worked again. 🗿

**Comment by PeggyFree** [comment]
> Nvm, restarted the computer and it worked again. 🗿

Thank you for your feedback. I spent hours trying to find the cause of my OOM after a fresh install, a reboot did the trick.
