### ISSUE TITLE
[Issue][Intel/Arc]: Unable to generate image

### ISSUE THREAD

**Issue by juzi5201314** [vladmandic/automatic#1526]
### Issue Description

`Exception: Native API failed. Native API returns: -5 (PI_ERROR_OUT_OF_RESOURCES) -5
                         (PI_ERROR_OUT_OF_RESOURCES)`

and i get `Time taken: 8.29s | GPU active 7420 MB reserved 7618 MB | System peak 7363 MB total 6477 MB`.

Looks like video memory is full, but before starting, the video memory usage is 0.3/8GB, the picture size is 100x100, the sampling method is DPM++ 2M Karras, and the batch size is 1. This shouldn't take up so much video memory at all.

### Version Platform Description

on wsl2

```
$ free -h
               total        used        free      shared  buff/cache   available
Mem:            23Gi       616Mi       8.6Gi       3.0Mi        14Gi        22Gi
Swap:          6.0Gi          0B       6.0Gi
```

```23:00:09-696796 INFO     Torch backend: Intel IPEX 1.13.120+xpu
23:00:09-832735 INFO     Intel(R) oneAPI DPC++/C++ Compiler 2023.1.0 (2023.1.0.20230320)
                         Target: x86_64-unknown-linux-gnu
                         Thread model: posix
                         InstalledDir: /opt/intel/oneapi/compiler/2023.1.0/linux/bin-llvm
                         Configuration file: /opt/intel/oneapi/compiler/2023.1.0/linux/bin-llvm/../bin/icpx.cfg
23:00:09-836116 INFO     Torch detected GPU: Intel(R) Graphics [0x56a1] VRAM 6477 Compute Units 448
23:00:09-846125 INFO     Disabled extensions-builtin: ['a1111-sd-webui-lycoris']
23:00:09-846776 INFO     Enabled extensions-builtin: ['sd-dynamic-thresholding',
                         'stable-diffusion-webui-images-browser', 'sd-webui-agent-scheduler',
                         'sd-extension-system-info', 'stable-diffusion-webui-rembg', 'ScuNET',
                         'multidiffusion-upscaler-for-automatic1111', 'Lora', 'clip-interrogator-ext', 'SwinIR',
                         'sd-webui-controlnet', 'LDSR']
23:00:09-848008 INFO     Disabled extensions: ['a1111-sd-webui-lycoris']
23:00:09-848596 INFO     Enabled extensions: []
23:00:09-849392 INFO     No changes detected: Quick launch active
23:00:09-851012 INFO     Extension preload: 0.0s /home/soeur/automatic/extensions-builtin
23:00:09-851645 INFO     Extension preload: 0.0s /home/soeur/automatic/extensions
23:00:09-852756 INFO     Server arguments: ['--use-ipex']```

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
100x100? can you try with default 512x512.
and run with `--debug` flag, it will show memory stats in console.
looping in @Disty0

**Comment by juzi5201314** [comment]
I tried to use `--medvram`, it can display preview images during operation, but still the same error occurs at 100%。
```
100%|███████████████████████████████████████████████████████████████████████████████████| 20/20 [00:27<00:00,  1.39s/it]
23:58:13-803766 ERROR    Exception: Native API failed. Native API returns: -5 (PI_ERROR_OUT_OF_RESOURCES) -5
                         (PI_ERROR_OUT_OF_RESOURCES)
23:58:13-804870 ERROR    Arguments: args=('task(x9tlufg8izi7bih)', 'cat', '', [], 20, 3, False, False, 1, 1, 6, 1, -1.0,
                         -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False,
                         'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64,
                         False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 512, 64, True, True, True, False,
                         False, 7, 100, 'Constant', 0, 'Constant', 0, 4,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f57d560a4d0>,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f57d6641450>,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f5809b8f9d0>, False,
                         False, 'positive', 'comma', 0, False, False, '', 0, '', [], 0, '', [], 0, '', [], True, False,
                         False, False, 0, False, None, None, False, None, None, False, None, None, False, 50) kwargs={}
23:58:13-808709 ERROR    gradio call: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ /home/soeur/automatic/modules/call_queue.py:34 in f                                                                  │
│                                                                                                                      │
│    33 │   │   │   try:                                                                                               │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                          │
│                                                                                                                      │
│ /home/soeur/automatic/modules/txt2img.py:56 in txt2img                                                               │
│                                                                                                                      │
│   55 │   if processed is None:                                                                                       │
│ ❱ 56 │   │   processed = processing.process_images(p)                                                                │
│   57 │   p.close()                                                                                                   │
│                                                                                                                      │
│                                               ... 18 frames hidden ...                                               │
│                                                                                                                      │
│ /home/soeur/automatic/venv/lib/python3.10/site-packages/torch/nn/modules/normalization.py:273 in forward             │
│                                                                                                                      │
│   272 │   def forward(self, input: Tensor) -> Tensor:                                                                │
│ ❱ 273 │   │   return F.group_norm(                                                                                   │
│   274 │   │   │   input, self.num_groups, self.weight, self.bias, self.eps)                                          │
│                                                                                                                      │
│ /home/soeur/automatic/venv/lib/python3.10/site-packages/torch/nn/functional.py:2528 in group_norm                    │
│                                                                                                                      │
│   2527 │   _verify_batch_size([input.size(0) * input.size(1) // num_groups, num_groups] + list(                      │
│ ❱ 2528 │   return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.e                      │
│   2529                                                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Native API failed. Native API returns: -5 (PI_ERROR_OUT_OF_RESOURCES) -5 (PI_ERROR_OUT_OF_RESOURCES)
23:58:14-098618 DEBUG    gc: collected=61 device=xpu {'ram': {'used': 8.27, 'total': 23.47}, 'gpu': {'used': 4.0,
                         'total': 6.32}, 'retries': 0, 'oom': 0}
```

**Comment by Disty0** [comment]
Can't reproduce. Probably a memory leak issue from WSL, use native Linux.
Also did you apply this OneAPI DPC++ compiler patch that fixes some memory leak issues?
https://intel.github.io/intel-extension-for-pytorch/xpu/1.13.120+xpu/tutorials/installation.html
```
wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/89283df8-c667-47b0-b7e1-c4573e37bd3e/2023.1-linux-hotfix.zip
unzip 2023.1-linux-hotfix.zip && cd 2023.1-linux-hotfix
chmod +x ./installpatch.sh && sudo ONEAPI_ROOT=/opt/intel/oneapi ./installpatch.sh
```

And default settings has been changed for IPEX.
Default optimization method is now Sub-quadratic. It uses way less memory.
Upcast Sampling is disabled now. It also uses less memory.

Also do you use FP32 / float32 / --no-half / Precision type Full?
If so, they double the memory usage.

Native Linux at 2048x2048:
`GPU active 12086 MB reserved 14950 MB | System peak 10038 MB total 15474 MB`
At 1024x1024:
`GPU active 5945 MB reserved 6756 MB | System peak 5433 MB total 15474 MB`
At 512x512:
`GPU active 4408 MB reserved 4732 MB | System peak 4216 MB total 15474 MB`

**Comment by juzi5201314** [comment]
> Also did you apply this OneAPI DPC++ compiler patch that fixes some memory leak issues?

yes

> Also do you use FP32 / float32 / --no-half / Precision type Full?
If so, they double the memory usage.

I found it:
```
12:37:33-070532 DEBUG    Load model: name=/home/soeur/automatic/models/Stable-diffusion/anything-v4.0-pruned-fp16.ckpt
                         dict=True
12:37:33-071269 DEBUG    Verifying Torch settings
12:37:33-071847 INFO     Torch override dtype: no-half set
12:37:33-072377 INFO     Torch override VAE dtype: no-half set
12:37:33-072993 DEBUG    Desired Torch parameters: dtype=FP32 no-half=True no-half-vae=True upscast=False
12:37:33-073633 INFO     Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32
12:37:33-074229 DEBUG    Torch default device: xpu
```
I noticed that no-half is enforced, but why?
My startup parameters: `./webui.sh --use-ipex --debug`

**Comment by juzi5201314** [comment]
> Probably a memory leak issue from WSL, use native Linux.

What is strange to me is that when using the same version of intel-extension-for-pytorch, the same model and the same wsl2 version, it was possible to run on wsl before, I just updated this repo and oneapi dependency . Does this mean that the problem is not on wsl, but the memory leak caused by the commit during this period or something else.

**Comment by Disty0** [comment]
FP32 is not normal and SD model alone will use 4 GB+ of VRAM because of it.

I'd say easiest is resetting your webui.
Either reinstall the webui or remove your config.json and venv folder and try again.

Before that, you can try setting the proper compute settings:
![image](https://github.com/vladmandic/automatic/assets/47277141/be336f8b-c71f-4f32-b936-88c919ca67b2)

![image](https://github.com/vladmandic/automatic/assets/47277141/9cf67f68-df79-4f32-936d-985a7bcab3bf)

**Comment by juzi5201314** [comment]
> FP32 is not normal and SD model alone will use 4 GB+ of VRAM because of it.
> 
> I'd say easiest is resetting your webui. Either reinstall the webui or remove your config.json and venv folder and try again.
> 
> Before that, you can try setting the proper compute settings: ![image](https://user-images.githubusercontent.com/47277141/249376958-be336f8b-c71f-4f32-b936-88c919ca67b2.png)
> 
> ![image](https://user-images.githubusercontent.com/47277141/249377036-9cf67f68-df79-4f32-936d-985a7bcab3bf.png)

This solved the problem for me.
I swear I haven't changed these settings before (😥

**Comment by Disty0** [comment]
If you started the webui without --use-ipex at the first start, it probably set the default settings for the CPU.
