### ISSUE TITLE
[Issue]: WON'T CONVERT __getitem__ | UnspecializedNNModuleVariable' object has no attribute 'module_key'

### ISSUE THREAD

**Issue by dannkunt** [vladmandic/automatic#1791]
### Issue Description

Just updated to latest git from a7f5e75a350a5e517c64174db5a6aca318e395e5. Now it's completely broken. Can't generate a single image


### Version Platform Description

❯ ./webui.sh --experimental --use-cuda --listen --backend original
Create and activate python venv
Launching launch.py...
22:05:07-003612 INFO     Starting SD.Next                                                                                                                                                                                                   
22:05:07-006826 INFO     Python 3.10.12 on Linux                                                                                                                                                                                            
22:05:07-020061 INFO     Version: b8f2b902 Fri Jul 21 14:49:28 2023 -0400                                                                                                                                                                   
22:05:07-391294 INFO     Latest published version: 511a8cbb61f2c9c09e64a96df0b801e7e73a4236 2023-07-21T19:04:27Z                                                                                                                            
22:05:07-393853 INFO     nVidia CUDA toolkit detected                                                                                                                                                                                       
22:05:07-431239 WARNING  Modified files: ['.idea/', 'scripts/prompt_gallery.py', 'venv310/', 'venv311/', 'vulkaninfo.html']                                                                                                                 
22:05:07-460352 INFO     Disabled extensions: ['sd-webui-controlnet', 'sd-dynamic-thresholding', 'multidiffusion-upscaler-for-automatic1111', 'a1111-sd-webui-lycoris']                                                                     
22:05:07-461219 INFO     Enabled extensions-builtin: ['LDSR', 'Lora', 'ScuNET', 'SwinIR', 'clip-interrogator-ext', 'sd-extension-system-info', 'sd-webui-model-converter', 'stable-diffusion-webui-images-browser',                         
                         'stable-diffusion-webui-rembg', 'sd-webui-agent-scheduler']                                                                                                                                                        
22:05:07-462562 INFO     Enabled extensions: ['sd-dynamic-prompts', 'posex', 'sd-webui-depth-lib', 'sd-webui-inpaint-anything', 'stable-diffusion-webui-extensions', 'adetailer', 'OneButtonPrompt', 'PromptGallery-stable-diffusion-webui',
                         'prompt_gallery_name.json', 'sd-model-preview-xd', 'stable-diffusion-pickle-scanner'] 

### Relevant log output

```shell
0%|                                                                                                                                                                                                                | 0/99 [00:00<?, ?it/s]22:14:09-150236 ERROR    WON'T CONVERT __getitem__ /run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/venv/lib/python3.10/site-packages/torch/nn/modules/container.py line 115                             
                         due to:                                                                                                                                                                                                            
                         Traceback (most recent call last):                                                                                                                                                                                 
                           File "/run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/venv/lib/python3.10/site-packages/torch/_dynamo/variables/nn_module.py", line 276, in call_method                      
                             key = mod_var.module_key                                                                                                                                                                                       
                         AttributeError: 'UnspecializedNNModuleVariable' object has no attribute 'module_key'                                                                                                                               
                                                                                                                                                                                                                                            
                         from user code:                                                                                                                                                                                                    
                            File "/run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 120, in __getitem__                            
                             return self._get_item_by_idx(self._modules.values(), idx)                                                                                                                                                      
                                                                                                                                                                                                                                            
                         Set torch._dynamo.config.verbose=True for more information                                                                                                                                                         
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            
22:14:09-150236 ERROR    WON'T CONVERT __getitem__ /run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/venv/lib/python3.10/site-packages/torch/nn/modules/container.py line 115                             
                         due to:                                                                                                                                                                                                            
                         Traceback (most recent call last):                                                                                                                                                                                 
                           File "/run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/venv/lib/python3.10/site-packages/torch/_dynamo/variables/nn_module.py", line 276, in call_method                      
                             key = mod_var.module_key                                                                                                                                                                                       
                         AttributeError: 'UnspecializedNNModuleVariable' object has no attribute 'module_key'                                                                                                                               
                                                                                                                                                                                                                                            
                         from user code:                                                                                                                                                                                                    
                            File "/run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 120, in __getitem__                            
                             return self._get_item_by_idx(self._modules.values(), idx)                                                                                                                                                      
                                                                                                                                                                                                                                            
                         Set torch._dynamo.config.verbose=True for more information                                                                                                                                                         
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            
  1%|██                                                                                                                                                                                                    | 1/99 [00:39<1:04:16, 39.35s/it]22:14:45-880762 ERROR    WON'T CONVERT <graph break in lora_apply_weights> /run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/extensions-builtin/Lora/lora.py line 320                                     
                         due to:                                                                                                                                                                                                            
                         Traceback (most recent call last):                                                                                                                                                                                 
                           File "/run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/venv/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 280, in from_real_tensor                     
                             raise UnsupportedFakeTensorException("meta converter nyi")                                                                                                                                                     
                         torch._subclasses.fake_tensor.UnsupportedFakeTensorException: meta converter nyi                                                                                                                                   
                                                                                                                                                                                                                                            
                         During handling of the above exception, another exception occurred:                                                                                                                                                
                                                                                                                                                                                                                                            
                         Traceback (most recent call last):                                                                                                                                                                                 
                           File "/run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/venv/lib/python3.10/site-packages/torch/_dynamo/exc.py", line 71, in unimplemented                                     
                             raise Unsupported(msg)                                                                                                                                                                                         
                         torch._dynamo.exc.Unsupported: Unsupported: meta converter nyi with fake tensor propagation.                                                                                                                       
                                                                                                                                                                                                                                            
                         Set torch._dynamo.config.verbose=True for more information                                                                                                                                                         
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            
22:14:45-880762 ERROR    WON'T CONVERT <graph break in lora_apply_weights> /run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/extensions-builtin/Lora/lora.py line 320                                     
                         due to:                                                                                                                                                                                                            
                         Traceback (most recent call last):                                                                                                                                                                                 
                           File "/run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/venv/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 280, in from_real_tensor                     
                             raise UnsupportedFakeTensorException("meta converter nyi")                                                                                                                                                     
                         torch._subclasses.fake_tensor.UnsupportedFakeTensorException: meta converter nyi                                                                                                                                   
                                                                                                                                                                                                                                            
                         During handling of the above exception, another exception occurred:                                                                                                                                                
                                                                                                                                                                                                                                            
                         Traceback (most recent call last):                                                                                                                                                                                 
                           File "/run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/venv/lib/python3.10/site-packages/torch/_dynamo/exc.py", line 71, in unimplemented                                     
                             raise Unsupported(msg)                                                                                                                                                                                         
                         torch._dynamo.exc.Unsupported: Unsupported: meta converter nyi with fake tensor propagation.                                                                                                                       
                                                                                                                                                                                                                                            
                         Set torch._dynamo.config.verbose=True for more information                                                                                                                                                         
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            
  2%|████                                                                                                                                                                                                  | 2/99 [02:20<1:53:28, 70.19s/it]
22:16:25-503598 ERROR    Exception: CUDA error: operation failed due to a previous error during capture                                                                                                                                     
                         CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.                                                                                            
                         For debugging consider passing CUDA_LAUNCH_BLOCKING=1.                                                                                                                                                             
                         Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.                                                                                                                                                
                                                                                                                                                                                                                                            
22:16:25-505115 ERROR    Arguments: args=('task(a49t1sog71c6trt)', 'masterpiece, best quality, realistic, 8k, official art, cinematic light, ultra high res, 1girl,  \\(hsr\\), black coat, chinese clothes, (bangs:1.2), red eyes, pant,   
                         dark blue hair, dynamic pose, dynamic angles, nsfw, (natural skin texture, hyperrealism, soft light, sharp:1.2), (intricate details:1.12), hdr, (intricate details, hyperdetailed:1.15)', 'watermark, text, logo,  
                         contact, error, blurry, cropped, username, artist name, (worst quality, low quality:1.4), monochrome, simple background', [], 99, 3, 3, False, False, 1, 1, 6, 6, 0.7, 2, 2734987545.0, -1.0, 0, 0, 0, 960, 544,   
                         True, 0.45, 2, 'R-ESRGAN 4x+', 40, 1080, 1920, 0.5, 1, '', '', [], 0, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0,              
                         'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True,                 
                         'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7,
                         'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1,               
                         'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0,                   
                         'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True,                 
                         'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7,
                         'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1,               
                         'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0,                   
                         'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True,                 
                         'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7,
                         'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1,               
                         'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0,                   
                         'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True,                 
                         'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7,
                         'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1,               
                         'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, False, '', 0, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0,                     
                         'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, None, None, '', '', '', '', 'Auto rename', {'label': 'Upload avatars config'}, 'Open outputs directory', 'Export to WebUI style', True, {'label': 'Presets'},
                         {'label': 'QC preview'}, '', [], 'Select', 'QC scan', 'Show pics', None, False, False, 'positive', 'comma', 0, False, False, '', 7, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, 5, 'all',   
                         'all', 'all', '', '', '', '1', 'none', False, '', '', 'comma', '', True, '', '20') kwargs={}                                                                                                                       
22:16:25-512859 ERROR    gradio call: RuntimeError                                                                                                                                                                                          
╭───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────╮
│ /run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/venv/lib/python3.10/site-packages/torch/_dynamo/backends/cudagraphs.py:63 in __call__                            │
│                                                                                                                                                                                                      │
│    62 │   │   │   with torch.cuda.graph(self.graph):                                                                                                                                                 │
│ ❱  63 │   │   │   │   self.static_outputs = self.gm(*self.static_inputs)                                                                                                                             │
│    64 │   │   │   # NB: recording doesn't actually run the operations, so                                                                                                                            │
│                                                                                                                                                                                                      │
│ /run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/venv/lib/python3.10/site-packages/torch/fx/graph_module.py:662 in call_wrapped                                   │
│                                                                                                                                                                                                      │
│   661 │   │   def call_wrapped(self, *args, **kwargs):                                                                                                                                               │
│ ❱ 662 │   │   │   return self._wrapped_call(self, *args, **kwargs)                                                                                                                                   │
│   663                                                                                                                                                                                                │
│                                                                                                                                                                                                      │
│                                                                                       ... 3 frames hidden ...                                                                                        │
│ in forward:6                                                                                                                                                                                         │
│                                                                                                                                                                                                      │
│ /run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/venv/lib/python3.10/site-packages/torch/_ops.py:287 in __call__                                                  │
│                                                                                                                                                                                                      │
│   286 │   def __call__(self, *args, **kwargs):                                                                                                                                                       │
│ ❱ 287 │   │   return self._op(*args, **kwargs or {})                                                                                                                                                 │
│   288                                                                                                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: status != cudaStreamCaptureStatus::cudaStreamCaptureStatusInvalidated INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":1519, please report a bug to PyTorch. 

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────╮
│ /run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/modules/call_queue.py:34 in f                                                                                    │
│                                                                                                                                                                                                      │
│    33 │   │   │   try:                                                                                                                                                                               │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                                                                                                    │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                                                                                                          │
│                                                                                                                                                                                                      │
│ /run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/modules/txt2img.py:65 in txt2img                                                                                 │
│                                                                                                                                                                                                      │
│   64 │   if processed is None:                                                                                                                                                                       │
│ ❱ 65 │   │   processed = processing.process_images(p)                                                                                                                                                │
│   66 │   p.close()                                                                                                                                                                                   │
│                                                                                                                                                                                                      │
│                                                                                       ... 55 frames hidden ...                                                                                       │
│                                                                                                                                                                                                      │
│ /run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/venv/lib/python3.10/site-packages/torch/cuda/graphs.py:173 in __exit__                                           │
│                                                                                                                                                                                                      │
│   172 │   def __exit__(self, exc_type, exc_value, traceback):                                                                                                                                        │
│ ❱ 173 │   │   self.cuda_graph.capture_end()                                                                                                                                                          │
│   174 │   │   self.stream_ctx.__exit__(exc_type, exc_value, traceback)                                                                                                                               │
│                                                                                                                                                                                                      │
│ /run/media/dannkunt/8af48620-644d-4e44-94f6-c4d83475b0b1/stable-diffusion-automatic/venv/lib/python3.10/site-packages/torch/cuda/graphs.py:79 in capture_end                                         │
│                                                                                                                                                                                                      │
│    78 │   │   """                                                                                                                                                                                    │
│ ❱  79 │   │   super().capture_end()                                                                                                                                                                  │
│    80                                                                                                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA error: operation failed due to a previous error during capture
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```


### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
this has nothing to do with recent changes, the code that is older.
seems like you have torch compile enabled.
delete `config.json` to reset configuration.

**Comment by dannkunt** [comment]
Yes, the problem was in torch compile
