### ISSUE TITLE
[issue]: IPEX: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by juzi5201314** [vladmandic/automatic#1923]
### Issue Description

I updated to the latest commit to use ipex 2.0.110+xpu, but I got an error when generating the image.
Also, I updated the intel oneapi toolkits to 2023.2.0 using apt.
I am not using ipexrun because numactl is not supported on wsl and ipex will use it.

It looks like it's not using ipex but cuda? but it does enable use-ipex

### Version Platform Description

 Python 3.10.6 on Linux
Version: d7ae6c61 Thu Aug 3 17:49:52 2023 +0200
Intel OneAPI Toolkit detected

### Relevant log output

```
00:11:05-538971 INFO     Starting SD.Next
00:11:05-541754 INFO     Python 3.10.6 on Linux
00:11:05-544701 INFO     Version: d7ae6c61 Thu Aug 3 17:49:52 2023 +0200
00:11:06-526165 INFO     Intel OneAPI Toolkit detected
00:11:06-540272 WARNING  Modified files: ['modules/lora', 'modules/lycoris', 'webui.sh', 'cmd_opts.data_dir/']
00:11:06-544136 INFO     Disabled extensions: ['a1111-sd-webui-lycoris']
00:11:06-544922 INFO     Enabled extensions-builtin: ['sd-dynamic-thresholding',
                         'stable-diffusion-webui-images-browser', 'sd-webui-agent-scheduler',
                         'sd-extension-system-info', 'stable-diffusion-webui-rembg', 'ScuNET',
                         'multidiffusion-upscaler-for-automatic1111', 'Lora', 'clip-interrogator-ext', 'SwinIR',
                         'sd-webui-controlnet', 'LDSR']
00:11:06-546352 INFO     Enabled extensions: ['stable-diffusion-webui-dataset-tag-editor']
00:11:06-547119 INFO     No changes detected: Quick launch active
00:11:06-547665 INFO     Verifying requirements
00:11:06-557018 WARNING  Package wrong version: timm 0.4.12 required 0.6.13
00:11:06-557743 INFO     Installing package: timm==0.6.13
00:11:08-999624 INFO     Disabled extensions: ['a1111-sd-webui-lycoris']
00:11:09-000482 INFO     Enabled extensions-builtin: ['sd-dynamic-thresholding',
                         'stable-diffusion-webui-images-browser', 'sd-webui-agent-scheduler',
                         'sd-extension-system-info', 'stable-diffusion-webui-rembg', 'ScuNET',
                         'multidiffusion-upscaler-for-automatic1111', 'Lora', 'clip-interrogator-ext', 'SwinIR',
                         'sd-webui-controlnet', 'LDSR']
00:11:09-001622 INFO     Enabled extensions: ['stable-diffusion-webui-dataset-tag-editor']
00:11:09-003190 INFO     Extension preload: 0.0s /home/soeur/automatic/extensions-builtin
00:11:09-003813 INFO     Extension preload: 0.0s /home/soeur/automatic/extensions
00:11:09-009555 INFO     Server arguments: ['--use-ipex', '--listen']
/home/soeur/automatic/venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2023-08-04 00:11:12.032545: I itex/core/devices/gpu/itex_gpu_runtime.cc:129] Selected platform: Intel(R) Level-Zero
2023-08-04 00:11:12.032823: I itex/core/devices/gpu/itex_gpu_runtime.cc:154] number of sub-devices is zero, expose root device.
No module 'xformers'. Proceeding without it.
00:11:14-233061 INFO     Pipeline: Backend.ORIGINAL
00:11:14-455078 INFO     Libraries loaded
00:11:14-456193 INFO     Using data path: /home/soeur/automatic
00:11:14-457446 INFO     Available VAEs: /home/soeur/automatic/models/VAE 0
00:11:14-458823 INFO     Available models: /home/soeur/automatic/models/Stable-diffusion 2
00:11:15-229348 INFO     ControlNet v1.1.227
ControlNet preprocessor location: /home/soeur/automatic/extensions-builtin/sd-webui-controlnet/annotator/downloads
00:11:15-311817 INFO     ControlNet v1.1.227
Image Browser: ImageReward is not installed, cannot be used.
00:11:16-304661 INFO     Loading UI theme: name=black-orange style=Auto
Running on local URL:  http://0.0.0.0:7860
00:11:17-441584 INFO     Local URL: http://localhost:7860/
00:11:17-442482 INFO     Initializing middleware
00:11:17-527418 INFO     [AgentScheduler] Task queue is empty
00:11:17-528232 INFO     [AgentScheduler] Registering APIs
Loading weights: /home/soeur/automatic/models/Stable-diffusion/chilloutmix_NiPrunedFp32Fix.safetensors ━━━━━ 0.0… -:--:…
                                                                                                             GB
00:11:18-593204 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
00:11:21-285354 INFO     Applied IPEX Optimize.
00:11:21-286472 INFO     Compiling pipeline=DiffusionWrapper mode=ipex
00:11:21-300234 INFO     Model complilation done.
00:11:21-300853 INFO     Applying InvokeAI cross attention optimization
00:11:21-697496 INFO     Embeddings: loaded=0 skipped=0
00:11:21-700914 INFO     Model loaded in 3.4s (load=0.1s config=0.2s create=0.3s apply=0.8s vae=0.3s move=1.1s
                         hijack=0.2s embeddings=0.4s)
00:11:21-950445 INFO     Model load finished: {'ram': {'used': 8.53, 'total': 23.47}, 'gpu': {'used': 2.02, 'total':
                         7.91}, 'retries': 0, 'oom': 0} cached=0
00:11:22-220584 INFO     Startup time: 13.2s (torch=4.0s gradio=0.8s libraries=0.7s scripts=1.5s onchange=0.4s
                         ui-txt2img=0.1s ui-img2img=0.1s ui-settings=0.1s ui-extensions=0.5s launch=0.4s
                         app-started=0.2s checkpoint=4.6s)
00:13:09-420360 INFO     Settings changed: 29 ['cuda_cast_unet', 'opt_channelslast', 'cuda_compile_type',
                         'ipex_optimize', 'directml_memory_provider', 'diffusers_refiner_latents',
                         'diffusers_move_unet', 'diffusers_vae_upcast', 'diffusers_model_load_variant',
                         'diffusers_vae_load_variant', 'image_watermark_enabled', 'image_watermark',
                         'save_images_before_refiner', 'schedulers_solver_order', 'schedulers_sep_diffusers',
                         'schedulers_prediction_type', 'schedulers_use_karras', 'schedulers_use_loworder',
                         'schedulers_use_thresholding', 'schedulers_dpm_solver', 'schedulers_beta_schedule',
                         'schedulers_beta_start', 'schedulers_beta_end', 'schedulers_sep_kdiffusers',
                         'schedulers_sep_compvis', 'dataset_editor_image_columns', 'dataset_editor_max_res',
                         'dataset_editor_use_temp_files', 'dataset_editor_use_raw_clip_token']
Initializing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 0:00:00
00:13:15-854548 ERROR    Exception: Torch not compiled with CUDA enabled
00:13:15-855311 ERROR    Arguments: args=('task(4edl1tkjwrt32f4)', 'a', '', [], 20, 0, None, False, False, 1, 1, 6, 6,
                         0.7, 1, -1.0, -1.0, 0, 0, 0, 512, 512, False, 0.7, 2, 'Latent', 20, 0, 0, 0, '', '', [], 0,
                         False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1,
                         64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0,
                         False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 512, 64, True, True, True, False,
                         False, 7, 100, 'Constant', 0, 'Constant', 0, 4,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f7a86fd1120>,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f7a65ec5f90>,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7f7a8c2eb8e0>, False,
                         False, 'positive', 'comma', 0, False, False, '', 0, '', [], 0, '', [], 0, '', [], True, False,
                         False, False, 0, False, None, None, False, None, None, False, None, None, False, 50) kwargs={}
00:13:15-859229 ERROR    gradio call: AssertionError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ /home/soeur/automatic/modules/call_queue.py:34 in f                                                                  │
│                                                                                                                      │
│    33 │   │   │   try:                                                                                               │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                          │
│                                                                                                                      │
│ /home/soeur/automatic/modules/txt2img.py:64 in txt2img                                                               │
│                                                                                                                      │
│   63 │   if processed is None:                                                                                       │
│ ❱ 64 │   │   processed = processing.process_images(p)                                                                │
│   65 │   p.close()                                                                                                   │
│                                                                                                                      │
│                                               ... 25 frames hidden ...                                               │
│                                                                                                                      │
│ /home/soeur/automatic/venv/lib/python3.10/site-packages/torch/cuda/random.py:22 in get_rng_state                     │
│                                                                                                                      │
│    21 │   """                                                                                                        │
│ ❱  22 │   _lazy_init()                                                                                               │
│    23 │   if isinstance(device, str):                                                                                │
│                                                                                                                      │
│ /home/soeur/automatic/venv/lib/python3.10/site-packages/torch/cuda/__init__.py:239 in _lazy_init                     │
│                                                                                                                      │
│    238 │   │   if not hasattr(torch._C, '_cuda_getDeviceCount'):                                                     │
│ ❱  239 │   │   │   raise AssertionError("Torch not compiled with CUDA enabled")                                      │
│    240 │   │   if _cudart is None:                                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: Torch not compiled with CUDA enabled
```

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
cc @Disty0

**Comment by Disty0** [comment]
Update to latest commit and start the webui with --reinstall to upgrade torch.
Also ipex compile mode is slower than no compile.

**Comment by juzi5201314** [comment]
> Update to latest commit and start the webui with --reinstall to upgrade torch. Also ipex compile mode is slower than no compile rn.

The latest commit solves the problem

**Comment by 1983lynx** [comment]
@vladmandic Could you check the latest version of IPEX and integrate it?
https://pytorch-extension.intel.com/installation?platform=gpu&version=v2.6.10%2Bxpu&os=windows&package=pip

>>Also ipex compile mode is slower than no compile rn
Is this situation still true today?

**Comment by vladmandic** [comment]
please don't comment on a 2y old issue...
