### ISSUE TITLE
[Issue]: Perfomance Issue after Update

### ISSUE THREAD

**Issue by xGeekpower** [vladmandic/automatic#2344]
### Issue Description

I did a fresh install and installed the latest update, my generation time for 1 img in txt2img went from 10-15sec to 2-5min, img2img takes about 15min now, settings should be the default not sure if my GPU is too low now or if I need to mess with the settings.

### Version Platform Description

Windows 10/FIrefox.
NVIDIA GeForce RTX 2060 6GB VRAM

### Relevant log output

```shell
Using VENV: E:\DIFFUSION_VLAD\automatic\venv
14:11:24-660131 INFO     Starting SD.Next
14:11:24-692070 INFO     Python 3.10.11 on Windows
14:11:24-906708 INFO     Version: app=sd.next updated=2023-10-18 hash=66f75b6a
                         url=https://github.com/vladmandic/automatic/tree/master
14:11:25-807150 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.11
14:11:25-830088 INFO     nVidia CUDA toolkit detected: nvidia-smi present
14:11:26-175134 WARNING  Modified files: ['scripts/detect_extension.py']
14:11:27-044060 INFO     Extensions: disabled=[]
14:11:27-046115 INFO     Extensions: enabled=['clip-interrogator-ext', 'Lora', 'sd-extension-chainner',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg'] extensions-builtin
14:11:27-201274 INFO     Extensions: enabled=['a1111-sd-webui-tagcomplete', 'adetailer', 'canvas-zoom',
                         'multidiffusion-upscaler-for-automatic1111', 'sd-canvas-editor', 'sd-dynamic-prompts',
                         'sd-pixel', 'sd-webui-3d-open-pose-editor', 'sd-webui-depth-lib',
                         'sd-webui-infinite-image-browsing', 'sd-webui-pixelart', 'sd-webui-segment-anything',
                         'sd-webui-txt-img-to-3d-model', 'sd_webui_SAG', 'stable-diffusion-webui-pixelization',
                         'ultimate-upscale-for-automatic1111'] extensions
14:11:27-384206 INFO     Verifying requirements
14:11:27-415103 INFO     Verifying packages
14:11:27-419091 INFO     Verifying repositories
14:11:32-828882 INFO     Verifying submodules
14:13:28-174618 INFO     Extensions enabled: ['clip-interrogator-ext', 'Lora', 'sd-extension-chainner',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg',
                         'a1111-sd-webui-tagcomplete', 'adetailer', 'canvas-zoom',
                         'multidiffusion-upscaler-for-automatic1111', 'sd-canvas-editor', 'sd-dynamic-prompts',
                         'sd-pixel', 'sd-webui-3d-open-pose-editor', 'sd-webui-depth-lib',
                         'sd-webui-infinite-image-browsing', 'sd-webui-pixelart', 'sd-webui-segment-anything',
                         'sd-webui-txt-img-to-3d-model', 'sd_webui_SAG', 'stable-diffusion-webui-pixelization',
                         'ultimate-upscale-for-automatic1111']
14:13:28-185560 INFO     Verifying packages
14:13:28-263218 INFO     Extension preload: {'extensions-builtin': 0.05, 'extensions': 0.0}
14:13:28-267208 INFO     Command line args: []
14:13:41-165296 INFO     Engine: backend=Backend.ORIGINAL compute=cuda mode=no_grad device=cuda
                         cross-optimization="Scaled-Dot-Product"
14:13:41-428313 INFO     Device: device=NVIDIA GeForce RTX 2060 n=1 arch=sm_90 cap=(7, 5) cuda=12.1 cudnn=8801
                         driver=537.58
14:13:47-306668 INFO     Available VAEs: E:\DIFFUSION_MODELS\VAE items=35
14:13:56-849251 INFO     Available models: models\Stable-diffusion items=810 time=9.51s
14:14:14-382057 INFO     Extension: script='extensions-builtin\sd-webui-controlnet\scripts\controlnet.py' Warning:
                         ControlNet failed to load SGM - will use LDM instead.
14:14:14-385081 INFO     Extension: script='extensions-builtin\sd-webui-controlnet\scripts\controlnet.py' ControlNet
                         preprocessor location:
                         E:\DIFFUSION_VLAD\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
14:14:14-401008 INFO     Extension: script='extensions-builtin\sd-webui-controlnet\scripts\hook.py' Warning: ControlNet
                         failed to load SGM - will use LDM instead.
14:14:21-938057 INFO     Extension: script='extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py'
                         Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will
                         be limited to those added through the extra networks menu.
14:14:22-969257 INFO     Extension: script='extensions\adetailer\scripts\!adetailer.py' [-] ADetailer initialized.
                         version: 23.10.1, num models: 25
14:14:25-949204 INFO     Extensions time: 26.12s { automatic=0.16s clip-interrogator-ext=2.77s Lora=5.42s
                         sd-extension-chainner=0.54s sd-extension-system-info=0.10s sd-webui-agent-scheduler=1.85s
                         sd-webui-controlnet=3.74s stable-diffusion-webui-images-browser=0.57s
                         stable-diffusion-webui-rembg=5.88s a1111-sd-webui-tagcomplete=1.07s adetailer=1.03s
                         multidiffusion-upscaler-for-automatic1111=0.13s sd-canvas-editor=0.17s
                         sd-dynamic-prompts=0.26s sd-webui-3d-open-pose-editor=0.19s sd-webui-depth-lib=0.37s
                         sd-webui-infinite-image-browsing=0.27s sd-webui-segment-anything=0.83s
                         sd-webui-txt-img-to-3d-model=0.68s }
14:14:26-978870 INFO     Loading UI theme: name=invoked style=Dark base=style.css
14:15:47-350511 INFO     Local URL: http://127.0.0.1:7860/
14:15:47-353161 INFO     Initializing middleware
14:15:47-842002 INFO     [AgentScheduler] Task queue is empty
14:15:47-844993 INFO     [AgentScheduler] Registering APIs
14:15:48-319319 INFO     Select: model="Lineart\MeKaMix65 [416a142e32]"
Loading weights: E:\DIFFUSION_VLAD\automatic\models\Stable-diffusion\Lineart\MeKaMix65.safetensors ------ 0.0/4… -:--:…
                                                                                                          GB
14:15:53-186699 INFO     Torch override dtype: no-half set
14:15:53-192654 INFO     Torch override VAE dtype: no-half set
14:15:53-195645 INFO     Setting Torch parameters: device=cuda dtype=torch.float32 vae=torch.float32 unet=torch.float32
                         context=no_grad fp16=False bf16=False
14:16:10-592942 INFO     LDM: LatentDiffusion: Running in eps-prediction mode
14:16:10-595934 INFO     LDM: 14:15:56-793171 INFO     MOTD: N/A
14:16:10-600921 INFO     LDM: DiffusionWrapper has 859.52 M params.
14:16:10-601918 INFO     Autodetect: model="Stable Diffusion" class=StableDiffusionPipeline
                         file="E:\DIFFUSION_VLAD\automatic\models\Stable-diffusion\Lineart\MeKaMix65.safetensors"
                         size=4068MB
Loading weights: E:\DIFFUSION_MODELS\VAE\kl-f8-anime2.vae.pt ------------------------ ---------- 283.0/404.7 MB 0:00:00
14:18:08-176716 INFO     Cross-attention: optimization=Scaled-Dot-Product options=[]
14:18:09-137789 INFO     Browser session: client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0)
                         Gecko/20100101 Firefox/118.0
14:18:20-428291 INFO     Loaded embeddings: loaded=337 skipped=8 time=12.22s
14:18:20-481069 INFO     Model loaded in 152.13s { load=4.84s config=0.12s create=17.34s hash=0.10s apply=107.42s
                         vae=6.42s move=3.42s hijack=0.20s embeddings=12.23s }
14:18:20-489047 INFO     GPU high memory utilization: 91% {'ram': {'used': 2.69, 'total': 15.95}, 'gpu': {'used': 5.45,
                         'total': 6.0}, 'retries': 0, 'oom': 0}
14:18:25-506127 INFO     Model load finished: {'ram': {'used': 3.5, 'total': 15.95}, 'gpu': {'used': 5.43, 'total':
                         6.0}, 'retries': 0, 'oom': 0} cached=0
14:18:25-677668 INFO     Startup time: 297.33s { torch=9.55s gradio=1.19s diffusers=0.18s libraries=7.96s vae=0.09s
                         extensions=26.12s models=9.54s face-restore=2.98s upscalers=0.28s extra-networks=0.64s
                         ui-extra-networks=58.83s ui-txt2img=1.28s ui-img2img=0.52s ui-models=0.05s ui-settings=1.68s
                         ui-extensions=16.00s ui-defaults=0.63s launch=1.46s api=0.12s app-started=0.80s
                         checkpoint=157.36s }
Loading weights: E:\DIFFUSION_MODELS\Lora\Artists\rabbit-(wlsdnjs950)-1037it-novae.safetensors -------- 0.0/15… -:--:--
                                                                                                        MB
Loading weights: E:\DIFFUSION_MODELS\Lora\Artists\Artist_Alexi_rzr87h.safetensors ---------------- 0.0/151.1 MB -:--:--
Loading weights: E:\DIFFUSION_MODELS\Lora\Artists\shirow-mix2-512d128a-768p-e08.safetensors --------- 0.0/604.2 -:--:--
                                                                                                      MB
Loading weights: E:\DIFFUSION_MODELS\Lora\Artists\hyocorou-wd-e04.safetensors -------------------- 0.0/151.1 MB -:--:--
Loading weights: E:\DIFFUSION_MODELS\Lora\Artists\samdoesart-(sam-yang)-1613it-novae.safetensors ------ 0.0/15… -:--:--
                                                                                                        MB
Loading weights: E:\DIFFUSION_MODELS\Lora\Artists\marui maru_e07.safetensors --------------------- 0.0/152.7 MB -:--:--
14:21:10-308344 INFO     GPU high memory utilization: 91% {'ram': {'used': 3.92, 'total': 15.95}, 'gpu': {'used': 5.46,
                         'total': 6.0}, 'retries': 0, 'oom': 0}
14:21:10-829926 INFO     Applying LoRA: ['rabbit-(wlsdnjs950)-1037it-novae', 'alexi', 'shirow-mix2-512d128a-768p-e08',
                         'hyocorou-wd-e04', 'samdoesart-(sam-yang)-1613it-novae', 'marui maru_e07'] patch=0.00s
                         load=35.17s
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:34<00:00,  1.74s/it]
14:21:49-989650 INFO     GPU high memory utilization: 91% {'ram': {'used': 6.18, 'total': 15.95}, 'gpu': {'used': 5.48,
                         'total': 6.0}, 'retries': 0, 'oom': 0}
[Tiled VAE]: input_size: torch.Size([1, 4, 96, 64]), tile_size: 64, padding: 11
[Tiled VAE]: split to 2x1 = 2 tiles. Optimal tile size 64x64, original tile size 64x64
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 42 x 64 image
[Tiled VAE]: Executing Decoder Task Queue: 100%|█████████████████████████████████████| 246/246 [00:49<00:00,  4.92it/s]
14:22:51-928406 INFO     GPU high memory utilization: 97% {'ram': {'used': 6.88, 'total': 15.95}, 'gpu': {'used': 5.84,
                         'total': 6.0}, 'retries': 0, 'oom': 0}
[Tiled VAE]: Done in 63.004s, max VRAM alloc 5053.194 MB

WARNING  NMS time limit 0.550s exceeded
0: 640x448 1 face, 767.0ms
Speed: 421.8ms preprocess, 767.0ms inference, 676.8ms postprocess per image at shape (1, 3, 640, 448)
14:22:58-177139 INFO     GPU high memory utilization: 91% {'ram': {'used': 6.77, 'total': 15.95}, 'gpu': {'used': 5.44,
                         'total': 6.0}, 'retries': 0, 'oom': 0}
14:23:00-108047 INFO     Upscaler loaded: type=RealESRGAN 4x+ model=models\RealESRGAN\RealESRGAN_x4plus.pth
Upscaling ---------------------------------------- 100% 0:00:00 0:00:05
14:23:06-196493 INFO     GPU high memory utilization: 94% {'ram': {'used': 6.67, 'total': 15.95}, 'gpu': {'used': 5.61,
                         'total': 6.0}, 'retries': 0, 'oom': 0}
Loading weights: E:\DIFFUSION_MODELS\Lora\Artists\rabbit-(wlsdnjs950)-1037it-novae.safetensors -------- 0.0/15… -:--:--
                                                                                                        MB
14:23:42-195112 INFO     GPU high memory utilization: 93% {'ram': {'used': 7.01, 'total': 15.95}, 'gpu': {'used': 5.6,
                         'total': 6.0}, 'retries': 0, 'oom': 0}
14:23:43-024860 INFO     Applying LoRA: ['rabbit-(wlsdnjs950)-1037it-novae'] patch=0.00s load=4.25s
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:19<00:00,  1.01it/s]
14:24:04-148805 INFO     GPU high memory utilization: 100% {'ram': {'used': 6.76, 'total': 15.95}, 'gpu': {'used': 6.0,
                         'total': 6.0}, 'retries': 0, 'oom': 0}
14:24:46-175288 INFO     GPU high memory utilization: 91% {'ram': {'used': 5.72, 'total': 15.95}, 'gpu': {'used': 5.47,
                         'total': 6.0}, 'retries': 0, 'oom': 0}
14:24:46-809864 INFO     Processed: images=1 time=108.68s its=0.18 memory={'ram': {'used': 5.34, 'total': 15.95},
                         'gpu': {'used': 5.28, 'total': 6.0}, 'retries': 0, 'oom': 0}
14:24:48-813567 INFO     Processed: images=1 time=253.15s its=0.08 memory={'ram': {'used': 5.34, 'total': 15.95},
                         'gpu': {'used': 5.34, 'total': 6.0}, 'retries': 0, 'oom': 0}
14:25:56-614969 INFO     GPU high memory utilization: 91% {'ram': {'used': 5.04, 'total': 15.95}, 'gpu': {'used': 5.48,
                         'total': 6.0}, 'retries': 0, 'oom': 0}
Loading weights: E:\DIFFUSION_MODELS\Lora\Artists\rabbit-(wlsdnjs950)-1037it-novae.safetensors -------- 0.0/15… -:--:--
                                                                                                        MB
Loading weights: E:\DIFFUSION_MODELS\Lora\Artists\Artist_Alexi_rzr87h.safetensors ---------------- 0.0/151.1 MB -:--:--
Loading weights: E:\DIFFUSION_MODELS\Lora\Artists\shirow-mix2-512d128a-768p-e08.safetensors ---------------------------------------- 0.0/604.2 MB -:--:--
Loading weights: E:\DIFFUSION_MODELS\Lora\Artists\hyocorou-wd-e04.safetensors ---------------------------------------- 0.0/151.1 MB -:--:--
Loading weights: E:\DIFFUSION_MODELS\Lora\Artists\samdoesart-(sam-yang)-1613it-novae.safetensors ------ 0.0/15… -:--:--
                                                                                                        MB
Loading weights: E:\DIFFUSION_MODELS\Lora\Artists\marui maru_e07.safetensors --------------------- 0.0/152.7 MB -:--:--
14:26:31-462513 INFO     GPU high memory utilization: 92% {'ram': {'used': 7.2, 'total': 15.95}, 'gpu': {'used': 5.49,
                         'total': 6.0}, 'retries': 0, 'oom': 0}
14:26:32-055048 INFO     Applying LoRA: ['rabbit-(wlsdnjs950)-1037it-novae', 'alexi', 'shirow-mix2-512d128a-768p-e08',
                         'hyocorou-wd-e04', 'samdoesart-(sam-yang)-1613it-novae', 'marui maru_e07'] patch=0.00s
                         load=34.94s
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:26<00:00,  1.31s/it]
14:27:01-617195 INFO     GPU high memory utilization: 99% {'ram': {'used': 7.11, 'total': 15.95}, 'gpu': {'used': 5.94,
                         'total': 6.0}, 'retries': 0, 'oom': 0}
[Tiled VAE]: input_size: torch.Size([1, 4, 96, 64]), tile_size: 64, padding: 11
[Tiled VAE]: split to 2x1 = 2 tiles. Optimal tile size 64x64, original tile size 64x64
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 42 x 64 image
[Tiled VAE]: Executing Decoder Task Queue: 100%|█████████████████████████████████████| 246/246 [00:08<00:00, 30.45it/s]
14:27:12-141985 INFO     GPU high memory utilization: 100% {'ram': {'used': 8.19, 'total': 15.95}, 'gpu': {'used': 6.0,
                         'total': 6.0}, 'retries': 0, 'oom': 0}
[Tiled VAE]: Done in 12.010s, max VRAM alloc 5068.131 MB
14:27:15-238267 INFO     GPU high memory utilization: 92% {'ram': {'used': 7.15, 'total': 15.95}, 'gpu': {'used': 5.55,
                         'total': 6.0}, 'retries': 0, 'oom': 0}
14:27:15-714015 INFO     Processed: images=1 time=78.60s its=0.25 memory={'ram': {'used': 7.15, 'total': 15.95}, 'gpu':
                         {'used': 5.46, 'total': 6.0}, 'retries': 0, 'oom': 0}
14:28:49-871158 INFO     GPU high memory utilization: 91% {'ram': {'used': 6.72, 'total': 15.95}, 'gpu': {'used': 5.46,
                         'total': 6.0}, 'retries': 0, 'oom': 0}
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by brknsoul** [comment]
Your 2060 GPU is using SDP instead of xformers. Try changing this in System > Settings > Compute Settings;
![image](https://github.com/vladmandic/automatic/assets/1969381/fc34de5f-7709-4d0c-9288-9984d21f4b72)


Also, the recommended driver version is 531.79. Drivers after this have a change in memory management, which is not good for Stable Diffusion.

**Comment by xGeekpower** [comment]
I was using SDP before the update without any issue but I will test this ty.

**Comment by vladmandic** [comment]
this is what #1285 talks about.
change settings to get memory utilization down. there is no magic bullet.

**Comment by xGeekpower** [comment]
Yeah changing the driver did the trick ty.
