### ISSUE TITLE
[Extension]: Dynamic thresholding with LCM Lora with SD1.5 models produces bad output

### ISSUE THREAD

**Issue by patientx** [vladmandic/automatic#2492]
### Issue Description

When I use any sd 1.5 model I have with lcm's sd 1.5 lora and set the sampler to LCM as I must , the results are garbled if I enable HYPERTILE.

I have to use hypertile because normally with --medvram and all the optimizations I can use generating gives out of memory error as soon as the first generation or if I am lucky in second or third one. This is with 512x512. 

Also if I don't use sampler LCM as suggested but something else like SDE or euler the output is ok.

Here are some sample generations and log. 

model photon with settings I used 
![photon](https://github.com/vladmandic/automatic/assets/5392772/e578e37b-2765-4094-b235-09241cab40ed)
model lyriel with settings I used
![lyriel](https://github.com/vladmandic/automatic/assets/5392772/9286fb7d-9d59-4fe3-b45f-20070cbd6550)

Some results :
![00109-epicrealism_naturalSinRC1VAE-Cheerleaders cheering on the school field lora lcm](https://github.com/vladmandic/automatic/assets/5392772/45eae725-7d4d-4643-b0c3-78dab37322d0)
![00110-lyriel_v16-Cheerleaders cheering on the school field lora lcm](https://github.com/vladmandic/automatic/assets/5392772/19f067c8-e880-4444-b295-228653a97a24)
![00111-photon_v1-Cheerleaders cheering on the school field lora lcm](https://github.com/vladmandic/automatic/assets/5392772/a60eb520-8f69-4426-ae3e-5b218e7b5d3f)
![00106-epicphotogasm_z-Cheerleaders cheering on the school field lora lcm](https://github.com/vladmandic/automatic/assets/5392772/a8e58c4c-1922-494f-aa92-1f56b2ec0023)

some outputs with other samplers :
![00103-epicphotogasm_z-Cheerleaders cheering on the school field lora lcm](https://github.com/vladmandic/automatic/assets/5392772/50398a98-aaa3-4d5f-8588-6d300158fe00)
![00104-epicphotogasm_z-Cheerleaders cheering on the school field lora lcm](https://github.com/vladmandic/automatic/assets/5392772/ad3ecbeb-4f82-4f39-8bc7-b452d978580c)

### Version Platform Description

windows 10 , 16 gb ddr4-3000, nvme drive with ryzen 3600x cpu and rx 6600 gpu

Starting SD.Next
Python 3.10.11 on Windows
Version: app=sd.next updated=2023-11-10 hash=056b04dc url=https://github.com/vladmandic/automatic/tree/master
Platform: arch=AMD64 cpu=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD system=Windows release=Windows-10-10.0.19045-SP0 python=3.10.11
Setting environment tuning
Torch overrides: cuda=False rocm=False ipex=False diml=True openvino=False
Torch allowed: cuda=False rocm=False ipex=False diml=True openvino=False
Using DirectML Backend

### Relevant log output

```shell
2023-11-10 18:29:08,887 | sd | INFO | launch | Starting SD.Next
2023-11-10 18:29:08,889 | sd | INFO | installer | Python 3.10.11 on Windows
2023-11-10 18:29:09,081 | sd | INFO | installer | Version: app=sd.next updated=2023-11-10 hash=056b04dc url=https://github.com/vladmandic/automatic/tree/master
2023-11-10 18:29:10,703 | sd | INFO | launch | Platform: arch=AMD64 cpu=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD system=Windows release=Windows-10-10.0.19045-SP0 python=3.10.11
2023-11-10 18:29:10,704 | sd | DEBUG | installer | Setting environment tuning
2023-11-10 18:29:10,706 | sd | DEBUG | installer | Torch overrides: cuda=False rocm=False ipex=False diml=True openvino=False
2023-11-10 18:29:10,707 | sd | DEBUG | installer | Torch allowed: cuda=False rocm=False ipex=False diml=True openvino=False
2023-11-10 18:29:10,709 | sd | INFO | installer | Using DirectML Backend
2023-11-10 18:29:10,810 | sd | WARNING | installer | Modified files: ['repositories/BLIP/BLIP.gif', 'repositories/CodeFormer/.gitignore']
2023-11-10 18:29:10,855 | sd | DEBUG | installer | Repository update time: Fri Nov 10 18:10:41 2023
2023-11-10 18:29:10,857 | sd | INFO | launch | Startup: standard
2023-11-10 18:29:10,858 | sd | INFO | installer | Verifying requirements
2023-11-10 18:29:10,872 | sd | INFO | installer | Verifying packages
2023-11-10 18:29:10,874 | sd | INFO | installer | Verifying submodules
2023-11-10 18:29:13,844 | sd | DEBUG | installer | Submodule: extensions-builtin/sd-extension-chainner / main
2023-11-10 18:29:13,945 | sd | DEBUG | installer | Submodule: extensions-builtin/sd-extension-system-info / main
2023-11-10 18:29:14,045 | sd | DEBUG | installer | Submodule: extensions-builtin/sd-webui-agent-scheduler / main
2023-11-10 18:29:14,166 | sd | DEBUG | installer | Submodule: extensions-builtin/sd-webui-controlnet / main
2023-11-10 18:29:14,275 | sd | DEBUG | installer | Submodule: extensions-builtin/stable-diffusion-webui-images-browser / main
2023-11-10 18:29:14,373 | sd | DEBUG | installer | Submodule: extensions-builtin/stable-diffusion-webui-rembg / master
2023-11-10 18:29:14,470 | sd | DEBUG | installer | Submodule: modules/k-diffusion / master
2023-11-10 18:29:14,561 | sd | DEBUG | installer | Submodule: modules/lora / main
2023-11-10 18:29:14,657 | sd | DEBUG | installer | Submodule: wiki / master
2023-11-10 18:29:14,715 | sd | DEBUG | paths | Register paths
2023-11-10 18:29:15,006 | sd | DEBUG | installer | Installed packages: 227
2023-11-10 18:29:15,008 | sd | DEBUG | installer | Extensions all: ['clip-interrogator-ext', 'Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg']
2023-11-10 18:29:15,010 | sd | DEBUG | installer | Running extension installer: E:\automatic\extensions-builtin\clip-interrogator-ext\install.py
2023-11-10 18:29:23,997 | sd | DEBUG | installer | Running extension installer: E:\automatic\extensions-builtin\sd-extension-system-info\install.py
2023-11-10 18:29:24,791 | sd | DEBUG | installer | Running extension installer: E:\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
2023-11-10 18:29:25,587 | sd | DEBUG | installer | Running extension installer: E:\automatic\extensions-builtin\sd-webui-controlnet\install.py
2023-11-10 18:29:26,382 | sd | DEBUG | installer | Running extension installer: E:\automatic\extensions-builtin\stable-diffusion-webui-images-browser\install.py
2023-11-10 18:29:27,173 | sd | DEBUG | installer | Running extension installer: E:\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
2023-11-10 18:29:27,968 | sd | DEBUG | installer | Extensions all: ['multidiffusion-upscaler-for-automatic1111', 'sd-webui-reactor']
2023-11-10 18:29:28,252 | sd | DEBUG | installer | Running extension installer: E:\automatic\extensions\sd-webui-reactor\install.py
2023-11-10 18:29:30,969 | sd | INFO | installer | Extensions enabled: ['clip-interrogator-ext', 'Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'multidiffusion-upscaler-for-automatic1111', 'sd-webui-reactor']
2023-11-10 18:29:30,971 | sd | INFO | installer | Verifying requirements
2023-11-10 18:29:30,985 | sd | DEBUG | launch | Setup complete without errors: 1699630171
2023-11-10 18:29:30,995 | sd | INFO | installer | Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
2023-11-10 18:29:30,997 | sd | DEBUG | launch | Starting module: <module 'webui' from 'e:\\automatic\\webui.py'>
2023-11-10 18:29:30,998 | sd | INFO | launch | Command line args: ['--use-directml', '--medvram', '--debug'] medvram=True debug=True use_directml=True
2023-11-10 18:29:38,645 | sd | INFO | loader | Load packages: torch=2.0.0+cpu diffusers=0.23.0 gradio=3.43.2
2023-11-10 18:29:39,681 | sd | DEBUG | shared | Read: file="config.json" len=58
2023-11-10 18:29:39,685 | sd | DEBUG | shared | Unknown settings: ['queue_history_retention_days']
2023-11-10 18:29:39,744 | sd | INFO | shared | Engine: backend=Backend.DIFFUSERS compute=directml mode=no_grad device=privateuseone:0 cross-optimization="Split attention"
2023-11-10 18:29:39,841 | sd | INFO | shared | Device: device=AMD Radeon RX 6600 n=3 directml=0.2.0.dev230426
2023-11-10 18:29:40,654 | sd | DEBUG | webui | Entering start sequence
2023-11-10 18:29:40,657 | sd | DEBUG | webui | Initializing
2023-11-10 18:29:40,659 | sd | INFO | sd_vae | Available VAEs: path="D:\stable-diffusion-webui-directml\models\VAE" items=0
2023-11-10 18:29:40,661 | sd | INFO | shared | Disabling uncompatible extensions: backend=Backend.DIFFUSERS ['sd-webui-controlnet', 'multidiffusion-upscaler-for-automatic1111', 'a1111-sd-webui-lycoris']
2023-11-10 18:29:40,665 | sd | DEBUG | modelloader | Scanning diffusers cache: models\Diffusers D:\stable-diffusion-webui-directml\models\Diffusers items=1 time=0.00
2023-11-10 18:29:40,667 | sd | DEBUG | shared | Read: file="cache.json" len=2
2023-11-10 18:29:40,679 | sd | DEBUG | shared | Read: file="metadata.json" len=242
2023-11-10 18:29:40,682 | sd | INFO | sd_models | Available models: path="D:\stable-diffusion-webui-directml\models\Stable-diffusion" items=9 time=0.02
2023-11-10 18:29:40,998 | sd | DEBUG | webui | Load extensions
2023-11-10 18:29:43,903 | sd | INFO | script_loading | Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
2023-11-10 18:29:45,584 | sd | INFO | webui | Extensions time: 4.59 { clip-interrogator-ext=2.03 Lora=0.24 sd-extension-chainner=0.10 sd-webui-agent-scheduler=0.47 stable-diffusion-webui-images-browser=0.12 stable-diffusion-webui-rembg=1.00 sd-webui-reactor=0.55 }
2023-11-10 18:29:45,705 | sd | DEBUG | shared | Read: file="html/upscalers.json" len=4
2023-11-10 18:29:45,707 | sd | DEBUG | shared | Read: file="extensions-builtin\sd-extension-chainner\models.json" len=24
2023-11-10 18:29:45,710 | sd | DEBUG | chainner_model | chaiNNer models: path="models\chaiNNer" defined=24 discovered=0 downloaded=1
2023-11-10 18:29:45,713 | sd | DEBUG | upscaler | Upscaler type=ESRGAN folder="D:\stable-diffusion-webui-directml\models\ESRGAN" model="4x-UniScale-Balanced [72000g]" path="D:\stable-diffusion-webui-directml\models\ESRGAN\4x-UniScale-Balanced [72000g].pth"
2023-11-10 18:29:45,714 | sd | DEBUG | upscaler | Upscaler type=ESRGAN folder="D:\stable-diffusion-webui-directml\models\ESRGAN" model="4x_foolhardy_Remacri" path="D:\stable-diffusion-webui-directml\models\ESRGAN\4x_foolhardy_Remacri.pth"
2023-11-10 18:29:45,716 | sd | DEBUG | upscaler | Upscaler type=ESRGAN folder="D:\stable-diffusion-webui-directml\models\ESRGAN" model="8x_NMKD-Superscale_150000_G" path="D:\stable-diffusion-webui-directml\models\ESRGAN\8x_NMKD-Superscale_150000_G.pth"
2023-11-10 18:29:45,718 | sd | DEBUG | upscaler | Upscaler type=ESRGAN folder="D:\stable-diffusion-webui-directml\models\ESRGAN" model="ESRGAN_4x" path="D:\stable-diffusion-webui-directml\models\ESRGAN\ESRGAN_4x.pth"
2023-11-10 18:29:45,719 | sd | DEBUG | upscaler | Upscaler type=ESRGAN folder="D:\stable-diffusion-webui-directml\models\ESRGAN" model="TGHQFace8x_500k" path="D:\stable-diffusion-webui-directml\models\ESRGAN\TGHQFace8x_500k.pth"
2023-11-10 18:29:45,723 | sd | DEBUG | upscaler | Upscaler type=SwinIR folder="D:\stable-diffusion-webui-directml\models\SwinIR" model="SwinIR_4x" path="D:\stable-diffusion-webui-directml\models\SwinIR\SwinIR_4x.pth"
2023-11-10 18:29:45,727 | sd | DEBUG | modelloader | Load upscalers: total=58 downloaded=11 user=6 ['None', 'Lanczos', 'Nearest', 'ChaiNNer', 'ESRGAN', 'LDSR', 'RealESRGAN', 'SCUNet', 'SD', 'SwinIR']
2023-11-10 18:29:45,755 | sd | DEBUG | styles | Load styles: folder="D:\stable-diffusion-webui-directml\models\styles" items=288
2023-11-10 18:29:45,762 | sd | DEBUG | webui | Creating UI
2023-11-10 18:29:45,984 | sd | INFO | theme | Load UI theme: name="black-teal" style=Dark base=style.css
2023-11-10 18:29:46,032 | sd | DEBUG | shared | Read: file="html\reference.json" len=14
2023-11-10 18:29:46,205 | sd | DEBUG | ui_extra_networks | Extra networks: page='model' items=23 subdirs=11 tab=txt2img dirs=['D:\\stable-diffusion-webui-directml\\models\\Stable-diffusion', 'D:\\stable-diffusion-webui-directml\\models\\Diffusers', 'models\\Reference', 'e:\\automatic\\models\\Stable-diffusion'] list=0.01 desc=0.00 info=0.00
2023-11-10 18:29:46,239 | sd | DEBUG | ui_extra_networks | Extra networks: page='style' items=288 subdirs=2 tab=txt2img dirs=['D:\\stable-diffusion-webui-directml\\models\\styles', 'html'] list=0.02 desc=0.00 info=0.00
2023-11-10 18:29:46,242 | sd | DEBUG | ui_extra_networks | Extra networks: page='embedding' items=0 subdirs=0 tab=txt2img dirs=['D:\\stable-diffusion-webui-directml\\models\\embeddings'] list=0.00 desc=0.00 info=0.00
2023-11-10 18:29:46,245 | sd | DEBUG | ui_extra_networks | Extra networks: page='hypernetwork' items=0 subdirs=0 tab=txt2img dirs=['D:\\stable-diffusion-webui-directml\\models\\hypernetworks'] list=0.00 desc=0.00 info=0.00
2023-11-10 18:29:46,247 | sd | DEBUG | ui_extra_networks | Extra networks: page='vae' items=0 subdirs=1 tab=txt2img dirs=['D:\\stable-diffusion-webui-directml\\models\\VAE'] list=0.00 desc=0.00 info=0.00
2023-11-10 18:29:46,272 | sd | DEBUG | ui_extra_networks | Extra networks: page='lora' items=231 subdirs=1 tab=txt2img dirs=['D:\\stable-diffusion-webui-directml\\models\\Lora', 'models\\LyCORIS'] list=0.14 desc=0.17 info=0.17
2023-11-10 18:29:46,466 | sd | DEBUG | shared | Read: file="ui-config.json" len=4
2023-11-10 18:29:46,673 | sd | DEBUG | theme | Themes: builtin=6 default=5 external=55
2023-11-10 18:29:47,310 | sd | DEBUG | script_callbacks | Script: 0.55 ui_tabs e:\automatic\extensions-builtin\stable-diffusion-webui-images-browser\scripts\image_browser.py
2023-11-10 18:29:47,316 | sd | DEBUG | shared | Read: file="E:\automatic\html\extensions.json" len=319
2023-11-10 18:29:48,359 | sd | DEBUG | ui_extensions | Extension list: processed=303 installed=10 enabled=8 disabled=2 visible=303 hidden=0
2023-11-10 18:29:48,675 | sd | INFO | webui | Local URL: http://127.0.0.1:7860/
2023-11-10 18:29:48,677 | sd | DEBUG | webui | Gradio registered functions: 1584
2023-11-10 18:29:48,679 | sd | INFO | middleware | Initializing middleware
2023-11-10 18:29:48,684 | sd | DEBUG | webui | Creating API
2023-11-10 18:29:48,903 | sd | INFO | task_runner | [AgentScheduler] Task queue is empty
2023-11-10 18:29:48,905 | sd | INFO | api | [AgentScheduler] Registering APIs
2023-11-10 18:29:49,017 | sd | DEBUG | webui | Scripts setup: ['X/Y/Z Grid:0.006', 'ReActor:0.008']
2023-11-10 18:29:49,019 | sd | DEBUG | sd_models | Model metadata: file="metadata.json" no changes
2023-11-10 18:29:49,021 | sd | DEBUG | webui | Model auto load disabled
2023-11-10 18:29:49,022 | sd | DEBUG | shared | Save: file="config.json" len=3210
2023-11-10 18:29:49,024 | sd | INFO | webui | Startup time: 18.02 { torch=6.67 gradio=0.90 diffusers=0.07 libraries=2.01 extensions=4.59 face-restore=0.32 upscalers=0.14 ui-extra-networks=0.51 ui-img2img=0.07 ui-settings=0.27 ui-extensions=1.65 ui-defaults=0.07 launch=0.24 api=0.09 app-started=0.25 }
2023-11-10 18:30:00,130 | sd | DEBUG | launch | Server alive=True jobs=0 requests=2 uptime=21 memory used=0.83 total=15.93 idle
2023-11-10 18:30:10,307 | sd | DEBUG | theme | Themes: builtin=6 default=5 external=55
2023-11-10 18:30:10,570 | sd | INFO | api | Browser session: client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2023-11-10 18:30:18,216 | sd | INFO | sd_models | Select: model="epicphotogasm_z [d37263937f]"
2023-11-10 18:30:18,583 | sd | DEBUG | sd_models | Load model weights: existing=False target=D:\stable-diffusion-webui-directml\models\Stable-diffusion\epicphotogasm_z.safetensors info=None
2023-11-10 18:30:18,630 | sd | INFO | devices | Torch override dtype: no-half set
2023-11-10 18:30:18,632 | sd | INFO | devices | Torch override VAE dtype: no-half set
2023-11-10 18:30:18,633 | sd | DEBUG | devices | Desired Torch parameters: dtype=FP16 no-half=True no-half-vae=True upscast=False
2023-11-10 18:30:18,634 | sd | INFO | devices | Setting Torch parameters: device=privateuseone:0 dtype=torch.float32 vae=torch.float32 unet=torch.float32 context=no_grad fp16=True bf16=False
2023-11-10 18:30:18,636 | sd | INFO | sd_models | Autodetect: model="Stable Diffusion" class=StableDiffusionPipeline file="D:\stable-diffusion-webui-directml\models\Stable-diffusion\epicphotogasm_z.safetensors" size=2034MB
2023-11-10 18:30:21,756 | sd | DEBUG | sd_models | Setting model: pipeline=StableDiffusionPipeline config={'low_cpu_mem_usage': True, 'torch_dtype': torch.float32, 'load_connected_pipeline': True, 'extract_ema': True, 'force_zeros_for_empty_prompt ': True, 'requires_aesthetics_score': False, 'use_safetensors': True}
2023-11-10 18:30:21,758 | sd | DEBUG | sd_models | Setting model: enable VAE slicing
2023-11-10 18:30:21,761 | sd | DEBUG | sd_models | Setting model: enable VAE tiling
2023-11-10 18:30:21,768 | sd | DEBUG | sd_models | Setting model VAE: name=None upcast=True
2023-11-10 18:30:26,603 | sd | INFO | textual_inversion | Load embeddings: loaded=0 skipped=0 time=0.00
2023-11-10 18:30:26,861 | sd | DEBUG | devices | gc: collected=973 device=privateuseone:0 {'ram': {'used': 2.29, 'total': 15.93}, 'gpu': {'used': 4.17, 'total': 5.59}, 'retries': 0, 'oom': 0}
2023-11-10 18:30:26,867 | sd | INFO | sd_models | Load model: time=8.02 { load=8.02 } native=512 {'ram': {'used': 2.29, 'total': 15.93}, 'gpu': {'used': 4.17, 'total': 5.59}, 'retries': 0, 'oom': 0}
2023-11-10 18:31:00,227 | sd | DEBUG | txt2img | txt2img: id_task=task(59n6r223sltey2v)|prompt=Cheerleaders cheering on the school field,  <lora:lcm-lora-sd15:1.0>|negative_prompt=colorful, vibrant, noisy, blurry, deformed, (deformed, distorted, disfigured:1.3),poorly drawn,bad anatomy,wrong anatomy,extra limb,missing limb,floating limbs,(mutated hands and fingers:1.4),disconnected limbs,mutation,mutated,ugly,disgusting,blurry,amputation|prompt_styles=[]|steps=4|sampler_index=15|latent_index=0|full_quality=True|restore_faces=False|tiling=False|n_iter=1|batch_size=1|cfg_scale=2|clip_skip=1|seed=-1.0|subseed=-1.0|subseed_strength=0|seed_resize_from_h=0|seed_resize_from_w=0||height=512|width=512|enable_hr=False|denoising_strength=0.5|hr_scale=2|hr_upscaler=None|hr_force=False|hr_second_pass_steps=20|hr_resize_x=0|hr_resize_y=0|image_cfg_scale=6|diffusers_guidance_rescale=0.7|refiner_steps=5|refiner_start=0.8|refiner_prompt=|refiner_negative=|override_settings_texts=[]
2023-11-10 18:31:00,232 | sd | INFO | sd_hijack_hypertile | Applying hypertile: unet=256
2023-11-10 18:31:00,713 | sd | INFO | extra_networks_lora | Applying LoRA: ['lcm-lora-sd15'] patch=0.00 load=0.46
2023-11-10 18:31:00,717 | sd | DEBUG | sd_samplers | Sampler: sampler="LCM" config={'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'prediction_type': 'epsilon', 'set_alpha_to_one': False, 'rescale_betas_zero_snr': False}
2023-11-10 18:31:01,253 | sd | DEBUG | processing_diffusers | Diffuser pipeline: StableDiffusionPipeline task=DiffusersTaskType.TEXT_2_IMAGE set={'prompt_embeds': torch.Size([1, 77, 768]), 'negative_prompt_embeds': torch.Size([1, 77, 768]), 'guidance_scale': 2, 'generator': device(type='cpu'), 'output_type': 'latent', 'num_inference_steps': 4, 'eta': 1.0, 'guidance_rescale': 0.7, 'height': 512, 'width': 512, 'parser': 'Full parser'}
2023-11-10 18:31:10,621 | sd | DEBUG | processing_diffusers | Moving to CPU: model=UNet
2023-11-10 18:31:13,220 | sd | DEBUG | processing_diffusers | VAE decode: name=baked dtype=torch.float32 upcast=False images=1 latents=torch.Size([1, 4, 64, 64]) time=2.598
2023-11-10 18:31:13,237 | sd | DEBUG | images | Saving: image="outputs\text\00106-epicphotogasm_z-Cheerleaders cheering on the school field lora lcm.jpg" type=JPEG size=512x512
2023-11-10 18:31:13,244 | sd | INFO | processing | Processed: images=1 time=13.00 its=0.31 memory={'ram': {'used': 5.33, 'total': 15.93}, 'gpu': {'used': 6.98, 'total': 9.82}, 'retries': 0, 'oom': 0}
2023-11-10 18:32:00,159 | sd | DEBUG | launch | Server alive=True jobs=0 requests=115 uptime=141 memory used=5.33 total=15.93 idle
2023-11-10 18:33:38,900 | sd | INFO | sd_models | Select: model="epicrealism_naturalSinRC1VAE [84d76a0328]"
2023-11-10 18:33:38,906 | sd | DEBUG | sd_models | Load model weights: existing=False target=D:\stable-diffusion-webui-directml\models\Stable-diffusion\epicrealism_naturalSinRC1VAE.safetensors info=None
2023-11-10 18:33:38,953 | sd | DEBUG | sd_models | Unload weights model: {'ram': {'used': 5.33, 'total': 15.93}, 'gpu': {'used': 6.97, 'total': 9.81}, 'retries': 0, 'oom': 0}
2023-11-10 18:33:39,219 | sd | DEBUG | devices | gc: collected=967 device=privateuseone:0 {'ram': {'used': 5.33, 'total': 15.93}, 'gpu': {'used': 6.97, 'total': 9.81}, 'retries': 0, 'oom': 0}
2023-11-10 18:33:39,493 | sd | INFO | devices | Torch override dtype: no-half set
2023-11-10 18:33:39,495 | sd | INFO | devices | Torch override VAE dtype: no-half set
2023-11-10 18:33:39,496 | sd | DEBUG | devices | Desired Torch parameters: dtype=FP16 no-half=True no-half-vae=True upscast=False
2023-11-10 18:33:39,497 | sd | INFO | devices | Setting Torch parameters: device=privateuseone:0 dtype=torch.float32 vae=torch.float32 unet=torch.float32 context=no_grad fp16=True bf16=False
2023-11-10 18:33:39,499 | sd | INFO | sd_models | Autodetect: model="Stable Diffusion" class=StableDiffusionPipeline file="D:\stable-diffusion-webui-directml\models\Stable-diffusion\epicrealism_naturalSinRC1VAE.safetensors" size=2034MB
2023-11-10 18:33:42,895 | sd | DEBUG | sd_models | Setting model: pipeline=StableDiffusionPipeline config={'low_cpu_mem_usage': True, 'torch_dtype': torch.float32, 'load_connected_pipeline': True, 'extract_ema': True, 'force_zeros_for_empty_prompt ': True, 'requires_aesthetics_score': False, 'use_safetensors': True}
2023-11-10 18:33:42,897 | sd | DEBUG | sd_models | Setting model: enable VAE slicing
2023-11-10 18:33:42,899 | sd | DEBUG | sd_models | Setting model: enable VAE tiling
2023-11-10 18:33:42,905 | sd | DEBUG | sd_models | Setting model VAE: name=None upcast=True
2023-11-10 18:33:43,724 | sd | INFO | textual_inversion | Load embeddings: loaded=0 skipped=0 time=0.00
2023-11-10 18:33:43,995 | sd | DEBUG | devices | gc: collected=1226 device=privateuseone:0 {'ram': {'used': 5.01, 'total': 15.93}, 'gpu': {'used': 6.97, 'total': 9.81}, 'retries': 0, 'oom': 0}
2023-11-10 18:33:44,000 | sd | INFO | sd_models | Load model: time=4.49 { load=4.49 } native=512 {'ram': {'used': 5.01, 'total': 15.93}, 'gpu': {'used': 6.97, 'total': 9.81}, 'retries': 0, 'oom': 0}
2023-11-10 18:33:44,006 | sd | DEBUG | shared | Save: file="config.json" len=3223
2023-11-10 18:33:44,007 | sd | DEBUG | ui | Setting changed: key=sd_model_checkpoint, value=epicrealism_naturalSinRC1VAE [84d76a0328]
2023-11-10 18:33:49,347 | sd | DEBUG | txt2img | txt2img: id_task=task(0j8go7xox6ymjeg)|prompt=Cheerleaders cheering on the school field,  <lora:lcm-lora-sd15:1.0>|negative_prompt=colorful, vibrant, noisy, blurry, deformed, (deformed, distorted, disfigured:1.3),poorly drawn,bad anatomy,wrong anatomy,extra limb,missing limb,floating limbs,(mutated hands and fingers:1.4),disconnected limbs,mutation,mutated,ugly,disgusting,blurry,amputation|prompt_styles=[]|steps=4|sampler_index=15|latent_index=0|full_quality=True|restore_faces=False|tiling=False|n_iter=1|batch_size=1|cfg_scale=2|clip_skip=1|seed=-1.0|subseed=-1.0|subseed_strength=0|seed_resize_from_h=0|seed_resize_from_w=0||height=512|width=512|enable_hr=False|denoising_strength=0.5|hr_scale=2|hr_upscaler=None|hr_force=False|hr_second_pass_steps=20|hr_resize_x=0|hr_resize_y=0|image_cfg_scale=6|diffusers_guidance_rescale=0.7|refiner_steps=5|refiner_start=0.8|refiner_prompt=|refiner_negative=|override_settings_texts=[]
2023-11-10 18:33:49,352 | sd | INFO | sd_hijack_hypertile | Applying hypertile: unet=256
2023-11-10 18:33:49,912 | sd | INFO | extra_networks_lora | Applying LoRA: ['lcm-lora-sd15'] patch=0.00 load=0.55
2023-11-10 18:33:49,915 | sd | DEBUG | sd_samplers | Sampler: sampler="LCM" config={'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'prediction_type': 'epsilon', 'set_alpha_to_one': False, 'rescale_betas_zero_snr': False}
2023-11-10 18:33:50,296 | sd | DEBUG | processing_diffusers | Diffuser pipeline: StableDiffusionPipeline task=DiffusersTaskType.TEXT_2_IMAGE set={'prompt_embeds': torch.Size([1, 77, 768]), 'negative_prompt_embeds': torch.Size([1, 77, 768]), 'guidance_scale': 2, 'generator': device(type='cpu'), 'output_type': 'latent', 'num_inference_steps': 4, 'eta': 1.0, 'guidance_rescale': 0.7, 'height': 512, 'width': 512, 'parser': 'Full parser'}
2023-11-10 18:33:55,481 | sd | DEBUG | processing_diffusers | Moving to CPU: model=UNet
2023-11-10 18:33:57,783 | sd | DEBUG | processing_diffusers | VAE decode: name=baked dtype=torch.float32 upcast=False images=1 latents=torch.Size([1, 4, 64, 64]) time=2.301
2023-11-10 18:33:57,934 | sd | DEBUG | images | Saving: image="outputs\text\00107-epicrealism_naturalSinRC1VAE-Cheerleaders cheering on the school field lora lcm.jpg" type=JPEG size=512x512
2023-11-10 18:33:57,940 | sd | INFO | processing | Processed: images=1 time=8.58 its=0.47 memory={'ram': {'used': 6.58, 'total': 15.93}, 'gpu': {'used': 6.97, 'total': 9.82}, 'retries': 0, 'oom': 0}
2023-11-10 18:34:00,109 | sd | DEBUG | launch | Server alive=True jobs=0 requests=116 uptime=261 memory used=6.58 total=15.93 idle
2023-11-10 18:35:01,370 | sd | DEBUG | txt2img | txt2img: id_task=task(jcm7466an04td0i)|prompt=Cheerleaders cheering on the school field,  <lora:lcm-lora-sd15:1.0>|negative_prompt=colorful, vibrant, noisy, blurry, deformed, (deformed, distorted, disfigured:1.3),poorly drawn,bad anatomy,wrong anatomy,extra limb,missing limb,floating limbs,(mutated hands and fingers:1.4),disconnected limbs,mutation,mutated,ugly,disgusting,blurry,amputation|prompt_styles=[]|steps=4|sampler_index=15|latent_index=0|full_quality=True|restore_faces=False|tiling=False|n_iter=1|batch_size=1|cfg_scale=2|clip_skip=1|seed=-1.0|subseed=-1.0|subseed_strength=0|seed_resize_from_h=0|seed_resize_from_w=0||height=512|width=512|enable_hr=False|denoising_strength=0.5|hr_scale=2|hr_upscaler=None|hr_force=False|hr_second_pass_steps=20|hr_resize_x=0|hr_resize_y=0|image_cfg_scale=6|diffusers_guidance_rescale=0.7|refiner_steps=5|refiner_start=0.8|refiner_prompt=|refiner_negative=|override_settings_texts=[]
2023-11-10 18:35:01,375 | sd | INFO | sd_hijack_hypertile | Applying hypertile: unet=256
2023-11-10 18:35:01,908 | sd | INFO | extra_networks_lora | Applying LoRA: ['lcm-lora-sd15'] patch=0.00 load=0.53
2023-11-10 18:35:01,911 | sd | DEBUG | sd_samplers | Sampler: sampler="LCM" config={'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'prediction_type': 'epsilon', 'set_alpha_to_one': False, 'rescale_betas_zero_snr': False}
2023-11-10 18:35:02,056 | sd | DEBUG | processing_diffusers | Diffuser pipeline: StableDiffusionPipeline task=DiffusersTaskType.TEXT_2_IMAGE set={'prompt_embeds': torch.Size([1, 77, 768]), 'negative_prompt_embeds': torch.Size([1, 77, 768]), 'guidance_scale': 2, 'generator': device(type='cpu'), 'output_type': 'latent', 'num_inference_steps': 4, 'eta': 1.0, 'guidance_rescale': 0.7, 'height': 512, 'width': 512, 'parser': 'Full parser'}
2023-11-10 18:35:06,553 | sd | DEBUG | processing_diffusers | Moving to CPU: model=UNet
2023-11-10 18:35:08,872 | sd | DEBUG | processing_diffusers | VAE decode: name=baked dtype=torch.float32 upcast=False images=1 latents=torch.Size([1, 4, 64, 64]) time=2.319
2023-11-10 18:35:08,999 | sd | DEBUG | images | Saving: image="outputs\text\00108-epicrealism_naturalSinRC1VAE-Cheerleaders cheering on the school field lora lcm.jpg" type=JPEG size=512x512
2023-11-10 18:35:09,006 | sd | INFO | processing | Processed: images=1 time=7.63 its=0.52 memory={'ram': {'used': 6.89, 'total': 15.93}, 'gpu': {'used': 6.97, 'total': 9.9}, 'retries': 0, 'oom': 0}
2023-11-10 18:36:00,048 | sd | DEBUG | launch | Server alive=True jobs=0 requests=117 uptime=381 memory used=6.88 total=15.93 idle
2023-11-10 18:36:15,494 | sd | DEBUG | txt2img | txt2img: id_task=task(ll8ifb2uq7dt4z0)|prompt=Cheerleaders cheering on the school field,  <lora:lcm-lora-sd15:1.0>|negative_prompt=colorful, vibrant, noisy, blurry, deformed, (deformed, distorted, disfigured:1.3),poorly drawn,bad anatomy,wrong anatomy,extra limb,missing limb,floating limbs,(mutated hands and fingers:1.4),disconnected limbs,mutation,mutated,ugly,disgusting,blurry,amputation|prompt_styles=[]|steps=8|sampler_index=15|latent_index=0|full_quality=True|restore_faces=False|tiling=False|n_iter=1|batch_size=1|cfg_scale=2|clip_skip=1|seed=-1.0|subseed=-1.0|subseed_strength=0|seed_resize_from_h=0|seed_resize_from_w=0||height=512|width=512|enable_hr=False|denoising_strength=0.5|hr_scale=2|hr_upscaler=None|hr_force=False|hr_second_pass_steps=20|hr_resize_x=0|hr_resize_y=0|image_cfg_scale=6|diffusers_guidance_rescale=0.7|refiner_steps=5|refiner_start=0.8|refiner_prompt=|refiner_negative=|override_settings_texts=[]
2023-11-10 18:36:15,501 | sd | INFO | sd_hijack_hypertile | Applying hypertile: unet=256
2023-11-10 18:36:16,036 | sd | INFO | extra_networks_lora | Applying LoRA: ['lcm-lora-sd15'] patch=0.00 load=0.53
2023-11-10 18:36:16,040 | sd | DEBUG | sd_samplers | Sampler: sampler="LCM" config={'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'prediction_type': 'epsilon', 'set_alpha_to_one': False, 'rescale_betas_zero_snr': False}
2023-11-10 18:36:16,204 | sd | DEBUG | processing_diffusers | Diffuser pipeline: StableDiffusionPipeline task=DiffusersTaskType.TEXT_2_IMAGE set={'prompt_embeds': torch.Size([1, 77, 768]), 'negative_prompt_embeds': torch.Size([1, 77, 768]), 'guidance_scale': 2, 'generator': device(type='cpu'), 'output_type': 'latent', 'num_inference_steps': 8, 'eta': 1.0, 'guidance_rescale': 0.7, 'height': 512, 'width': 512, 'parser': 'Full parser'}
2023-11-10 18:36:25,095 | sd | DEBUG | processing_diffusers | Moving to CPU: model=UNet
2023-11-10 18:36:27,330 | sd | DEBUG | processing_diffusers | VAE decode: name=baked dtype=torch.float32 upcast=False images=1 latents=torch.Size([1, 4, 64, 64]) time=2.235
2023-11-10 18:36:27,512 | sd | DEBUG | images | Saving: image="outputs\text\00109-epicrealism_naturalSinRC1VAE-Cheerleaders cheering on the school field lora lcm.jpg" type=JPEG size=512x512
2023-11-10 18:36:27,518 | sd | INFO | processing | Processed: images=1 time=12.01 its=0.67 memory={'ram': {'used': 7.14, 'total': 15.93}, 'gpu': {'used': 6.97, 'total': 9.9}, 'retries': 0, 'oom': 0}
2023-11-10 18:37:59,894 | sd | DEBUG | launch | Server alive=True jobs=0 requests=118 uptime=500 memory used=7.14 total=15.93 idle
2023-11-10 18:38:57,329 | sd | INFO | sd_models | Select: model="lyriel_v16 [ec6f68ea63]"
2023-11-10 18:38:57,331 | sd | DEBUG | sd_models | Load model weights: existing=False target=D:\stable-diffusion-webui-directml\models\Stable-diffusion\lyriel_v16.safetensors info=None
2023-11-10 18:38:57,349 | sd | DEBUG | sd_models | Unload weights model: {'ram': {'used': 7.14, 'total': 15.93}, 'gpu': {'used': 6.97, 'total': 9.9}, 'retries': 0, 'oom': 0}
2023-11-10 18:38:57,732 | sd | DEBUG | devices | gc: collected=36771 device=privateuseone:0 {'ram': {'used': 5.35, 'total': 15.93}, 'gpu': {'used': 6.97, 'total': 9.9}, 'retries': 0, 'oom': 0}
2023-11-10 18:38:57,880 | sd | INFO | devices | Torch override dtype: no-half set
2023-11-10 18:38:57,881 | sd | INFO | devices | Torch override VAE dtype: no-half set
2023-11-10 18:38:57,883 | sd | DEBUG | devices | Desired Torch parameters: dtype=FP16 no-half=True no-half-vae=True upscast=False
2023-11-10 18:38:57,884 | sd | INFO | devices | Setting Torch parameters: device=privateuseone:0 dtype=torch.float32 vae=torch.float32 unet=torch.float32 context=no_grad fp16=True bf16=False
2023-11-10 18:38:57,886 | sd | INFO | sd_models | Autodetect: model="Stable Diffusion" class=StableDiffusionPipeline file="D:\stable-diffusion-webui-directml\models\Stable-diffusion\lyriel_v16.safetensors" size=2034MB
2023-11-10 18:39:01,395 | sd | DEBUG | sd_models | Setting model: pipeline=StableDiffusionPipeline config={'low_cpu_mem_usage': True, 'torch_dtype': torch.float32, 'load_connected_pipeline': True, 'extract_ema': True, 'force_zeros_for_empty_prompt ': True, 'requires_aesthetics_score': False, 'use_safetensors': True}
2023-11-10 18:39:01,397 | sd | DEBUG | sd_models | Setting model: enable VAE slicing
2023-11-10 18:39:01,398 | sd | DEBUG | sd_models | Setting model: enable VAE tiling
2023-11-10 18:39:01,403 | sd | DEBUG | sd_models | Setting model VAE: name=None upcast=True
2023-11-10 18:39:02,166 | sd | INFO | textual_inversion | Load embeddings: loaded=0 skipped=0 time=0.00
2023-11-10 18:39:02,418 | sd | DEBUG | devices | gc: collected=1226 device=privateuseone:0 {'ram': {'used': 5.01, 'total': 15.93}, 'gpu': {'used': 6.97, 'total': 9.9}, 'retries': 0, 'oom': 0}
2023-11-10 18:39:02,423 | sd | INFO | sd_models | Load model: time=4.41 { load=4.41 } native=512 {'ram': {'used': 5.01, 'total': 15.93}, 'gpu': {'used': 6.97, 'total': 9.9}, 'retries': 0, 'oom': 0}
2023-11-10 18:39:02,427 | sd | DEBUG | shared | Save: file="config.json" len=3174
2023-11-10 18:39:02,429 | sd | DEBUG | ui | Setting changed: key=sd_model_checkpoint, value=lyriel_v16 [ec6f68ea63]
2023-11-10 18:39:11,225 | sd | DEBUG | txt2img | txt2img: id_task=task(a6tj9al7v4x400r)|prompt=Cheerleaders cheering on the school field,  <lora:lcm-lora-sd15:1.0>|negative_prompt=colorful, vibrant, noisy, blurry, deformed, (deformed, distorted, disfigured:1.3),poorly drawn,bad anatomy,wrong anatomy,extra limb,missing limb,floating limbs,(mutated hands and fingers:1.4),disconnected limbs,mutation,mutated,ugly,disgusting,blurry,amputation|prompt_styles=[]|steps=8|sampler_index=15|latent_index=0|full_quality=True|restore_faces=False|tiling=False|n_iter=1|batch_size=1|cfg_scale=2|clip_skip=1|seed=-1.0|subseed=-1.0|subseed_strength=0|seed_resize_from_h=0|seed_resize_from_w=0||height=512|width=512|enable_hr=False|denoising_strength=0.5|hr_scale=2|hr_upscaler=None|hr_force=False|hr_second_pass_steps=20|hr_resize_x=0|hr_resize_y=0|image_cfg_scale=6|diffusers_guidance_rescale=0.7|refiner_steps=5|refiner_start=0.8|refiner_prompt=|refiner_negative=|override_settings_texts=[]
2023-11-10 18:39:11,235 | sd | INFO | sd_hijack_hypertile | Applying hypertile: unet=256
2023-11-10 18:39:11,753 | sd | INFO | extra_networks_lora | Applying LoRA: ['lcm-lora-sd15'] patch=0.00 load=0.51
2023-11-10 18:39:11,756 | sd | DEBUG | sd_samplers | Sampler: sampler="LCM" config={'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'prediction_type': 'epsilon', 'set_alpha_to_one': False, 'rescale_betas_zero_snr': False}
2023-11-10 18:39:12,121 | sd | DEBUG | processing_diffusers | Diffuser pipeline: StableDiffusionPipeline task=DiffusersTaskType.TEXT_2_IMAGE set={'prompt_embeds': torch.Size([1, 77, 768]), 'negative_prompt_embeds': torch.Size([1, 77, 768]), 'guidance_scale': 2, 'generator': device(type='cpu'), 'output_type': 'latent', 'num_inference_steps': 8, 'eta': 1.0, 'guidance_rescale': 0.7, 'height': 512, 'width': 512, 'parser': 'Full parser'}
2023-11-10 18:39:21,750 | sd | DEBUG | processing_diffusers | Moving to CPU: model=UNet
2023-11-10 18:39:23,995 | sd | DEBUG | processing_diffusers | VAE decode: name=baked dtype=torch.float32 upcast=False images=1 latents=torch.Size([1, 4, 64, 64]) time=2.245
2023-11-10 18:39:24,208 | sd | DEBUG | images | Saving: image="outputs\text\00110-lyriel_v16-Cheerleaders cheering on the school field lora lcm.jpg" type=JPEG size=512x512
2023-11-10 18:39:24,214 | sd | INFO | processing | Processed: images=1 time=12.97 its=0.62 memory={'ram': {'used': 6.61, 'total': 15.93}, 'gpu': {'used': 6.98, 'total': 9.9}, 'retries': 0, 'oom': 0}
2023-11-10 18:39:55,744 | sd | INFO | sd_models | Select: model="photon_v1 [ec41bd2a82]"
2023-11-10 18:39:55,746 | sd | DEBUG | sd_models | Load model weights: existing=False target=D:\stable-diffusion-webui-directml\models\Stable-diffusion\photon_v1.safetensors info=None
2023-11-10 18:39:55,765 | sd | DEBUG | sd_models | Unload weights model: {'ram': {'used': 6.61, 'total': 15.93}, 'gpu': {'used': 6.98, 'total': 9.9}, 'retries': 0, 'oom': 0}
2023-11-10 18:39:56,149 | sd | DEBUG | devices | gc: collected=15761 device=privateuseone:0 {'ram': {'used': 5.33, 'total': 15.93}, 'gpu': {'used': 6.98, 'total': 9.9}, 'retries': 0, 'oom': 0}
2023-11-10 18:39:56,380 | sd | INFO | devices | Torch override dtype: no-half set
2023-11-10 18:39:56,382 | sd | INFO | devices | Torch override VAE dtype: no-half set
2023-11-10 18:39:56,383 | sd | DEBUG | devices | Desired Torch parameters: dtype=FP16 no-half=True no-half-vae=True upscast=False
2023-11-10 18:39:56,384 | sd | INFO | devices | Setting Torch parameters: device=privateuseone:0 dtype=torch.float32 vae=torch.float32 unet=torch.float32 context=no_grad fp16=True bf16=False
2023-11-10 18:39:56,386 | sd | INFO | sd_models | Autodetect: model="Stable Diffusion" class=StableDiffusionPipeline file="D:\stable-diffusion-webui-directml\models\Stable-diffusion\photon_v1.safetensors" size=2034MB
2023-11-10 18:39:59,612 | sd | DEBUG | sd_models | Setting model: pipeline=StableDiffusionPipeline config={'low_cpu_mem_usage': True, 'torch_dtype': torch.float32, 'load_connected_pipeline': True, 'extract_ema': True, 'force_zeros_for_empty_prompt ': True, 'requires_aesthetics_score': False, 'use_safetensors': True}
2023-11-10 18:39:59,614 | sd | DEBUG | sd_models | Setting model: enable VAE slicing
2023-11-10 18:39:59,615 | sd | DEBUG | sd_models | Setting model: enable VAE tiling
2023-11-10 18:39:59,620 | sd | DEBUG | sd_models | Setting model VAE: name=None upcast=True
2023-11-10 18:40:00,103 | sd | DEBUG | launch | Server alive=True jobs=0 requests=119 uptime=621 memory used=8.27 total=15.93 idle
2023-11-10 18:40:00,504 | sd | INFO | textual_inversion | Load embeddings: loaded=0 skipped=0 time=0.00
2023-11-10 18:40:00,744 | sd | DEBUG | devices | gc: collected=1321 device=privateuseone:0 {'ram': {'used': 4.99, 'total': 15.93}, 'gpu': {'used': 6.98, 'total': 9.9}, 'retries': 0, 'oom': 0}
2023-11-10 18:40:00,749 | sd | INFO | sd_models | Load model: time=4.34 { load=4.34 } native=512 {'ram': {'used': 4.99, 'total': 15.93}, 'gpu': {'used': 6.98, 'total': 9.9}, 'retries': 0, 'oom': 0}
2023-11-10 18:40:00,753 | sd | DEBUG | shared | Save: file="config.json" len=3173
2023-11-10 18:40:00,755 | sd | DEBUG | ui | Setting changed: key=sd_model_checkpoint, value=photon_v1 [ec41bd2a82]
2023-11-10 18:40:02,536 | sd | DEBUG | txt2img | txt2img: id_task=task(tp4enyrjhdwclkv)|prompt=Cheerleaders cheering on the school field,  <lora:lcm-lora-sd15:1.0>|negative_prompt=colorful, vibrant, noisy, blurry, deformed, (deformed, distorted, disfigured:1.3),poorly drawn,bad anatomy,wrong anatomy,extra limb,missing limb,floating limbs,(mutated hands and fingers:1.4),disconnected limbs,mutation,mutated,ugly,disgusting,blurry,amputation|prompt_styles=[]|steps=8|sampler_index=15|latent_index=0|full_quality=True|restore_faces=False|tiling=False|n_iter=1|batch_size=1|cfg_scale=2|clip_skip=1|seed=-1.0|subseed=-1.0|subseed_strength=0|seed_resize_from_h=0|seed_resize_from_w=0||height=512|width=512|enable_hr=False|denoising_strength=0.5|hr_scale=2|hr_upscaler=None|hr_force=False|hr_second_pass_steps=20|hr_resize_x=0|hr_resize_y=0|image_cfg_scale=6|diffusers_guidance_rescale=0.7|refiner_steps=5|refiner_start=0.8|refiner_prompt=|refiner_negative=|override_settings_texts=[]
2023-11-10 18:40:02,542 | sd | INFO | sd_hijack_hypertile | Applying hypertile: unet=256
2023-11-10 18:40:03,098 | sd | INFO | extra_networks_lora | Applying LoRA: ['lcm-lora-sd15'] patch=0.00 load=0.55
2023-11-10 18:40:03,102 | sd | DEBUG | sd_samplers | Sampler: sampler="LCM" config={'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'prediction_type': 'epsilon', 'set_alpha_to_one': False, 'rescale_betas_zero_snr': False}
2023-11-10 18:40:03,487 | sd | DEBUG | processing_diffusers | Diffuser pipeline: StableDiffusionPipeline task=DiffusersTaskType.TEXT_2_IMAGE set={'prompt_embeds': torch.Size([1, 77, 768]), 'negative_prompt_embeds': torch.Size([1, 77, 768]), 'guidance_scale': 2, 'generator': device(type='cpu'), 'output_type': 'latent', 'num_inference_steps': 8, 'eta': 1.0, 'guidance_rescale': 0.7, 'height': 512, 'width': 512, 'parser': 'Full parser'}
2023-11-10 18:40:13,167 | sd | DEBUG | processing_diffusers | Moving to CPU: model=UNet
2023-11-10 18:40:15,500 | sd | DEBUG | processing_diffusers | VAE decode: name=baked dtype=torch.float32 upcast=False images=1 latents=torch.Size([1, 4, 64, 64]) time=2.332
2023-11-10 18:40:15,601 | sd | DEBUG | images | Saving: image="outputs\text\00111-photon_v1-Cheerleaders cheering on the school field lora lcm.jpg" type=JPEG size=512x512
2023-11-10 18:40:15,607 | sd | INFO | processing | Processed: images=1 time=13.06 its=0.61 memory={'ram': {'used': 6.85, 'total': 15.93}, 'gpu': {'used': 6.98, 'total': 10.19}, 'retries': 0, 'oom': 0}
2023-11-10 18:41:59,955 | sd | DEBUG | launch | Server alive=True jobs=0 requests=120 uptime=741 memory used=6.84 total=15.93 idle
2023-11-10 18:43:59,864 | sd | DEBUG | launch | Server alive=True jobs=0 requests=120 uptime=860 memory used=6.84 total=15.93 idle
2023-11-10 18:45:59,818 | sd | DEBUG | launch | Server alive=True jobs=0 requests=120 uptime=980 memory used=6.84 total=15.93 idle
2023-11-10 18:47:59,947 | sd | DEBUG | launch | Server alive=True jobs=0 requests=120 uptime=1101 memory used=6.84 total=15.93 idle
2023-11-10 18:50:00,107 | sd | DEBUG | launch | Server alive=True jobs=0 requests=120 uptime=1221 memory used=6.84 total=15.93 idle
2023-11-10 18:52:00,243 | sd | DEBUG | launch | Server alive=True jobs=0 requests=120 uptime=1341 memory used=6.84 total=15.93 idle
```

### Backend

Diffusers

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i understand your issue, but i'm not going over all possible combinations - if hypertile with lcm results in bad quality, it is what it is unless you want to contribute. such edge cases take extreme amount of time for very little return.

**Comment by patientx** [comment]
Having the same out of memory problems in comfyui as well, so tried hypertile there, the output problem isn't present there.

**Comment by vladmandic** [comment]
i believe you and i'm sure its solvable, but i cannot dedicate time to it.

**Comment by patientx** [comment]
OK, No problem. Thanks for your hardwork. I found a workaround. Using SDE as a sampler is "slower" but still produces impressive results in just 4 steps.

**Comment by vladmandic** [comment]
when you report upstream, you can mark that issue here for tracking purposes.
