### ISSUE TITLE
[Issue]: CUDA Crash

### ISSUE THREAD

**Issue by TheDuriel** [vladmandic/automatic#277]
### Issue Description

After generating a number of images, with no apparent direct cause, I get this crash; requiring a restart.:

Log (Which I think contains the same crash twice.):
```
venv "D:\Projects\AWaifuGenerator\automatic\venv\Scripts\Python.exe"
12:43:38-824897 INFO     Python 3.10.6 on Windows
12:43:38-908671 INFO     Running setup
12:43:38-945573 INFO     Version: e6701f5c Wed Apr 19 14:12:19 2023 -0400
12:43:39-364908 INFO     Updating Wiki
12:43:41-503641 INFO     Installing requirements
12:43:41-833759 INFO     Installing packages
12:43:41-835753 INFO     Installing repositories
12:43:42-001311 INFO     Installing submodules
12:43:52-833065 INFO     Updating submodules
12:44:04-851900 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'model-keyword', 'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker',
                         'ScuNET', 'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer',
                         'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-controlnet',
                         'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR']
12:44:26-951572 INFO     Extensions enabled: ['a1111-sd-webui-tagcomplete', 'stable-diffusion-webui-sonar']
12:44:28-318181 INFO     Setting environment tuning
12:44:30-015427 INFO     Torch 2.0.0+cu118
12:44:30-034405 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
12:44:30-037369 INFO     Torch detected GPU: NVIDIA GeForce RTX 2070 SUPER VRAM 8192 Arch (7, 5) Cores 40
12:44:30-039363 INFO     Torch detected GPU: NVIDIA GeForce GTX 745 VRAM 4096 Arch (5, 0) Cores 3
12:44:30-040360 INFO     Server arguments: []
Available models: D:\Projects\AWaifuGenerator\automatic\models\Stable-diffusion 10
Loading theme: black-orange
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Loading weights: D:\Projects\AWaifuGenerator\automatic\models\Stable-diffusion\corneos7thHeavenMix_v2.safetensors -  -…
Creating model from config: D:\Projects\AWaifuGenerator\automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights: D:\Projects\AWaifuGenerator\automatic\models\Stable-diffusion\nai.vae.pt ---------- 0.0/822.8  -:--:--
                                                                                                     MB
Applying scaled dot product cross attention optimization
Embeddings loaded:  (0)
Model loaded in 3.3s (load=0.6s create=0.4s apply=0.6s vae=1.1s move=0.5s)
Startup time: 17.1s (torch=4.2s gradio=1.7s libraries=0.8s codeformer=0.1s scripts=3.6s ui=2.8s start=0.1s scripts
app_started_callback=0.1s checkpoint=3.6s)
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:08<00:00,  1.18it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.27it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.21it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.29it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.43it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.38it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.35it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.33it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:09<00:00,  2.21it/s]
 45%|█████████████████████████████████████▎                                             | 9/20 [00:03<00:04,  2.58it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.41it/s]
Exception in thread MemMon:
Traceback (most recent call last):
  File "C:\Users\Duriel\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\Projects\AWaifuGenerator\automatic\modules\memmon.py", line 56, in run
    free, total = self.cuda_mem_get_info()
  File "D:\Projects\AWaifuGenerator\automatic\modules\memmon.py", line 37, in cuda_mem_get_info
    return torch.cuda.mem_get_info(index)
  File "D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\torch\cuda\memory.py", line 618, in mem_get_info
    return torch.cuda.cudart().cudaMemGetInfo(device)
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

API error: POST: http://127.0.0.1:7860/internal/progress {'error': 'RuntimeError', 'detail': '', 'body': '', 'errors': 'CUDA error: misaligned address\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n'}
HTTP API: RuntimeError
gradio call: RuntimeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\Projects\AWaifuGenerator\automatic\modules\call_queue.py:61 in f                                                 │
│                                                                                                                     │
│    60 │   │   │   │   pr.enable()                                                                                   │
│ >  61 │   │   │   res = list(func(*args, **kwargs))                                                                 │
│    62 │   │   │   if shared.cmd_opts.profile:                                                                       │
│                                                                                                                     │
│ D:\Projects\AWaifuGenerator\automatic\modules\call_queue.py:39 in f                                                 │
│                                                                                                                     │
│    38 │   │   │   try:                                                                                              │
│ >  39 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    40 │   │   │   finally:                                                                                          │
│                                                                                                                     │
│                                               ... 2 frames hidden ...                                               │
│                                                                                                                     │
│ D:\Projects\AWaifuGenerator\automatic\modules\processing.py:662 in process_images_inner                             │
│                                                                                                                     │
│    661 │   │   │                                                                                                    │
│ >  662 │   │   │   x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtyp                     │
│    663 │   │   │   for x in x_samples_ddim:                                                                         │
│                                                                                                                     │
│ D:\Projects\AWaifuGenerator\automatic\modules\processing.py:662 in <listcomp>                                       │
│                                                                                                                     │
│    661 │   │   │                                                                                                    │
│ >  662 │   │   │   x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtyp                     │
│    663 │   │   │   for x in x_samples_ddim:                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\anyio\streams\memory.py:94 in receive                  │
│                                                                                                                     │
│ D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\anyio\streams\memory.py:89 in receive_nowait           │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
WouldBlock

During handling of the above exception, another exception occurred:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\starlette\middleware\base.py:78 in call_next           │
│                                                                                                                     │
│ D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\anyio\streams\memory.py:114 in receive                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
EndOfStream

During handling of the above exception, another exception occurred:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\Projects\AWaifuGenerator\automatic\modules\middleware.py:68 in exception_handling                                │
│                                                                                                                     │
│   67 │   │   try:                                                                                                   │
│ > 68 │   │   │   return await call_next(req)                                                                        │
│   69 │   │   except CancelledError:                                                                                 │
│                                                                                                                     │
│ D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\starlette\middleware\base.py:84 in call_next           │
│                                                                                                                     │
│                                              ... 37 frames hidden ...                                               │
│                                                                                                                     │
│ D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\torch\nn\modules\normalization.py:273 in forward       │
│                                                                                                                     │
│   272 │   def forward(self, input: Tensor) -> Tensor:                                                               │
│ > 273 │   │   return F.group_norm(                                                                                  │
│   274 │   │   │   input, self.num_groups, self.weight, self.bias, self.eps)                                         │
│                                                                                                                     │
│ D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\torch\nn\functional.py:2530 in group_norm              │
│                                                                                                                     │
│   2529 │   _verify_batch_size([input.size(0) * input.size(1) // num_groups, num_groups] + list(                     │
│ > 2530 │   return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.e                     │
│   2531                                                                                                              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Projects\AWaifuGenerator\automatic\modules\call_queue.py", line 93, in f
    mem_stats = {k: -(v//-(1024*1024)) for k, v in shared.mem_mon.stop().items()}
  File "D:\Projects\AWaifuGenerator\automatic\modules\memmon.py", line 95, in stop
    return self.read()
  File "D:\Projects\AWaifuGenerator\automatic\modules\memmon.py", line 80, in read
    free, total = self.cuda_mem_get_info()
  File "D:\Projects\AWaifuGenerator\automatic\modules\memmon.py", line 37, in cuda_mem_get_info
    return torch.cuda.mem_get_info(index)
  File "D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\torch\cuda\memory.py", line 618, in mem_get_info
    return torch.cuda.cudart().cudaMemGetInfo(device)
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

gradio call: RuntimeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\Projects\AWaifuGenerator\automatic\modules\call_queue.py:61 in f                                                 │
│                                                                                                                     │
│    60 │   │   │   │   pr.enable()                                                                                   │
│ >  61 │   │   │   res = list(func(*args, **kwargs))                                                                 │
│    62 │   │   │   if shared.cmd_opts.profile:                                                                       │
│                                                                                                                     │
│ D:\Projects\AWaifuGenerator\automatic\modules\call_queue.py:35 in f                                                 │
│                                                                                                                     │
│    34 │   │   with queue_lock:                                                                                      │
│ >  35 │   │   │   shared.state.begin()                                                                              │
│    36 │   │   │   progress.start_task(id_task)                                                                      │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ D:\Projects\AWaifuGenerator\automatic\modules\devices.py:59 in torch_gc                                             │
│                                                                                                                     │
│    58 │   │   with torch.cuda.device(get_cuda_device_string()):                                                     │
│ >  59 │   │   │   torch.cuda.empty_cache()                                                                          │
│    60 │   │   │   torch.cuda.ipc_collect()                                                                          │
│                                                                                                                     │
│ D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\torch\cuda\memory.py:133 in empty_cache                │
│                                                                                                                     │
│   132 │   if is_initialized():                                                                                      │
│ > 133 │   │   torch._C._cuda_emptyCache()                                                                           │
│   134                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Projects\AWaifuGenerator\automatic\modules\call_queue.py", line 93, in f
    mem_stats = {k: -(v//-(1024*1024)) for k, v in shared.mem_mon.stop().items()}
  File "D:\Projects\AWaifuGenerator\automatic\modules\memmon.py", line 95, in stop
    return self.read()
  File "D:\Projects\AWaifuGenerator\automatic\modules\memmon.py", line 80, in read
    free, total = self.cuda_mem_get_info()
  File "D:\Projects\AWaifuGenerator\automatic\modules\memmon.py", line 37, in cuda_mem_get_info
    return torch.cuda.mem_get_info(index)
  File "D:\Projects\AWaifuGenerator\automatic\venv\lib\site-packages\torch\cuda\memory.py", line 618, in mem_get_info
    return torch.cuda.cudart().cudaMemGetInfo(device)
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### Version Platform Description

Version: e6701f5c Wed Apr 19 14:12:19 2023 -0400

![image](https://user-images.githubusercontent.com/44248915/233344757-128564cb-ad95-4d02-b2a6-99ea1c0e0bb4.png)

Processor	Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz   3.60 GHz
Installed RAM	32.0 GB
GPU0		Nvidia RTX 2070SUPER
GPU1		Nvidia GTX 745 4G

**Comment by vladmandic** [comment]
i'm sorry that it happend, but not sure if i can do anything about it here.
typically, that can happen if display drivers are changed/updated and you try to use app without performing system reboot first.

**Comment by TheDuriel** [comment]
Still happening after driver update, cuda update, and restart. Will do more investigation before complaining more tho.

**Comment by uwidev** [comment]
I have a GTX1070, and for some reason, I keep having issues with anything above pytorch 2.0+. I had a similar error when trying to run [LoRA_Easy_Training_Scripts](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts) with anything above 2.0. I feel like it's a GPU compatibility issue or something.

In my case, generation seems to be a coin flip as to whether they will work or not. I have generation running for several batches, and then I get some memory not aligned error or something and I have to restart the entire webui all over again.

Here's some logs and system info on my end.

![image](https://user-images.githubusercontent.com/10101319/233800355-13091680-4bce-4a89-b075-7c7f1597e4a0.png)

![image](https://user-images.githubusercontent.com/10101319/233798287-ce25a0fe-0f3a-4ed8-b377-06f6437a22b4.png)

**Comment by TheDuriel** [comment]
@uwidev My issue turned out to be VRAM most likely. Crashes have gone away once I reduced the batch size back to 1.

It appears this repo might have higher requirements than base automatic.

**Comment by vladmandic** [comment]
Yeah, misaligned access is deep inside torch, not in the app.
If you feel adventurous, you could try torch 2.1 nightly.

**Comment by uwidev** [comment]
> @uwidev My issue turned out to be VRAM most likely. Crashes have gone away once I reduced the batch size back to 1. (One crash every few thousand images at most.)
> 
> It appears this repo might have higher requirements than base automatic.

Running at medvram seems to have stopped my crashes, but I don't know if running medvram would be worth the performance loss compared to the original repo.

That said, I really do wonder if this is a fork issue or merely a torch 2.0 issue. Would it be possible to downgrade to the torch version on the original repo? If so, how would I go about doing so (cause there seems to be some dependency finicky stuff too).

**Comment by vladmandic** [comment]
you should be able to try any torch.
1. `pip uninstall torch torchaudio torchvision`
2. set which torch you'd like to try. for example:  
  TORCH_COMMAND='torch torchaudio torchvision --index-url https://download.pytorch.org/whl/cu118'
4. run `webui` so it installs desired torch

**Comment by mgmandahl** [comment]
I've been having the same issue, I'm running with a 1080ti. I tried xformers, it seems that the crashing got worse, especially with the Animator extension. I did like you said and unistalled and reinstalled torch I kept it at CU118. I switched back to SPD. still crashing. Wondering is I should just go to an earlier version of Torch?

**Comment by TheDuriel** [comment]
Further investigation.

Crashes are extremely random. 2000 images, fine. Then suddenly every 30. Each time requiring a restart of the whole thing.

Crashes definitely increase in frequency with greater batch sizes, but that's all I can determine. Crashes also seem to increase in frequency while running some other software that uses vram. But if I check process explorer I'm not seeing it reach GPU limits. (RTX2070S)

~~Never had any crashes on AUTOMATIC1111.~~ Looooooving this branch though. Hopeful I can stumble into finding the cause of this.

**Comment by vladmandic** [comment]
Thanks for the update - keep me posted!

**Comment by vladmandic** [comment]
All valid, but...CuDNN for me has more problems 8.8. Than 8.7. And torch 2.0 is definitely buggy a but, can't wait for a service release. I don't want to downgrade to 1.13 as I'd be loosing too much new functionality.

Once backlog quiets down, I'll go back to testing torch 2.1 nightlies.

**Comment by TheDuriel** [comment]
Culprit found.

"Live Previews" appear to either: Reserve/use a lot more vram than is reported. | Have a memory leak somewhere.

Found an old issue on automatic1111 about it from dec 22. Turning off has alleviated what where almost guaranteed crashes.

**Comment by vladmandic** [comment]
Which type of preview? I've been recommending approx nn for number of reasons.

**Comment by TheDuriel** [comment]
Was using Full, didn't see a description for the settings back when I picked them. Reading the tooltip for NN now makes it sound much more appealing than my "the first option in the list" approach back when I set things up.

Can also report that Full **doubles** generation times for highres fix compared to none or NN.

Going to use NN for a while and see if the crashes crop up with it.
