### ISSUE TITLE
[Issue]: AMD GPU not detected on clean install.

### ISSUE THREAD

**Issue by Turokosh** [vladmandic/automatic#2884]
### Issue Description

Hello, when installing an SD, the program does not detect the GPU, although the output from the console seems to be correct, I can’t understand what the problem is. Just in case, I installed ROCm 6.0 but the problem is still there.

### Version Platform Description

OS: Ubuntu 22.04.3, Platform: arch=x86_64 cpu=x86_64
Python 3.10.12 on Linux                                
Version: app=sd.next updated=2024-02-18 hash=9c12b74
AMD ROCm toolkit detected
ROCm agents detected: ['gfx1030']
ROCm agent used by default: idx=0 gpu=gfx1030 arch=navi2
ROCm version detected: 6.0
Torch "2.3.0.dev20240218+rocm6.0"
Device: None (6900xt)

### Relevant log output

```shell
turokosh@turokosh:~/Desktop/automatic$ ./webui.sh --use-rocm --debug
Create and activate python venv
Launching launch.py...
02:42:23-840795 INFO     Starting SD.Next                                       
02:42:23-842546 INFO     Logger:                                                
                         file="/home/turokosh/Desktop/automatic/sdnext.log"     
                         level=DEBUG size=64 mode=create                        
02:42:23-843188 INFO     Python 3.10.12 on Linux                                
02:42:23-848460 INFO     Version: app=sd.next updated=2024-02-18 hash=9c12b747  
                         url=https://github.com/vladmandic/automatic/tree/master
02:42:24-175193 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux          
                         release=6.5.0-18-generic python=3.10.12                
02:42:24-179830 DEBUG    Setting environment tuning                             
02:42:24-182631 DEBUG    HF cache folder: /home/turokosh/.cache/huggingface/hub 
02:42:24-184614 DEBUG    Torch overrides: cuda=False rocm=True ipex=False       
                         diml=False openvino=False                              
02:42:24-186631 DEBUG    Torch allowed: cuda=False rocm=True ipex=False         
                         diml=False openvino=False                              
02:42:24-188619 INFO     AMD ROCm toolkit detected                              
02:42:24-208389 DEBUG    ROCm agents detected: ['gfx1030']                      
02:42:24-208893 DEBUG    ROCm agent used by default: idx=0 gpu=gfx1030          
                         arch=navi2x                                            
02:42:24-234944 DEBUG    ROCm version detected: 6.0                             
02:42:24-293452 DEBUG    Package not found: onnxruntime-training                
02:42:24-294219 DEBUG    Package not found: built                               
02:42:24-294808 DEBUG    Package not found: with                                
02:42:24-295393 DEBUG    Package not found: ROCm                                
02:42:24-295957 INFO     Installing package:                                    
                         https://download.onnxruntime.ai/onnxruntime_training-1.
                         17.0%2Brocm60-cp310-cp310-manylinux_2_17_x86_64.manylin
                         ux2014_x86_64.whl                                      
02:42:24-296744 DEBUG    Running pip: install --upgrade                         
                         https://download.onnxruntime.ai/onnxruntime_training-1.
                         17.0%2Brocm60-cp310-cp310-manylinux_2_17_x86_64.manylin
                         ux2014_x86_64.whl                                      
02:42:25-225366 WARNING  Failed to automatically install onxnruntime package for
                         ROCm. Please manually install it if you need.          
02:42:25-231849 DEBUG    Repository update time: Mon Feb 19 00:40:13 2024       
02:42:25-232387 INFO     Startup: standard                                      
02:42:25-232784 INFO     Verifying requirements                                 
02:42:25-240469 INFO     Verifying packages                                     
02:42:25-241399 INFO     Verifying submodules                                   
02:42:25-877298 DEBUG    Submodule: extensions-builtin/sd-extension-chainner /  
                         main                                                   
02:42:25-896272 DEBUG    Submodule: extensions-builtin/sd-extension-system-info 
                         / main                                                 
02:42:25-913918 DEBUG    Submodule: extensions-builtin/sd-webui-agent-scheduler 
                         / main                                                 
02:42:25-932440 DEBUG    Submodule: extensions-builtin/sd-webui-controlnet /    
                         main                                                   
02:42:25-961501 DEBUG    Submodule:                                             
                         extensions-builtin/stable-diffusion-webui-images-browse
                         r / main                                               
02:42:25-974527 DEBUG    Submodule:                                             
                         extensions-builtin/stable-diffusion-webui-rembg /      
                         master                                                 
02:42:25-992265 DEBUG    Submodule: modules/k-diffusion / master                
02:42:26-009979 DEBUG    Submodule: modules/lora / main                         
02:42:26-029095 DEBUG    Submodule: wiki / master                               
02:42:26-041422 DEBUG    Register paths                                         
02:42:26-084111 DEBUG    Installed packages: 234                                
02:42:26-084651 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner',      
                         'sd-extension-system-info',                            
                         'stable-diffusion-webui-rembg',                        
                         'stable-diffusion-webui-images-browser',               
                         'sd-webui-controlnet', 'sd-webui-agent-scheduler']     
02:42:26-126869 DEBUG    Running extension installer:                           
                         /home/turokosh/Desktop/automatic/extensions-builtin/sd-
                         extension-system-info/install.py                       
02:42:26-222003 DEBUG    Running extension installer:                           
                         /home/turokosh/Desktop/automatic/extensions-builtin/sta
                         ble-diffusion-webui-rembg/install.py                   
02:42:26-314099 DEBUG    Running extension installer:                           
                         /home/turokosh/Desktop/automatic/extensions-builtin/sta
                         ble-diffusion-webui-images-browser/install.py          
02:42:26-405627 DEBUG    Running extension installer:                           
                         /home/turokosh/Desktop/automatic/extensions-builtin/sd-
                         webui-controlnet/install.py                            
02:42:26-507348 DEBUG    Running extension installer:                           
                         /home/turokosh/Desktop/automatic/extensions-builtin/sd-
                         webui-agent-scheduler/install.py                       
02:42:26-597518 DEBUG    Extensions all: []                                     
02:42:26-598061 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner',  
                         'sd-extension-system-info',                            
                         'stable-diffusion-webui-rembg',                        
                         'stable-diffusion-webui-images-browser',               
                         'sd-webui-controlnet', 'sd-webui-agent-scheduler']     
02:42:26-598683 INFO     Verifying requirements                                 
02:42:26-611567 DEBUG    Setup complete without errors: 1708303347              
02:42:26-612976 INFO     Extension preload: {'extensions-builtin': 0.0,         
                         'extensions': 0.0}                                     
02:42:26-613684 DEBUG    Starting module: <module 'webui' from                  
                         '/home/turokosh/Desktop/automatic/webui.py'>           
02:42:26-614330 INFO     Command line args: ['--use-rocm', '--debug'] debug=True
                         use_rocm=True                                          
02:42:26-614871 DEBUG    Env flags: []                                          
02:42:28-325999 DEBUG    Package not found: olive-ai                            
02:42:28-769049 INFO     Load packages: {'torch': '2.3.0.dev20240218+rocm6.0',  
                         'diffusers': '0.26.2', 'gradio': '3.43.2'}             
02:42:28-995506 DEBUG    Read: file="config.json" json=22 bytes=880 time=0.000  
02:42:28-997605 INFO     Engine: backend=Backend.DIFFUSERS compute=cpu          
                         device=cpu attention="Doggettx's" mode=no_grad      
02:42:28-998199 INFO     Device:                                                
02:42:29-306403 INFO     ONNX: selected=CPUExecutionProvider,                   
                         available=['AzureExecutionProvider',                   
                         'CPUExecutionProvider']                                
02:42:29-335309 DEBUG    Importing LDM                                          
02:42:29-340408 DEBUG    Entering start sequence                                
02:42:29-341164 DEBUG    Initializing                                           
02:42:29-345739 INFO     Available VAEs: path="models/VAE" items=0              
02:42:29-346397 INFO     Disabled extensions: ['sd-webui-controlnet']           
02:42:29-346934 DEBUG    Scanning diffusers cache: models/Diffusers             
                         models/Diffusers items=0 time=0.00                     
02:42:29-347553 DEBUG    Read: file="cache.json" json=1 bytes=167 time=0.000    
02:42:29-348118 DEBUG    Read: file="metadata.json" json=1 bytes=83 time=0.000  
02:42:29-348643 INFO     Available models: path="models/Stable-diffusion"       
                         items=1 time=0.00                                      
02:42:29-433609 DEBUG    Load extensions                                        
02:42:29-497862 INFO     LoRA networks: available=0 folders=2                   
02:42:29-714391 INFO     Extension:                                             
                         script='extensions-builtin/sd-webui-agent-scheduler/scr
                         ipts/task_scheduler.py' Using sqlite file:             
                         extensions-builtin/sd-webui-agent-scheduler/task_schedu
                         ler.sqlite3                                            
02:42:29-809781 INFO     Extensions init time: 0.38 img2imgalt.py=0.05          
                         sd-webui-agent-scheduler=0.21                          
                         stable-diffusion-webui-images-browser=0.09             
02:42:29-813143 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2640     
                         time=0.000                                             
02:42:29-813831 DEBUG    Read:                                                  
                         file="extensions-builtin/sd-extension-chainner/models.j
                         son" json=24 bytes=2693 time=0.000                     
02:42:29-814530 DEBUG    chaiNNer models: path="models/chaiNNer" defined=24     
                         discovered=0 downloaded=0                              
02:42:29-815324 DEBUG    Load upscalers: total=52 downloaded=0 user=0 time=0.00 
                         ['None', 'Lanczos', 'Nearest', 'ChaiNNer',             
                         'RealESRGAN', 'SD', 'LDSR', 'SCUNet', 'SwinIR',        
                         'ESRGAN']                                              
02:42:29-818648 DEBUG    Load styles: folder="models/styles" items=288 time=0.00
02:42:29-819679 DEBUG    Creating UI                                            
02:42:29-820162 INFO     Load UI theme: name="black-teal" style=Auto            
                         base=sdnext.css                                        
02:42:29-821965 DEBUG    UI initialize: txt2img                                 
02:42:29-826038 DEBUG    List items: function=create_items                      
02:42:29-829658 DEBUG    Read: file="html/reference.json" json=36 bytes=18838   
                         time=0.000                                             
02:42:29-831237 DEBUG    Extra networks: page='model' items=37 subfolders=2     
                         tab=txt2img folders=['models/Stable-diffusion',        
                         'models/Diffusers', 'models/Reference'] list=0.00      
                         thumb=0.00 desc=0.00 info=0.00 workers=4               
02:42:29-836410 DEBUG    Extra networks: page='style' items=288 subfolders=1    
                         tab=txt2img folders=['models/styles', 'html'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=4               
02:42:29-837319 DEBUG    Extra networks: page='embedding' items=0 subfolders=0  
                         tab=txt2img folders=['models/embeddings'] list=0.00    
                         thumb=0.00 desc=0.00 info=0.00 workers=4               
02:42:29-838165 DEBUG    Extra networks: page='hypernetwork' items=0            
                         subfolders=0 tab=txt2img                               
                         folders=['models/hypernetworks'] list=0.00 thumb=0.00  
                         desc=0.00 info=0.00 workers=4                          
02:42:29-839035 DEBUG    Extra networks: page='vae' items=0 subfolders=0        
                         tab=txt2img folders=['models/VAE'] list=0.00 thumb=0.00
                         desc=0.00 info=0.00 workers=4                          
02:42:29-839870 DEBUG    Extra networks: page='lora' items=0 subfolders=0       
                         tab=txt2img folders=['models/Lora', 'models/LyCORIS']  
                         list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=4     
02:42:29-871908 DEBUG    UI initialize: img2img                                 
02:42:29-926893 DEBUG    UI initialize: control models=models/control           
02:42:30-079090 DEBUG    Read: file="ui-config.json" json=0 bytes=2 time=0.000  
02:42:30-112260 DEBUG    Themes: builtin=11 default=5 external=55               
02:42:30-412654 INFO     Extension list is empty: refresh required              
02:42:30-434401 DEBUG    Extension list: processed=7 installed=7 enabled=6      
                         disabled=1 visible=7 hidden=0                          
02:42:30-508209 DEBUG    Root paths: ['/home/turokosh/Desktop/automatic']       
02:42:30-542731 INFO     Local URL: http://127.0.0.1:7860/                      
02:42:30-543286 DEBUG    Gradio functions: registered=2024                      
02:42:30-543755 INFO     Initializing middleware                                
02:42:30-545373 DEBUG    Creating API                                           
02:42:30-631204 INFO     [AgentScheduler] Task queue is empty                   
02:42:30-631813 INFO     [AgentScheduler] Registering APIs                      
02:42:30-815205 DEBUG    Scripts setup: []                                      
02:42:30-815889 DEBUG    Model metadata: file="metadata.json" no changes        
02:42:30-817138 DEBUG    Model requested: fn=<lambda>                           
02:42:30-817654 INFO     Select: model="v2 [7ffbd01916]"                        
02:42:30-818882 DEBUG    Load model: existing=False                             
                         target=/home/turokosh/Desktop/automatic/models/Stable-d
                         iffusion/v2.safetensors info=None                      
02:42:30-820645 DEBUG    Desired Torch parameters: dtype=FP16 no-half=False     
                         no-half-vae=False upscast=False                        
02:42:30-821219 INFO     Setting Torch parameters: device=cpu                   
                         dtype=torch.float16 vae=torch.float16                  
                         unet=torch.float16 context=no_grad fp16=True bf16=None 
02:42:30-821817 DEBUG    Diffusers loading:                                     
                         path="/home/turokosh/Desktop/automatic/models/Stable-di
                         ffusion/v2.safetensors"                                
02:42:30-822290 INFO     Autodetect: model="Stable Diffusion"                   
                         class=StableDiffusionPipeline                          
                         file="/home/turokosh/Desktop/automatic/models/Stable-di
                         ffusion/v2.safetensors" size=7346MB                    
02:42:31-793502 DEBUG    Setting model: pipeline=StableDiffusionPipeline        
                         config={'low_cpu_mem_usage': True, 'torch_dtype':      
                         torch.float16, 'load_connected_pipeline': True,        
                         'variant': 'fp16', 'extract_ema': True,                
                         'use_safetensors': True}                               
02:42:31-795126 DEBUG    Setting model: enable VAE slicing                      
02:42:31-812257 INFO     Load embeddings: loaded=0 skipped=0 time=0.00          
02:42:31-939784 DEBUG    GC: collected=2468 device=cpu {'ram': {'used': 6.92,   
                         'total': 62.53}} time=0.13                             
02:42:31-942634 INFO     Load model: time=0.99 load=0.99 native=512 {'ram':     
                         {'used': 6.92, 'total': 62.53}}                        
02:42:31-944113 DEBUG    Save: file="config.json" json=22 bytes=880 time=0.000  
02:42:31-944759 DEBUG    Script callback init time:                             
                         image_browser.py:ui_tabs=0.25                          
                         task_scheduler.py:app_started=0.19                     
02:42:31-945351 INFO     Startup time: 5.32 torch=1.69 gradio=0.44              
                         libraries=0.57 extensions=0.38 face-restore=0.08       
                         ui-en=0.08 ui-control=0.08 ui-settings=0.08            
                         ui-extensions=0.29 launch=0.06 app-started=0.22        
                         checkpoint=1.13                                        
02:42:37-688461 INFO     MOTD: N/A                                              
02:42:38-517052 DEBUG    Themes: builtin=11 default=5 external=55               
02:42:38-651858 INFO     Browser session: user=None client=127.0.0.1            
                         agent=Mozilla/5.0 (X11; Linux x86_64)                  
                         AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0
                         Safari/537.36
```

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by Turokosh** [comment]
At some point everything just worked. AMD GPU is some kind of anomaly.

**Comment by tornado130** [comment]
hey bro i have AMD 7800XT. Can you help me how did you solve the issue, my sd next keep using CPU instead of GPU

**Comment by Turokosh** [comment]
> hey bro i have AMD 7800XT. Can you help me how did you solve the issue, my sd next keep using CPU instead of GPU

Hello, I don’t understand what exactly it was that fixed it, since I tried everything. 
If ROCM is installed correctly (the "rocminfo" command output is correct), this may help for Linux:
sudo usermod -a -G render <YourUsernameHere>
sudo usermod -a -G video <YourUsernameHere>
Command line arguments such as "skip СUDA test" will force CPU usage.
