### ISSUE TITLE
[Issue]: Out Of Memory Error when TXT2IMG after latest commit

### ISSUE THREAD

**Issue by Lauson1ex** [vladmandic/automatic#2904]
### Issue Description

SD.Next autoupdated today. Now, every time I try to generate anything in TXT2IMG, I get an out of memory error. Everything worked fine until at least February 22nd, hash=`9c12b747`. This is performing a batch_size=`4` generation at 704x704 with the Euler a sampler and 20 steps. It used to work on `9c12b747`, but not on `c5f6c25a`.

### Version Platform Description

Python 3.10.6 on Windows 11
Microsoft Edge
SD.Next version=`2024-02-23` hash=`c5f6c25a`
`master` branch

### Relevant log output

```shell
02:58:51-769972 INFO     Starting SD.Next
02:58:51-783934 INFO     Logger: file="G:\dev\sd-next\sdnext.log" level=INFO size=9931580 mode=append
02:58:51-785929 INFO     Python 3.10.6 on Windows
02:58:51-955477 INFO     Version: app=sd.next updated=2024-02-23 hash=c5f6c25a
                         url=https://github.com/vladmandic/automatic/tree/master
02:58:52-952461 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel system=Windows
                         release=Windows-10-10.0.22621-SP0 python=3.10.6
02:58:52-955453 INFO     nVidia CUDA toolkit detected: nvidia-smi present
02:59:46-174300 INFO     Load packages: {'torch': '2.1.1+cu121', 'diffusers': '0.26.3', 'gradio': '3.43.2'}
02:59:52-109905 INFO     Engine: backend=Backend.ORIGINAL compute=cuda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
02:59:52-301803 INFO     Device: device=NVIDIA GeForce GTX 1070 n=1 arch=sm_90 cap=(6, 1) cuda=12.1 cudnn=8801

03:11:48-706670 ERROR    gradio call: OutOfMemoryError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ G:\dev\sd-next\modules\call_queue.py:31 in f                                                                         │
│                                                                                                                      │
│   30 │   │   │   try:                                                                                                │
│ ❱ 31 │   │   │   │   res = func(*args, **kwargs)                                                                     │
│   32 │   │   │   │   progress.record_results(id_task, res)                                                           │
│                                                                                                                      │
│ G:\dev\sd-next\modules\txt2img.py:88 in txt2img                                                                      │
│                                                                                                                      │
│   87 │   if processed is None:                                                                                       │
│ ❱ 88 │   │   processed = processing.process_images(p)                                                                │
│   89 │   p.close()                                                                                                   │
│                                                                                                                      │
│ G:\dev\sd-next\modules\processing.py:187 in process_images                                                           │
│                                                                                                                      │
│   186 │   │   │   with context_hypertile_vae(p), context_hypertile_unet(p):                                          │
│ ❱ 187 │   │   │   │   processed = process_images_inner(p)                                                            │
│   188                                                                                                                │
│                                                                                                                      │
│ G:\dev\sd-next\modules\processing.py:294 in process_images_inner                                                     │
│                                                                                                                      │
│   293 │   │   │   │   │   from modules.processing_original import process_original                                   │
│ ❱ 294 │   │   │   │   │   x_samples_ddim = process_original(p)                                                       │
│   295 │   │   │   │   elif shared.backend == shared.Backend.DIFFUSERS:                                               │
│                                                                                                                      │
│ G:\dev\sd-next\modules\processing_original.py:39 in process_original                                                 │
│                                                                                                                      │
│    38 │   with devices.without_autocast() if devices.unet_needs_upcast else devices.autocast():                      │
│ ❱  39 │   │   samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=p.seeds, subseeds=p.subse │
│    40 │   x_samples_ddim = [processing.decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae │
│                                                                                                                      │
│                                               ... 35 frames hidden ...                                               │
│                                                                                                                      │
│ G:\dev\sd-next\repositories\ldm\modules\attention.py:272 in _forward                                                 │
│                                                                                                                      │
│   271 │   def _forward(self, x, context=None):                                                                       │
│ ❱ 272 │   │   x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x                 │
│   273 │   │   x = self.attn2(self.norm2(x), context=context) + x                                                     │
│                                                                                                                      │
│ G:\dev\sd-next\venv\lib\site-packages\torch\nn\modules\module.py:1518 in _wrapped_call_impl                          │
│                                                                                                                      │
│   1517 │   │   else:                                                                                                 │
│ ❱ 1518 │   │   │   return self._call_impl(*args, **kwargs)                                                           │
│   1519                                                                                                               │
│                                                                                                                      │
│ G:\dev\sd-next\venv\lib\site-packages\torch\nn\modules\module.py:1527 in _call_impl                                  │
│                                                                                                                      │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                       │
│ ❱ 1527 │   │   │   return forward_call(*args, **kwargs)                                                              │
│   1528                                                                                                               │
│                                                                                                                      │
│ G:\dev\sd-next\modules\sd_hijack_optimizations.py:389 in scaled_dot_product_no_mem_attention_forward                 │
│                                                                                                                      │
│   388 │   with torch.backends.cuda.sdp_kernel(enable_flash=True, enable_math=True, enable_mem_efficient=False):      │
│ ❱ 389 │   │   return scaled_dot_product_attention_forward(self, x, context, mask)                                    │
│   390                                                                                                                │
│                                                                                                                      │
│ G:\dev\sd-next\modules\sd_hijack_optimizations.py:374 in scaled_dot_product_attention_forward                        │
│                                                                                                                      │
│   373 │   # the output of sdp = (batch, num_heads, seq_len, head_dim)                                                │
│ ❱ 374 │   hidden_states = torch.nn.functional.scaled_dot_product_attention(                                          │
│   375 │   │   q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
OutOfMemoryError: CUDA out of memory. Tried to allocate 3.58 GiB. GPU 0 has a total capacty of 8.00 GiB of which 1.21 GiB is free. Of the allocated memory 5.79 GiB is allocated by PyTorch, and 38.13 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
03:11:49-034203 INFO     High memory utilization: GPU=85% RAM=19% {'ram': {'used': 6.04, 'total': 31.93}, 'gpu':
                         {'used': 6.79, 'total': 8.0}, 'retries': 3, 'oom': 3}
```

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
what changed between the two versions that might have this impact is additional memory attention option - try changing them (i cannot reproduce the problem on my system):

![image](https://github.com/vladmandic/automatic/assets/57876960/936608f5-cb34-4b00-880d-e6d40c2459d2)

**Comment by Taithrah** [comment]
Works for me: be81d48601616e62e73090aaa6e8b8dc97e9cca8
Introduces the issue for me: ee7517dfb82ead84e422d8b32203e824c4071cb4

Upscaling is successful with GANs.
Latent upscale leads to OOM

OOM or errors occur when memory attention is off or with certain combinations.
Errors may include missing fused or math kernel errors.

Here are my logs, be81d48 and ee7517d. I can post more if needed.

[sdnext-be81d48601616e62e73090aaa6e8b8dc97e9cca8.log](https://github.com/vladmandic/automatic/files/14393501/sdnext-be81d48601616e62e73090aaa6e8b8dc97e9cca8.log)

[sdnext-ee7517dfb82ead84e422d8b32203e824c4071cb4.log](https://github.com/vladmandic/automatic/files/14393502/sdnext-ee7517dfb82ead84e422d8b32203e824c4071cb4.log)

**Comment by vladmandic** [comment]
thats exactly what i though - it would be useful if you could point which combo works best for you?

**Comment by Taithrah** [comment]
I apologize, miscommunication on my part. I still run into memory issues. I will try a log a few combinations in a bit, maybe i missed one.

**Comment by Taithrah** [comment]
I have tried 8 combinations of SDP options. Please let me know if I missed any.


[SDP-Combo-01.log](https://github.com/vladmandic/automatic/files/14393776/SDP-Combo-01.log)
Flash Attention: off
Memory Attention: off
Math Attention: off

RuntimeError: No viable backend for scaled_dot_product_attention was found. This is likely due to turning off both the math kernel and the fused kernels.


[SDP-Combo-02.log](https://github.com/vladmandic/automatic/files/14393777/SDP-Combo-02.log)
Flash Attention: on
Memory Attention: off
Math Attention: off

RuntimeError: No available kernel. Aborting execution.


[SDP-Combo-03.log](https://github.com/vladmandic/automatic/files/14393778/SDP-Combo-03.log)
Flash Attention: off
Memory Attention: on
Math Attention: off

OutOfMemoryError: CUDA out of memory. Tried to allocate 22.78 GiB. GPU 0 has a total capacity of 23.99 GiB of which 19.92 GiB is free. Of the allocated memory 2.44 GiB is allocated by PyTorch, and 8.43 MiB is reserved by PyTorch but unallocated.


[SDP-Combo-04.log](https://github.com/vladmandic/automatic/files/14393779/SDP-Combo-04.log)
Flash Attention: on
Memory Attention: on
Math Attention: off

OutOfMemoryError: CUDA out of memory. Tried to allocate 22.78 GiB. GPU 0 has a total capacity of 23.99 GiB of which 19.92 GiB is free. Of the allocated memory 2.44 GiB is allocated by PyTorch, and 8.43 MiB is reserved by PyTorch but unallocated.


[SDP-Combo-05.log](https://github.com/vladmandic/automatic/files/14393780/SDP-Combo-05.log)
Flash Attention: off
Memory Attention: off
Math Attention: on

OutOfMemoryError: CUDA out of memory. Tried to allocate 22.78 GiB. GPU 0 has a total capacity of 23.99 GiB of which 19.89 GiB is free. Of the allocated memory 2.44 GiB is allocated by PyTorch, and 35.18 MiB is reserved by PyTorch but unallocated.


[SDP-Combo-06.log](https://github.com/vladmandic/automatic/files/14393781/SDP-Combo-06.log)
Flash Attention: on
Memory Attention: off
Math Attention: on

OutOfMemoryError: CUDA out of memory. Tried to allocate 22.78 GiB. GPU 0 has a total capacity of 23.99 GiB of which 19.92 GiB is free. Of the allocated memory 2.44 GiB is allocated by PyTorch, and 8.43 MiB is reserved by PyTorch but unallocated.


[SDP-Combo-07.log](https://github.com/vladmandic/automatic/files/14393782/SDP-Combo-07.log)
Flash Attention: off
Memory Attention: on
Math Attention: on

OutOfMemoryError: CUDA out of memory. Tried to allocate 22.78 GiB. GPU 0 has a total capacity of 23.99 GiB of which 19.89 GiB is free. Of the allocated memory 2.44 GiB is allocated by PyTorch, and 35.18 MiB is reserved by PyTorch but unallocated.


[SDP-Combo-08.log](https://github.com/vladmandic/automatic/files/14393783/SDP-Combo-08.log)
Flash Attention: on
Memory Attention: on
Math Attention: on

OutOfMemoryError: CUDA out of memory. Tried to allocate 22.78 GiB. GPU 0 has a total capacity of 23.99 GiB of which 19.89 GiB is free. Of the allocated memory 2.44 GiB is allocated by PyTorch, and 35.18 MiB is reserved by PyTorch but unallocated.

**Comment by Taithrah** [comment]
I noticed both @Lauson1ex and myself are using original backend. I switched the backend to diffusers and I don't encounter a OOM when upscaling and all three SDP options on.

Just in case, here is a log.
[sdnext.log](https://github.com/vladmandic/automatic/files/14394354/sdnext.log)

**Comment by Lauson1ex** [comment]
> what changed between the two versions that might have this impact is additional memory attention option - try changing them (i cannot reproduce the problem on my system):
> 
> ![image](https://private-user-images.githubusercontent.com/57876960/307521256-936608f5-cb34-4b00-880d-e6d40c2459d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MzQwNTYsIm5iZiI6MTcwODgzMzc1NiwicGF0aCI6Ii81Nzg3Njk2MC8zMDc1MjEyNTYtOTM2NjA4ZjUtY2IzNC00YjAwLTg4MGQtZTZkNDBjMjQ1OWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDA0MDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhOWM5MTdiZDhmNDQxOTE1ZDE2YmJhY2M5NzFlYzcwNWQ4ZmVmZGE2OTYyMGIxZDVmZWE5NDU0YjRmMmJhZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8zxWDKS6djWVDy7h6W3XbKyl2U9N4CmLJtNgjbDWHuU)

I tried every permutation of these options. Much like @Taithrah results, all of them OOM.

**Comment by klausman** [comment]
Same error/symptoms here on original backend. I tried a bunch of different upscalers, including really simple ones like non-latent Nearest and Lanczos, all causing OOMs. I also tried the xFormers attention method, both with and without Flash attention, and it worked fine.

What I find a bit peculiar is that the when the OOM happens it's because it requests twice the total VRAM the card has (mine is a 3090Ti with 24G of VRAM and the OOM-causing request wants 48G additional RAM). But I see that the other reports do not have that (Unless there is some 11GB GPU I am unaware of...), so it might be a red herring.

I am not well versed in the codebase, but I have coded Python for a living for over a decade, so if you have some hints where to look, I might be able to help.

**Comment by vladmandic** [comment]
if you can test 4 changes, it should be 5min - i wish i could reproduce.
if statement from @Taithrah is accurate that working=be81d48, not-working=ee7517d then its really short list to check.
try 4 changes, one-at-the-time so we know which one works, not all at once.

1. in `modules/devices.py` remove:
```py
  torch.backends.cudnn.deterministic = shared.opts.cudnn_deterministic
```
2. in modules/devices.py, remove:
```py
    try:
        if shared.opts.cross_attention_optimization == "Scaled-Dot-Product":
            torch.backends.cuda.enable_flash_sdp('Flash attention' in shared.opts.sdp_options)
            torch.backends.cuda.enable_mem_efficient_sdp('Memory attention' in shared.opts.sdp_options)
            torch.backends.cuda.enable_math_sdp('Math attention' in shared.opts.sdp_options)
    except Exception:
        pass
```
3. in `modules/sd_hijack.py` replace
```py
    if can_use_sdp and shared.opts.cross_attention_optimization == "Scaled-Dot-Product":
        optimization_method = 'sdp'
        if 'Memory attention' in shared.opts.sdp_options:
            ldm.modules.attention.CrossAttention.forward = sd_hijack_optimizations.scaled_dot_product_no_mem_attention_forward
            ldm.modules.diffusionmodules.model.AttnBlock.forward = sd_hijack_optimizations.sdp_no_mem_attnblock_forward
        else:
            ldm.modules.attention.CrossAttention.forward = sd_hijack_optimizations.scaled_dot_product_attention_forward
            ldm.modules.diffusionmodules.model.AttnBlock.forward = sd_hijack_optimizations.sdp_attnblock_forward
```
with 
```py
    if can_use_sdp and shared.opts.cross_attention_optimization == "Scaled-Dot-Product"
        ldm.modules.attention.CrossAttention.forward = sd_hijack_optimizations.scaled_dot_product_no_mem_attention_forward
        ldm.modules.diffusionmodules.model.AttnBlock.forward = sd_hijack_optimizations.sdp_no_mem_attnblock_forward
```
4. same, but replace with:
```py
    if can_use_sdp and shared.opts.cross_attention_optimization == "Scaled-Dot-Product"
        ldm.modules.attention.CrossAttention.forward = sd_hijack_optimizations.scaled_dot_product_attention_forward
        ldm.modules.diffusionmodules.model.AttnBlock.forward = sd_hijack_optimizations.sdp_attnblock_forward
```

**Comment by Taithrah** [comment]
I can confirm, while on commit ee7517dfb82ead84e422d8b32203e824c4071cb4. 
The following change worked. 
```
if can_use_sdp and shared.opts.cross_attention_optimization == "Scaled-Dot-Product":
        ldm.modules.attention.CrossAttention.forward = sd_hijack_optimizations.scaled_dot_product_attention_forward
        ldm.modules.diffusionmodules.model.AttnBlock.forward = sd_hijack_optimizations.sdp_attnblock_forward
```

**Comment by klausman** [comment]
Same here: change #4 makes the OOM go away, #1-#3 make no difference for OOMing.

**Comment by vladmandic** [comment]
perfect - thanks. i'll make an update shortly.
