### ISSUE TITLE
[Issue]: rocBLAS error with Zluda

### ISSUE THREAD

**Issue by Cappyadams** [vladmandic/automatic#3485]
### Issue Description

So I just installed this and set it up, and for some reason I'm getting an error that says
`rocBLAS error: Could not load C:\Program Files\AMD\ROCm\6.1\bin\/rocblas/library/TensileLibrary.dat`
everything else is fine, it's just that one error-

### Version Platform Description

OS: Windows 11
GPU: Radeon RX5700

### Relevant log output

```shell
Using VENV: D:\Stable\SD_NEXT\automatic\venv
15:57:58-905948 INFO     Starting SD.Next
15:57:58-908948 INFO     Logger: file="D:\Stable\SD_NEXT\automatic\sdnext.log" level=DEBUG size=65 mode=create
15:57:58-910949 INFO     Python version=3.10.11 platform=Windows
                         bin="D:\Stable\SD_NEXT\automatic\venv\Scripts\python.exe"
                         venv="D:\Stable\SD_NEXT\automatic\venv"
15:57:59-112187 INFO     Version: app=sd.next updated=2024-09-13 hash=e7ec07f9 branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
15:57:59-450536 INFO     Platform: arch=AMD64 cpu=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
15:57:59-453039 DEBUG    Setting environment tuning
15:57:59-454055 INFO     HF cache folder: C:\Users\distd\.cache\huggingface\hub
15:57:59-455057 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
15:57:59-465564 DEBUG    Torch overrides: cuda=False rocm=True ipex=False diml=False openvino=False
15:57:59-466566 DEBUG    Torch allowed: cuda=False rocm=True ipex=False diml=False openvino=False
15:57:59-467566 INFO     Python version=3.10.11 platform=Windows
                         bin="D:\Stable\SD_NEXT\automatic\venv\Scripts\python.exe"
                         venv="D:\Stable\SD_NEXT\automatic\venv"
15:57:59-471567 INFO     AMD ROCm toolkit detected
15:57:59-486109 INFO     ROCm agents detected: []
15:57:59-488109 INFO     ROCm version detected: 6.1
15:57:59-489110 WARNING  ZLUDA support: experimental
15:57:59-533341 INFO     Using ZLUDA in C:\ZLUDA
15:58:01-546581 WARNING  Modified files: ['installer.py']
15:58:01-614258 INFO     Verifying requirements
15:58:01-619261 INFO     Verifying packages
15:58:01-667536 DEBUG    Repository update time: Fri Sep 13 17:51:56 2024
15:58:01-668535 INFO     Startup: standard
15:58:01-669535 INFO     Verifying submodules
15:58:03-889355 DEBUG    Submodule: extensions-builtin/sd-extension-chainner / main
15:58:04-015040 DEBUG    Git detached head detected: folder="extensions-builtin/sd-extension-system-info" reattach=main
15:58:04-017449 DEBUG    Submodule: extensions-builtin/sd-extension-system-info / main
15:58:04-094518 DEBUG    Submodule: extensions-builtin/sd-webui-agent-scheduler / main
15:58:04-213644 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
15:58:04-214657 DEBUG    Submodule: extensions-builtin/sdnext-modernui / main
15:58:04-298546 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-rembg / master
15:58:04-378279 DEBUG    Submodule: modules/k-diffusion / master
15:58:04-495000 DEBUG    Git detached head detected: folder="wiki" reattach=master
15:58:04-496024 DEBUG    Submodule: wiki / master
15:58:04-544967 DEBUG    Register paths
15:58:04-614978 DEBUG    Installed packages: 170
15:58:04-616461 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
15:58:04-812126 DEBUG    Running extension installer:
                         D:\Stable\SD_NEXT\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
15:58:05-217470 DEBUG    Running extension installer:
                         D:\Stable\SD_NEXT\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
15:58:05-547845 DEBUG    Extensions all: []
15:58:05-548845 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
15:58:05-549845 INFO     Verifying requirements
15:58:05-550845 DEBUG    Setup complete without errors: 1728745086
15:58:05-555351 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
15:58:05-557353 DEBUG    Starting module: <module 'webui' from 'D:\\Stable\\SD_NEXT\\automatic\\webui.py'>
15:58:05-558354 INFO     Command line args: ['--lowvram', '--debug', '--use-zluda', '--autolaunch', '--device-id', '0',
                         '--use-rocm'] lowvram=True autolaunch=True device_id=0 use_rocm=True use_zluda=True debug=True
15:58:05-560355 DEBUG    Env flags: []
15:58:09-915638 INFO     Load packages: {'torch': '2.3.0+cu118', 'diffusers': '0.31.0.dev0', 'gradio': '3.43.2'}
15:58:11-098780 DEBUG    Read: file="config.json" json=30 bytes=1277 time=0.000
15:58:11-101834 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda:0 attention="Scaled-Dot-Product"
                         mode=no_grad
15:58:11-119860 INFO     Device: device=Radeon RX 5700 [ZLUDA] n=1 arch=compute_37 cap=(8, 8) cuda=11.8 cudnn=8700
                         driver=
15:58:11-121860 DEBUG    Read: file="html\reference.json" json=52 bytes=29118 time=0.000

rocBLAS error: Could not load C:\Program Files\AMD\ROCm\6.1\bin\/rocblas/library/TensileLibrary.dat

rocBLAS error: Could not initialize Tensile library
Press any key to continue . . .
```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by Disty0** [comment]
Use ROCm 5.7: https://github.com/vladmandic/automatic/wiki/ZLUDA#install-hip-sdk

**Comment by Cappyadams** [comment]
> Use ROCm 5.7: https://github.com/vladmandic/automatic/wiki/ZLUDA#install-hip-sdk

Just did that, it still doesn't work-

**Comment by Cappyadams** [comment]
> > Use ROCm 5.7: https://github.com/vladmandic/automatic/wiki/ZLUDA#install-hip-sdk
> 
> Just did that, it still doesn't work-

### UPDATE
I fixed all the errors! Turned out I accidently installed the wrong version of ROCm
but.. now when I try to generate an image, it keeps saying "Compiling in progress. Please wait..." over and over
is this normal? sorry for the silly question-
![image](https://github.com/user-attachments/assets/00b00f68-3fda-4220-9558-1138b3ede986)

**Comment by Disty0** [comment]
Compiling takes up to 30 minutes when using Zluda for the first time.

**Comment by Cappyadams** [comment]
> Compiling takes up to 30 minutes when using Zluda for the first time.

Ohhh I see! btw, I don't know if this is the right time to ask and stuff, but after I got everything working and after it finished compiling and stuff, I tried using a lora and the program completely ignored it- 
is there a way to fix this?

**Comment by brknsoul** [comment]
It's typically best to ask on Discord. Ensure you're matching the lora type with the model type.
SD15 loras won't work with SDXL, and vice-versa.
