### ISSUE TITLE
[Issue]: Lightning models not loading

### ISSUE THREAD

**Issue by Maraket** [vladmandic/automatic#3537]
### Issue Description

[sdnext.log](https://github.com/user-attachments/files/17566282/sdnext.log)
### Issue

When attempting to run the txt2img function using Juggernaut-XL-Lightning model, I am receiving the below error and my image isn't being generated

```
15:41:03-236422 ERROR    Load {op}: no model loaded
15:41:03-239423 WARNING  Aborted: op=txt model not loaded
```

### Steps that led to error

0. Run `./webui.bat --use-zluda --autolaunch --debug`
1. Navigated to Models tab
2. Navigated to Huggingface subtab
3. Entered Huggingface token
4. In `Search models` searched for `lightning`
5. Selected `RunDiffusion/Juggernaut-XL-Lightning` from returned list
6. Clicked `Download model` and waited for it to download
7. Clicked refresh `Base model`
8. Selected `Diffusters\RunDiffusion/Juggernaut-XL-Lightning [a3035ee9ae]`
9. Navigated to `Text` tab
10. Entered a simple prompt, in this case `a pumpkin`
11. Width and height set to 512, and steps set to 8, all other values left as default
12. Clicked `Generate`
13. Received error in gui: `Error: model not loaded`

### Do any other models work

I have had success running `Diffusers\stabilityai/stable-diffusion-3.5-large [ceddf0a7fd]`, downloaded the same way as lightning and have also had success with a few other models directly downloaded from CivitAi.

Attempting to use `Diffusers\ByteDance/SDXL-Lightning [c9a24f48e1]` via the same steps as previous, provided the same result of the model not loading.

### Attempts to remediate
> Disclaimer I didn't do any research other then reading the error log and taking wild guesses to remediate so if you ask yourself why did I do these things as they clearly wouldn't have any impact, understand there was no real solid reasoning

- Attempted to download the Juggernaut-XL-Lightning model into the snapshot directory 
- Under System -> Settings -> Networks tried
  - Use reference values when available
  - Build info on first access
  - Lora Preferred name set to alias

### Debug log

Please find attached the debug log, though note, this log excludes the download as I had already downloaded the model, so I would need to see if I can find the model, else download another lightning model as I suspect that is the culprit.
[sdnext.log](https://github.com/user-attachments/files/17566279/sdnext.log)

### Version Platform Description

2024-10-30 15:38:29,511 | sd | INFO | launch | Starting SD.Next
2024-10-30 15:38:29,518 | sd | INFO | installer | Logger: file="C:\AI\WebUI\automatic\sdnext.log" level=DEBUG size=65 mode=create
2024-10-30 15:38:29,522 | sd | INFO | installer | Python: version=3.10.11 platform=Windows bin="C:\AI\WebUI\automatic\venv\Scripts\python.exe" venv="C:\AI\WebUI\automatic\venv"
2024-10-30 15:38:29,751 | sd | INFO | installer | Version: app=sd.next updated=2024-10-24 hash=3ba9ebc8 branch=master url=https://github.com/vladmandic/automatic/tree/master ui=main
2024-10-30 15:38:30,321 | sd | INFO | installer | Repository latest available 41f9a3508696e90bda5e4c61ff4b767414decdc3 2024-10-29T19:35:58Z
2024-10-30 15:38:30,332 | sd | INFO | launch | Platform: arch=AMD64 cpu=AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD system=Windows release=Windows-10-10.0.19045-SP0 python=3.10.11
2024-10-30 15:38:30,338 | sd | DEBUG | installer | Setting environment tuning
2024-10-30 15:38:30,341 | sd | DEBUG | installer | Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
2024-10-30 15:38:30,372 | sd | DEBUG | installer | Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=True
2024-10-30 15:38:30,387 | sd | INFO | installer | Python: version=3.10.11 platform=Windows bin="C:\AI\WebUI\automatic\venv\Scripts\python.exe" venv="C:\AI\WebUI\automatic\venv"
2024-10-30 15:38:30,395 | sd | INFO | installer | ROCm: AMD toolkit detected
2024-10-30 15:38:30,934 | sd | INFO | installer | ROCm: agents=['gfx1032']
2024-10-30 15:38:30,937 | sd | INFO | installer | ROCm: version=5.7, using agent gfx1032
2024-10-30 15:38:30,939 | sd | WARNING | installer | ZLUDA support: experimental
2024-10-30 15:38:32,986 | sd | INFO | installer | Using ZLUDA in C:\AI\WebUI\automatic\.zluda

### Relevant log output

```shell
2024-10-30 15:38:29,511 | sd | INFO | launch | Starting SD.Next
2024-10-30 15:38:29,518 | sd | INFO | installer | Logger: file="C:\AI\WebUI\automatic\sdnext.log" level=DEBUG size=65 mode=create
2024-10-30 15:38:29,522 | sd | INFO | installer | Python: version=3.10.11 platform=Windows bin="C:\AI\WebUI\automatic\venv\Scripts\python.exe" venv="C:\AI\WebUI\automatic\venv"
2024-10-30 15:38:29,751 | sd | INFO | installer | Version: app=sd.next updated=2024-10-24 hash=3ba9ebc8 branch=master url=https://github.com/vladmandic/automatic/tree/master ui=main
2024-10-30 15:38:30,321 | sd | INFO | installer | Repository latest available 41f9a3508696e90bda5e4c61ff4b767414decdc3 2024-10-29T19:35:58Z
2024-10-30 15:38:30,332 | sd | INFO | launch | Platform: arch=AMD64 cpu=AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD system=Windows release=Windows-10-10.0.19045-SP0 python=3.10.11
2024-10-30 15:38:30,338 | sd | DEBUG | installer | Setting environment tuning
2024-10-30 15:38:30,341 | sd | DEBUG | installer | Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
2024-10-30 15:38:30,372 | sd | DEBUG | installer | Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=True
2024-10-30 15:38:30,387 | sd | INFO | installer | Python: version=3.10.11 platform=Windows bin="C:\AI\WebUI\automatic\venv\Scripts\python.exe" venv="C:\AI\WebUI\automatic\venv"
2024-10-30 15:38:30,395 | sd | INFO | installer | ROCm: AMD toolkit detected
2024-10-30 15:38:30,934 | sd | INFO | installer | ROCm: agents=['gfx1032']
2024-10-30 15:38:30,937 | sd | INFO | installer | ROCm: version=5.7, using agent gfx1032
2024-10-30 15:38:30,939 | sd | WARNING | installer | ZLUDA support: experimental
2024-10-30 15:38:32,986 | sd | INFO | installer | Using ZLUDA in C:\AI\WebUI\automatic\.zluda
2024-10-30 15:38:38,446 | sd | DEBUG | installer | Package: xformers not found
2024-10-30 15:38:38,449 | sd | INFO | installer | Install: package="--pre xformers" mode=pip
2024-10-30 15:38:38,451 | sd | DEBUG | installer | Running: pip="install --upgrade --no-deps --pre xformers"
2024-10-30 15:38:50,124 | sd | DEBUG | installer | xFormers cannot install: No module named 'xformers'
2024-10-30 15:38:50,371 | sd | INFO | installer | Verifying requirements
2024-10-30 15:38:50,379 | sd | INFO | installer | Verifying packages
2024-10-30 15:38:50,429 | sd | DEBUG | installer | Timestamp repository update time: Fri Oct 25 06:30:10 2024
2024-10-30 15:38:50,432 | sd | INFO | launch | Startup: standard
2024-10-30 15:38:50,434 | sd | INFO | installer | Verifying submodules
2024-10-30 15:38:53,001 | sd | DEBUG | installer | Git submodule: extensions-builtin/sd-extension-chainner / main
2024-10-30 15:38:53,105 | sd | DEBUG | installer | Git submodule: extensions-builtin/sd-extension-system-info / main
2024-10-30 15:38:53,199 | sd | DEBUG | installer | Git submodule: extensions-builtin/sd-webui-agent-scheduler / main
2024-10-30 15:38:53,344 | sd | DEBUG | installer | Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
2024-10-30 15:38:53,348 | sd | DEBUG | installer | Git submodule: extensions-builtin/sdnext-modernui / main
2024-10-30 15:38:53,441 | sd | DEBUG | installer | Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
2024-10-30 15:38:53,540 | sd | DEBUG | installer | Git submodule: modules/k-diffusion / master
2024-10-30 15:38:53,635 | sd | DEBUG | installer | Git submodule: wiki / master
2024-10-30 15:38:53,696 | sd | DEBUG | paths | Register paths
2024-10-30 15:38:53,803 | sd | DEBUG | installer | Installed packages: 181
2024-10-30 15:38:53,806 | sd | DEBUG | installer | Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
2024-10-30 15:38:54,113 | sd | DEBUG | installer | Extension installer: C:\AI\WebUI\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
2024-10-30 15:38:59,669 | sd | DEBUG | installer | Extension installer: C:\AI\WebUI\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
2024-10-30 15:39:09,917 | sd | DEBUG | installer | Extensions all: []
2024-10-30 15:39:09,920 | sd | INFO | installer | Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
2024-10-30 15:39:09,924 | sd | INFO | installer | Verifying requirements
2024-10-30 15:39:09,926 | sd | DEBUG | launch | Setup complete without errors: 1730263150
2024-10-30 15:39:09,934 | sd | DEBUG | installer | Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
2024-10-30 15:39:09,937 | sd | DEBUG | launch | Starting module: <module 'webui' from 'C:\\AI\\WebUI\\automatic\\webui.py'>
2024-10-30 15:39:09,940 | sd | INFO | launch | Command line args: ['--use-zluda', '--autolaunch', '--debug'] autolaunch=True use_zluda=True debug=True
2024-10-30 15:39:09,944 | sd | DEBUG | launch | Env flags: []
2024-10-30 15:39:21,418 | sd | INFO | loader | System packages: {'torch': '2.3.1+cu118', 'diffusers': '0.32.0.dev0', 'gradio': '3.43.2', 'transformers': '4.45.2', 'accelerate': '1.0.0'}
2024-10-30 15:39:22,714 | sd | DEBUG | shared | Huggingface cache: folder="C:\Users\drake\.cache\huggingface\hub"
2024-10-30 15:39:23,184 | sd | INFO | shared | Device detect: memory=8.0 ptimization=medvram
2024-10-30 15:39:23,188 | sd | DEBUG | shared | Read: file="config.json" json=34 bytes=1483 time=0.000
2024-10-30 15:39:23,194 | sd | INFO | shared | Engine: backend=Backend.DIFFUSERS compute=zluda device=cuda attention="xFormers" mode=no_grad
2024-10-30 15:39:23,208 | sd | DEBUG | shared | Read: file="html\reference.json" json=58 bytes=30996 time=0.009
2024-10-30 15:39:23,447 | sd | INFO | devices | Torch parameters: backend=zluda device=cuda config=Auto dtype=torch.float16 vae=torch.float16 unet=torch.float16 context=no_grad nohalf=False nohalfvae=False upscast=False deterministic=False test-fp16=True test-bf16=False optimization="xFormers"
2024-10-30 15:39:24,525 | sd | DEBUG | __init__ | ONNX: version=1.19.2 provider=CPUExecutionProvider, available=['AzureExecutionProvider', 'CPUExecutionProvider']
2024-10-30 15:39:24,640 | sd | INFO | shared | Device: device=AMD Radeon RX 6600 [ZLUDA] n=1 arch=compute_37 capability=(8, 8) cuda=11.8 cudnn=8700 driver=
2024-10-30 15:39:24,792 | sd | DEBUG | sd_hijack | Importing LDM
2024-10-30 15:39:24,812 | sd | DEBUG | webui | Entering start sequence
2024-10-30 15:39:24,818 | sd | DEBUG | webui | Initializing
2024-10-30 15:39:24,882 | sd | INFO | sd_vae | Available VAEs: path="models\VAE" items=0
2024-10-30 15:39:24,885 | sd | INFO | sd_unet | Available UNets: path="models\UNET" items=0
2024-10-30 15:39:24,888 | sd | INFO | model_te | Available TEs: path="models\Text-encoder" items=0
2024-10-30 15:39:24,892 | sd | INFO | extensions | Disabled extensions: ['sdnext-modernui']
2024-10-30 15:39:24,901 | sd | DEBUG | shared | Read: file="cache.json" json=2 bytes=756 time=0.005
2024-10-30 15:39:24,913 | sd | DEBUG | shared | Read: file="metadata.json" json=9 bytes=11178 time=0.007
2024-10-30 15:39:24,919 | sd | DEBUG | modelloader | Scanning diffusers cache: folder="models\Diffusers" items=3 time=0.00
2024-10-30 15:39:24,922 | sd | INFO | sd_models | Available Models: path="models\Stable-diffusion" items=7 time=0.03
2024-10-30 15:39:25,050 | sd | INFO | yolo | Available Yolo: path="models\yolo" items=6 downloaded=0
2024-10-30 15:39:25,054 | sd | DEBUG | webui | Load extensions
2024-10-30 15:39:25,175 | sd | INFO | networks | Available LoRAs: items=3 folders=2
2024-10-30 15:39:25,234 | sd | INFO | script_loading | Extension: script='extensions-builtin\Lora\scripts\lora_script.py' [2;36m15:39:25-175332[0m[2;36m [0m[34mINFO    [0m Available LoRAs: [33mitems[0m=[1;36m3[0m [33mfolders[0m=[1;36m2[0m
2024-10-30 15:39:26,159 | sd | INFO | script_loading | Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
2024-10-30 15:39:26,168 | sd | DEBUG | webui | Extensions init time: 1.11 Lora=0.08 sd-extension-chainner=0.22 sd-webui-agent-scheduler=0.69
2024-10-30 15:39:26,205 | sd | DEBUG | shared | Read: file="html/upscalers.json" json=4 bytes=2672 time=0.008
2024-10-30 15:39:26,218 | sd | DEBUG | shared | Read: file="extensions-builtin\sd-extension-chainner\models.json" json=24 bytes=2719 time=0.008
2024-10-30 15:39:26,223 | sd | DEBUG | chainner_model | chaiNNer models: path="models\chaiNNer" defined=24 discovered=0 downloaded=0
2024-10-30 15:39:26,230 | sd | INFO | modelloader | Available Upscalers: items=53 downloaded=0 user=0 time=0.06 types=['None', 'Lanczos', 'Nearest', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'LDSR', 'RealESRGAN', 'SCUNet', 'SD', 'SwinIR']
2024-10-30 15:39:26,924 | sd | INFO | styles | Available Styles: folder="models\styles" items=288 time=0.69
2024-10-30 15:39:26,935 | sd | DEBUG | webui | Creating UI
2024-10-30 15:39:26,937 | sd | DEBUG | theme | UI themes available: type=Standard themes=12
2024-10-30 15:39:26,940 | sd | INFO | theme | UI theme: type=Standard name="black-teal"
2024-10-30 15:39:26,954 | sd | DEBUG | ui_javascript | UI theme: css="C:\AI\WebUI\automatic\javascript\black-teal.css" base="sdnext.css" user="None"
2024-10-30 15:39:26,960 | sd | DEBUG | ui_txt2img | UI initialize: txt2img
2024-10-30 15:39:27,024 | sd | DEBUG | ui_extra_networks | Networks: page='model' items=64 subfolders=2 tab=txt2img folders=['models\\Stable-diffusion', 'models\\Diffusers', 'models\\Reference'] list=0.03 thumb=0.01 desc=0.01 info=0.01 workers=8 sort=Default
2024-10-30 15:39:27,035 | sd | DEBUG | ui_extra_networks | Networks: page='lora' items=3 subfolders=0 tab=txt2img folders=['models\\Lora', 'models\\LyCORIS'] list=0.02 thumb=0.00 desc=0.00 info=0.00 workers=8 sort=Default
2024-10-30 15:39:27,055 | sd | DEBUG | ui_extra_networks | Networks: page='style' items=288 subfolders=1 tab=txt2img folders=['models\\styles', 'html'] list=0.04 thumb=0.00 desc=0.00 info=0.00 workers=8 sort=Default
2024-10-30 15:39:27,067 | sd | DEBUG | ui_extra_networks | Networks: page='embedding' items=0 subfolders=0 tab=txt2img folders=['models\\embeddings'] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=8 sort=Default
2024-10-30 15:39:27,077 | sd | DEBUG | ui_extra_networks | Networks: page='vae' items=0 subfolders=0 tab=txt2img folders=['models\\VAE'] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=8 sort=Default
2024-10-30 15:39:27,085 | sd | DEBUG | ui_extra_networks | Networks: page='history' items=0 subfolders=0 tab=txt2img folders=[] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=8 sort=Default
2024-10-30 15:39:27,279 | sd | DEBUG | ui_img2img | UI initialize: img2img
2024-10-30 15:39:27,482 | sd | DEBUG | ui_control_helpers | UI initialize: control models=models\control
2024-10-30 15:39:28,043 | sd | DEBUG | shared | Read: file="ui-config.json" json=0 bytes=2 time=0.001
2024-10-30 15:39:28,277 | sd | DEBUG | theme | UI themes available: type=Standard themes=12
2024-10-30 15:39:28,758 | sd | DEBUG | shared | Reading failed: C:\AI\WebUI\automatic\html\extensions.json [Errno 2] No such file or directory: 'C:\\AI\\WebUI\\automatic\\html\\extensions.json'
2024-10-30 15:39:28,761 | sd | INFO | ui_extensions | Extension list is empty: refresh required
2024-10-30 15:39:29,416 | sd | DEBUG | ui_extensions | Extension list: processed=6 installed=6 enabled=5 disabled=1 visible=6 hidden=0
2024-10-30 15:39:29,620 | sd | DEBUG | webui | Root paths: ['C:\\AI\\WebUI\\automatic']
2024-10-30 15:39:29,761 | sd | INFO | webui | Local URL: http://127.0.0.1:7860/
2024-10-30 15:39:29,763 | sd | DEBUG | webui | Gradio functions: registered=1897
2024-10-30 15:39:29,768 | sd | DEBUG | middleware | FastAPI middleware: ['Middleware', 'Middleware']
2024-10-30 15:39:29,774 | sd | DEBUG | webui | Creating API
2024-10-30 15:39:30,049 | sd | INFO | task_runner | [AgentScheduler] Task queue is empty
2024-10-30 15:39:30,052 | sd | INFO | api | [AgentScheduler] Registering APIs
2024-10-30 15:39:30,224 | sd | DEBUG | webui | Scripts setup: ['IP Adapters:0.046', 'XYZ Grid:0.046', 'Face:0.027', 'AnimateDiff:0.015', 'CogVideoX:0.016', 'Ctrl-X:0.011', 'DemoFusion:0.006', 'HDR:0.009', 'LUT Color grading:0.013', 'Prompt enhance:0.008', 'Prompt matrix:0.007', 'Text-to-Video:0.009', 'Image-to-Video:0.011', 'Stable Video Diffusion:0.011']
2024-10-30 15:39:30,231 | sd | DEBUG | sd_models | Model metadata: file="metadata.json" no changes
2024-10-30 15:39:30,235 | sd | DEBUG | modeldata | Model requested: fn=run:<lambda>
2024-10-30 15:39:30,238 | sd | INFO | sd_models | Load model: select="Diffusers\RunDiffusion/Juggernaut-XL-Lightning [a3035ee9ae]"
2024-10-30 15:39:30,243 | sd | INFO | sd_models | Autodetect model: detect="Stable Diffusion XL" class=StableDiffusionXLPipeline file="models\Diffusers\models--RunDiffusion--Juggernaut-XL-Lightning\snapshots\a3035ee9ae36901d8a66b0eb646eb550c2e3ea99" size=0MB
2024-10-30 15:39:30,251 | sd | ERROR | sd_models | Load {op}: no model loaded
2024-10-30 15:39:30,254 | sd | DEBUG | script_callbacks | Script callback init time: system-info.py:app_started=0.09 task_scheduler.py:app_started=0.20
2024-10-30 15:39:30,256 | sd | DEBUG | shared | Save: file="config.json" json=34 bytes=1433 time=0.002
2024-10-30 15:39:30,260 | sd | INFO | webui | Startup time: 20.30 torch=7.93 gradio=3.09 diffusers=0.17 libraries=3.64 samplers=0.07 extensions=1.11 detailer=0.13 upscalers=0.07 networks=0.70 ui-networks=0.34 ui-txt2img=0.15 ui-img2img=0.15 ui-control=0.26 ui-extras=0.08 ui-models=0.07 ui-settings=0.70 ui-extensions=0.72 ui-defaults=0.11 launch=0.22 api=0.16 app-started=0.29
2024-10-30 15:39:30,282 | sd | INFO | webui | Launching browser
2024-10-30 15:39:33,360 | sd | INFO | server | MOTD: N/A
2024-10-30 15:39:37,981 | sd | DEBUG | theme | UI themes available: type=Standard themes=12
2024-10-30 15:39:38,580 | sd | INFO | api | Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
2024-10-30 15:39:59,671 | sd | DEBUG | launch | Server: alive=True jobs=1 requests=27 uptime=37 memory=0.96/31.95 backend=Backend.DIFFUSERS state=idle
2024-10-30 15:40:39,744 | sd | INFO | sd_models | Load model: select="Diffusers\ByteDance/SDXL-Lightning [c9a24f48e1]"
2024-10-30 15:40:39,750 | sd | INFO | sd_models | Autodetect model: detect="Stable Diffusion XL" class=StableDiffusionXLPipeline file="models\Diffusers\models--ByteDance--SDXL-Lightning\snapshots\c9a24f48e1c025556787b0c58dd67a091ece2e44" size=0MB
2024-10-30 15:40:39,759 | sd | ERROR | sd_models | Load {op}: no model loaded
2024-10-30 15:40:39,763 | sd | DEBUG | ui | Setting changed: sd_model_checkpoint=Diffusers\ByteDance/SDXL-Lightning [c9a24f48e1] progress=True
2024-10-30 15:40:39,765 | sd | DEBUG | shared | Save: file="config.json" json=34 bytes=1421 time=0.002
2024-10-30 15:40:42,208 | sd | INFO | sd_models | Load model: select="Diffusers\RunDiffusion/Juggernaut-XL-Lightning [a3035ee9ae]"
2024-10-30 15:40:42,213 | sd | INFO | sd_models | Autodetect model: detect="Stable Diffusion XL" class=StableDiffusionXLPipeline file="models\Diffusers\models--RunDiffusion--Juggernaut-XL-Lightning\snapshots\a3035ee9ae36901d8a66b0eb646eb550c2e3ea99" size=0MB
2024-10-30 15:40:42,221 | sd | ERROR | sd_models | Load {op}: no model loaded
2024-10-30 15:40:42,225 | sd | DEBUG | ui | Setting changed: sd_model_checkpoint=Diffusers\RunDiffusion/Juggernaut-XL-Lightning [a3035ee9ae] progress=True
2024-10-30 15:40:42,228 | sd | DEBUG | shared | Save: file="config.json" json=34 bytes=1433 time=0.003
2024-10-30 15:41:03,221 | sd | DEBUG | modeldata | Model requested: fn=f:txt2img
2024-10-30 15:41:03,224 | sd | INFO | sd_models | Load model: select="Diffusers\RunDiffusion/Juggernaut-XL-Lightning [a3035ee9ae]"
2024-10-30 15:41:03,227 | sd | INFO | sd_models | Autodetect model: detect="Stable Diffusion XL" class=StableDiffusionXLPipeline file="models\Diffusers\models--RunDiffusion--Juggernaut-XL-Lightning\snapshots\a3035ee9ae36901d8a66b0eb646eb550c2e3ea99" size=0MB
2024-10-30 15:41:03,236 | sd | ERROR | sd_models | Load {op}: no model loaded
2024-10-30 15:41:03,239 | sd | WARNING | txt2img | Aborted: op=txt model not loaded
2024-10-30 15:41:59,747 | sd | DEBUG | launch | Server: alive=True jobs=1 requests=63 uptime=157 memory=0.95/31.95 backend=Backend.DIFFUSERS state=idle
2024-10-30 15:43:59,824 | sd | DEBUG | launch | Server: alive=True jobs=1 requests=78 uptime=277 memory=0.95/31.95 backend=Backend.DIFFUSERS state=idle
2024-10-30 15:45:59,851 | sd | DEBUG | launch | Server: alive=True jobs=1 requests=86 uptime=397 memory=0.95/31.95 backend=Backend.DIFFUSERS state=idle
2024-10-30 15:48:00,284 | sd | DEBUG | launch | Server: alive=True jobs=1 requests=98 uptime=518 memory=0.95/31.95 backend=Backend.DIFFUSERS state=idle
2024-10-30 15:49:57,859 | sd | INFO | sd_models | Load model: select="realisticVisionV60B1_v51HyperInpaintVAE [7417b4ec2d]"
2024-10-30 15:49:57,869 | sd | INFO | sd_models | Autodetect model: detect="Stable Diffusion Inpaint" class=StableDiffusionInpaintPipeline file="C:\AI\WebUI\automatic\models\Stable-diffusion\realisticVisionV60B1_v51HyperInpaintVAE.safetensors" size=4068MB
2024-10-30 15:50:00,363 | sd | DEBUG | launch | Server: alive=True jobs=1 requests=128 uptime=638 memory=3.69/31.95 backend=Backend.DIFFUSERS state=idle
2024-10-30 15:50:03,021 | sd | DEBUG | sd_models | Setting model: pipeline=StableDiffusionInpaintPipeline config={'low_cpu_mem_usage': True, 'torch_dtype': torch.float16, 'load_connected_pipeline': True, 'extract_ema': False, 'use_safetensors': True, 'cache_dir': 'C:\\Users\\drake\\.cache\\huggingface\\hub'}
2024-10-30 15:50:03,031 | sd | INFO | textual_inversion | Load network: type=embeddings loaded=0 skipped=0 time=0.00
2024-10-30 15:50:03,034 | sd | DEBUG | sd_models | Setting model: component=VAE slicing=True
2024-10-30 15:50:03,038 | sd | DEBUG | sd_models | Setting model: component=VAE tiling=True
2024-10-30 15:50:03,041 | sd | DEBUG | sd_models | Setting model: attention="xFormers"
2024-10-30 15:50:03,043 | sd | ERROR | sd_models | Load model: Refer to https://github.com/facebookresearch/xformers for more information on how to install xformers
2024-10-30 15:50:03,046 | sd | ERROR | errors | Model: ModuleNotFoundError
2024-10-30 15:50:04,544 | sd | DEBUG | devices | GC: utilization={'gpu': 2, 'ram': 9, 'threshold': 80} gc={'collected': 377, 'saved': 0.0} before={'gpu': 0.18, 'ram': 2.97} after={'gpu': 0.18, 'ram': 2.97, 'retries': 0, 'oom': 0} device=cuda fn=reload_model_weights:load_diffuser time=0.24
2024-10-30 15:50:04,570 | sd | INFO | sd_models | Load model: time=5.17 load=5.16 native=256 memory={'ram': {'used': 2.97, 'total': 31.95}, 'gpu': {'used': 0.18, 'total': 7.98}, 'retries': 0, 'oom': 0}
2024-10-30 15:50:04,586 | sd | DEBUG | ui | Setting changed: sd_model_checkpoint=realisticVisionV60B1_v51HyperInpaintVAE [7417b4ec2d] progress=True
2024-10-30 15:50:04,588 | sd | DEBUG | shared | Save: file="config.json" json=34 bytes=1487 time=0.002
2024-10-30 15:50:17,389 | sd | INFO | sd_models | Load model: select="Diffusers\RunDiffusion/Juggernaut-XL-Lightning [a3035ee9ae]"
2024-10-30 15:50:17,669 | sd | DEBUG | devices | GC: utilization={'gpu': 2, 'ram': 9, 'threshold': 80} gc={'collected': 654, 'saved': 0.0} before={'gpu': 0.18, 'ram': 2.97} after={'gpu': 0.18, 'ram': 2.97, 'retries': 0, 'oom': 0} device=cuda fn=reload_model_weights:unload_model_weights time=0.25
2024-10-30 15:50:17,682 | sd | DEBUG | sd_models | Unload weights model: {'ram': {'used': 2.97, 'total': 31.95}, 'gpu': {'used': 0.18, 'total': 7.98}, 'retries': 0, 'oom': 0}
2024-10-30 15:50:17,695 | sd | INFO | sd_models | Autodetect model: detect="Stable Diffusion XL" class=StableDiffusionXLPipeline file="models\Diffusers\models--RunDiffusion--Juggernaut-XL-Lightning\snapshots\a3035ee9ae36901d8a66b0eb646eb550c2e3ea99" size=0MB
2024-10-30 15:50:17,706 | sd | ERROR | sd_models | Load {op}: no model loaded
2024-10-30 15:50:17,711 | sd | DEBUG | ui | Setting changed: sd_model_checkpoint=Diffusers\RunDiffusion/Juggernaut-XL-Lightning [a3035ee9ae] progress=True
2024-10-30 15:50:17,713 | sd | DEBUG | shared | Save: file="config.json" json=34 bytes=1495 time=0.002
2024-10-30 15:50:18,916 | sd | DEBUG | modeldata | Model requested: fn=f:txt2img
2024-10-30 15:50:18,919 | sd | INFO | sd_models | Load model: select="Diffusers\RunDiffusion/Juggernaut-XL-Lightning [a3035ee9ae]"
2024-10-30 15:50:18,923 | sd | INFO | sd_models | Autodetect model: detect="Stable Diffusion XL" class=StableDiffusionXLPipeline file="models\Diffusers\models--RunDiffusion--Juggernaut-XL-Lightning\snapshots\a3035ee9ae36901d8a66b0eb646eb550c2e3ea99" size=0MB
2024-10-30 15:50:18,931 | sd | ERROR | sd_models | Load {op}: no model loaded
2024-10-30 15:50:18,935 | sd | WARNING | txt2img | Aborted: op=txt model not loaded
2024-10-30 15:51:17,262 | sd | DEBUG | modeldata | Model requested: fn=f:txt2img
2024-10-30 15:51:17,266 | sd | INFO | sd_models | Load model: select="Diffusers\RunDiffusion/Juggernaut-XL-Lightning [a3035ee9ae]"
2024-10-30 15:51:17,272 | sd | INFO | sd_models | Autodetect model: detect="Stable Diffusion XL" class=StableDiffusionXLPipeline file="models\Diffusers\models--RunDiffusion--Juggernaut-XL-Lightning\snapshots\a3035ee9ae36901d8a66b0eb646eb550c2e3ea99" size=0MB
2024-10-30 15:51:17,282 | sd | ERROR | sd_models | Load {op}: no model loaded
2024-10-30 15:51:17,286 | sd | WARNING | txt2img | Aborted: op=txt model not loaded
2024-10-30 15:51:59,582 | sd | DEBUG | launch | Server: alive=True jobs=1 requests=162 uptime=757 memory=2.95/31.95 backend=Backend.DIFFUSERS state=idle
2024-10-30 15:53:59,670 | sd | DEBUG | launch | Server: alive=True jobs=1 requests=192 uptime=877 memory=2.95/31.95 backend=Backend.DIFFUSERS state=idle
2024-10-30 15:55:59,816 | sd | DEBUG | launch | Server: alive=True jobs=1 requests=222 uptime=997 memory=2.95/31.95 backend=Backend.DIFFUSERS state=idle
2024-10-30 15:57:35,085 | sd | INFO | webui | Exiting
```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
you're running `updated=2024-10-24` version, this should be fixed in the latest version already.
i just tried and it works.

**Comment by Maraket** [comment]
[sdnext.log](https://github.com/user-attachments/files/17593571/sdnext.log)
Unsure if this would apply, but on a fresh clone of the repo I freshly downloaded ByteDance/SDXL-Lightning and appeared to encounter the same error. 
Interestingly, doing a fresh pull on my previous repo, got Diffusters\RunDiffusion/Juggernaut-XL-Lightning appearing to work, so unsure if there is an issue with how the model is configured in hugging face, or if there is an issue with SD.Next

**Comment by vladmandic** [comment]
> I freshly downloaded ByteDance/SDXL-Lightning

if you take a look at <https://huggingface.co/ByteDance/SDXL-Lightning/tree/main>, you'll see that repo is NOT an actual model, its a collection of different loras/unets and models.

you could download (for example), `sdxl_lightning_8step.safetensors` and place it in your models/stable-diffusion folder and it should work.

**Comment by Maraket** [comment]
@vladmandic thank you for your patience and time, and apologies for my stupidity not to look deeper into it's documentation.
