### ISSUE TITLE
[Issue]: App hangs indefinitely on "Generate 100% Finishing" state after completing (and saving) current job 

### ISSUE THREAD

**Issue by CurseWave** [vladmandic/automatic#3588]
### Issue Description

Since the last update, I've been unable to cleanly chain art generation together. Whenever my app completes a batch of image, the text2img panel remains in a perpetual state of finishing the image. This happens while the image are already saved and seemingly finished in the storage. 

The current workaround I found: Refresh the browser page to reset the app. 

Attempted fix: Starting the app with the "--share" option, as per another user that had the same issue. 

This issue occurred across browsers: I tested on Firefox, Konqueror and Chrome, to the same effects. 
![Screenshot-Generate-100-Finishing](https://github.com/user-attachments/assets/dae0ef50-a770-426c-a7a7-452ac99313d2)
[sdnext.log](https://github.com/user-attachments/files/17878224/sdnext.log)

### Version Platform Description

22:11:45-942059 INFO     Starting SD.Next                                                                                                                                                                        
22:11:45-944996 INFO     Logger: file="/home/FullMoon/SDNext/sdnext.log" level=INFO size=5183838 mode=append                                                                                                     
22:11:45-946001 INFO     Python: version=3.10.6 platform=Linux bin="/home/FullMoon/SDNext/venv/bin/python3" venv="/home/FullMoon/SDNext/venv"                                                                    
22:11:45-963508 INFO     Version: app=sd.next updated=2024-11-21 hash=f5a2fa15 branch=master url=https://github.com/vladmandic/automatic/tree/master ui=main                                                     
22:11:46-092447 INFO     Repository latest available 6846f4e5d3e650d2a8dc8460906901086a350d27 2024-11-22T18:01:15Z                                                                                               
22:11:46-094718 INFO     Platform: arch=x86_64 cpu= system=Linux release=6.11.3-arch1-1 python=3.10.6 docker=False                                                                                               
22:11:46-096057 INFO     Args: ['--share']                                                                                                                                                                       
22:11:46-141121 INFO     Python: version=3.10.6 platform=Linux bin="/home/FullMoon/SDNext/venv/bin/python3" venv="/home/FullMoon/SDNext/venv"                                                                    
22:11:46-142112 INFO     ROCm: AMD toolkit detected                                                                                                                                                              
22:11:46-166917 INFO     ROCm: agents=['gfx1030']                                                                                                                                                                
22:11:46-167742 INFO     ROCm: version=6.0, using agent gfx1030 

### Relevant log output

```shell
2024-11-22 21:57:30.076	INFO	sd	modelloader	Available Upscalers: items=53 downloaded=3 user=0 time=0.00 types=['None', 'Lanczos', 'Nearest', 'SD', 'ESRGAN', 'LDSR', 'SCUNet', 'RealESRGAN', 'AuraSR', 'SwinIR', 'ChaiNNer']
2024-11-22 21:57:30.081	INFO	sd	styles	Available Styles: folder='models/styles' items=288 time=0.00
2024-11-22 21:57:30.082	INFO	sd	webui	UI start
2024-11-22 21:57:30.083	INFO	sd	theme	UI theme: type=Modern name='Default'
2024-11-22 21:57:31.277	INFO	sd	ui_extensions	Extension list is empty: refresh required
2024-11-22 21:57:32.656	INFO	sd	webui	Local URL: http://127.0.0.1:7860/
2024-11-22 21:57:32.658	INFO	sd	webui	Share URL: https://d64cd2ce06cd91a752.gradio.live
2024-11-22 21:57:32.758	INFO	sd	task_runner	[AgentScheduler] Task queue is empty
2024-11-22 21:57:32.758	INFO	sd	api	[AgentScheduler] Registering APIs
2024-11-22 21:57:32.872	INFO	sd	webui	Startup time: 519.63 ldm=516.77 extensions=0.05 ui-networks=0.17 ui-txt2img=0.12 ui-img2img=0.13 ui-control=0.25 ui-extras=0.06 ui-models=0.06 ui-settings=0.34 ui-extensions=0.12 ui-defaults=0.08 launch=1.22 app-started=0.20
2024-11-22 21:58:22.547	INFO	sd	server	MOTD: N/A
2024-11-22 21:58:27.230	INFO	sd	api	Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0
2024-11-22 21:58:35.738	INFO	sd	processing_diffusers	Base: class=StableDiffusionXLImg2ImgPipeline
2024-11-22 21:58:39.192	ERROR	sd	processing_diffusers	Processing: step=base args={'prompt_embeds': 'cuda:0:torch.float16:torch.Size([4, 385, 2048])', 'pooled_prompt_embeds': 'cuda:0:torch.float16:torch.Size([4, 1280])', 'negative_prompt_embeds': 'cuda:0:torch.float16:torch.Size([4, 385, 2048])', 'negative_pooled_prompt_embeds': 'cuda:0:torch.float16:torch.Size([4, 1280])', 'guidance_scale': 5.5, 'generator': [, , , ], 'callback_on_step_end': , 'callback_on_step_end_tensor_inputs': ['latents', 'prompt_embeds', 'negative_prompt_embeds', 'add_text_embeds', 'add_time_ids', 'negative_pooled_prompt_embeds', 'add_neg_time_ids'], 'num_inference_steps': 84, 'eta': 1.0, 'guidance_rescale': 0.7, 'denoising_start': None, 'denoising_end': None, 'output_type': 'latent', 'image': [, , , ], 'strength': 0.3} HIP out of memory. Tried to allocate 4.17 GiB. GPU 0 has a total capacity of 15.98 GiB of which 3.65 GiB is free. Of the allocated memory 11.46 GiB is allocated by PyTorch, and 379.19 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
2024-11-22 21:58:39.196	ERROR	sd	errors	Processing: OutOfMemoryError
2024-11-22 21:58:39.792	INFO	sd	processing	Processed: images=0 its=0.00 time=4.06 timers={'encode': 0.42, 'args': 0.43, 'process': 3.59} memory={'ram': {'used': 13.48, 'total': 62.72}, 'gpu': {'used': 12.34, 'total': 15.98}, 'retries': 6, 'oom': 6}
2024-11-22 21:58:39.793	INFO	sd	run	Control: pipeline units=0 process=0 time=4.08 init=0.00 proc=0.00 ctrl=4.08 outputs=0
2024-11-22 21:58:49.090	INFO	sd	processing_diffusers	Base: class=StableDiffusionXLImg2ImgPipeline
2024-11-22 21:58:55.390	ERROR	sd	processing_diffusers	Processing: step=base args={'prompt_embeds': 'cuda:0:torch.float16:torch.Size([4, 385, 2048])', 'pooled_prompt_embeds': 'cuda:0:torch.float16:torch.Size([4, 1280])', 'negative_prompt_embeds': 'cuda:0:torch.float16:torch.Size([4, 385, 2048])', 'negative_pooled_prompt_embeds': 'cuda:0:torch.float16:torch.Size([4, 1280])', 'guidance_scale': 5.5, 'generator': [, , , ], 'callback_on_step_end': , 'callback_on_step_end_tensor_inputs': ['latents', 'prompt_embeds', 'negative_prompt_embeds', 'add_text_embeds', 'add_time_ids', 'negative_pooled_prompt_embeds', 'add_neg_time_ids'], 'num_inference_steps': 84, 'eta': 1.0, 'guidance_rescale': 0.7, 'denoising_start': None, 'denoising_end': None, 'output_type': 'latent', 'image': [, , , ], 'strength': 0.3} HIP out of memory. Tried to allocate 4.17 GiB. GPU 0 has a total capacity of 15.98 GiB of which 3.03 GiB is free. Of the allocated memory 11.96 GiB is allocated by PyTorch, and 486.26 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
2024-11-22 21:58:55.394	ERROR	sd	errors	Processing: OutOfMemoryError
2024-11-22 21:58:56.526	INFO	sd	processing	Processed: images=0 its=0.00 time=7.44 timers={'gc': 0.26, 'encode': 0.37, 'args': 0.38, 'process': 7.03} memory={'ram': {'used': 13.48, 'total': 62.72}, 'gpu': {'used': 8.17, 'total': 15.98}, 'retries': 7, 'oom': 7}
2024-11-22 21:58:56.527	INFO	sd	run	Control: pipeline units=0 process=0 time=7.46 init=0.00 proc=0.00 ctrl=7.46 outputs=0
2024-11-22 21:59:01.288	INFO	sd	processing_diffusers	Base: class=StableDiffusionXLPipeline
2024-11-22 21:59:58.503	INFO	sd	processing_diffusers	Upscale: mode=1 upscaler='ESRGAN 4x Ultrasharp' context='Add with forward' resize=0x0 upscale=1920x3200
2024-11-22 22:00:00.642	INFO	sd	esrgan_model	Upscaler loaded: type=ESRGAN model=models/ESRGAN/ESRGAN-UltraSharp-4x.pth
2024-11-22 22:00:00.809	WARNING	sd	upscaler	Upscaler compile not available: backend=onediff available=['cudagraphs', 'inductor', 'onnxrt', 'openxla', 'tvm']
2024-11-22 22:00:12.676	INFO	sd	yolo	Load: type=Detailer name='face-yolo8n' model='/home/FullMoon/SDNext/models/yolo/face-yolo8n.pt' ultralytics=8.3.16 classes=['face']
2024-11-22 22:00:12.824	INFO	sd	yolo	Detailer: model='face-yolo8n' items=[{'label': 'face', 'score': 0.79, 'size': '430x580'}] args={'conf': 0.4, 'iou': 0.6} denoise=0.41 blur=10 width=1024 height=1024 padding=20
2024-11-22 22:00:13.001	INFO	sd	processing_diffusers	Base: class=StableDiffusionXLInpaintPipeline
2024-11-22 22:00:22.509	INFO	sd	processing	Processed: images=1 its=1.55 time=9.67 timers={'gc': 0.54, 'init': 0.44, 'encode': 0.5, 'args': 0.55, 'callback': 17.02, 'pipeline': 65.15, 'hires': 14.48, 'decode': 0.49, 'post': 0.09} memory={'ram': {'used': 13.51, 'total': 62.72}, 'gpu': {'used': 8.12, 'total': 15.98}, 'retries': 7, 'oom': 7}
2024-11-22 22:00:25.179	INFO	sd	images	Save: image='text2img/00022-1-Euler a-1519872537-20241122215901.png' type=PNG width=1920 height=3200 size=6788846
2024-11-22 22:00:25.250	INFO	sd	yolo	Detailer: model='face-yolo8n' items=[{'label': 'face', 'score': 0.77, 'size': '348x456'}] args={'conf': 0.4, 'iou': 0.6} denoise=0.41 blur=10 width=1024 height=1024 padding=20
2024-11-22 22:00:25.431	INFO	sd	processing_diffusers	Base: class=StableDiffusionXLInpaintPipeline
2024-11-22 22:00:35.656	INFO	sd	processing	Processed: images=1 its=1.44 time=10.39 timers={'gc': 1.06, 'init': 3.36, 'encode': 0.63, 'args': 0.72, 'move': 0.03, 'callback': 17.23, 'pipeline': 74.08, 'hires': 14.48, 'decode': 1.5, 'post': 0.19} memory={'ram': {'used': 13.51, 'total': 62.72}, 'gpu': {'used': 7.57, 'total': 15.98}, 'retries': 7, 'oom': 7}
2024-11-22 22:00:38.264	INFO	sd	images	Save: image='text2img/00023-2-Euler a-1519872538-20241122215901.png' type=PNG width=1920 height=3200 size=6608301
2024-11-22 22:00:38.333	INFO	sd	yolo	Detailer: model='face-yolo8n' items=[{'label': 'face', 'score': 0.77, 'size': '428x569'}] args={'conf': 0.4, 'iou': 0.6} denoise=0.41 blur=10 width=1024 height=1024 padding=20
2024-11-22 22:00:38.511	INFO	sd	processing_diffusers	Base: class=StableDiffusionXLInpaintPipeline
2024-11-22 22:00:48.530	INFO	sd	processing	Processed: images=1 its=1.47 time=10.18 timers={'gc': 1.55, 'init': 6.22, 'encode': 0.77, 'args': 0.9, 'move': 0.04, 'callback': 17.64, 'pipeline': 82.82, 'hires': 14.48, 'decode': 2.5, 'post': 0.29} memory={'ram': {'used': 13.51, 'total': 62.72}, 'gpu': {'used': 7.6, 'total': 15.98}, 'retries': 7, 'oom': 7}
2024-11-22 22:00:51.158	INFO	sd	images	Save: image='text2img/00024-3-Euler a-1519872539-20241122215901.png' type=PNG width=1920 height=3200 size=6815052
2024-11-22 22:00:51.229	INFO	sd	yolo	Detailer: model='face-yolo8n' items=[{'label': 'face', 'score': 0.76, 'size': '376x530'}] args={'conf': 0.4, 'iou': 0.6} denoise=0.41 blur=10 width=1024 height=1024 padding=20
2024-11-22 22:00:51.409	INFO	sd	processing_diffusers	Base: class=StableDiffusionXLInpaintPipeline
2024-11-22 22:01:01.410	INFO	sd	processing	Processed: images=1 its=1.48 time=10.17 timers={'gc': 2.04, 'init': 9.09, 'encode': 0.91, 'args': 1.07, 'move': 0.05, 'callback': 18.05, 'pipeline': 91.55, 'hires': 14.48, 'decode': 3.49, 'post': 0.39} memory={'ram': {'used': 13.51, 'total': 62.72}, 'gpu': {'used': 7.58, 'total': 15.98}, 'retries': 7, 'oom': 7}
2024-11-22 22:01:04.018	INFO	sd	images	Save: image='text2img/00025-4-Euler a-1519872540-20241122215901.png' type=PNG width=1920 height=3200 size=7078897
2024-11-22 22:01:04.290	INFO	sd	images	Save: image='outputs/grids/01254--Euler a-1519872537-20241122215901-grid.jpg' type=JPEG width=3840 height=6400 size=11286702
2024-11-22 22:01:04.305	INFO	sd	processing	Processed: images=5 its=1.02 time=122.75 timers={'gc': 2.04, 'init': 9.09, 'encode': 0.91, 'args': 1.07, 'move': 0.05, 'callback': 18.05, 'pipeline': 91.55, 'hires': 14.48, 'decode': 3.49, 'post': 3.28} memory={'ram': {'used': 13.51, 'total': 62.72}, 'gpu': {'used': 7.58, 'total': 15.98}, 'retries': 7, 'oom': 7}
```

### Backend

Diffusers

### UI

ModernUI

### Branch

Master

### Model

StableDiffusion XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i'll check, but there were no changes in that part of the code.
`--share` will definitely not help.
does this problem occur with standard ui as well?
also, can you try `--disable-queue` command line param?

**Comment by vladmandic** [comment]
i'm not saying you shouldn't use modern, i'm just trying to find out exact scenario when this is happening since i cannot reproduce.
can you run sdnext with browser inspector window open and once issue occurs upload a screenshot of the inspector?
since you've already tried different browsers, lets focus on chrome for now just so we're on the same page.

**Comment by CurseWave** [comment]
So I noticed that the text panel seems to work in Chrome, but not the control panel (which is what I've been using for a while). Anyhow, I repro'd the issue on Chrome: 

![image](https://github.com/user-attachments/assets/a36cb74b-af20-436e-b9bf-bc2a3e704724)

**Comment by vladmandic** [comment]
ok, this is useful info, i'll check.

**Comment by vladmandic** [comment]
i just fixed the first issue.
second one with reference to `props` indicates mismatch in ui state, likely due to stale js code.
so please update first and then make sure that browser cache is cleared. and report back with new logs if issue persists.

**Comment by CurseWave** [comment]
Issue still occurs after update + browser cache clearing. New logs: 

```
2024-11-23 18:59:19.931	INFO	sd	modelloader	Available Upscalers: items=53 downloaded=3 user=0 time=0.01 types=['None', 'Lanczos', 'Nearest', 'ChaiNNer', 'SD', 'ESRGAN', 'LDSR', 'SCUNet', 'RealESRGAN', 'AuraSR', 'SwinIR']
2024-11-23 18:59:19.938	INFO	sd	styles	Available Styles: folder='models/styles' items=288 time=0.00
2024-11-23 18:59:19.940	INFO	sd	webui	UI start
2024-11-23 18:59:19.941	INFO	sd	theme	UI theme: type=Modern name='Default'
2024-11-23 18:59:21.169	INFO	sd	ui_extensions	Extension list is empty: refresh required
2024-11-23 18:59:21.614	INFO	sd	webui	Local URL: http://127.0.0.1:7860/
2024-11-23 18:59:21.797	INFO	sd	task_runner	[AgentScheduler] Task queue is empty
2024-11-23 18:59:21.798	INFO	sd	api	[AgentScheduler] Registering APIs
2024-11-23 18:59:22.104	INFO	sd	sd_checkpoint	Load model: select='ponyRealism_V22MainVAE [7c97ecf786]'
2024-11-23 18:59:22.106	INFO	sd	sd_detect	Autodetect model: detect='Stable Diffusion XL' class=StableDiffusionXLPipeline file='/home/FullMoon/SDNext/models/Stable-diffusion/ponyRealism_V22MainVAE.safetensors' size=6776MB
2024-11-23 18:59:40.820	INFO	sd	textual_inversion	Load network: type=embeddings loaded=0 skipped=0 time=0.00
2024-11-23 18:59:41.364	INFO	sd	sd_models_compile	Model compile: pipeline=StableDiffusionXLPipeline mode=default backend=onediff fullgraph=True compile=['Model', 'Upscaler']
2024-11-23 18:59:41.366	WARNING	sd	sd_models_compile	Model compile: task=onediff No module named 'onediff'
2024-11-23 18:59:41.629	INFO	sd	sd_models	Load model: time=19.26 load=18.71 move=0.52 native=1024 memory={'ram': {'used': 12.64, 'total': 62.72}, 'gpu': {'used': 7.04, 'total': 15.98}, 'retries': 0, 'oom': 0}
2024-11-23 18:59:41.631	INFO	sd	webui	Startup time: 29.13 torch=4.76 gradio=0.69 diffusers=0.06 libraries=1.15 extensions=0.68 ui-networks=0.17 ui-txt2img=0.20 ui-img2img=0.13 ui-control=0.24 ui-extras=0.05 ui-models=0.05 ui-settings=0.31 ui-extensions=0.30 ui-defaults=0.08 launch=0.11 api=0.10 app-started=0.38 checkpoint=19.53
2024-11-23 18:59:42.953	INFO	sd	server	MOTD: N/A
2024-11-23 18:59:47.296	INFO	sd	api	Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0
2024-11-23 18:59:57.265	INFO	sd	processing_diffusers	Base: class=StableDiffusionXLPipeline
2024-11-23 19:00:55.071	INFO	sd	processing_diffusers	Upscale: mode=1 upscaler='ESRGAN 4x Ultrasharp' context='Add with forward' resize=0x0 upscale=2240x2880
2024-11-23 19:00:57.228	INFO	sd	esrgan_model	Upscaler loaded: type=ESRGAN model=models/ESRGAN/ESRGAN-UltraSharp-4x.pth
2024-11-23 19:00:57.390	WARNING	sd	upscaler	Upscaler compile not available: backend=onediff available=['cudagraphs', 'inductor', 'onnxrt', 'openxla', 'tvm']
2024-11-23 19:01:09.550	INFO	sd	yolo	Load: type=Detailer name='face-yolo8n' model='/home/FullMoon/SDNext/models/yolo/face-yolo8n.pt' ultralytics=8.3.16 classes=['face']
2024-11-23 19:01:10.243	INFO	sd	yolo	Detailer: model='face-yolo8n' items=[{'label': 'face', 'score': 0.77, 'size': '349x556'}] args={'conf': 0.65, 'iou': 0.6} denoise=0.3 blur=10 width=1024 height=1024 padding=20
2024-11-23 19:01:10.437	INFO	sd	processing_diffusers	Base: class=StableDiffusionXLInpaintPipeline
2024-11-23 19:01:20.194	INFO	sd	processing	Processed: images=1 its=1.51 time=9.94 timers={'gc': 0.44, 'init': 1.04, 'encode': 0.95, 'args': 1.03, 'move': 0.02, 'callback': 24.1, 'pipeline': 65.56, 'hires': 14.67, 'decode': 0.51, 'post': 0.1} memory={'ram': {'used': 12.82, 'total': 62.72}, 'gpu': {'used': 8.01, 'total': 15.98}, 'retries': 0, 'oom': 0}
2024-11-23 19:01:22.986	INFO	sd	images	Save: image='text2img/00000-1-Euler a-3222296368-20241123185957.png' type=PNG width=2240 height=2880 size=6722164
2024-11-23 19:01:23.063	INFO	sd	yolo	Detailer: model='face-yolo8n' items=[{'label': 'face', 'score': 0.73, 'size': '335x517'}] args={'conf': 0.65, 'iou': 0.6} denoise=0.3 blur=10 width=1024 height=1024 padding=20
2024-11-23 19:01:23.244	INFO	sd	processing_diffusers	Base: class=StableDiffusionXLInpaintPipeline
2024-11-23 19:01:34.473	INFO	sd	processing	Processed: images=1 its=1.32 time=11.40 timers={'gc': 0.88, 'init': 4.09, 'encode': 1.09, 'args': 1.21, 'move': 0.03, 'callback': 24.63, 'pipeline': 75.52, 'hires': 14.67, 'decode': 1.49, 'post': 0.21} memory={'ram': {'used': 12.82, 'total': 62.72}, 'gpu': {'used': 7.5, 'total': 15.98}, 'retries': 0, 'oom': 0}
2024-11-23 19:01:37.255	INFO	sd	images	Save: image='text2img/00001-2-Euler a-3222296369-20241123185957.png' type=PNG width=2240 height=2880 size=7544583
2024-11-23 19:01:37.328	INFO	sd	yolo	Detailer: model='face-yolo8n' items=[{'label': 'face', 'score': 0.78, 'size': '336x524'}] args={'conf': 0.65, 'iou': 0.6} denoise=0.3 blur=10 width=1024 height=1024 padding=20
2024-11-23 19:01:37.515	INFO	sd	processing_diffusers	Base: class=StableDiffusionXLInpaintPipeline
2024-11-23 19:01:48.120	INFO	sd	processing	Processed: images=1 its=1.39 time=10.78 timers={'gc': 1.32, 'init': 7.13, 'encode': 1.23, 'args': 1.39, 'move': 0.04, 'callback': 25.05, 'pipeline': 84.87, 'hires': 14.67, 'decode': 2.45, 'post': 0.31} memory={'ram': {'used': 12.82, 'total': 62.72}, 'gpu': {'used': 7.5, 'total': 15.98}, 'retries': 0, 'oom': 0}
2024-11-23 19:01:50.948	INFO	sd	images	Save: image='text2img/00002-3-Euler a-3222296370-20241123185957.png' type=PNG width=2240 height=2880 size=7100027
2024-11-23 19:01:51.026	INFO	sd	yolo	Detailer: model='face-yolo8n' items=[{'label': 'face', 'score': 0.76, 'size': '479x756'}] args={'conf': 0.65, 'iou': 0.6} denoise=0.3 blur=10 width=1024 height=1024 padding=20
2024-11-23 19:01:51.214	INFO	sd	processing_diffusers	Base: class=StableDiffusionXLInpaintPipeline
2024-11-23 19:02:01.219	INFO	sd	processing	Processed: images=1 its=1.47 time=10.18 timers={'gc': 1.77, 'init': 10.22, 'encode': 1.37, 'args': 1.57, 'move': 0.06, 'callback': 25.46, 'pipeline': 93.6, 'hires': 14.67, 'decode': 3.41, 'post': 0.42} memory={'ram': {'used': 12.82, 'total': 62.72}, 'gpu': {'used': 7.51, 'total': 15.98}, 'retries': 0, 'oom': 0}
2024-11-23 19:02:04.050	INFO	sd	images	Save: image='text2img/00003-4-Euler a-3222296371-20241123185957.png' type=PNG width=2240 height=2880 size=7095887
2024-11-23 19:02:04.335	INFO	sd	images	Save: image='outputs/grids/01338--Euler a-3222296368-20241123185957-grid.jpg' type=JPEG width=4480 height=5760 size=11333535
2024-11-23 19:02:04.349	INFO	sd	processing	Processed: images=5 its=0.99 time=126.80 timers={'gc': 1.77, 'init': 10.22, 'encode': 1.37, 'args': 1.57, 'move': 0.06, 'callback': 25.46, 'pipeline': 93.6, 'hires': 14.67, 'decode': 3.41, 'post': 3.55} memory={'ram': {'used': 12.82, 'total': 62.72}, 'gpu': {'used': 7.53, 'total': 15.98}, 'retries': 0, 'oom': 0}
```

Client Log
```
2024-11-23 23:59:47.293initPromptChecker
2024-11-23 23:59:47.294initLogMonitor
2024-11-23 23:59:47.294initContextMenu
2024-11-23 23:59:47.294initDragDrop
2024-11-23 23:59:47.303initSettings
2024-11-23 23:59:47.303initImageViewer
2024-11-23 23:59:47.303initGallery
2024-11-23 23:59:47.303initGenerationParams
2024-11-23 23:59:47.303initControlUI
2024-11-23 23:59:47.319reconnectUI
2024-11-23 23:59:47.805toggleCompact false undefined
2024-11-23 23:59:47.808setFontSize 14
2024-11-23 23:59:47.810initPrompts
2024-11-23 23:59:47.813uiReady
2024-11-23 23:59:47.813userAgent Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0
2024-11-23 23:59:47.813UI settings {"uiux_hide_legacy":true,"uiux_persist_layout":true,"uiux_no_slider_layout":false,"uiux_show_input_range_ticks":true,"uiux_show_labels_aside":false,"uiux_show_labels_main":false,"uiux_show_labels_tabs":false,"uiux_show_labels_control":false,"uiux_no_headers_params":false,"uiux_show_outline_params":true,"uiux_mobile_scale":0.7,"uiux_enable_console_log":false,"uiux_max_resolution_output":4096,"uiux_disable_transitions":false}
2024-11-23 23:59:47.813UI: Go to the Firefox about:config page, then search and toggle layout. css.has-selector. enabled
2024-11-23 23:59:47.815UI removeStyleSheets 33
2024-11-23 23:59:47.881UI removeElements 17708/17838
2024-11-23 23:59:47.881mainUiUx 0.068
2024-11-23 23:59:47.882initExtraNetworks
2024-11-23 23:59:47.882loadAllTemplates 0
2024-11-23 23:59:47.893initModels 7
2024-11-23 23:59:48.074loadAllPortals 0.076
2024-11-23 23:59:48.137hideLegacy true
2024-11-23 23:59:48.213setStored: tab-main_group-current=control_nav
2024-11-23 23:59:48.214setStored: tab-layout_extra_networks-current=btn-en-layout-control
2024-11-23 23:59:48.216extraTweaks 0.078
2024-11-23 23:59:48.284removeSplash
2024-11-23 23:59:48.285startupTime 6.05
2024-11-23 23:59:48.287showNetworks
2024-11-23 23:59:48.570initIndexDB 0
2024-11-23 23:59:48.625setHints {"type":2,"elements":3122,"localized":0,"hints":831,"data":292,"time":50}
2024-11-23 23:59:56.944submitControl
2024-11-24 00:03:18.826setStored: tab-extra_networks-current=btn_model_merger
2024-11-24 00:03:19.839setStored: tab-extra_networks-current=btn_extensions
2024-11-24 00:03:25.019setStored: tab-extra_networks-current=btn_console
2024-11-24 00:03:27.318setStored: split-app-sizes=61.02828857029996,88.97171142970004
```

![image](https://github.com/user-attachments/assets/64e507b8-094c-4311-9986-2a70935fd664)

**Comment by vladmandic** [comment]
is the verbose level included in browser inspector console log? there should be `taskEnd` message ~30sec after last progress update no matter what.

**Comment by CurseWave** [comment]
I've tried to get all the info from Firefox, here's the chrome output: 

![image](https://github.com/user-attachments/assets/20d35240-0a8c-4b5e-a276-9a348eabc0f3)

**Comment by vladmandic** [comment]
open file `javascript/progressBar.js` and find line 
> // debug('onProgress', res);
and just remove `//` from it.
save, clear browser cache, reload, try - it should have much more detailed logging in browser console.

**Comment by CurseWave** [comment]
There isn't a debug line like this in the mentioned file. I searched manually and with control+F, there doesn't seem to be many commented lines at all.

**Comment by vladmandic** [comment]
ah, sorry, forgot to mention you have to be on dev branch and with latest update.

**Comment by CurseWave** [comment]
I _think_ that I repro'd the issue, but I'm not seeing the exact same behavior on the dev branch. I am not sure I have 100% the exact same set up as my master install, I had to copy my config files and jsons to get close. So the console still displayed error, but I wasn't hanging as described above. 
![image](https://github.com/user-attachments/assets/9a763f19-ee83-404e-b33e-25cf8d83fcc9)_
