### ISSUE TITLE
[Extension]: Adetailer OOM error after update

### ISSUE THREAD

**Issue by Sinmero** [vladmandic/automatic#3657]
### Issue Description

After updating to xmas version i get `ONNX failed to initialize: DLL load failed while importing onnx_cpp2py_export` error on launch.

It keeps starting as usual after that and i am able to generate images except of OOM errors when detailer is running.
Somehow if i keep changing the prompt for each generation i get stable 1.7 generation speed and everything is fine but as soon as i generate 2 images with the same prompt the speed start to jump 1.7~1.3 and i get OOM error when detailer should start doing its thing. 

Also the same seed images seem to be different compared to those before the update.

I get this error on both the old install and on the clean one.

Basically i would like to not have OOM when detailer is running and images to look the same as before if possible.

I tried --reinstall. It didnt help.
I tried running 
`pip uninstall onnx onnxruntime onnxruntime-gpu`
`pip install onnx onnx==1.14.0 onnxruntime-gpu==1.15.0`
As was suggested somewhere on the internet. It didnt help.

### Version Platform Description

21:02:26-515369 INFO     Logger: file="F:\AI\vladmandicXLCopium\automatic\sdnext.log" level=INFO size=20687 mode=append
21:02:26-530996 INFO     Python: version=3.10.6 platform=Windows
                         bin="F:\AI\vladmandicXLCopium\automatic\venv\Scripts\python.exe"
                         venv="F:\AI\vladmandicXLCopium\automatic\venv"
21:02:26-677802 INFO     Version: app=sd.next updated=2024-12-24 hash=451eeab1 branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
21:02:27-163525 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.6 docker=False
21:02:27-163525 INFO     Args: []
21:02:27-179150 INFO     CUDA: nVidia toolkit detected
21:02:27-317167 INFO     Install: verifying requirements
21:02:27-317167 INFO     Verifying packages
21:02:27-348420 INFO     Extensions: disabled=['sdnext-modernui', 'Lora']
21:02:27-348420 INFO     Extensions: enabled=['sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-rembg'] extensions-builtin
21:02:27-364045 INFO     Extensions: enabled=['adetailer', 'sd-dynamic-prompts'] extensions
21:02:27-364045 INFO     Startup: quick launch
21:02:27-364045 INFO     Extensions: disabled=['sdnext-modernui', 'Lora']
21:02:27-364045 INFO     Extensions: enabled=['sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-rembg'] extensions-builtin
21:02:27-364045 INFO     Extensions: enabled=['adetailer', 'sd-dynamic-prompts'] extensions
21:02:27-379672 INFO     Command line args: []
21:02:37-210008 INFO     Device detect: memory=8.0 optimization=balanced
21:02:37-749124 WARNING  Setting validation: unknown=['multiple_tqdm']
21:02:37-749124 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
21:02:37-780376 INFO     Torch parameters: backend=cuda device=cuda config=Auto dtype=torch.bfloat16 vae=torch.bfloat16
                         unet=torch.bfloat16 context=no_grad nohalf=False nohalfvae=False upcast=False
                         deterministic=False test-fp16=True test-bf16=True optimization="Scaled-Dot-Product"
21:02:40-383575 ERROR    ONNX failed to initialize: DLL load failed while importing onnx_cpp2py_export: Произошел сбой
                         в программе инициализации библиотеки динамической компоновки (DLL).
21:02:43-399918 INFO     Device: device=NVIDIA GeForce RTX 3070 Ti n=1 arch=sm_90 capability=(8, 6) cuda=12.4
                         cudnn=90100 driver=566.36

### Relevant log output

```shell
20:46:32-727672 INFO     Starting SD.Next
20:46:32-727672 INFO     Logger: file="F:\AI\vladmandicXLCopium\automatic\sdnext.log" level=DEBUG size=65 mode=create
20:46:32-727672 INFO     Python: version=3.10.6 platform=Windows
                         bin="F:\AI\vladmandicXLCopium\automatic\venv\Scripts\python.exe"
                         venv="F:\AI\vladmandicXLCopium\automatic\venv"
20:46:32-883931 INFO     Version: app=sd.next updated=2024-12-24 hash=451eeab1 branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
20:46:33-336490 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.6 docker=False
20:46:33-336490 DEBUG    Packages: venv=venv site=['venv', 'venv\\lib\\site-packages']
20:46:33-336490 INFO     Args: ['--debug']
20:46:33-336490 DEBUG    Setting environment tuning
20:46:33-336490 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
20:46:33-352117 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=False
20:46:33-367743 INFO     CUDA: nVidia toolkit detected
20:46:33-508385 INFO     Install: verifying requirements
20:46:33-524003 INFO     Verifying packages
20:46:33-539629 DEBUG    Timestamp repository update time: Tue Dec 24 16:58:24 2024
20:46:33-555255 INFO     Startup: standard
20:46:33-555255 INFO     Verifying submodules
20:46:35-346626 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
20:46:35-409131 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
20:46:35-471634 DEBUG    Git submodule: extensions-builtin/sd-webui-agent-scheduler / main
20:46:35-565390 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
20:46:35-565390 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / main
20:46:35-627895 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
20:46:35-690399 DEBUG    Git submodule: modules/k-diffusion / master
20:46:35-784155 DEBUG    Git detached head detected: folder="wiki" reattach=master
20:46:35-784155 DEBUG    Git submodule: wiki / master
20:46:35-831034 DEBUG    Register paths
20:46:35-893537 DEBUG    Installed packages: 188
20:46:35-893537 DEBUG    Extensions all: ['sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-rembg']
20:46:36-002919 DEBUG    Extension installer:
                         F:\AI\vladmandicXLCopium\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
20:46:38-065157 DEBUG    Extension installer:
                         F:\AI\vladmandicXLCopium\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
20:46:44-331739 DEBUG    Extensions all: ['adetailer', 'sd-dynamic-prompts']
20:46:44-331739 DEBUG    Extension force: name="adetailer" commit=a89c01d
20:46:44-917579 DEBUG    Extension installer: F:\AI\vladmandicXLCopium\automatic\extensions\adetailer\install.py
20:46:54-401666 INFO     Extension installed packages: adetailer ['cffi==1.17.1', 'jax==0.4.38', 'jaxlib==0.4.38',
                         'mediapipe==0.10.20', 'ml-dtypes==0.5.0', 'opencv-contrib-python==4.10.0.84',
                         'sounddevice==0.5.1']
20:46:54-401666 DEBUG    Extension installer:
                         F:\AI\vladmandicXLCopium\automatic\extensions\sd-dynamic-prompts\install.py
20:46:54-620430 INFO     Extensions enabled: ['sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-rembg', 'adetailer', 'sd-dynamic-prompts']
20:46:54-636056 INFO     Install: verifying requirements
20:46:54-636056 DEBUG    Setup complete without errors: 1735148815
20:46:54-636056 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
20:46:54-636056 INFO     Command line args: ['--debug'] debug=True
20:46:54-636056 DEBUG    Env flags: []
20:46:54-636056 DEBUG    Starting module: <module 'webui' from 'F:\\AI\\vladmandicXLCopium\\automatic\\webui.py'>
20:47:01-036066 DEBUG    Huggingface cache: folder="C:\Users\\.cache\huggingface\hub"
20:47:02-634596 INFO     Device detect: memory=8.0 optimization=balanced
20:47:02-634596 DEBUG    Read: file="config.json" json=42 bytes=2164 time=0.000 fn=<module>:load
20:47:02-991327 WARNING  Setting validation: unknown=['multiple_tqdm']
20:47:02-991327 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
20:47:02-991327 DEBUG    Read: file="html\reference.json" json=62 bytes=32964 time=0.000
                         fn=_call_with_frames_removed:<module>
20:47:03-038205 INFO     Torch parameters: backend=cuda device=cuda config=Auto dtype=torch.bfloat16 vae=torch.bfloat16
                         unet=torch.bfloat16 context=no_grad nohalf=False nohalfvae=False upcast=False
                         deterministic=False test-fp16=True test-bf16=True optimization="Scaled-Dot-Product"
20:47:05-761517 ERROR    ONNX failed to initialize: DLL load failed while importing onnx_cpp2py_export: Произошел сбой
                         в программе инициализации библиотеки динамической компоновки (DLL).
20:47:08-462422 DEBUG    ONNX failed to initialize XL pipelines: Failed to import
                         optimum.onnxruntime.modeling_diffusion because of the following error (look up to see its
                         traceback):
                         Failed to import optimum.onnx.graph_transformations because of the following error (look up to
                         see its traceback):
                         DLL load failed while importing onnx_cpp2py_export: Произошел сбой в программе инициализации
                         библиотеки динамической компоновки (DLL).
20:47:08-516403 INFO     Device: device=NVIDIA GeForce RTX 3070 Ti n=1 arch=sm_90 capability=(8, 6) cuda=12.4
                         cudnn=90100 driver=566.36
20:47:09-067793 INFO     Torch: torch==2.5.1+cu124 torchvision==0.20.1+cu124
20:47:09-083419 INFO     Packages: diffusers==0.33.0.dev0 transformers==4.47.1 accelerate==1.2.1 gradio==3.43.2
20:47:09-522109 DEBUG    Importing LDM
20:47:09-537735 DEBUG    Entering start sequence
20:47:09-537735 DEBUG    Initializing
20:47:09-537735 DEBUG    Read: file="metadata.json" json=340 bytes=1103701 time=0.000 fn=initialize:init_metadata
20:47:09-553361 DEBUG    Read: file="cache.json" json=2 bytes=585 time=0.000 fn=initialize:init_cache
20:47:09-600239 INFO     Available VAEs: path="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\VAE" items=8
20:47:09-600239 INFO     Available UNets: path="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\UNET" items=0
20:47:09-600239 INFO     Available TEs: path="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\Text-encoder" items=0
20:47:09-615865 INFO     Available Models: items=45
                         safetensors="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\Stable-diffusion":45
                         diffusers="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\Diffusers":0 time=0.02
20:47:09-647117 INFO     Available LoRAs: path="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\Lora" items=296
                         folders=3 time=0.02
20:47:09-662743 INFO     Available Styles: folder="models\styles" items=288 time=0.02
20:47:09-756499 INFO     Available Yolo: path="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\yolo" items=6
                         downloaded=1
20:47:09-756499 DEBUG    Disabled extensions: ['Lora', 'sdnext-modernui']
20:47:09-756499 INFO     Load extensions
20:47:10-522175 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py'
                         Using sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
20:47:10-898541 INFO     Extension: script='extensions\adetailer\scripts\!adetailer.py' [-] ADetailer initialized.
                         version: 24.5.1, num models: 10
20:47:10-945248 DEBUG    Extensions init time: 1.17 pulid_ext.py=0.19 sd-webui-agent-scheduler=0.45 adetailer=0.38
20:47:10-960874 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2672 time=0.000 fn=__init__:__init__
20:47:10-976493 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=24 bytes=2719
                         time=0.000 fn=__init__:find_scalers
20:47:10-976493 DEBUG    chaiNNer models: path="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\chaiNNer" defined=24
                         discovered=0 downloaded=3
20:47:10-976493 DEBUG    Upscaler type=ESRGAN folder="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\ESRGAN"
                         model="4x-UltraMix_Restore"
                         path="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\ESRGAN\4x-UltraMix_Restore.pth"
20:47:10-976493 DEBUG    Upscaler type=ESRGAN folder="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\ESRGAN"
                         model="4x-UltraMix_Smooth"
                         path="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\ESRGAN\4x-UltraMix_Smooth.pth"
20:47:10-976493 DEBUG    Upscaler type=ESRGAN folder="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\ESRGAN"
                         model="4x_foolhardy_Remacri"
                         path="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\ESRGAN\4x_foolhardy_Remacri.pth"
20:47:10-992119 DEBUG    Upscaler type=ESRGAN folder="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\ESRGAN"
                         model="ESRGAN_4x"
                         path="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\ESRGAN\ESRGAN_4x.pth"
20:47:10-992119 DEBUG    Upscaler type=SCUNet folder="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\SCUNet"
                         model="ScuNET" path="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\SCUNet\ScuNET.pth"
20:47:10-992119 DEBUG    Upscaler type=SwinIR folder="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\SwinIR"
                         model="SwinIR_4x"
                         path="F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\SwinIR\SwinIR_4x.pth"
20:47:10-992119 INFO     Available Upscalers: items=59 downloaded=13 user=6 time=0.05 types=['None', 'Lanczos',
                         'Nearest', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'LDSR', 'RealESRGAN', 'SCUNet', 'SD', 'SwinIR']
20:47:11-007745 INFO     UI start
20:47:11-007745 DEBUG    UI themes available: type=Standard themes=13
20:47:11-007745 INFO     UI theme: type=Standard name="invoked"
20:47:11-007745 DEBUG    UI theme: css="F:\AI\vladmandicXLCopium\automatic\javascript\invoked.css" base="sdnext.css"
                         user="None"
20:47:11-007745 DEBUG    UI initialize: txt2img
20:47:11-179631 DEBUG    Networks: page='model' items=106 subfolders=8 tab=txt2img
                         folders=['F:\\AI\\AUTOMATIC1111\\stable-diffusion-webui\\models\\Stable-diffusion',
                         'F:\\AI\\AUTOMATIC1111\\stable-diffusion-webui\\models\\Diffusers', 'models\\Reference']
                         list=0.09 thumb=0.02 desc=0.00 info=0.00 workers=8 sort=Date [Newest]
20:47:11-195257 DEBUG    Networks: page='lora' items=296 subfolders=10 tab=txt2img
                         folders=['F:\\AI\\AUTOMATIC1111\\stable-diffusion-webui\\models\\Lora'] list=0.14 thumb=0.06
                         desc=0.13 info=0.00 workers=8 sort=Date [Newest]
20:47:11-210883 DEBUG    Networks: page='style' items=288 subfolders=1 tab=txt2img folders=['models\\styles', 'html']
                         list=0.09 thumb=0.00 desc=0.00 info=0.00 workers=8 sort=Date [Newest]
20:47:11-210883 DEBUG    Networks: page='embedding' items=34 subfolders=0 tab=txt2img
                         folders=['F:\\AI\\AUTOMATIC1111\\stable-diffusion-webui\\embeddings'] list=0.08 thumb=0.02
                         desc=0.02 info=0.00 workers=8 sort=Date [Newest]
20:47:11-210883 DEBUG    Networks: page='vae' items=8 subfolders=0 tab=txt2img
                         folders=['F:\\AI\\AUTOMATIC1111\\stable-diffusion-webui\\models\\VAE'] list=0.06 thumb=0.03
                         desc=0.00 info=0.00 workers=8 sort=Date [Newest]
20:47:11-226509 DEBUG    Networks: page='history' items=0 subfolders=0 tab=txt2img folders=[] list=0.00 thumb=0.00
                         desc=0.00 info=0.00 workers=8 sort=Date [Newest]
20:47:11-320273 DEBUG    Script: op=before-component total=0.02 scripts=['MuLan: Multi Language Prompts:0.02']
20:47:11-539037 DEBUG    UI initialize: img2img
20:47:11-726550 DEBUG    Script: op=before-component total=0.02 scripts=['IP Adapters:0.02']
20:47:11-789054 DEBUG    UI initialize: control models=F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\control
20:47:12-421476 DEBUG    Script: op=after-component total=0.02 scripts=['Regional prompting:0.02']
20:47:12-499608 DEBUG    Read: file="ui-config.json" json=0 bytes=2 time=0.000 fn=__init__:read_from_file
20:47:12-843379 DEBUG    Script: op=before-component total=0.02 scripts=['ADetailer:0.02']
20:47:12-843379 DEBUG    UI themes available: type=Standard themes=13
20:47:13-694490 DEBUG    Extension list: processed=41 installed=8 enabled=6 disabled=2 visible=41 hidden=0
20:47:13-867975 DEBUG    Root paths: ['F:\\AI\\vladmandicXLCopium\\automatic']
20:47:13-977359 INFO     Local URL: http://127.0.0.1:7860/
20:47:13-977359 DEBUG    Gradio functions: registered=2299
20:47:13-977359 DEBUG    API middleware: [<class 'starlette.middleware.base.BaseHTTPMiddleware'>, <class
                         'starlette.middleware.gzip.GZipMiddleware'>]
20:47:13-977359 DEBUG    API initialize
20:47:14-383643 INFO     [AgentScheduler] Task queue is empty
20:47:14-383643 INFO     [AgentScheduler] Registering APIs
20:47:14-539903 DEBUG    Scripts setup: ['IP Adapters:0.016', 'ADetailer:0.125', 'Dynamic Prompts v2.17.1:0.016', 'XYZ
                         Grid:0.047', 'Face: Multiple ID Transfers:0.031', 'FreeScale: Tuning-Free Scale Fusion:0.016',
                         'K-Diffusion Samplers:0.109', 'LUT Color grading:0.031', 'Regional prompting:0.016', 'Style
                         Aligned Image Generation:0.016', 'Video: CogVideoX:0.016', 'Video: Hunyuan Video:0.016', 'SD
                         Upscale:0.016', 'Video: VGen Image-to-Video:0.016']
20:47:14-539903 DEBUG    Model metadata: file="metadata.json" no changes
20:47:14-539903 DEBUG    Model requested: fn=run:<lambda>
20:47:14-539903 INFO     Load model: select="SDXL\noobaiXLNAIXL_epsilonPred11Version [6681e8e4b1]"
Diffusers  9.96it/s ████████ 100% 7/7 00:00 00:00 Loading pipeline components...
20:47:15-305571 DEBUG    Setting model: pipeline=StableDiffusionXLPipeline config={'low_cpu_mem_usage': True,
                         'torch_dtype': torch.bfloat16, 'load_connected_pipeline': True, 'extract_ema': False,
                         'config': 'configs/sdxl', 'use_safetensors': True, 'cache_dir':
                         'C:\\Users\\\\.cache\\huggingface\\hub'}
20:47:21-822587 INFO     Load network: type=embeddings loaded=2 skipped=32 time=6.52
20:47:21-822587 DEBUG    Setting model: component=VAE slicing=True
20:47:21-822587 DEBUG    Setting model: attention="Scaled-Dot-Product"
20:47:21-838212 INFO     Offload: type=balanced op=init watermark=0.25-0.7 gpu=2.000-5.6:8.0 cpu=31.910 limit=0.00
20:47:21-853838 DEBUG    Offload: type=balanced module=unet cls=UNet2DConditionModel dtype=torch.bfloat16 quant=None
                         params=2.391 size=4.782
20:47:21-869465 DEBUG    Offload: type=balanced module=text_encoder_2 cls=CLIPTextModelWithProjection
                         dtype=torch.bfloat16 quant=None params=0.647 size=1.294
20:47:21-869465 DEBUG    Offload: type=balanced module=text_encoder cls=CLIPTextModel dtype=torch.bfloat16 quant=None
                         params=0.115 size=0.229
20:47:21-869465 DEBUG    Offload: type=balanced module=vae cls=AutoencoderKL dtype=torch.bfloat16 quant=None
                         params=0.078 size=0.156
20:47:21-869465 INFO     Offload: type=balanced op=apply class=StableDiffusionXLPipeline modules=4 size=6.461
20:47:21-869465 INFO     Load model: time=7.33 load=0.77 embeddings=6.52 native=1024 memory={'ram': {'used': 3.21,
                         'total': 31.91}, 'gpu': {'used': 1.1, 'total': 8.0}, 'retries': 0, 'oom': 0}
20:47:21-885090 DEBUG    Script callback init time: wildcards_tab.py:ui_tabs=0.08 system-info.py:app_started=0.28
                         task_scheduler.py:app_started=0.19
20:47:21-885090 DEBUG    Save: file="config.json" json=42 bytes=2102 time=0.000
20:47:21-885090 INFO     Startup time: 19.53 torch=6.71 libraries=0.45 samplers=0.06 detailer=0.09 extensions=1.17
                         ui-networks=0.36 ui-txt2img=0.30 ui-img2img=0.19 ui-control=0.27 ui-extras=0.06 ui-models=0.23
                         ui-settings=0.53 ui-extensions=0.71 ui-defaults=0.09 launch=0.17 api=0.09 app-started=0.47
                         checkpoint=7.35
20:47:21-885090 DEBUG    Settings: unused=['multiple_tqdm']
20:48:00-122737 DEBUG    Server: alive=True requests=1 memory=3.21/31.91 status='idle' task='' timestamp=None id=''
                         job=0 jobs=0 total=1 step=0 steps=0 queued=0 uptime=61 elapsed=45.58 eta=None progress=0
```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by Sinmero** [comment]
Here is the OOM log:
```
22:48:25-998652 DEBUG    GC: current={'gpu': 7.1, 'ram': 12.69, 'oom': 0} prev={'gpu': 7.25, 'ram': 12.69} load={'gpu':
                         89, 'ram': 40} gc={'gpu': 0.15, 'py': 236} fn=f:end why=threshold time=0.22
22:50:00-213145 DEBUG    Server: alive=True requests=322 memory=12.69/31.91 status='idle' task='' timestamp=None id=''
                         job=0 jobs=2 total=1 step=0 steps=0 queued=0 uptime=340 elapsed=325.18 eta=None progress=0
22:50:04-161560 DEBUG    GC: current={'gpu': 7.18, 'ram': 12.69, 'oom': 0} prev={'gpu': 7.09, 'ram': 12.69}
                         load={'gpu': 90, 'ram': 40} gc={'gpu': -0.09, 'py': 241} fn=f:begin why=threshold time=0.22
22:50:04-169579 INFO     Base: class=StableDiffusionXLPipeline
22:50:04-169579 DEBUG    Sampler: sampler="Euler a" class="EulerAncestralDiscreteScheduler
                         config={'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012,
                         'beta_schedule': 'scaled_linear', 'prediction_type': 'v_prediction', 'steps_offset': 0,
                         'timestep_spacing': 'linspace'}
Load network: F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\Lora\SDXL\Illustrous\Styleincoth-Illu-Incoth.safetens…
22:50:05-124012 DEBUG    LoRA name="Styleincoth-Illu-Incoth" type={'ModuleTypeLora'} keys=986 direct=True
22:50:05-382756 DEBUG    GC: current={'gpu': 7.1, 'ram': 12.24, 'oom': 0} prev={'gpu': 7.1, 'ram': 12.26} load={'gpu':
                         89, 'ram': 38} gc={'gpu': 0.0, 'py': 35411} fn=activate:network_load why=threshold time=0.24

22:50:05-394782 DEBUG    Torch generator: device=cuda seeds=[3086985652]
22:50:05-394782 DEBUG    Diffuser pipeline: StableDiffusionXLPipeline task=DiffusersTaskType.TEXT_2_IMAGE batch=1/1x1
                         set={'guidance_scale': 5, 'num_inference_steps': 30, 'eta': 1.0, 'guidance_rescale': 1,
                         'denoising_end': None, 'output_type': 'latent', 'width': 1024, 'height': 1408, 'parser':
                         'native', 'prompt': 'embeds'}
Load network: F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\Lora\SDXL\Illustrous\Styleincoth-Illu-Incoth.safetens…
22:50:06-136727 DEBUG    LoRA name="Styleincoth-Illu-Incoth" type={'ModuleTypeLora'} keys=986 direct=True
22:50:06-385473 DEBUG    GC: current={'gpu': 7.1, 'ram': 12.65, 'oom': 0} prev={'gpu': 7.1, 'ram': 12.66} load={'gpu':
                         89, 'ram': 40} gc={'gpu': 0.0, 'py': 34711} fn=activate:network_load why=threshold time=0.23

Progress  1.23it/s █████████████████████████████████ 100% 30/30 00:24 00:00 Base
22:50:31-689288 DEBUG    GC: current={'gpu': 7.61, 'ram': 12.17, 'oom': 0} prev={'gpu': 7.61, 'ram': 12.17}
                         load={'gpu': 95, 'ram': 38} gc={'gpu': 0.0, 'py': 272} fn=process_base:nextjob why=threshold
                         time=0.24
Network: type=LoRA action=deactivate ------------------------- 100% 0:00:00 0:00:00 networks=1 modules=3 deactivate=986
22:50:37-270578 DEBUG    VAE decode: vae name="default" dtype=torch.bfloat16 device=cpu upcast=False slicing=True
                         tiling=False latents shape=torch.Size([1, 4, 176, 128]) dtype=torch.bfloat16 device=cuda:0
                         time=4.825

0: 640x480 1 face, 138.3ms
Speed: 2.0ms preprocess, 138.3ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 480)
22:50:37-739663 DEBUG    Pipeline class change: original=StableDiffusionXLPipeline
                         target=StableDiffusionXLInpaintPipeline device=cuda:0 fn=process_images_inner:init
22:50:37-781749 DEBUG    Mask: size=1024x1408 masked=194091px area=0.13 auto=None blur=0.062 erode=0.010 dilate=0.125
                         type=Grayscale time=0.04
22:50:37-799792 DEBUG    Image resize: input=<PIL.Image.Image image mode=L size=515x708 at 0x18DA38B2320> width=1024
                         height=1408 mode="Crop" upscaler="None" context="None" type=image result=<PIL.Image.Image
                         image mode=L size=1024x1408 at 0x18DA874D8A0> time=0.00 fn=process_images_inner:init
22:50:37-849940 DEBUG    Image resize: input=<PIL.Image.Image image mode=RGB size=515x708 at 0x18DA6A57310> width=1024
                         height=1408 mode="Fill" upscaler="None" context="None" type=image result=<PIL.Image.Image
                         image mode=RGB size=1024x1408 at 0x18DA874DAB0> time=0.02 fn=process_images_inner:init
22:50:37-851951 INFO     Base: class=StableDiffusionXLInpaintPipeline
22:50:37-859970 DEBUG    Sampler: sampler="Euler a" class="EulerAncestralDiscreteScheduler
                         config={'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012,
                         'beta_schedule': 'scaled_linear', 'prediction_type': 'v_prediction', 'steps_offset': 0,
                         'timestep_spacing': 'linspace'}
Load network: F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\Lora\SDXL\Illustrous\Styleincoth-Illu-Incoth.safetens…
22:50:38-583897 DEBUG    LoRA name="Styleincoth-Illu-Incoth" type={'ModuleTypeLora'} keys=986 direct=True
Network: type=LoRA action=activate --------------------- 100% 0:00:00 0:00:00 networks=1 modules=545 apply=264 backup=0
22:50:38-714209 INFO     Load network: type=LoRA apply=['Styleincoth-Illu-Incoth'] mode=fuse te=[1.0] unet=[[1.0, 1.0,
                         1.0]] time={'calc': 0.1, 'activate': 0.11, 'load': 0.72}
22:50:38-722220 DEBUG    Torch generator: device=cuda seeds=[3086985652]
22:50:38-724230 DEBUG    Diffuser pipeline: StableDiffusionXLInpaintPipeline task=DiffusersTaskType.INPAINTING
                         batch=1/1x1 set={'guidance_scale': 5, 'num_inference_steps': 61, 'eta': 1.0,
                         'guidance_rescale': 0.7, 'denoising_start': None, 'denoising_end': None, 'output_type':
                         'latent', 'image': [<PIL.Image.Image image mode=RGB size=1024x1408 at 0x18DA874DAB0>],
                         'mask_image': <PIL.Image.Image image mode=L size=1024x1408 at 0x18DA874D8A0>, 'strength': 0.5,
                         'height': 1408, 'width': 1024, 'parser': 'native', 'prompt': 'embeds'}
Load network: F:\AI\AUTOMATIC1111\stable-diffusion-webui\models\Lora\SDXL\Illustrous\Styleincoth-Illu-Incoth.safetens…
22:50:39-466109 DEBUG    LoRA name="Styleincoth-Illu-Incoth" type={'ModuleTypeLora'} keys=986 direct=True
Network: type=LoRA action=activate -------------------- 100% 0:00:00 0:00:01 networks=1 modules=1911 apply=722 backup=0
22:50:40-536844 INFO     Load network: type=LoRA apply=['Styleincoth-Illu-Incoth'] mode=fuse te=[1.0] unet=[[1.0, 1.0,
                         1.0]] time={'calc': 0.62, 'apply': 0.51, 'activate': 1.16, 'load': 0.72}
22:50:42-564495 ERROR    Processing: step=base args={'prompt_embeds': 'cuda:0:torch.bfloat16:torch.Size([1, 77,
                         2048])', 'pooled_prompt_embeds': 'cuda:0:torch.bfloat16:torch.Size([1, 1280])',
                         'negative_prompt_embeds': 'cuda:0:torch.bfloat16:torch.Size([1, 77, 2048])',
                         'negative_pooled_prompt_embeds': 'cuda:0:torch.bfloat16:torch.Size([1, 1280])',
                         'guidance_scale': 5, 'generator': [<torch._C.Generator object at 0x0000018DA8774E30>],
                         'callback_on_step_end': <function diffusers_callback at 0x0000018D350A1FC0>,
                         'callback_on_step_end_tensor_inputs': ['latents', 'prompt_embeds', 'add_text_embeds',
                         'add_time_ids', 'mask', 'masked_image_latents'], 'num_inference_steps': 61, 'eta': 1.0,
                         'guidance_rescale': 0.7, 'denoising_start': None, 'denoising_end': None, 'output_type':
                         'latent', 'image': [<PIL.Image.Image image mode=RGB size=1024x1408 at 0x18DA874DAB0>],
                         'mask_image': <PIL.Image.Image image mode=L size=1024x1408 at 0x18DA874D8A0>, 'strength': 0.5,
                         'height': 1408, 'width': 1024} CUDA out of memory. Tried to allocate 352.00 MiB. GPU 0 has a
                         total capacity of 8.00 GiB of which 0 bytes is free. Of the allocated memory 6.84 GiB is
                         allocated by PyTorch, and 155.01 MiB is reserved by PyTorch but unallocated. If reserved but
                         unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to
                         avoid fragmentation.  See documentation for Memory Management
                         (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
22:50:42-584543 ERROR    Processing: OutOfMemoryError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ F:\AI\vladmandicXLCopium\automatic\modules\processing_diffusers.py:102 in process_base                              │
│                                                                                                                     │
│   101 │   │   else:                                                                                                 │
│ > 102 │   │   │   output = shared.sd_model(**base_args)                                                             │
│   103 │   │   if isinstance(output, dict):                                                                          │
│                                                                                                                     │
│ F:\AI\vladmandicXLCopium\automatic\venv\lib\site-packages\torch\utils\_contextlib.py:116 in decorate_context        │
│                                                                                                                     │
│   115 │   │   with ctx_factory():                                                                                   │
│ > 116 │   │   │   return func(*args, **kwargs)                                                                      │
│   117                                                                                                               │
│                                                                                                                     │
│ F:\AI\vladmandicXLCopium\automatic\venv\lib\site-packages\diffusers\pipelines\stable_diffusion_xl\pipeline_stable_d │
│                                                                                                                     │
│   1462 │   │   add_noise = True if self.denoising_start is None else False                                          │
│ > 1463 │   │   latents_outputs = self.prepare_latents(                                                              │
│   1464 │   │   │   batch_size * num_images_per_prompt,                                                              │
│                                                                                                                     │
│ F:\AI\vladmandicXLCopium\automatic\venv\lib\site-packages\diffusers\pipelines\stable_diffusion_xl\pipeline_stable_d │
│                                                                                                                     │
│    804 │   │   │   image = image.to(device=device, dtype=dtype)                                                     │
│ >  805 │   │   │   image_latents = self._encode_vae_image(image=image, generator=generator)                         │
│    806 │   │   │   image_latents = image_latents.repeat(batch_size // image_latents.shape[0], 1, 1, 1)              │
│                                                                                                                     │
│ F:\AI\vladmandicXLCopium\automatic\venv\lib\site-packages\diffusers\pipelines\stable_diffusion_xl\pipeline_stable_d │
│                                                                                                                     │
│    837 │   │   if isinstance(generator, list):                                                                      │
│ >  838 │   │   │   image_latents = [                                                                                │
│    839 │   │   │   │   retrieve_latents(self.vae.encode(image[i : i + 1]), generator=generator[i])                  │
│                                                                                                                     │
│ F:\AI\vladmandicXLCopium\automatic\venv\lib\site-packages\diffusers\pipelines\stable_diffusion_xl\pipeline_stable_d │
│                                                                                                                     │
│    838 │   │   │   image_latents = [                                                                                │
│ >  839 │   │   │   │   retrieve_latents(self.vae.encode(image[i : i + 1]), generator=generator[i])                  │
│    840 │   │   │   │   for i in range(image.shape[0])                                                               │
│                                                                                                                     │
│ F:\AI\vladmandicXLCopium\automatic\venv\lib\site-packages\diffusers\utils\accelerate_utils.py:46 in wrapper         │
│                                                                                                                     │
│   45 │   │   │   self._hf_hook.pre_forward(self)                                                                    │
│ > 46 │   │   return method(self, *args, **kwargs)                                                                   │
│   47                                                                                                                │
│                                                                                                                     │
│ F:\AI\vladmandicXLCopium\automatic\venv\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl.py:282 in en │
│                                                                                                                     │
│   281 │   │   else:                                                                                                 │
│ > 282 │   │   │   h = self._encode(x)                                                                               │
│   283                                                                                                               │
│                                                                                                                     │
│                                               ... 2 frames hidden ...                                               │
│                                                                                                                     │
│ F:\AI\vladmandicXLCopium\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1747 in _call_impl             │
│                                                                                                                     │
│   1746 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                      │
│ > 1747 │   │   │   return forward_call(*args, **kwargs)                                                             │
│   1748                                                                                                              │
│                                                                                                                     │
│ F:\AI\vladmandicXLCopium\automatic\venv\lib\site-packages\diffusers\models\autoencoders\vae.py:185 in forward       │
│                                                                                                                     │
│   184 │   │   │   for down_block in self.down_blocks:                                                               │
│ > 185 │   │   │   │   sample = down_block(sample)                                                                   │
│   186                                                                                                               │
│                                                                                                                     │
│ F:\AI\vladmandicXLCopium\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1736 in _wrapped_call_impl     │
│                                                                                                                     │
│   1735 │   │   else:                                                                                                │
│ > 1736 │   │   │   return self._call_impl(*args, **kwargs)                                                          │
│   1737                                                                                                              │
│                                                                                                                     │
│ F:\AI\vladmandicXLCopium\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1747 in _call_impl             │
│                                                                                                                     │
│   1746 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                      │
│ > 1747 │   │   │   return forward_call(*args, **kwargs)                                                             │
│   1748                                                                                                              │
│                                                                                                                     │
│ F:\AI\vladmandicXLCopium\automatic\venv\lib\site-packages\diffusers\models\unets\unet_2d_blocks.py:1520 in forward  │
│                                                                                                                     │
│   1519 │   │   for resnet in self.resnets:                                                                          │
│ > 1520 │   │   │   hidden_states = resnet(hidden_states, temb=None)                                                 │
│   1521                                                                                                              │
│                                                                                                                     │
│ F:\AI\vladmandicXLCopium\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1736 in _wrapped_call_impl     │
│                                                                                                                     │
│   1735 │   │   else:                                                                                                │
│ > 1736 │   │   │   return self._call_impl(*args, **kwargs)                                                          │
│   1737                                                                                                              │
│                                                                                                                     │
│ F:\AI\vladmandicXLCopium\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1747 in _call_impl             │
│                                                                                                                     │
│   1746 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                      │
│ > 1747 │   │   │   return forward_call(*args, **kwargs)                                                             │
│   1748                                                                                                              │
│                                                                                                                     │
│ F:\AI\vladmandicXLCopium\automatic\venv\lib\site-packages\diffusers\models\resnet.py:371 in forward                 │
│                                                                                                                     │
│   370 │   │                                                                                                         │
│ > 371 │   │   output_tensor = (input_tensor + hidden_states) / self.output_scale_factor                             │
│   372                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
OutOfMemoryError: CUDA out of memory. Tried to allocate 352.00 MiB. GPU 0 has a total capacity of 8.00 GiB of which 0 bytes is free. Of the allocated memory 6.84 GiB is allocated by PyTorch, and 155.01 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
22:50:43-288264 DEBUG    Analyzed: model="SDXL\noobaiXLNAIXL_vPred10Version" type=sdxl
                         class=StableDiffusionXLInpaintPipeline size=7105350110 mtime="2024-12-22 17:47:24"
                         modules=[name="vae" cls=AutoencoderKL config=True device=cuda:0 dtype=torch.bfloat16
                         params=83653863 modules=220, name="text_encoder" cls=CLIPTextModel config=True device=cpu
                         dtype=torch.bfloat16 params=123078912 modules=152, name="text_encoder_2"
                         cls=CLIPTextModelWithProjection config=True device=cpu dtype=torch.bfloat16 params=694690560
                         modules=393, name="tokenizer" cls=CLIPTokenizer config=False, name="tokenizer_2"
                         cls=CLIPTokenizer config=False, name="unet" cls=UNet2DConditionModel config=True device=cpu
                         dtype=torch.bfloat16 params=2567463684 modules=1911, name="image_encoder" cls=NoneType
                         config=False, name="feature_extractor" cls=NoneType config=False, name="scheduler"
                         cls=EulerAncestralDiscreteScheduler config=True, name="force_zeros_for_empty_prompt" cls=bool
                         config=False, name="requires_aesthetics_score" cls=bool config=False, name="_name_or_path"
                         cls=NoneType config=False, name="_class_name" cls=str config=False, name="_diffusers_version"
                         cls=str config=False]
22:50:43-688104 DEBUG    GC: current={'gpu': 7.78, 'ram': 12.58, 'oom': 0} prev={'gpu': 8.0, 'ram': 12.58} load={'gpu':
                         97, 'ram': 39} gc={'gpu': 0.22, 'py': 70897} fn=process_base:nextjob why=threshold time=0.27
22:50:43-920836 DEBUG    GC: current={'gpu': 7.09, 'ram': 12.57, 'oom': 0} prev={'gpu': 7.78, 'ram': 12.58}
                         load={'gpu': 89, 'ram': 39} gc={'gpu': 0.69, 'py': 250} fn=process_images:process_images_inner
                         why=threshold time=0.23
22:50:43-930878 DEBUG    Pipeline class change: original=StableDiffusionXLInpaintPipeline
                         target=StableDiffusionXLPipeline device=cuda:0 fn=process_images:process_images_inner
22:50:43-930878 INFO     Processed: images=0 its=0.00 time=6.20 timers={'init': 0.12, 'gc': 0.51, 'move': 2.69,
                         'preview': 0.12, 'process': 3.14, 'post': 0.24} memory={'ram': {'used': 12.57, 'total':
                         31.91}, 'gpu': {'used': 7.09, 'total': 8.0}, 'retries': 4, 'oom': 4}
22:50:44-161968 DEBUG    GC: current={'gpu': 7.09, 'ram': 12.57, 'oom': 0} prev={'gpu': 7.09, 'ram': 12.57}
                         load={'gpu': 89, 'ram': 39} gc={'gpu': 0.0, 'py': 254} fn=process_images:process_images_inner
                         why=final time=0.22
22:50:44-280379 ERROR    Running script postprocess image: extensions\adetailer\scripts\!adetailer.py: IndexError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ F:\AI\vladmandicXLCopium\automatic\modules\scripts.py:641 in postprocess_image                                      │
│                                                                                                                     │
│   640 │   │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_from:script.args_t │
│ > 641 │   │   │   │   │   script.postprocess_image(p, pp, *args)                                                    │
│   642 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ F:\AI\vladmandicXLCopium\automatic\extensions\adetailer\aaaaaa\traceback.py:167 in wrapper                          │
│                                                                                                                     │
│   166 │   │   │   │   error = RuntimeError(output)                                                                  │
│ > 167 │   │   │   raise error from None                                                                             │
│   168                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
IndexError:
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                   System info                                                   │
│ ┌─────────────┬───────────────────────────────────────────────────────────────────────────────────────────────┐ │
│ │             │ Value                                                                                         │ │
│ ├─────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤ │
│ │    Platform │ Windows-10-10.0.19045-SP0                                                                     │ │
│ │      Python │ 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]              │ │
│ │     Version │ Unknown (too old or vladmandic)                                                               │ │
│ │      Commit │ Unknown                                                                                       │ │
│ │ Commandline │ ['launch.py', '--debug']                                                                      │ │
│ │   Libraries │ {'torch': '2.5.1+cu124', 'torchvision': '0.20.1+cu124', 'ultralytics': '8.3.40', 'mediapipe': │ │
│ │             │ '0.10.20'}                                                                                    │ │
│ └─────────────┴───────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                     Inputs                                                      │
│ ┌─────────────────┬───────────────────────────────────────────────────────────────────────────────────────────┐ │
│ │                 │ Value                                                                                     │ │
│ ├─────────────────┼───────────────────────────────────────────────────────────────────────────────────────────┤ │
│ │          prompt │ masterpiece, best quality, newest, absurdres, highres, 1girl, tohsaka rin \(fate stay     │ │
│ │                 │ night\), blue eyes, rural town, brick houses, alleyway, detailed,                         │ │
│ │                 │ <lora:Styleincoth-Illu-Incoth:1.0> Incoth                                                 │ │
│ │ negative_prompt │ worst quality, worst aesthetic, bad quality, low quality, bad hands, bad anatomy,         │ │
│ │                 │ monochrome, oversaturated, missing, extra, fewer, bad, unfinished, error                  │ │
│ │          n_iter │ 1                                                                                         │ │
│ │      batch_size │ 1                                                                                         │ │
│ │           width │ 1024                                                                                      │ │
│ │          height │ 1408                                                                                      │ │
│ │    sampler_name │ Euler a                                                                                   │ │
│ │       enable_hr │ False                                                                                     │ │
│ │     hr_upscaler │ None                                                                                      │ │
│ │      checkpoint │ SDXL\noobaiXLNAIXL_vPred10Version                                                         │ │
│ │             vae │ Automatic                                                                                 │ │
│ │            unet │ None                                                                                      │ │
│ └─────────────────┴───────────────────────────────────────────────────────────────────────────────────────────┘ │
│                 ADetailer                                                                                       │
│ ┌─────────────────────┬─────────────────┐                                                                       │
│ │                     │ Value           │                                                                       │
│ ├─────────────────────┼─────────────────┤                                                                       │
│ │             version │ 24.5.1          │                                                                       │
│ │            ad_model │ face_yolov8n.pt │                                                                       │
│ │           ad_prompt │                 │                                                                       │
│ │  ad_negative_prompt │                 │                                                                       │
│ │ ad_controlnet_model │ None            │                                                                       │
│ │              is_api │ False           │                                                                       │
│ └─────────────────────┴─────────────────┘                                                                       │
│ ┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐            │
│ │ F:\AI\vladmandicXLCopium\automatic\extensions\adetailer\aaaaaa\traceback.py:147 in wrapper       │            │
│ │                                                                                                  │            │
│ │   146 │   │   try:                                                                               │            │
│ │ > 147 │   │   │   return func(*args, **kwargs)                                                   │            │
│ │   148 │   │   except Exception as e:                                                             │            │
│ │                                                                                                  │            │
│ │ F:\AI\vladmandicXLCopium\automatic\extensions\adetailer\scripts\!adetailer.py:821 in             │            │
│ │ postprocess_image                                                                                │            │
│ │                                                                                                  │            │
│ │    820 │   │   │   │   │   continue                                                              │            │
│ │ >  821 │   │   │   │   is_processed |= self._postprocess_image_inner(p, pp, args, n=n)           │            │
│ │    822                                                                                           │            │
│ │                                                                                                  │            │
│ │ F:\AI\vladmandicXLCopium\automatic\extensions\adetailer\scripts\!adetailer.py:792 in             │            │
│ │ _postprocess_image_inner                                                                         │            │
│ │                                                                                                  │            │
│ │    791 │   │   │   p2 = copy(i2i)                                                                │            │
│ │ >  792 │   │   │   p2.init_images = [processed.images[0]]                                        │            │
│ │    793                                                                                           │            │
│ └──────────────────────────────────────────────────────────────────────────────────────────────────┘            │
│ IndexError: list index out of range                                                                             │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

```

**Comment by vladmandic** [comment]
default settings have changed, new default is:
> 21:02:37-210008 INFO Device detect: memory=8.0 optimization=balanced

you can switch to sequential offload mode if you like. or you can change balanced mode thresholds.
see wiki article on offloading for more details.

but to start with, i'd highly recommend to use built-id detailer instead of extension.

**Comment by Sinmero** [comment]
Switching from balanced to model did it. It works as good as before. Thanks.

Also I was able to get rid of `ONNX failed to initialize: DLL load failed while importing onnx_cpp2py_export` error.
Downgrading onnx to 1.16.1 worked for me.
I ran this:
`F:\AI\vladmandicXLCopium\automatic\venv\Scripts\python.exe -m pip install onnx==1.16.1`
