### ISSUE TITLE
[Issue] Zluda nightly with HIP 6.2

### ISSUE THREAD

**Issue by chain2k** [vladmandic/automatic#3725]
Hi, I have a gfx1150 so I am trying to install nightly buid, in the attached screenshot you can see that the path to the zluda files is taken correctly, I have the files from ZLUDA-nightly-windows-rocm6-amd64.zip lying there. 
![Screenshot 2025-01-26 165049](https://github.com/user-attachments/assets/0a324f40-6f93-44ce-86a4-44485b964948)
I can also see that torch is version 2.4.1. 
However, at startup I get a message:
```
rocBLAS error: Cannot read C:\Program Files\AMD\ROCm\6.2\bin\/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1150”.
rocBLAS error: Could not initialize Tensile host:
regex_error(error_backref): The expression contained an invalid back reference.
```

The Notes.txt in **hipblaslt-rocmlibs-for-gfx1100-gfx1101-gfx1102-gfx1103-gfx1150-for.hip6.2.7z** specified that the library should be in _bin/hipblaslt/library_ and the **hipblaslt.dll** file in _rocm/6.2/bin_. That's where I placed them, and this bilibrary has TensileLibrary for gfx1150. But judging by the error the search is still in _/rocblas/library/_
Any ideas how I can fix this?
I start with the command `webui.bat --use-zluda --debug --autolaunch`
And I also noticed that in the directory where I placed nightly zluda appear copies of files with changed names, but in _venv\Lib\site-packages\torch\lib_ these files are different sizes, you can see it on the screenshot. I tried manually replacing them and restarting webui, but it didn't help.
![Screenshot 2025-01-26 171706](https://github.com/user-attachments/assets/1cdf1fb6-9200-406f-abad-b965bbef0e2f)

**Comment by chain2k** [comment]
Problem solved, for gfx1150 and some other new cards that use hipblaslt you need two sets of libraries, both for hipblast and for rocblas, as well as two dlls. Place both dlls in C:\Program Files\AMD\ROCm\ROCm\6.2\bin, and replace the two libraries in \rocblas\ and in \bin\hipblaslt\ respectively. Tested with ROCm 6.2.4. Libraries from https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases
