### ISSUE TITLE
[Issue]: InstantID AttributeError in img2img on Intel Arc A770

### ISSUE THREAD

**Issue by AndrewRainfall** [vladmandic/automatic#3775]
### Issue Description

"Face: Multiple ID Transfers - InstantID" script in img2img returns "AttributeError: 'NoneType' object has no attribute 'sd_checkpoint_info'"

It works fine in txt2img. Tested on dreamshaperXL_lightningDPMSDE

### Version Platform Description

16:12:01-983594 INFO     Starting SD.Next
16:12:01-989737 INFO     Logger: file="D:\sdnext\sdnext.log" level=DEBUG host="Rain" size=72 mode=create
16:12:01-993243 INFO     Python: version=3.10.11 platform=Windows bin="D:\sdnext\venv\Scripts\python.exe"
                         venv="D:\sdnext\venv"
16:12:02-488865 INFO     Version: app=sd.next updated=2025-02-21 hash=cb0eb555 branch=master
                         url=https://github.com/vladmandic/sdnext/tree/master ui=main
16:12:03-322479 INFO     Platform: arch=AMD64 cpu=AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.11 locale=('English_Europe', '1251')
                         docker=False
16:12:03-328817 DEBUG    Packages: prefix=venv site=['venv', 'venv\\lib\\site-packages']
16:12:03-330818 INFO     Args: ['--use-ipex', '--upgrade', '--autolaunch', '--debug']
16:12:03-332819 DEBUG    Setting environment tuning
16:12:03-334820 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
16:12:03-489890 DEBUG    Torch overrides: cuda=False rocm=False ipex=True directml=False openvino=False zluda=False
16:12:03-492891 INFO     Python: version=3.10.11 platform=Windows bin="D:\sdnext\venv\Scripts\python.exe"
                         venv="D:\sdnext\venv"
16:12:03-511896 INFO     IPEX: Intel OneAPI toolkit detected
16:12:04-242176 INFO     Install: verifying requirements
16:12:04-249178 INFO     Startup: standard
16:12:04-251178 INFO     Verifying submodules
16:12:09-739044 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
16:12:11-054425 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
16:12:12-271727 DEBUG    Git submodule: extensions-builtin/sd-webui-agent-scheduler / main
16:12:13-645258 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
16:12:13-647811 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / main
16:12:14-974206 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
16:12:16-264906 DEBUG    Git submodule: modules/k-diffusion / master
16:12:17-658629 DEBUG    Git detached head detected: folder="wiki" reattach=master
16:12:17-660630 DEBUG    Git submodule: wiki / master
16:12:18-890711 DEBUG    Register paths
16:12:19-008738 DEBUG    Installed packages: 194
16:12:19-010738 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
16:12:20-075494 DEBUG    Git submodule: extensions-builtin\sd-extension-chainner / main
16:12:21-388101 DEBUG    Git submodule: extensions-builtin\sd-extension-system-info / main
16:12:22-629323 DEBUG    Git submodule: extensions-builtin\sd-webui-agent-scheduler / main
16:12:23-686156 DEBUG    Extension installer: D:\sdnext\extensions-builtin\sd-webui-agent-scheduler\install.py
16:12:31-144343 DEBUG    Git submodule: extensions-builtin\sdnext-modernui / main
16:12:32-445939 DEBUG    Git submodule: extensions-builtin\stable-diffusion-webui-rembg / master
16:12:33-505377 DEBUG    Extension installer: D:\sdnext\extensions-builtin\stable-diffusion-webui-rembg\install.py
16:12:43-860265 DEBUG    Extensions all: []
16:12:43-862265 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']

### Relevant log output

```shell
16:12:01-983594 INFO     Starting SD.Next
16:12:01-989737 INFO     Logger: file="D:\sdnext\sdnext.log" level=DEBUG host="Rain" size=72 mode=create
16:12:01-993243 INFO     Python: version=3.10.11 platform=Windows bin="D:\sdnext\venv\Scripts\python.exe"
                         venv="D:\sdnext\venv"
16:12:02-488865 INFO     Version: app=sd.next updated=2025-02-21 hash=cb0eb555 branch=master
                         url=https://github.com/vladmandic/sdnext/tree/master ui=main
16:12:03-322479 INFO     Platform: arch=AMD64 cpu=AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.11 locale=('English_Europe', '1251')
                         docker=False
16:12:03-328817 DEBUG    Packages: prefix=venv site=['venv', 'venv\\lib\\site-packages']
16:12:03-330818 INFO     Args: ['--use-ipex', '--upgrade', '--autolaunch', '--debug']
16:12:03-332819 DEBUG    Setting environment tuning
16:12:03-334820 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
16:12:03-489890 DEBUG    Torch overrides: cuda=False rocm=False ipex=True directml=False openvino=False zluda=False
16:12:03-492891 INFO     Python: version=3.10.11 platform=Windows bin="D:\sdnext\venv\Scripts\python.exe"
                         venv="D:\sdnext\venv"
16:12:03-511896 INFO     IPEX: Intel OneAPI toolkit detected
16:12:04-242176 INFO     Install: verifying requirements
16:12:04-249178 INFO     Startup: standard
16:12:04-251178 INFO     Verifying submodules
16:12:09-739044 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
16:12:11-054425 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
16:12:12-271727 DEBUG    Git submodule: extensions-builtin/sd-webui-agent-scheduler / main
16:12:13-645258 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
16:12:13-647811 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / main
16:12:14-974206 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
16:12:16-264906 DEBUG    Git submodule: modules/k-diffusion / master
16:12:17-658629 DEBUG    Git detached head detected: folder="wiki" reattach=master
16:12:17-660630 DEBUG    Git submodule: wiki / master
16:12:18-890711 DEBUG    Register paths
16:12:19-008738 DEBUG    Installed packages: 194
16:12:19-010738 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
16:12:20-075494 DEBUG    Git submodule: extensions-builtin\sd-extension-chainner / main
16:12:21-388101 DEBUG    Git submodule: extensions-builtin\sd-extension-system-info / main
16:12:22-629323 DEBUG    Git submodule: extensions-builtin\sd-webui-agent-scheduler / main
16:12:23-686156 DEBUG    Extension installer: D:\sdnext\extensions-builtin\sd-webui-agent-scheduler\install.py
16:12:31-144343 DEBUG    Git submodule: extensions-builtin\sdnext-modernui / main
16:12:32-445939 DEBUG    Git submodule: extensions-builtin\stable-diffusion-webui-rembg / master
16:12:33-505377 DEBUG    Extension installer: D:\sdnext\extensions-builtin\stable-diffusion-webui-rembg\install.py
16:12:43-860265 DEBUG    Extensions all: []
16:12:43-862265 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
16:12:43-865266 INFO     Install: verifying requirements
16:12:43-867267 INFO     Updating Wiki
16:12:43-956286 DEBUG    Git submodule: D:\sdnext\wiki / master
16:12:45-103141 DEBUG    Setup complete without errors: 1740402765
16:12:45-196856 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
16:12:45-200549 INFO     Command line args: ['--use-ipex', '--upgrade', '--autolaunch', '--debug'] autolaunch=True
                         upgrade=True use_ipex=True debug=True args=[]
16:12:45-204119 DEBUG    Env flags: []
16:12:45-205648 DEBUG    Starting module: <module 'webui' from 'D:\\sdnext\\webui.py'>
16:13:12-651115 INFO     Torch: torch==2.6.0+xpu torchvision==0.21.0+xpu
16:13:12-653666 INFO     Packages: diffusers==0.33.0.dev0 transformers==4.48.3 accelerate==1.3.0 gradio==3.43.2
                         pydantic==1.10.21
16:13:13-678115 INFO     Device detect: memory=15.5 default=balanced
16:13:13-686117 DEBUG    Read: file="D:\sdnext\config.json" json=48 bytes=2132 time=0.000 fn=<module>:load
16:13:14-804487 INFO     Engine: backend=Backend.DIFFUSERS compute=ipex device=xpu attention="Scaled-Dot-Product"
                         mode=no_grad
16:13:14-829271 DEBUG    Read: file="html\reference.json" json=65 bytes=34218 time=0.021
                         fn=_call_with_frames_removed:<module>
16:13:14-833360 DEBUG    Torch attention: type="sdpa" flash=True memory=True math=True
16:13:16-702680 INFO     Torch parameters: backend=ipex device=xpu config=BF16 dtype=torch.bfloat16 context=no_grad
                         nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False, False] fp16=pass
                         bf16=pass optimization="Scaled-Dot-Product"
16:13:18-046940 DEBUG    ONNX: version=1.20.1 provider=OpenVINOExecutionProvider, available=['AzureExecutionProvider',
                         'CPUExecutionProvider']
16:13:18-343786 INFO     Device: device=Intel(R) Arc(TM) A770 Graphics n=1 ipex= driver=1.6.31896
16:13:18-755600 DEBUG    Entering start sequence
16:13:18-760612 DEBUG    Initializing
16:13:18-762613 DEBUG    Read: file="metadata.json" json=2 bytes=506 time=0.000 fn=initialize:init_metadata
16:13:18-786384 DEBUG    Read: file="cache.json" json=1 bytes=555 time=0.000 fn=initialize:init_cache
16:13:18-789398 DEBUG    Huggingface cache: path="C:\Users\Rain\.cache\huggingface\hub"
16:13:18-949732 INFO     Available VAEs: path="models\VAE" items=2
16:13:18-951732 INFO     Available UNets: path="models\UNET" items=0
16:13:18-954732 INFO     Available TEs: path="models\Text-encoder" items=0
16:13:18-957732 INFO     Available Models: items=2 safetensors="models\Stable-diffusion":2
                         diffusers="models\Diffusers":0 time=0.00
16:13:19-015993 INFO     Available LoRAs: path="models\Lora" items=0 folders=2 time=0.00
16:13:19-043000 INFO     Available Styles: folder="models\styles" items=288 time=0.02
16:13:19-238546 INFO     Available Detailer: path="models\yolo" items=10 downloaded=0
16:13:19-241557 DEBUG    Extensions: disabled=['Lora', 'sdnext-modernui']
16:13:19-243558 INFO     Load extensions
16:13:21-456675 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py'
                         Using sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
16:13:21-484975 DEBUG    Extensions init time: total=2.24 sd-webui-agent-scheduler=2.00 sd-extension-chainner=0.06
16:13:21-513302 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2672 time=0.016 fn=__init__:__init__
16:13:21-516726 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=24 bytes=2719
                         time=0.000 fn=__init__:find_scalers
16:13:21-520727 DEBUG    chaiNNer models: path="models\chaiNNer" defined=24 discovered=0 downloaded=0
16:13:21-526727 INFO     Available Upscalers: items=65 downloaded=2 user=0 time=0.04 types=['None', 'Resize', 'Latent',
                         'AsymmetricVAE', 'DCC', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'RealESRGAN', 'SCUNet', 'Diffusion',
                         'SwinIR']
16:13:21-534729 DEBUG    UI start sequence
16:13:21-537043 INFO     UI locale: name="en: English"
16:13:21-540131 INFO     UI theme: type=Standard name="black-teal" available=13
16:13:21-551281 DEBUG    UI theme: css="D:\sdnext\javascript\black-teal.css" base="sdnext.css" user="None"
16:13:21-555283 DEBUG    UI initialize: txt2img
16:13:21-629910 DEBUG    Networks: page='model' items=66 subfolders=4 tab=txt2img folders=['models\\Stable-diffusion',
                         'models\\Diffusers', 'models\\Reference'] list=0.02 thumb=0.01 desc=0.00 info=0.00 workers=8
16:13:21-637101 DEBUG    Networks: page='lora' items=0 subfolders=1 tab=txt2img folders=['models\\Lora'] list=0.02
                         thumb=0.00 desc=0.00 info=0.00 workers=8
16:13:21-652807 DEBUG    Networks: page='style' items=288 subfolders=3 tab=txt2img folders=['models\\styles', 'html']
                         list=0.03 thumb=0.00 desc=0.00 info=0.00 workers=8
16:13:21-660809 DEBUG    Networks: page='embedding' items=2 subfolders=1 tab=txt2img folders=['models\\embeddings']
                         list=0.01 thumb=0.00 desc=0.00 info=0.00 workers=8
16:13:21-667810 DEBUG    Networks: page='vae' items=2 subfolders=1 tab=txt2img folders=['models\\VAE'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=8
16:13:21-675812 DEBUG    Networks: page='history' items=0 subfolders=1 tab=txt2img folders=[] list=0.00 thumb=0.00
                         desc=0.00 info=0.00 workers=8
16:13:22-313228 DEBUG    UI initialize: img2img
16:13:22-615960 DEBUG    UI initialize: control models="models\control"
16:13:23-895718 DEBUG    Read: file="ui-config.json" json=47 bytes=2359 time=0.001 fn=__init__:read_from_file
16:13:24-491203 INFO     Extension list is empty: refresh required
16:13:25-612663 DEBUG    Extension list: processed=6 installed=6 enabled=4 disabled=2 visible=6 hidden=0
16:13:25-857107 DEBUG    Root paths: ['D:\\sdnext']
16:13:26-091916 INFO     Local URL: http://127.0.0.1:7860/
16:13:26-107373 DEBUG    API middleware: [<class 'starlette.middleware.base.BaseHTTPMiddleware'>, <class
                         'starlette.middleware.gzip.GZipMiddleware'>]
16:13:26-110375 DEBUG    API initialize
16:13:26-603106 INFO     [AgentScheduler] Task queue is empty
16:13:26-605115 INFO     [AgentScheduler] Registering APIs
16:13:26-807568 DEBUG    Scripts setup: time=0.913 ['K-Diffusion Samplers:0.35', 'XYZ Grid:0.074', 'IP Adapters:0.064',
                         'Mixture-of-Diffusers: Tile Control:0.038', 'Face: Multiple ID Transfers:0.037', 'FreeScale:
                         Tuning-Free Scale Fusion:0.021', 'Video: CogVideoX:0.02', 'Video: LTX Video:0.018', 'Video:
                         AnimateDiff:0.017', 'ConsiStory: Consistent Image Generation:0.016', 'LUT Color
                         grading:0.015', 'Video: VGen Image-to-Video:0.015', 'PuLID: ID Customization:0.014', 'Ctrl-X:
                         Controlling Structure and Appearance:0.014', 'Style Aligned Image Generation:0.013', 'Video:
                         Stable Video Diffusion:0.013', 'Video: Hunyuan Video:0.013', 'Video: ModelScope:0.01']
16:13:26-816604 DEBUG    Model metadata: file="metadata.json" no changes
16:13:26-819678 DEBUG    Model requested: fn=run:<lambda>
16:13:26-822241 INFO     Load model: select="dreamshaperXL_lightningDPMSDE [fdbe56354b]"
16:13:26-825829 INFO     Load module: type=VAE model="D:\sdnext\models\VAE\sdxl_vae.safetensors" source=settings
                         config={'low_cpu_mem_usage': False, 'torch_dtype': torch.bfloat16, 'use_safetensors': True,
                         'force_upcast': False, 'config': 'configs/sdxl\\vae'}
Progress 11.13s/it █████████ 100% 7/7 01:17 00:00 Loading pipeline components...
16:14:59-364966 DEBUG    Setting model: pipeline=StableDiffusionXLPipeline config={'low_cpu_mem_usage': True,
                         'torch_dtype': torch.bfloat16, 'load_connected_pipeline': True, 'extract_ema': False,
                         'config': 'configs/sdxl', 'use_safetensors': True, 'cache_dir':
                         'C:\\Users\\Rain\\.cache\\huggingface\\hub', 'force_upcast': False}
16:14:59-376713 INFO     Load network: type=embeddings loaded=0 skipped=2 time=0.00
16:14:59-379715 DEBUG    Setting model: component=VAE name="sdxl_vae.safetensors"
16:14:59-381716 DEBUG    Setting model: component=VAE upcast=False
16:14:59-382716 DEBUG    Setting model: component=VAE slicing=True
16:14:59-384717 DEBUG    Setting model: attention="Scaled-Dot-Product"
16:14:59-418724 INFO     Offload: type=balanced op=init watermark=0.25-0.7 gpu=3.885-10.877999999999998:15.54
                         cpu=31.950 limit=0.00
16:14:59-454731 DEBUG    Model module=unet type=UNet2DConditionModel dtype=torch.bfloat16 quant=None params=2.391
                         size=4.782
16:14:59-471735 DEBUG    Model module=text_encoder_2 type=CLIPTextModelWithProjection dtype=torch.bfloat16 quant=None
                         params=0.647 size=1.294
16:14:59-476737 DEBUG    Model module=text_encoder type=CLIPTextModel dtype=torch.bfloat16 quant=None params=0.115
                         size=0.229
16:14:59-481738 DEBUG    Model module=vae type=AutoencoderKL dtype=torch.bfloat16 quant=None params=0.078 size=0.156
16:14:59-486739 INFO     Model class=StableDiffusionXLPipeline modules=4 size=6.461
16:14:59-489740 DEBUG    Read: file="D:\sdnext\configs\sdxl\vae\config.json" json=15 bytes=675 time=0.000
                         fn=apply_vae_config:get_vae_config
16:14:59-495741 INFO     Load model: time=total=92.67 load=83.65 vae=8.90 move=0.08 native=1024 memory={'ram': {'used':
                         7.62, 'total': 31.95}, 'gpu': {'used': 0.0, 'total': 15.54}, 'retries': 0, 'oom': 0}
16:14:59-503744 DEBUG    Script init: ['system-info.py:app_started=0.32', 'task_scheduler.py:app_started=0.21']
16:14:59-505744 DEBUG    Save: file="D:\sdnext\config.json" json=48 bytes=2056 time=0.002
16:14:59-507745 INFO     Startup time: total=178.61 checkpoint=92.70 torch=67.55 launch=44.65 installer=44.31
                         libraries=6.66 gradio=2.78 extensions=2.24 ui-extensions=1.21 ui-settings=0.73 ui-txt2img=0.60
                         app-started=0.54 diffusers=0.47 ui-control=0.41 ui-models=0.39 ui-networks=0.36
                         ui-img2img=0.24 detailer=0.20 samplers=0.19 transformers=0.18 api=0.16 onnx=0.16
                         ui-defaults=0.14 ui-extras=0.07 lora=0.06
16:14:59-525748 INFO     Launching browser
16:15:04-117056 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/motd 127.0.0.1 1.1755
16:15:09-612386 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/sd-models 127.0.0.1 0.001
16:15:11-662108 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64)
                         AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36
16:15:11-669108 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/start 127.0.0.1 0.008
16:15:11-679111 INFO     UI: ready time=10.224
16:16:00-406805 DEBUG    Server: alive=True requests=21 memory=0/0 status='running' task='Load'
                         timestamp='20250224161326' id='' job=0 jobs=0 total=1 step=0 steps=0 queued=0 uptime=167
                         elapsed=153.59 eta=None progress=0
16:17:59-524404 DEBUG    Server: alive=True requests=21 memory=0/0 status='running' task='Load'
                         timestamp='20250224161326' id='' job=0 jobs=0 total=1 step=0 steps=0 queued=0 uptime=287
                         elapsed=272.71 eta=None progress=0
16:19:47-391495 DEBUG    Save temp: image="C:\Users\Rain\AppData\Local\Temp\gradio\tmpn70ijomy.png" width=1024
                         height=1024 size=1206263
16:19:52-877485 DEBUG    InsightFace: mp=antelopev2 provider=['OpenVINOExecutionProvider', 'CPUExecutionProvider']
16:19:55-099040 DEBUG    InstantID face: score=0.87 gender=male age=34 bbox=[269.69196 196.88948 695.7225  813.5108 ]
16:19:55-103040 DEBUG    InstantID loading: model=InstantX/InstantID
16:20:00-087915 DEBUG    Server: alive=True requests=35 memory=0/0 status='running' task='Load'
                         timestamp='20250224161326' id='task(pxe2olengwhppf0)' job=0 jobs=0 total=1 step=0 steps=0
                         queued=0 uptime=407 elapsed=393.27 eta=None progress=0
16:20:02-758252 DEBUG    Model move: device=xpu class=ControlNetModel accelerate=False fn=run:instant_id time=2.13
16:20:02-762759 DEBUG    Setting model: component=VAE upcast=False
16:20:02-765759 DEBUG    Setting model: component=VAE slicing=True
16:20:02-767758 DEBUG    Setting model: attention="Scaled-Dot-Product"
16:20:08-915005 WARNING  Pipeline class change failed: type=DiffusersTaskType.IMAGE_2_IMAGE
                         pipeline=StableDiffusionXLInstantIDPipeline AutoPipeline can't find a pipeline linked to
                         StableDiffusionXLInstantIDPipeline for None
16:20:08-919007 WARNING  Pipeline class set failed: type=DiffusersTaskType.IMAGE_2_IMAGE
                         pipeline=StableDiffusionXLInstantIDPipeline AutoPipeline can't find a pipeline linked to
                         StableDiffusionXLInstantIDPipeline for None
16:20:08-923008 ERROR    Exception: 'NoneType' object has no attribute 'sd_checkpoint_info'
16:20:08-925009 ERROR    Arguments: args=('task(pxe2olengwhppf0)', '', 0.0, 'a photo of a man, medium shot, daylight',
                         '(low quality, worst quality:1.4), cgi,  text, signature, watermark, extra limbs, badhandv4,
                         BadDream', [], <PIL.Image.Image image mode=RGBA size=1024x1024 at 0x125B3F81AE0>, None, None,
                         None, None, None, None, 6, 4, 4, 1, 1, True, False, False, False, '', '', 10, 0.3, 1, 1, 2, 2,
                         0.7, 0, 0.5, 1, 0, 2, 0.38, -1.0, -1.0, 0, 0, 0, 0, 0, 0, 1, 1, 'None', 'Add with forward', 0,
                         32, 0, None, '', '', '', 0, 0, 0, 0, False, 4, 0.95, False, 0.6, 1, '#000000', 0, False, None,
                         0.3, 1, 'Add with forward', 'None', False, 20, 1, 0, 0, 20, 0, '', '', [], 6, 1, False,
                         'None', 'None', 'None', 'None', 0.5, 0.5, 0.5, 0.5, None, None, None, None, False, False,
                         False, False, 0, 0, 0, 0, 1, 1, 1, 1, None, None, None, None, False, '', False, 0, '', [], 0,
                         '', [], 0, '', [], False, True, False, True, False, False, False, False, 0, False, 'None', 2,
                         True, 1, 0, 'constant', 1, 'constant', 1, '#04F404', 65, 0, 0, 0.15, 0.9, '', '', 0.5, '',
                         0.5, 5, None, '', 0.5, 5, None, True, 1, False, 'None', None, 'InstantID', [{'name':
                         'C:\\Users\\Rain\\AppData\\Local\\Temp\\gradio\\tmpn70ijomy.png', 'data':
                         'http://127.0.0.1:7860/file=C:\\Users\\Rain\\AppData\\Local\\Temp\\gradio\\tmpn70ijomy.png',
                         'is_file': True}], 'ReSwapper 256 0.2', False, 'FaceID Base', True, True, 1, 1, 1, 0.5, True,
                         'PhotoMaker v2', '', 1, 0.5, True, 'None', 0, True, True, 2, True, 1, 35, True, 1, 0.75, True,
                         2, 0.75, False, 3, 0.75, False, 4, 0.75, 0.65, True, False, 1, 1, 1, 0, 1, False, False,
                         False, None, 0.1, 1, True, '', 0.5, 0.9, '', 0.5, 0.9, 4, 0.5, 'Linear', 'None', True, None,
                         1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 128, 128, '', '', '', '', '', '', '', '', '', '', '', '', '',
                         '', '', '', 'OpenGVLab/InternVL-14B-224px', '<span>&nbsp Outpainting</span><br>', 128, 8,
                         ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], 20,
                         False, 0.7, 1.2, 128, False, False, 'positive', 'comma', 0, False, False, '', [], 0.8, 20,
                         'dpmpp_sde', 'v2', False, True, 'v1.1', '<span>&nbsp SD Upscale</span><br>', 64, 0, 2,
                         '7,8,9', 1, 0.01, 0.2, None, '', False, ['attention', 'adain_queries', 'adain_keys'], 1, 0, 0,
                         'THUDM/CogVideoX-2b', 'DDIM', 49, 6, 'balanced', True, 'None', 2, True, 1, 0, None, None,
                         '0.9.1', '', 'diffusers', True, 41, 'None', 2, True, 1, 0, False, 0.03, 'SVD 1.0', 14, True,
                         1, 3, 6, 0.5, 0.1, 'None', 2, True, 1, 0, 'None', 16, 'None', 2, True, 1, 0, 'none', 3, 4,
                         0.25, 0.25, 0.5, 0.5, 0, '', [], 0, '', [], 0, '', [], False, True, False, True, False, False,
                         False, False, 0, False, 'None', 2, True, 1, 0) kwargs={}
16:20:09-019575 ERROR    gradio call: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\sdnext\modules\call_queue.py:31 in f                                                                             │
│                                                                                                                     │
│   30 │   │   │   try:                                                                                               │
│ > 31 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│   32 │   │   │   │   progress.record_results(id_task, res)                                                          │
│                                                                                                                     │
│ D:\sdnext\modules\img2img.py:305 in img2img                                                                         │
│                                                                                                                     │
│   304 │   else:                                                                                                     │
│ > 305 │   │   processed = modules.scripts.scripts_img2img.run(p, *args)                                             │
│   306 │   │   if processed is None:                                                                                 │
│                                                                                                                     │
│ D:\sdnext\modules\scripts.py:511 in run                                                                             │
│                                                                                                                     │
│   510 │   │   if hasattr(script, 'run'):                                                                            │
│ > 511 │   │   │   processed = script.run(p, *parsed)                                                                │
│   512 │   │   else:                                                                                                 │
│                                                                                                                     │
│ D:\sdnext\modules\face\__init__.py:149 in run                                                                       │
│                                                                                                                     │
│   148 │   │   │   from modules.face.instantid import instant_id # instantid creates pipeline and triggers original  │
│ > 149 │   │   │   processed = instant_id(p, app=app, source_images=input_images, strength=id_strength, conditioning │
│   150                                                                                                               │
│                                                                                                                     │
│ D:\sdnext\modules\face\instantid.py:69 in instant_id                                                                │
│                                                                                                                     │
│   68 │   │   processing.process_init(p)                                                                             │
│ > 69 │   │   p.init(p.all_prompts, p.all_seeds, p.all_subseeds)                                                     │
│   70 │   orig_prompt_attention = shared.opts.prompt_attention                                                       │
│                                                                                                                     │
│ D:\sdnext\modules\processing_class.py:437 in init                                                                   │
│                                                                                                                     │
│   436 │   │   elif shared.native and getattr(self, 'init_images', None) is not None:                                │
│ > 437 │   │   │   shared.sd_model = sd_models.set_diffuser_pipe(self.sd_model, sd_models.DiffusersTaskType.IMAGE_2_ │
│   438                                                                                                               │
│                                                                                                                     │
│ D:\sdnext\modules\sd_models.py:834 in set_diffuser_pipe                                                             │
│                                                                                                                     │
│    833 │   #    return pipe                                                                                         │
│ >  834 │   new_pipe.sd_checkpoint_info = sd_checkpoint_info                                                         │
│    835 │   new_pipe.sd_model_checkpoint = sd_model_checkpoint                                                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'NoneType' object has no attribute 'sd_checkpoint_info'
```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion XL

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by AndrewRainfall** [comment]
Just tested with Photomaker, Faceswap and FaceID  - same problem.

In txt2img they return "RuntimeError: Could not infer dtype of NoneType"

-----------------------
Someone wrote that those errors may be connected with 
- incorrectly set names
- input_ids list contains “None” objects

But I don't understand what it means.

-----------------------
Upd: After several server restarts problem solved itself.

**Comment by vladmandic** [comment]
instantid does not support img2img. the other face modules do.
i just updated dev branch to handle this error gracefully.
also, there was a problem with instantid offloading, that is now handled as well.
