### ISSUE TITLE
[Issue]: Failure to load a video component loads base diffusion model

### ISSUE THREAD

**Issue by CalamitousFelicitousness** [vladmandic/automatic#4127]
### Issue Description

When loading any component for a video model in the video tab fails, SDNext immediately starts loading whatever model is present in the `Base model` selector. 
For example, in the log below (the exact loading error itself is irrelevant for this issue, it happens no matter what the error is, such as download errors) after a failed attempt to load the transformers for Wan2.2 14B it immediately loads in the SDXL model I happened to have selected in the menu, turning the log into a mess, and forcing a weird state where futher video attempts are unsuccesfull, only resolved by restart:

```
02:43:04-995916 DEBUG    Video: cls=StableDiffusionXLPipeline width=800 height=992 frames=17 steps=20
02:43:04-997416 INFO     Applying HyperTile: unet=128/384
02:43:05-051754 ERROR    Mismatch: type=sdxl cls=StableDiffusionXLPipeline request=StableDiffusionProcessingVideo
                         non-video model with video pipeline
```

### Version Platform Description

02:23:26-567441 INFO     Python: version=3.12.10 platform=Windows
                         bin="E:\AI-ImageGen\sdnext_dev\venv\Scripts\python.exe" venv="E:\AI-ImageGen\sdnext_dev\venv"
02:23:26-833939 INFO     Version: app=sd.next updated=2025-08-17 hash=85d494ee branch=dev
                         url=https://github.com/vladmandic/sdnext.git/tree/dev ui=dev
02:23:27-684256 INFO     Version: app=sd.next latest=2025-08-17T02:19:44Z hash=85d494ee branch=dev
02:23:27-724760 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 158 Stepping 12, GenuineIntel system=Windows
                         release=Windows-11-10.0.26100-SP0 python=3.12.10 locale=('English_United Kingdom', '1252')
                         docker=False

### Relevant log output

```shell
02:23:26-561940 INFO     Starting SD.Next
02:23:26-565938 INFO     Logger: file="E:\AI-ImageGen\sdnext_dev\sdnext.log" level=DEBUG host="TennesseeDesk" size=81
                         mode=create
02:23:26-567441 INFO     Python: version=3.12.10 platform=Windows
                         bin="E:\AI-ImageGen\sdnext_dev\venv\Scripts\python.exe" venv="E:\AI-ImageGen\sdnext_dev\venv"
02:23:26-833939 INFO     Version: app=sd.next updated=2025-08-17 hash=85d494ee branch=dev
                         url=https://github.com/vladmandic/sdnext.git/tree/dev ui=dev
02:23:27-684256 INFO     Version: app=sd.next latest=2025-08-17T02:19:44Z hash=85d494ee branch=dev
02:23:27-724760 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 158 Stepping 12, GenuineIntel system=Windows
                         release=Windows-11-10.0.26100-SP0 python=3.12.10 locale=('English_United Kingdom', '1252')
                         docker=False
02:23:27-726260 DEBUG    Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
02:23:27-727757 INFO     Args: ['--port', '7855', '--uv', '--insecure', '--debug', '--update']
02:23:27-728757 DEBUG    Setting environment tuning
02:23:27-729757 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
02:23:27-731260 INFO     Verifying torch installation
02:23:27-747755 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=False
02:23:27-781757 INFO     CUDA: nVidia toolkit detected
02:23:27-947163 INFO     Install: verifying requirements
02:23:27-951138 INFO     Startup: standard
02:23:27-952170 INFO     Verifying submodules
02:23:30-706495 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
02:23:31-797586 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
02:23:32-805120 DEBUG    Git submodule: extensions-builtin/sd-webui-agent-scheduler / main
02:23:33-868907 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / dev
02:23:34-924260 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
02:23:35-993911 DEBUG    Git submodule: wiki / master
02:23:37-084652 DEBUG    Installed packages: 185
02:23:37-086182 DEBUG    Extensions all: ['sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
02:23:37-176651 DEBUG    Git submodule: extensions-builtin\sd-extension-chainner / main
02:23:38-291967 DEBUG    Git submodule: extensions-builtin\sd-extension-system-info / main
02:23:39-409273 DEBUG    Git submodule: extensions-builtin\sd-webui-agent-scheduler / main
02:23:40-374402 DEBUG    Extension installer: builtin=True
                         file="E:\AI-ImageGen\sdnext_dev\extensions-builtin\sd-webui-agent-scheduler\install.py"
02:23:40-542114 DEBUG    Git submodule: extensions-builtin\sdnext-modernui / dev
02:23:41-653782 DEBUG    Git submodule: extensions-builtin\stable-diffusion-webui-rembg / master
02:23:42-671664 DEBUG    Extension installer: builtin=True
                         file="E:\AI-ImageGen\sdnext_dev\extensions-builtin\stable-diffusion-webui-rembg\install.py"
02:23:42-745704 DEBUG    Extensions all: ['OneButtonPrompt', 'sd-dynamic-prompts']
02:23:42-836409 DEBUG    Git submodule: extensions\OneButtonPrompt / main
02:23:43-919192 DEBUG    Git submodule: extensions\sd-dynamic-prompts / main
02:23:44-914501 DEBUG    Extension installer: builtin=False
                         file="E:\AI-ImageGen\sdnext_dev\extensions\sd-dynamic-prompts\install.py"
02:23:45-192287 INFO     Extensions enabled: ['sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg',
                         'OneButtonPrompt', 'sd-dynamic-prompts']
02:23:45-266318 INFO     Install: verifying requirements
02:23:45-270789 INFO     Updating Wiki
02:23:45-362299 DEBUG    Git submodule: E:\AI-ImageGen\sdnext_dev\wiki / master
02:23:46-318813 DEBUG    Setup complete without errors: 1755480226
02:23:46-323836 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
02:23:46-325337 INFO     Installer time: total=54.29 git=17.62 update=14.85 submodules=9.06 branch=1.41
                         sd-dynamic-prompts=1.36 stable-diffusion-webui-rembg=1.18 sd-webui-agent-scheduler=1.13
                         sd-extension-system-info=1.12 sd-extension-chainner=1.12 latest=1.11 sdnext-modernui=1.11
                         OneButtonPrompt=1.08 wiki=1.05 base=0.34 version=0.26 installed=0.15 requirements=0.15
                         files=0.09 torch=0.05
02:23:46-327339 INFO     Command line args: ['--port', '7855', '--uv', '--insecure', '--debug', '--update']
                         insecure=True port=7855 upgrade=True uv=True debug=True args=[]
02:23:46-328812 DEBUG    Env flags: []
02:23:46-329313 DEBUG    Starting module: <module 'webui' from 'E:\\AI-ImageGen\\sdnext_dev\\webui.py'>
Multiple distributions found for package optimum. Picked distribution: optimum
02:23:56-349984 INFO     Torch: torch==2.7.1+cu128 torchvision==0.22.1+cu128
02:23:56-352955 INFO     Packages: diffusers==0.35.0.dev0 transformers==4.55.2 accelerate==1.10.0 gradio==3.43.2
                         pydantic==1.10.21 numpy==2.1.2
02:23:56-868382 DEBUG    ONNX: version=1.22.1, available=['AzureExecutionProvider', 'CPUExecutionProvider']
02:23:57-025455 DEBUG    State initialized: id=2233658267632
02:23:57-109457 INFO     Device detect: memory=24.0 default=balanced optimization=highvram
02:23:57-114481 DEBUG    Read: file="E:\AI-ImageGen\sdnext_dev\config.json" json=42 bytes=2528 time=0.000
                         fn=<module>:load
02:23:57-116489 DEBUG    Setting validation: "schedulers_sigma"="betas" default="default" choices=['default', 'karras',
                         'exponential', 'polyexponential']
02:23:57-117491 DEBUG    Setting validation: "schedulers_beta_schedule"="scaled" default="default" choices=['default',
                         'linear', 'scaled_linear', 'squaredcos_cap_v2', 'sigmoid']
02:23:57-119514 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
02:23:57-120490 DEBUG    Torch cuDNN: benchmark=True
02:23:57-121514 DEBUG    Torch attention: type="sdpa" flash=True memory=True math=True
02:23:57-123498 DEBUG    Torch attention: type="dynamic attention"
02:23:57-181067 INFO     Torch parameters: backend=cuda device=cuda config=Auto dtype=torch.bfloat16 context=no_grad
                         nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False, True] fp16=pass
                         bf16=pass optimization="Scaled-Dot-Product"
02:23:57-258535 INFO     Device: device=NVIDIA GeForce RTX 3090 n=1 arch=sm_120 capability=(8, 6) cuda=12.8 cudnn=90701
                         driver=580.97
02:23:57-635596 DEBUG    Entering start sequence
02:23:57-638098 DEBUG    Initializing
02:23:57-677714 DEBUG    Read: file="metadata.json" json=1666 bytes=20785906 time=0.038 fn=initialize:init_metadata
02:23:57-680250 DEBUG    Read: file="cache.json" json=2 bytes=416 time=0.000 fn=initialize:init_cache
02:23:57-736003 INFO     Available VAEs: path="E:\AI-ImageGen\Database\models\VAE" items=9
02:23:57-737503 INFO     Available UNets: path="E:\AI-ImageGen\Database\models\UNET" items=0
02:23:57-738426 INFO     Available TEs: path="E:\AI-ImageGen\Database\models\Text-encoder" items=0
02:23:57-744997 INFO     Available Models: safetensors="E:\AI-ImageGen\Database\models\Stable-diffusion":14
                         diffusers="E:\AI-ImageGen\Database\models\Diffusers":13 items=27 time=0.00
02:23:57-841376 INFO     Available LoRAs: path="E:\AI-ImageGen\Database\models\Lora" items=790 folders=9 time=0.09
02:23:57-848899 INFO     Available Styles: path="E:\AI-ImageGen\Database\models\styles" items=20 time=0.01
02:23:57-943762 INFO     Available Detailer: path="E:\AI-ImageGen\Database\models\yolo" items=13 downloaded=3
02:23:57-945252 DEBUG    Extensions: disabled=[]
02:23:57-946258 INFO     Load extensions
02:23:58-847806 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using
                         sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
02:23:58-890805 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2672 time=0.001 fn=__init__:__init__
02:23:58-892780 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=25 bytes=2830 time=0.000
                         fn=__init__:find_scalers
02:23:58-894783 DEBUG    Available chaiNNer: path="E:\AI-ImageGen\Database\models\chaiNNer" defined=25 discovered=0
                         downloaded=24
02:23:58-897280 DEBUG    Upscaler type=ESRGAN folder="E:\AI-ImageGen\Database\models\ESRGAN"
                         model="4x_foolhardy_Remacri"
                         path="E:\AI-ImageGen\Database\models\ESRGAN\4x_foolhardy_Remacri.pth"
02:23:58-898281 DEBUG    Upscaler type=ESRGAN folder="E:\AI-ImageGen\Database\models\ESRGAN"
                         model="4x_NickelbackFS_72000_G"
                         path="E:\AI-ImageGen\Database\models\ESRGAN\4x_NickelbackFS_72000_G.pth"
02:23:58-899279 DEBUG    Upscaler type=ESRGAN folder="E:\AI-ImageGen\Database\models\ESRGAN" model="ESRGAN 4x
                         CountryRoads" path="E:\AI-ImageGen\Database\models\ESRGAN\ESRGAN 4x CountryRoads.pth"
02:23:58-903779 INFO     Available Upscalers: items=75 downloaded=48 user=3 time=0.02 types=['None', 'Resize', 'Latent',
                         'AsymmetricVAE', 'DCC', 'VIPS', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'RealESRGAN', 'SCUNet',
                         'Diffusion', 'SwinIR']
02:23:58-905779 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=25 bytes=2830 time=0.000
                         fn=__init__:find_scalers
02:23:58-908311 DEBUG    Available chaiNNer: path="E:\AI-ImageGen\Database\models\chaiNNer" defined=25 discovered=0
                         downloaded=24
02:23:58-910312 DEBUG    Upscaler type=ESRGAN folder="E:\AI-ImageGen\Database\models\ESRGAN"
                         model="4x_foolhardy_Remacri"
                         path="E:\AI-ImageGen\Database\models\ESRGAN\4x_foolhardy_Remacri.pth"
02:23:58-911310 DEBUG    Upscaler type=ESRGAN folder="E:\AI-ImageGen\Database\models\ESRGAN"
                         model="4x_NickelbackFS_72000_G"
                         path="E:\AI-ImageGen\Database\models\ESRGAN\4x_NickelbackFS_72000_G.pth"
02:23:58-912311 DEBUG    Upscaler type=ESRGAN folder="E:\AI-ImageGen\Database\models\ESRGAN" model="ESRGAN 4x
                         CountryRoads" path="E:\AI-ImageGen\Database\models\ESRGAN\ESRGAN 4x CountryRoads.pth"
02:23:58-916782 INFO     Available Upscalers: items=75 downloaded=48 user=3 time=0.01 types=['None', 'Resize', 'Latent',
                         'AsymmetricVAE', 'DCC', 'VIPS', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'RealESRGAN', 'SCUNet',
                         'Diffusion', 'SwinIR']
02:23:58-932280 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=25 bytes=2830 time=0.000
                         fn=__init__:find_scalers
02:23:58-934278 DEBUG    Available chaiNNer: path="E:\AI-ImageGen\Database\models\chaiNNer" defined=25 discovered=0
                         downloaded=24
02:23:58-936279 DEBUG    Upscaler type=ESRGAN folder="E:\AI-ImageGen\Database\models\ESRGAN"
                         model="4x_foolhardy_Remacri"
                         path="E:\AI-ImageGen\Database\models\ESRGAN\4x_foolhardy_Remacri.pth"
02:23:58-937282 DEBUG    Upscaler type=ESRGAN folder="E:\AI-ImageGen\Database\models\ESRGAN"
                         model="4x_NickelbackFS_72000_G"
                         path="E:\AI-ImageGen\Database\models\ESRGAN\4x_NickelbackFS_72000_G.pth"
02:23:58-939811 DEBUG    Upscaler type=ESRGAN folder="E:\AI-ImageGen\Database\models\ESRGAN" model="ESRGAN 4x
                         CountryRoads" path="E:\AI-ImageGen\Database\models\ESRGAN\ESRGAN 4x CountryRoads.pth"
02:23:58-944281 INFO     Available Upscalers: items=75 downloaded=48 user=3 time=0.01 types=['None', 'Resize', 'Latent',
                         'AsymmetricVAE', 'DCC', 'VIPS', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'RealESRGAN', 'SCUNet',
                         'Diffusion', 'SwinIR']
02:23:58-946378 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=25 bytes=2830 time=0.000
                         fn=__init__:find_scalers
02:23:58-948378 DEBUG    Available chaiNNer: path="E:\AI-ImageGen\Database\models\chaiNNer" defined=25 discovered=0
                         downloaded=24
02:23:58-950378 DEBUG    Upscaler type=ESRGAN folder="E:\AI-ImageGen\Database\models\ESRGAN"
                         model="4x_foolhardy_Remacri"
                         path="E:\AI-ImageGen\Database\models\ESRGAN\4x_foolhardy_Remacri.pth"
02:23:58-951378 DEBUG    Upscaler type=ESRGAN folder="E:\AI-ImageGen\Database\models\ESRGAN"
                         model="4x_NickelbackFS_72000_G"
                         path="E:\AI-ImageGen\Database\models\ESRGAN\4x_NickelbackFS_72000_G.pth"
02:23:58-952378 DEBUG    Upscaler type=ESRGAN folder="E:\AI-ImageGen\Database\models\ESRGAN" model="ESRGAN 4x
                         CountryRoads" path="E:\AI-ImageGen\Database\models\ESRGAN\ESRGAN 4x CountryRoads.pth"
02:23:58-956962 INFO     Available Upscalers: items=75 downloaded=48 user=3 time=0.01 types=['None', 'Resize', 'Latent',
                         'AsymmetricVAE', 'DCC', 'VIPS', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'RealESRGAN', 'SCUNet',
                         'Diffusion', 'SwinIR']
02:23:59-012959 DEBUG    Extensions init time: total=1.07 sd-webui-agent-scheduler=0.68 OneButtonPrompt=0.11
                         cogvideo.py=0.05
02:23:59-014958 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=25 bytes=2830 time=0.000
                         fn=__init__:find_scalers
02:23:59-017457 DEBUG    Available chaiNNer: path="E:\AI-ImageGen\Database\models\chaiNNer" defined=25 discovered=0
                         downloaded=24
02:23:59-019554 DEBUG    Upscaler type=ESRGAN folder="E:\AI-ImageGen\Database\models\ESRGAN"
                         model="4x_foolhardy_Remacri"
                         path="E:\AI-ImageGen\Database\models\ESRGAN\4x_foolhardy_Remacri.pth"
02:23:59-020517 DEBUG    Upscaler type=ESRGAN folder="E:\AI-ImageGen\Database\models\ESRGAN"
                         model="4x_NickelbackFS_72000_G"
                         path="E:\AI-ImageGen\Database\models\ESRGAN\4x_NickelbackFS_72000_G.pth"
02:23:59-021547 DEBUG    Upscaler type=ESRGAN folder="E:\AI-ImageGen\Database\models\ESRGAN" model="ESRGAN 4x
                         CountryRoads" path="E:\AI-ImageGen\Database\models\ESRGAN\ESRGAN 4x CountryRoads.pth"
02:23:59-026547 INFO     Available Upscalers: items=75 downloaded=48 user=3 time=0.01 types=['None', 'Resize', 'Latent',
                         'AsymmetricVAE', 'DCC', 'VIPS', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'RealESRGAN', 'SCUNet',
                         'Diffusion', 'SwinIR']
02:23:59-036015 INFO     Huggingface init: transfer=rust parallel=True direct=False token="hf_...rdoQ"
                         cache="E:\AI-ImageGen\Database\models\huggingface"
02:23:59-114102 WARNING  Cache location changed: previous="C:\Users\ohiom\.cache\huggingface\hub" size=21708 MB
02:23:59-156749 DEBUG    Huggingface cache: path="E:\AI-ImageGen\Database\models\huggingface" size=476072 MB
02:23:59-157741 DEBUG    UI start sequence
02:23:59-158719 INFO     UI locale: name="Auto"
02:23:59-159752 INFO     UI theme: type=Modern name="Default" available=35
02:23:59-168720 DEBUG    UI theme: css="extensions-builtin\sdnext-modernui\themes\Default.css" base="base.css"
                         user="None"
02:23:59-172229 DEBUG    UI initialize: txt2img
02:24:01-140600 DEBUG    Networks: type="model" items=27 subfolders=2 tab=txt2img
                         folders=['E:\\AI-ImageGen\\Database\\models\\Stable-diffusion', 'models\\Reference',
                         'E:\\AI-ImageGen\\Database\\models\\Stable-diffusion'] list=1.02 thumb=0.44 desc=0.04 info=0.03
                         workers=12
02:24:01-177627 DEBUG    Networks: type="lora" items=790 subfolders=33 tab=txt2img
                         folders=['E:\\AI-ImageGen\\Database\\models\\Lora'] list=1.82 thumb=0.17 desc=1.38 info=9.67
                         workers=12
02:24:01-185097 DEBUG    Networks: type="style" items=20 subfolders=3 tab=txt2img
                         folders=['E:\\AI-ImageGen\\Database\\models\\styles', 'html'] list=0.05 thumb=0.04 desc=0.00
                         info=0.00 workers=12
02:24:01-197120 DEBUG    Networks: type="wildcards" items=179 subfolders=6 tab=txt2img
                         folders=['E:\\AI-ImageGen\\Database\\models\\wildcards'] list=1.94 thumb=0.99 desc=0.00
                         info=0.00 workers=12
02:24:01-201097 DEBUG    Networks: type="embedding" items=55 subfolders=1 tab=txt2img
                         folders=['E:\\AI-ImageGen\\Database\\models\\embeddings'] list=1.57 thumb=0.44 desc=0.09
                         info=0.63 workers=12
02:24:01-205624 DEBUG    Networks: type="vae" items=9 subfolders=1 tab=txt2img
                         folders=['E:\\AI-ImageGen\\Database\\models\\VAE'] list=0.65 thumb=0.46 desc=0.00 info=0.10
                         workers=12
02:24:01-208122 DEBUG    Networks: type="history" items=0 subfolders=1 tab=txt2img folders=[] list=0.00 thumb=0.00
                         desc=0.00 info=0.00 workers=12
02:24:01-518465 DEBUG    UI initialize: img2img
02:24:01-826484 DEBUG    UI initialize: control models="E:\AI-ImageGen\Database\models\control"
02:24:02-040143 DEBUG    Script: fn="extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py" type=control
                         skip
02:24:02-041616 DEBUG    Script: fn="extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py" type=control skip
02:24:02-157216 DEBUG    Script: fn="extensions\OneButtonPrompt\scripts\onebuttonprompt.py" type=control skip
02:24:02-295715 DEBUG    UI initialize: video
02:24:02-758623 DEBUG    Read: file="ui-config.json" json=7 bytes=389 time=0.000 fn=__init__:read_from_file
02:24:02-764123 DEBUG    Settings: sections=24 settings=372/583 quicksettings=0
02:24:04-219398 DEBUG    Extension list: processed=412 installed=7 enabled=7 disabled=0 visible=412 hidden=0
02:24:04-851373 DEBUG    Root paths: ['E:\\AI-ImageGen\\sdnext_dev', 'models']
02:24:04-957235 INFO     Local URL: http://127.0.0.1:7855/
02:24:04-959733 DEBUG    API middleware: [<class 'starlette.middleware.base.BaseHTTPMiddleware'>, <class
                         'starlette.middleware.gzip.GZipMiddleware'>]
02:24:04-961262 DEBUG    API initialize
02:24:05-467644 INFO     [AgentScheduler] Task queue is empty
02:24:05-487666 INFO     [AgentScheduler] Registering APIs
02:24:06-051681 DEBUG    Scripts setup: time=0.609 ['One Button Prompt:0.071', 'XYZ Grid:0.059', 'IP Adapters:0.049',
                         'Prompt enhance:0.031']
02:24:06-052680 DEBUG    Model metadata: file="metadata.json" no changes
02:24:06-054680 DEBUG    Model requested: fn=threading.py:run:<lambda>
02:24:06-055684 INFO     Load model: select="Illustrious - Noob V-Pred 1.0 Personal Merge [d14ea71ad5]"
02:24:06-057681 INFO     Autodetect model: detect="Stable Diffusion XL" class=StableDiffusionXLPipeline
                         file="E:\AI-ImageGen\Database\models\Stable-diffusion\Illustrious - Noob V-Pred 1.0 Personal
                         Merge.safetensors"
02:24:06-059181 DEBUG    Cache clear
Progress  1.56s/it █████████ 100% 7/7 00:10 00:00 Loading pipeline components...
02:24:17-874393 DEBUG    Setting model: pipeline=StableDiffusionXLPipeline config={'low_cpu_mem_usage': True,
                         'torch_dtype': torch.bfloat16, 'load_connected_pipeline': True, 'extract_ema': False, 'config':
                         'configs/sdxl', 'use_safetensors': True, 'cache_dir':
                         'E:\\AI-ImageGen\\Database\\models\\huggingface'}
02:24:17-877392 INFO     Setting override: model="Illustrious - Noob V-Pred 1.0 Personal Merge" component=scheduler
                         prediction="v-prediction"
02:24:19-305064 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64)
                         AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0
02:24:19-427159 DEBUG    UI: connected
02:24:22-556596 INFO     UI: ready time=15.885
02:24:23-863439 INFO     Network load: type=embeddings loaded=19 skipped=36 time=5.98
02:24:23-864940 DEBUG    Setting model: component=vae {'slicing': True, 'tiling': True, 'tile': 1024, 'overlap': 0.25}
02:24:23-866438 DEBUG    Setting model: attention="Scaled-Dot-Product"
02:24:23-878436 DEBUG    Load model: post_quant=sdnq
02:24:23-879937 DEBUG    Quantization: type=SDNQ modules=['Model', 'TE'] dtype=int8 dtype_te=Same as model matmul=False
                         group_size=0 quant_conv=False matmul_conv=False quantize_with_gpu=True dequantize_fp32=False
                         pre_forward=True
02:24:25-797946 DEBUG    GC: current={'gpu': 1.28, 'ram': 8.6, 'oom': 0} prev={'gpu': 1.44, 'ram': 8.6} load={'gpu': 5,
                         'ram': 7} gc={'gpu': 0.16, 'py': 2811} fn=apply_function_to_model:sdnq_quantize_model why=sdnq
                         time=0.44
02:24:26-450961 DEBUG    GC: current={'gpu': 1.28, 'ram': 7.52, 'oom': 0} prev={'gpu': 1.33, 'ram': 7.52} load={'gpu':
                         5, 'ram': 6} gc={'gpu': 0.05, 'py': 127} fn=apply_function_to_model:sdnq_quantize_model
                         why=sdnq time=0.42
02:24:27-282884 DEBUG    GC: current={'gpu': 1.28, 'ram': 6.84, 'oom': 0} prev={'gpu': 1.35, 'ram': 6.84} load={'gpu':
                         5, 'ram': 5} gc={'gpu': 0.07, 'py': 127} fn=apply_function_to_model:sdnq_quantize_model
                         why=sdnq time=0.39
02:24:27-284391 INFO     Quantization: type=SDNQ time=3.40
02:24:27-285890 INFO     Offload: type=balanced op=init watermark=0.2-0.8 gpu=4.80-19.20:24.00 cpu=128.000 limit=0.00
                         always=[] never=['CLIPTextModel', 'CLIPTextModelWithProjection', 'AutoencoderKL']
02:24:27-311888 DEBUG    Module: name=unet cls=UNet2DConditionModel size=2.703 params=2567463684 quant=SDNQ
02:24:27-316888 DEBUG    Module: name=text_encoder_2 cls=CLIPTextModelWithProjection size=0.708 params=695571200
                         quant=SDNQ
02:24:27-319889 DEBUG    Module: name=vae cls=AutoencoderKL size=0.156 params=83653863 quant=None
02:24:27-322393 DEBUG    Module: name=text_encoder cls=CLIPTextModel size=0.151 params=123607296 quant=SDNQ
02:24:27-323890 INFO     Model class=StableDiffusionXLPipeline modules=4 size=3.718
02:24:27-327389 INFO     Load model: family=sdxl time={'total': 23.35, 'load': 11.82, 'embeddings': 5.99, 'options':
                         3.42, 'sdnq': 2.08} native=1024 memory={'ram': {'total': 127.92, 'used': 6.84, 'free': 121},
                         'gpu': {'used': 1.28, 'total': 24.0, 'active': 0.0, 'peak': 0.11, 'retries': 0, 'oom': 0,
                         'swap': 0}, 'job': 'Load'}
02:24:27-330894 DEBUG    Script init: ['task_scheduler.py:ui_tabs=0.37', 'wildcards_tab.py:ui_tabs=0.06',
                         'system-info.py:app_started=0.31', 'task_scheduler.py:app_started=0.63']
02:24:27-332083 INFO     Startup time: total=101.63 checkpoint=21.28 launch=20.39 numpy=20.29 installer=20.21 torch=6.75
                         ui-networks=2.29 libraries=2.09 ui-extensions=1.45 gradio=1.42 extensions=1.07 app-started=0.95
                         bnb=0.77 ui-defaults=0.55 ui-control=0.34 ui-txt2img=0.28 ui-img2img=0.25 ui-video=0.15
                         ui-models=0.15 api=0.14 cleanup=0.12 diffusers=0.11 samplers=0.10 lora=0.10 detailer=0.09
                         onnx=0.07 ui-extras=0.05
02:24:27-336588 DEBUG    Save: file="E:\AI-ImageGen\sdnext_dev\config.json" json=42 bytes=2468 time=0.006
02:24:42-936858 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64)
                         AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0
02:24:43-942600 DEBUG    UI: connected
02:24:46-890518 INFO     UI: ready time=13.7
02:24:52-133271 INFO     Settings: changed=1 ['sd_checkpoint_autoload']
02:24:52-137270 DEBUG    Save: file="E:\AI-ImageGen\sdnext_dev\config.json" json=43 bytes=2503 time=0.005
02:25:01-520503 INFO     Settings: changed=1 ['sdnq_use_quantized_matmul']
02:25:01-524503 DEBUG    Save: file="E:\AI-ImageGen\sdnext_dev\config.json" json=44 bytes=2540 time=0.004
02:25:59-137191 INFO     Settings: changed=1 ['quicksettings_list']
02:25:59-142195 DEBUG    Save: file="E:\AI-ImageGen\sdnext_dev\config.json" json=44 bytes=2563 time=0.005
02:26:27-418874 TRACE    Server: alive=True requests=109 memory=6.86/127.92 status='idle' task='' timestamp=None
                         current='' id='' job=0 jobs=0 total=2 step=0 steps=0 queued=0 uptime=151 elapsed=141.36
                         eta=None progress=0
02:26:43-278346 INFO     Settings: changed=1 ['keep_incomplete']
02:26:43-282350 DEBUG    Save: file="E:\AI-ImageGen\sdnext_dev\config.json" json=45 bytes=2591 time=0.004
02:27:49-225068 DEBUG    Cache clear
02:27:49-226069 DEBUG    Current model: {'ram': {'total': 127.92, 'used': 6.87, 'free': 121}, 'gpu': {'used': 1.28,
                         'total': 24.0, 'active': 0.0, 'peak': 0.0, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': 'Load'}
02:27:49-838255 DEBUG    GC: current={'gpu': 1.28, 'ram': 6.85, 'oom': 0} prev={'gpu': 1.28, 'ram': 6.85} load={'gpu':
                         5, 'ram': 5} gc={'gpu': 0.0, 'py': 63022} fn=load_model:unload_model_weights why=unload
                         time=0.46
02:27:49-840255 DEBUG    Unload model: {'ram': {'total': 127.92, 'used': 6.85, 'free': 121}, 'gpu': {'used': 1.28,
                         'total': 24.0, 'active': 0.0, 'peak': 0.0, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': 'Load'}
                         after
02:27:49-841756 DEBUG    Quantization: module="TE" type=sdnq dtype=int8 matmul=True group_size=0 quant_conv=False
                         matmul_conv=False dequantize_fp32=False quantize_with_gpu=True quantization_device=cuda
                         return_device=cpu device_map=default offload_mode=balanced non_blocking=False
02:27:50-772285 ERROR    video load: module=te cls=T5EncoderModel It looks like the config file at
                         'E:\AI-ImageGen\Database\models\huggingface\models--Wan-AI--Wan2.2-T2V-A14B-Diffusers\snapshots
                         \5be7df9619b54f4e2667b2755bc6a756675b5cd7\text_encoder\config.json' is not a valid JSON file.
02:27:50-773827 ERROR    video: OSError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│E:\AI-ImageGen\sdnext_dev\venv\Lib\site-packages\transformers\configuration_utils.py:743 in _get_config_dict          │
│                                                                                                                      │
│   742 │   │   │   │   # Load config dict                                                                             │
│❱  743 │   │   │   │   config_dict = cls._dict_from_json_file(resolved_config_file)                                   │
│   744                                                                                                                │
│                                                                                                                      │
│E:\AI-ImageGen\sdnext_dev\venv\Lib\site-packages\transformers\configuration_utils.py:845 in _dict_from_json_file      │
│                                                                                                                      │
│   844 │   │   │   text = reader.read()                                                                               │
│❱  845 │   │   return json.loads(text)                                                                                │
│   846                                                                                                                │
│                                                                                                                      │
│C:\Users\ohiom\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py:346 in loads                              │
│                                                                                                                      │
│  345 │   │   │   parse_constant is None and object_pairs_hook is None and not kw):                                   │
│❱ 346 │   │   return _default_decoder.decode(s)                                                                       │
│  347 │   if cls is None:                                                                                             │
│                                                                                                                      │
│C:\Users\ohiom\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py:338 in decode                              │
│                                                                                                                      │
│  337 │   │   """                                                                                                     │
│❱ 338 │   │   obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                       │
│  339 │   │   end = _w(s, end).end()                                                                                  │
│                                                                                                                      │
│C:\Users\ohiom\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py:356 in raw_decode                          │
│                                                                                                                      │
│  355 │   │   except StopIteration as err:                                                                            │
│❱ 356 │   │   │   raise JSONDecodeError("Expecting value", s, err.value) from None                                    │
│  357 │   │   return obj, end                                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│E:\AI-ImageGen\sdnext_dev\modules\video_models\video_load.py:28 in load_model                                         │
│                                                                                                                      │
│   27 │   │   debug(f'Video load: module=te repo="{selected.te or selected.repo}" folder="{selected.te_folder}" cls={ │
│❱  28 │   │   text_encoder = selected.te_cls.from_pretrained(                                                         │
│   29 │   │   │   pretrained_model_name_or_path=selected.te or selected.repo,                                         │
│                                                                                                                      │
│E:\AI-ImageGen\sdnext_dev\venv\Lib\site-packages\transformers\modeling_utils.py:317 in _wrapper                       │
│                                                                                                                      │
│   316 │   │   try:                                                                                                   │
│❱  317 │   │   │   return func(*args, **kwargs)                                                                       │
│   318 │   │   finally:                                                                                               │
│                                                                                                                      │
│E:\AI-ImageGen\sdnext_dev\venv\Lib\site-packages\transformers\modeling_utils.py:4829 in from_pretrained               │
│                                                                                                                      │
│  4828 │   │   │   config_path = config if config is not None else pretrained_model_name_or_path                      │
│❱ 4829 │   │   │   config, model_kwargs = cls.config_class.from_pretrained(                                           │
│  4830 │   │   │   │   config_path,                                                                                   │
│                                                                                                                      │
│E:\AI-ImageGen\sdnext_dev\venv\Lib\site-packages\transformers\configuration_utils.py:609 in from_pretrained           │
│                                                                                                                      │
│   608 │   │                                                                                                          │
│❱  609 │   │   config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)                     │
│   610 │   │   if cls.base_config_key and cls.base_config_key in config_dict:                                         │
│                                                                                                                      │
│E:\AI-ImageGen\sdnext_dev\venv\Lib\site-packages\transformers\configuration_utils.py:649 in get_config_dict           │
│                                                                                                                      │
│   648 │   │   # Get config dict associated with the base config file                                                 │
│❱  649 │   │   config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)                    │
│   650 │   │   if config_dict is None:                                                                                │
│                                                                                                                      │
│E:\AI-ImageGen\sdnext_dev\venv\Lib\site-packages\transformers\configuration_utils.py:747 in _get_config_dict          │
│                                                                                                                      │
│   746 │   │   except (json.JSONDecodeError, UnicodeDecodeError):                                                     │
│❱  747 │   │   │   raise OSError(f"It looks like the config file at '{resolved_config_file}' is not a valid JSON file │
│   748                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: It looks like the config file at 'E:\AI-ImageGen\Database\models\huggingface\models--Wan-AI--Wan2.2-T2V-A14B-Diffusers\snapshots\5be7df9619b54f4e2667b2755bc6a756675b5cd7\text_encoder\config.json' is not a valid JSON file.
02:27:51-506231 DEBUG    Quantization: module="Model" type=sdnq dtype=int8 matmul=True group_size=0 quant_conv=False
                         matmul_conv=False dequantize_fp32=False quantize_with_gpu=True quantization_device=cuda
                         return_device=cpu device_map=default offload_mode=balanced non_blocking=False
Progress ?it/s ████████████████████████████ 100% 12/12 00:00 ? Fetching 12 files
Progress  3.64s/it █████████▊     75% 9/12 00:31 00:10 Loading checkpoint shards02:28:27-839033 TRACE    Server: alive=True requests=210 memory=20.65/127.92 status='idle' task='' timestamp=None
                         current='task(h8n3v5o6e7m2urf)' id='' job=0 jobs=0 total=2 step=0 steps=0 queued=0 uptime=271
                         elapsed=261.78 eta=None progress=0
Progress  3.64s/it ████████████ 100% 12/12 00:43 00:00 Loading checkpoint shards
02:28:36-931087 DEBUG    GC: current={'gpu': 1.28, 'ram': 19.25, 'oom': 0} prev={'gpu': 1.28, 'ram': 19.25} load={'gpu':
                         5, 'ram': 15} gc={'gpu': 0.0, 'py': 567}
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.45
02:28:37-676747 ERROR    video load: module=pipe repo="Wan-AI/Wan2.2-T2V-A14B-Diffusers" cls=WanPipeline Expecting
                         value: line 1 column 1 (char 0)
02:28:37-678246 ERROR    video: JSONDecodeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│E:\AI-ImageGen\sdnext_dev\modules\video_models\video_load.py:64 in load_model                                         │
│                                                                                                                      │
│   63 │   │   debug(f'Video load: module=pipe repo="{selected.repo}" cls={selected.repo_cls.__name__}')               │
│❱  64 │   │   shared.sd_model = selected.repo_cls.from_pretrained(                                                    │
│   65 │   │   │   pretrained_model_name_or_path=selected.repo,                                                        │
│                                                                                                                      │
│E:\AI-ImageGen\sdnext_dev\venv\Lib\site-packages\huggingface_hub\utils\_validators.py:114 in _inner_fn                │
│                                                                                                                      │
│  113 │   │                                                                                                           │
│❱ 114 │   │   return fn(*args, **kwargs)                                                                              │
│  115                                                                                                                 │
│                                                                                                                      │
│E:\AI-ImageGen\sdnext_dev\venv\Lib\site-packages\diffusers\pipelines\pipeline_utils.py:833 in from_pretrained         │
│                                                                                                                      │
│   832 │   │   │   │   )                                                                                              │
│❱  833 │   │   │   cached_folder = cls.download(                                                                      │
│   834 │   │   │   │   pretrained_model_name_or_path,                                                                 │
│                                                                                                                      │
│E:\AI-ImageGen\sdnext_dev\venv\Lib\site-packages\huggingface_hub\utils\_validators.py:114 in _inner_fn                │
│                                                                                                                      │
│  113 │   │                                                                                                           │
│❱ 114 │   │   return fn(*args, **kwargs)                                                                              │
│  115                                                                                                                 │
│                                                                                                                      │
│E:\AI-ImageGen\sdnext_dev\venv\Lib\site-packages\diffusers\pipelines\pipeline_utils.py:1499 in download               │
│                                                                                                                      │
│  1498 │   │   │   )                                                                                                  │
│❱ 1499 │   │   │   config_dict = cls._dict_from_json_file(config_file)                                                │
│  1500 │   │   │   ignore_filenames = config_dict.pop("_ignore_files", [])                                            │
│                                                                                                                      │
│E:\AI-ImageGen\sdnext_dev\venv\Lib\site-packages\diffusers\configuration_utils.py:574 in _dict_from_json_file         │
│                                                                                                                      │
│  573 │   │   │   │   text = reader.read()                                                                            │
│❱ 574 │   │   return json.loads(text)                                                                                 │
│  575                                                                                                                 │
│                                                                                                                      │
│C:\Users\ohiom\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py:346 in loads                              │
│                                                                                                                      │
│  345 │   │   │   parse_constant is None and object_pairs_hook is None and not kw):                                   │
│❱ 346 │   │   return _default_decoder.decode(s)                                                                       │
│  347 │   if cls is None:                                                                                             │
│                                                                                                                      │
│C:\Users\ohiom\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py:338 in decode                              │
│                                                                                                                      │
│  337 │   │   """                                                                                                     │
│❱ 338 │   │   obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                       │
│  339 │   │   end = _w(s, end).end()                                                                                  │
│                                                                                                                      │
│C:\Users\ohiom\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py:356 in raw_decode                          │
│                                                                                                                      │
│  355 │   │   except StopIteration as err:                                                                            │
│❱ 356 │   │   │   raise JSONDecodeError("Expecting value", s, err.value) from None                                    │
│  357 │   │   return obj, end                                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
02:28:37-972165 DEBUG    Model requested: fn=video_run.py:generate:load_model
02:28:37-973386 INFO     Load model: select="Illustrious - Noob V-Pred 1.0 Personal Merge [d14ea71ad5]"
02:28:37-975393 INFO     Autodetect model: detect="Stable Diffusion XL" class=StableDiffusionXLPipeline
                         file="E:\AI-ImageGen\Database\models\Stable-diffusion\Illustrious - Noob V-Pred 1.0 Personal
                         Merge.safetensors"
02:28:37-976890 DEBUG    Cache clear
Progress  1.28it/s █████████ 100% 7/7 00:05 00:00 Loading pipeline components...
02:28:44-400095 DEBUG    Setting model: pipeline=StableDiffusionXLPipeline config={'low_cpu_mem_usage': True,
                         'torch_dtype': torch.bfloat16, 'load_connected_pipeline': True, 'extract_ema': False, 'config':
                         'configs/sdxl', 'use_safetensors': True, 'cache_dir':
                         'E:\\AI-ImageGen\\Database\\models\\huggingface'}
02:28:44-403598 INFO     Setting override: model="Illustrious - Noob V-Pred 1.0 Personal Merge" component=scheduler
                         prediction="v-prediction"
02:28:50-202554 INFO     Network load: type=embeddings loaded=19 skipped=36 time=5.80
02:28:50-204057 DEBUG    Setting model: component=vae {'slicing': True, 'tiling': True, 'tile': 1024, 'overlap': 0.25}
02:28:50-205568 DEBUG    Setting model: attention="Scaled-Dot-Product"
02:28:50-216570 DEBUG    Load model: post_quant=sdnq
02:28:50-218070 DEBUG    Quantization: type=SDNQ modules=['Model', 'TE'] dtype=int8 dtype_te=Same as model matmul=True
                         group_size=0 quant_conv=False matmul_conv=False quantize_with_gpu=True dequantize_fp32=False
                         pre_forward=True
02:28:52-502010 DEBUG    GC: current={'gpu': 1.28, 'ram': 22.41, 'oom': 0} prev={'gpu': 1.44, 'ram': 22.41} load={'gpu':
                         5, 'ram': 18} gc={'gpu': 0.16, 'py': 179} fn=apply_function_to_model:sdnq_quantize_model
                         why=sdnq time=0.50
02:28:53-057632 DEBUG    GC: current={'gpu': 1.28, 'ram': 22.48, 'oom': 0} prev={'gpu': 1.33, 'ram': 22.48} load={'gpu':
                         5, 'ram': 18} gc={'gpu': 0.05, 'py': 127} fn=apply_function_to_model:sdnq_quantize_model
                         why=sdnq time=0.45
02:28:54-179139 DEBUG    GC: current={'gpu': 1.28, 'ram': 20.03, 'oom': 0} prev={'gpu': 1.35, 'ram': 20.03} load={'gpu':
                         5, 'ram': 16} gc={'gpu': 0.07, 'py': 138} fn=apply_function_to_model:sdnq_quantize_model
                         why=sdnq time=0.42
02:28:54-182140 INFO     Quantization: type=SDNQ time=3.96
02:28:54-183140 INFO     Offload: type=balanced op=init watermark=0.2-0.8 gpu=4.80-19.20:24.00 cpu=128.000 limit=0.00
                         always=[] never=['CLIPTextModel', 'CLIPTextModelWithProjection', 'AutoencoderKL']
02:28:54-213670 DEBUG    Module: name=unet cls=UNet2DConditionModel size=2.703 params=2567463684 quant=SDNQ
02:28:54-218669 DEBUG    Module: name=text_encoder_2 cls=CLIPTextModelWithProjection size=0.708 params=695571200
                         quant=SDNQ
02:28:54-222140 DEBUG    Module: name=vae cls=AutoencoderKL size=0.156 params=83653863 quant=None
02:28:54-225169 DEBUG    Module: name=text_encoder cls=CLIPTextModel size=0.151 params=123607296 quant=SDNQ
02:28:54-226170 INFO     Model class=StableDiffusionXLPipeline modules=4 size=3.718
02:28:54-230166 INFO     Load model: family=sdxl time={'total': 18.77, 'load': 6.43, 'embeddings': 5.8, 'options': 3.98,
                         'sdnq': 2.51} native=1024 memory={'ram': {'total': 127.92, 'used': 20.03, 'free': 108}, 'gpu':
                         {'used': 1.28, 'total': 24.0, 'active': 0.0, 'peak': 0.59, 'retries': 0, 'oom': 0, 'swap': 0},
                         'job': 'Load'}
02:28:54-232641 DEBUG    Setting model: component=vae {'slicing': True, 'tiling': True, 'tile': 1024, 'overlap': 0.25}
02:28:54-234139 DEBUG    Setting model: attention="Scaled-Dot-Product"
02:28:54-245170 INFO     Offload: type=balanced op=init watermark=0.2-0.8 gpu=4.80-19.20:24.00 cpu=128.000 limit=0.00
                         always=[] never=['CLIPTextModel', 'CLIPTextModelWithProjection', 'AutoencoderKL']
02:28:54-274158 DEBUG    Module: name=unet cls=UNet2DConditionModel size=2.703 params=2567463684 quant=SDNQ
02:28:54-279168 DEBUG    Module: name=text_encoder_2 cls=CLIPTextModelWithProjection size=0.708 params=695571200
                         quant=SDNQ
02:28:54-283169 DEBUG    Module: name=vae cls=AutoencoderKL size=0.156 params=83653863 quant=None
02:28:54-284167 TRACE    State history: uptime=297 jobs=10 tasks=0 latents=0 images=0
02:28:54-287197 DEBUG    Module: name=text_encoder cls=CLIPTextModel size=0.151 params=123607296 quant=SDNQ
02:28:54-288667 INFO     Exiting
02:28:54-289168 INFO     Model class=StableDiffusionXLPipeline modules=4 size=3.718
02:28:54-290710 INFO     Video load: cls=StableDiffusionXLPipeline model="WAN 2.2 A14B I2V" time=48.13
forrtl: error (200): program aborting due to control-C event
```

### Backend

Diffusers

### Compute

nVidia CUDA

### Interface

ModernUI

### Branch

Dev

### Model

Other

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i understand the issue, but handling of that is extremely messy. if model is not loaded, it can be pulled by any operation. and since last known model was sdxl in base, that's what gets pulled.

only thing i dont understand it this statement:
>  and forcing a weird state where futher video attempts are unsuccesfull, only resolved by restart:

you can use that base model in txt/img/control tabs or if you want to use video tab, load a video model. the fact that all this happened does not change that. as soon as you sucessfully load a video model, it should all be good. no server restart needed.

anyhow, i'm putting this in a backlog for now.
