### ISSUE TITLE
[Issue]: Wildcards not changing for batched generations

### ISSUE THREAD

**Issue by epsilon7430** [vladmandic/automatic#4255]
### Issue Description

The first choice of a wildcard set is used for all gens in a job, whether batch count >1 or batch size >1.  This seems to be a new issue as of sdnext hash 7c8f42fab.  Happens in both modern and standard UIs.

For log sample, the positive prompt was "castle in the clouds, (__Color_Palettes\simplecolors__)" and for both image gens the wildcard choice was "violet".

### Version Platform Description

sdnext 7c8f42fab
Edge browser
Win 11

### Relevant log output

```shell
2025-10-10 20:20:26,272 | PC | sd | INFO | launch | Starting SD.Next
2025-10-10 20:20:26,275 | PC | sd | INFO | installer | Logger: file="C:\Users\Owner\sdnext\sdnext.log" level=DEBUG host="PC" size=74 mode=create
2025-10-10 20:20:26,276 | PC | sd | INFO | installer | Python: version=3.12.7 platform=Windows bin="C:\Users\Owner\sdnext\venv\Scripts\python.exe" venv="C:\Users\Owner\sdnext\venv"
2025-10-10 20:20:26,405 | PC | sd | INFO | installer | Version: app=sd.next updated=2025-09-16 hash=7c8f42fab branch=master url=https://github.com/vladmandic/sdnext/tree/master ui=main
2025-10-10 20:20:27,005 | PC | sd | INFO | installer | Version: app=sd.next latest=2025-09-16T13:03:46Z hash=7c8f42fa branch=master
2025-10-10 20:20:27,028 | PC | sd | INFO | launch | Platform: arch=AMD64 cpu=Intel64 Family 6 Model 151 Stepping 2, GenuineIntel system=Windows release=Windows-11-10.0.22631-SP0 python=3.12.7 locale=('English_Canada', '1252') docker=False
2025-10-10 20:20:27,029 | PC | sd | DEBUG | installer | Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
2025-10-10 20:20:27,030 | PC | sd | INFO | launch | Args: ['--debug']
2025-10-10 20:20:27,032 | PC | sd | DEBUG | installer | Setting environment tuning
2025-10-10 20:20:27,032 | PC | sd | DEBUG | installer | Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
2025-10-10 20:20:27,033 | PC | sd | INFO | installer | Verifying torch installation
2025-10-10 20:20:27,035 | PC | sd | DEBUG | installer | Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=False
2025-10-10 20:20:27,039 | PC | sd | INFO | installer | CUDA: nVidia toolkit detected
2025-10-10 20:20:27,119 | PC | sd | INFO | installer | Install: verifying requirements
2025-10-10 20:20:27,161 | PC | sd | DEBUG | installer | Timestamp repository update time: Tue Sep 16 06:03:46 2025
2025-10-10 20:20:27,162 | PC | sd | INFO | launch | Startup: standard
2025-10-10 20:20:27,162 | PC | sd | INFO | installer | Verifying submodules
2025-10-10 20:20:28,878 | PC | sd | DEBUG | installer | Git submodule: extensions-builtin/sd-extension-chainner / main
2025-10-10 20:20:28,967 | PC | sd | DEBUG | installer | Git detached head detected: folder="extensions-builtin/sd-extension-system-info" reattach=main
2025-10-10 20:20:28,967 | PC | sd | DEBUG | installer | Git submodule: extensions-builtin/sd-extension-system-info / main
2025-10-10 20:20:29,021 | PC | sd | DEBUG | installer | Git submodule: extensions-builtin/sd-webui-agent-scheduler / main
2025-10-10 20:20:29,099 | PC | sd | DEBUG | installer | Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
2025-10-10 20:20:29,100 | PC | sd | DEBUG | installer | Git submodule: extensions-builtin/sdnext-modernui / main
2025-10-10 20:20:29,152 | PC | sd | DEBUG | installer | Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
2025-10-10 20:20:29,236 | PC | sd | DEBUG | installer | Git detached head detected: folder="wiki" reattach=master
2025-10-10 20:20:29,237 | PC | sd | DEBUG | installer | Git submodule: wiki / master
2025-10-10 20:20:29,309 | PC | sd | DEBUG | installer | Installed packages: 195
2025-10-10 20:20:29,310 | PC | sd | DEBUG | installer | Extensions all: ['sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
2025-10-10 20:20:29,369 | PC | sd | DEBUG | installer | Extension installer: builtin=True file="C:\Users\Owner\sdnext\extensions-builtin\sd-webui-agent-scheduler\install.py"
2025-10-10 20:20:29,433 | PC | sd | DEBUG | installer | Extension installer: builtin=True file="C:\Users\Owner\sdnext\extensions-builtin\stable-diffusion-webui-rembg\install.py"
2025-10-10 20:20:29,466 | PC | sd | DEBUG | installer | Extensions all: ['adetailer', 'sd-dynamic-prompts']
2025-10-10 20:20:29,466 | PC | sd | DEBUG | installer | Extension force: name="adetailer" commit=a89c01d
2025-10-10 20:20:29,497 | PC | sd | DEBUG | installer | Extension installer: builtin=False file="C:\Users\Owner\sdnext\extensions\adetailer\install.py"
2025-10-10 20:20:29,639 | PC | sd | DEBUG | installer | Extension installer: builtin=False file="C:\Users\Owner\sdnext\extensions\sd-dynamic-prompts\install.py"
2025-10-10 20:20:29,797 | PC | sd | INFO | installer | Extensions enabled: ['sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg', 'adetailer', 'sd-dynamic-prompts']
2025-10-10 20:20:29,829 | PC | sd | INFO | installer | Install: verifying requirements
2025-10-10 20:20:29,831 | PC | sd | DEBUG | launch | Setup complete without errors: 1760152830
2025-10-10 20:20:29,835 | PC | sd | DEBUG | installer | Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
2025-10-10 20:20:29,836 | PC | sd | INFO | launch | Installer time: total=6.51 git=2.24 submodules=2.12 latest=0.73 branch=0.43 base=0.19 adetailer=0.17 sd-dynamic-prompts=0.16 version=0.13 requirements=0.07 installed=0.07
2025-10-10 20:20:29,837 | PC | sd | INFO | launch | Command line args: ['--debug'] debug=True args=[]
2025-10-10 20:20:29,838 | PC | sd | DEBUG | launch | Env flags: []
2025-10-10 20:20:29,838 | PC | sd | DEBUG | launch | Starting module: <module 'webui' from 'C:\\Users\\Owner\\sdnext\\webui.py'>
2025-10-10 20:20:35,724 | PC | sd | INFO | loader | Torch: torch==2.7.1+cu128 torchvision==0.22.1+cu128
2025-10-10 20:20:35,726 | PC | sd | INFO | loader | Packages: diffusers==0.36.0.dev0 transformers==4.56.1 accelerate==1.10.1 gradio==3.43.2 pydantic==1.10.21 numpy==2.1.2
2025-10-10 20:20:36,172 | PC | sd | DEBUG | __init__ | ONNX: version=1.22.1, available=['AzureExecutionProvider', 'CPUExecutionProvider']
2025-10-10 20:20:36,267 | PC | sd | DEBUG | shared_state | State initialized: id=2064077625856
2025-10-10 20:20:36,358 | PC | sd | INFO | shared_defaults | Device detect: memory=16.0 default=balanced
2025-10-10 20:20:36,362 | PC | sd | DEBUG | json_helpers | Read: file="C:\Users\Owner\sdnext\config.json" json=27 bytes=1350 time=0.000 fn=<module>:load
2025-10-10 20:20:36,363 | PC | sd | WARNING | options_handler | Setting validation: unknown=['multiple_tqdm']
2025-10-10 20:20:36,365 | PC | sd | INFO | shared | Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product" mode=no_grad
2025-10-10 20:20:36,366 | PC | sd | DEBUG | json_helpers | Read: file="html\reference.json" json=101 bytes=49022 time=0.001 fn=_call_with_frames_removed:<module>
2025-10-10 20:20:36,366 | PC | sd | DEBUG | devices | Torch cuDNN: benchmark=True
2025-10-10 20:20:36,367 | PC | sd | DEBUG | devices | Torch attention: type="sdpa" flash=True memory=True math=True
2025-10-10 20:20:36,402 | PC | sd | INFO | devices | Torch parameters: backend=cuda device=cuda config=Auto dtype=torch.bfloat16 context=no_grad nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False, True] fp16=pass bf16=pass optimization="Scaled-Dot-Product"
2025-10-10 20:20:36,442 | PC | sd | INFO | shared | Device: device=NVIDIA GeForce RTX 4060 Ti n=1 arch=sm_120 capability=(8, 9) cuda=12.8 cudnn=90701 driver=560.94
2025-10-10 20:20:36,567 | PC | sd | DEBUG | webui | Entering start sequence
2025-10-10 20:20:36,593 | PC | sd | DEBUG | webui | Initializing
2025-10-10 20:20:36,619 | PC | sd | DEBUG | json_helpers | Read: file="metadata.json" json=2147 bytes=9596541 time=0.025 fn=initialize:init_metadata
2025-10-10 20:20:36,621 | PC | sd | DEBUG | json_helpers | Read: file="cache.json" json=2 bytes=10190 time=0.001 fn=initialize:init_cache
2025-10-10 20:20:36,656 | PC | sd | INFO | sd_vae | Available VAEs: path="C:\Users\Owner\Documents\Stable Diffusion Models\VAE" items=6
2025-10-10 20:20:36,657 | PC | sd | INFO | sd_unet | Available UNets: path="C:\Users\Owner\Documents\Stable Diffusion Models\UNET" items=0
2025-10-10 20:20:36,661 | PC | sd | INFO | model_te | Available TEs: path="C:\Users\Owner\Documents\Stable Diffusion Models\Text-encoder" items=0
2025-10-10 20:20:36,667 | PC | sd | INFO | sd_checkpoint | Available Models: safetensors="C:\Users\Owner\Documents\Stable Diffusion Models\Stable-diffusion":50 diffusers="C:\Users\Owner\Documents\Stable Diffusion Models\Diffusers":5 reference=101 items=55 time=0.00
2025-10-10 20:20:36,778 | PC | sd | INFO | lora_load | Available LoRAs: path="C:\Users\Owner\Documents\Stable Diffusion Models\Lora" items=2049 folders=4 time=0.10
2025-10-10 20:20:36,793 | PC | sd | INFO | styles | Available Styles: path="C:\Users\Owner\Documents\Stable Diffusion Models\styles" items=321 time=0.01
2025-10-10 20:20:36,851 | PC | sd | INFO | yolo | Available Detailer: path="C:\Users\Owner\Documents\Stable Diffusion Models\yolo" items=15 downloaded=9
2025-10-10 20:20:36,852 | PC | sd | DEBUG | extensions | Extensions: disabled=['sdnext-modernui']
2025-10-10 20:20:36,853 | PC | sd | INFO | webui | Load extensions
2025-10-10 20:20:37,563 | PC | sd | INFO | script_loading | Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
2025-10-10 20:20:37,751 | PC | sd | INFO | script_loading | Extension: script='extensions\adetailer\scripts\!adetailer.py' [-] ADetailer initialized. version: 24.5.1, num models: 13
2025-10-10 20:20:37,783 | PC | sd | DEBUG | webui | Extensions init time: total=0.93 sd-webui-agent-scheduler=0.37 xyz_grid.py=0.21 adetailer=0.18
2025-10-10 20:20:37,789 | PC | sd | DEBUG | json_helpers | Read: file="html/upscalers.json" json=4 bytes=2672 time=0.000 fn=__init__:__init__
2025-10-10 20:20:37,790 | PC | sd | DEBUG | json_helpers | Read: file="extensions-builtin\sd-extension-chainner\models.json" json=25 bytes=2830 time=0.000 fn=__init__:find_scalers
2025-10-10 20:20:37,792 | PC | sd | DEBUG | chainner_model | Available chaiNNer: path="C:\Users\Owner\Documents\Stable Diffusion Models\chaiNNer" defined=25 discovered=0 downloaded=2
2025-10-10 20:20:37,793 | PC | sd | DEBUG | upscaler | Upscaler type=ESRGAN folder="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN" model="ESRGAN_4x" path="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN\ESRGAN_4x.pth"
2025-10-10 20:20:37,794 | PC | sd | DEBUG | upscaler | Upscaler type=ESRGAN folder="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN" model="KCJPUNK_1.0_233089_ G-4x" path="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN\KCJPUNK_1.0_233089_ G-4x.pth"
2025-10-10 20:20:37,795 | PC | sd | DEBUG | upscaler | Upscaler type=ESRGAN folder="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN" model="NickelbackFS_72000_G-4x" path="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN\NickelbackFS_72000_G-4x.pth"
2025-10-10 20:20:37,796 | PC | sd | DEBUG | upscaler | Upscaler type=ESRGAN folder="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN" model="NMKD-Faces_160000_G-8x" path="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN\NMKD-Faces_160000_G-8x.pth"
2025-10-10 20:20:37,796 | PC | sd | DEBUG | upscaler | Upscaler type=ESRGAN folder="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN" model="NMKD-Superscale-Artisoftject_210000_G.pth-4x" path="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN\NMKD-Superscale-Artisoftject_210000_G.pth-4x.pth"
2025-10-10 20:20:37,797 | PC | sd | DEBUG | upscaler | Upscaler type=ESRGAN folder="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN" model="NMKD-Superscale-SP_178000_G-4x" path="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN\NMKD-Superscale-SP_178000_G-4x.pth"
2025-10-10 20:20:37,798 | PC | sd | DEBUG | upscaler | Upscaler type=ESRGAN folder="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN" model="NMKD-Superscale_150000_G-8x" path="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN\NMKD-Superscale_150000_G-8x.pth"
2025-10-10 20:20:37,798 | PC | sd | DEBUG | upscaler | Upscaler type=ESRGAN folder="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN" model="Opscaler_general-4x" path="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN\Opscaler_general-4x.pth"
2025-10-10 20:20:37,799 | PC | sd | DEBUG | upscaler | Upscaler type=ESRGAN folder="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN" model="UltraMix_Balanced-4x" path="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN\UltraMix_Balanced-4x.pth"
2025-10-10 20:20:37,800 | PC | sd | DEBUG | upscaler | Upscaler type=ESRGAN folder="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN" model="UltraMix_Restore-4x" path="C:\Users\Owner\Documents\Stable Diffusion Models\ESRGAN\UltraMix_Restore-4x.pth"
2025-10-10 20:20:37,801 | PC | sd | DEBUG | upscaler | Upscaler type=SCUNet folder="C:\Users\Owner\Documents\Stable Diffusion Models\SCUNet" model="ScuNET" path="C:\Users\Owner\Documents\Stable Diffusion Models\SCUNet\ScuNET.pth"
2025-10-10 20:20:37,802 | PC | sd | DEBUG | upscaler | Upscaler type=SwinIR folder="C:\Users\Owner\Documents\Stable Diffusion Models\SwinIR" model="Swin2SR_RealworldSR_X4_64_BSRGAN_PSNR.v2" path="C:\Users\Owner\Documents\Stable Diffusion Models\SwinIR\Swin2SR_RealworldSR_X4_64_BSRGAN_PSNR.v2.pth"
2025-10-10 20:20:37,803 | PC | sd | DEBUG | upscaler | Upscaler type=SwinIR folder="C:\Users\Owner\Documents\Stable Diffusion Models\SwinIR" model="SwinIR_4x" path="C:\Users\Owner\Documents\Stable Diffusion Models\SwinIR\SwinIR_4x.pth"
2025-10-10 20:20:37,804 | PC | sd | INFO | modelloader | Available Upscalers: items=85 downloaded=24 user=13 time=0.02 types=['None', 'Resize', 'Latent', 'AsymmetricVAE', 'DCC', 'VIPS', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'RealESRGAN', 'SCUNet', 'Diffusion', 'SwinIR']
2025-10-10 20:20:37,811 | PC | sd | INFO | models_hf | Huggingface init: transfer=rust parallel=True direct=False token="None" cache="C:\Users\Owner\Documents\Stable Diffusion Models\huggingface"
2025-10-10 20:20:37,842 | PC | sd | WARNING | models_hf | Cache location changed: previous="C:\Users\Owner\.cache\huggingface\hub" size=53172 MB
2025-10-10 20:20:37,847 | PC | sd | DEBUG | models_hf | Huggingface cache: path="C:\Users\Owner\Documents\Stable Diffusion Models\huggingface" size=203 MB
2025-10-10 20:20:37,848 | PC | sd | DEBUG | webui | UI start sequence
2025-10-10 20:20:37,851 | PC | sd | INFO | theme | UI locale: name="Auto"
2025-10-10 20:20:37,852 | PC | sd | INFO | theme | UI theme: type=Standard name="black-teal" available=14
2025-10-10 20:20:37,853 | PC | sd | DEBUG | ui_javascript | UI theme: css="C:\Users\Owner\sdnext\javascript\black-teal.css" base="['sdnext.css', 'timesheet.css']" user="None"
2025-10-10 20:20:37,855 | PC | sd | DEBUG | ui_txt2img | UI initialize: txt2img
2025-10-10 20:20:40,105 | PC | sd | DEBUG | ui_extra_networks | Networks: type="model" items=155 subfolders=8 tab=txt2img folders=['C:\\Users\\Owner\\Documents\\Stable Diffusion Models\\Stable-diffusion', 'models\\Reference', 'C:\\Users\\Owner\\Documents\\Stable Diffusion Models\\Stable-diffusion'] list=0.52 thumb=0.18 desc=0.04 info=0.03 workers=12
2025-10-10 20:20:40,150 | PC | sd | DEBUG | ui_extra_networks | Networks: type="lora" items=2049 subfolders=40 tab=txt2img folders=['C:\\Users\\Owner\\Documents\\Stable Diffusion Models\\Lora'] list=1.10 thumb=0.25 desc=1.01 info=4.78 workers=12
2025-10-10 20:20:40,162 | PC | sd | DEBUG | ui_extra_networks | Networks: type="style" items=321 subfolders=3 tab=txt2img folders=['C:\\Users\\Owner\\Documents\\Stable Diffusion Models\\styles', 'html'] list=0.16 thumb=0.05 desc=0.00 info=0.00 workers=12
2025-10-10 20:20:40,277 | PC | sd | DEBUG | ui_extra_networks | Networks: type="wildcards" items=595 subfolders=141 tab=txt2img folders=['C:\\Users\\Owner\\Documents\\Stable Diffusion Models\\wildcards'] list=2.23 thumb=1.39 desc=0.00 info=0.00 workers=12
2025-10-10 20:20:40,302 | PC | sd | DEBUG | ui_extra_networks | Networks: type="embedding" items=1291 subfolders=20 tab=txt2img folders=['C:\\Users\\Owner\\Documents\\Stable Diffusion Models\\embeddings'] list=1.25 thumb=0.12 desc=0.11 info=0.17 workers=12
2025-10-10 20:20:40,306 | PC | sd | DEBUG | ui_extra_networks | Networks: type="vae" items=6 subfolders=1 tab=txt2img folders=['C:\\Users\\Owner\\Documents\\Stable Diffusion Models\\VAE'] list=0.06 thumb=0.05 desc=0.00 info=0.00 workers=12
2025-10-10 20:20:40,307 | PC | sd | DEBUG | ui_extra_networks | Networks: type="history" items=0 subfolders=1 tab=txt2img folders=[] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=12
2025-10-10 20:20:40,499 | PC | sd | DEBUG | ui_img2img | UI initialize: img2img
2025-10-10 20:20:40,885 | PC | sd | DEBUG | ui_control_helpers | UI initialize: control models="C:\Users\Owner\Documents\Stable Diffusion Models\control"
2025-10-10 20:20:41,024 | PC | sd | DEBUG | scripts_manager | Script: fn="extensions\adetailer\scripts\!adetailer.py" type=control skip
2025-10-10 20:20:41,025 | PC | sd | DEBUG | scripts_manager | Script: fn="extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py" type=control skip
2025-10-10 20:20:41,026 | PC | sd | DEBUG | scripts_manager | Script: fn="extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py" type=control skip
2025-10-10 20:20:41,185 | PC | sd | DEBUG | ui_video | UI initialize: video
2025-10-10 20:20:41,524 | PC | sd | DEBUG | json_helpers | Read: file="ui-config.json" json=6 bytes=237 time=0.000 fn=__init__:read_from_file
2025-10-10 20:20:41,529 | PC | sd | DEBUG | ui_settings | Settings: sections=26 settings=378/585 quicksettings=0
2025-10-10 20:20:42,422 | PC | sd | DEBUG | ui_extensions | Extension list: processed=411 installed=6 enabled=6 disabled=0 visible=411 hidden=0
2025-10-10 20:20:42,809 | PC | sd | DEBUG | webui | Root paths: ['C:\\Users\\Owner\\sdnext', 'models']
2025-10-10 20:20:42,896 | PC | sd | INFO | webui | Local URL: http://127.0.0.1:7860/
2025-10-10 20:20:42,898 | PC | sd | DEBUG | middleware | API middleware: [<class 'starlette.middleware.base.BaseHTTPMiddleware'>, <class 'starlette.middleware.gzip.GZipMiddleware'>]
2025-10-10 20:20:42,899 | PC | sd | DEBUG | webui | API initialize
2025-10-10 20:20:43,036 | PC | sd | INFO | task_runner | [AgentScheduler] Task queue is empty
2025-10-10 20:20:43,037 | PC | sd | INFO | api | [AgentScheduler] Registering APIs
2025-10-10 20:20:43,371 | PC | sd | DEBUG | webui | Scripts setup: time=0.366 ['ADetailer:0.046', 'XYZ Grid:0.034']
2025-10-10 20:20:43,372 | PC | sd | DEBUG | sd_checkpoint | Model metadata: file="metadata.json" no changes
2025-10-10 20:20:43,374 | PC | sd | DEBUG | modeldata | Model requested: fn=threading.py:run:<lambda>
2025-10-10 20:20:43,375 | PC | sd | INFO | sd_checkpoint | Load model: select="PDXL\PDXL CyberRealistic Pony v12.7 [69975d352a]"
2025-10-10 20:20:43,376 | PC | sd | INFO | sd_detect | Autodetect model: detect="Stable Diffusion XL" class=StableDiffusionXLPipeline file="C:\Users\Owner\Documents\Stable Diffusion Models\Stable-diffusion\PDXL\PDXL CyberRealistic Pony v12.7.safetensors"
2025-10-10 20:20:43,377 | PC | sd | INFO | sd_detect | Autodetect vae: detect="Stable Diffusion XL" class=StableDiffusionXLPipeline file="C:\Users\Owner\Documents\Stable Diffusion Models\Stable-diffusion\PDXL\PDXL CyberRealistic Pony v12.7.safetensors"
2025-10-10 20:20:43,378 | PC | sd | INFO | sd_vae | Load module: type=VAE model="C:\Users\Owner\Documents\Stable Diffusion Models\VAE\liquid111vae_sdxl9745VAE_for_mmmmilk.safetensors" source=settings config={'low_cpu_mem_usage': False, 'torch_dtype': torch.bfloat16, 'use_safetensors': True, 'config': 'configs/sdxl\\vae'}
2025-10-10 20:20:43,739 | PC | sd | DEBUG | sd_models | Cache clear
2025-10-10 20:20:44,049 | PC | sd | DEBUG | server | UI: connected
2025-10-10 20:20:48,072 | PC | sd | DEBUG | sd_models | Setting model: pipeline=StableDiffusionXLPipeline config={'low_cpu_mem_usage': True, 'torch_dtype': torch.bfloat16, 'load_connected_pipeline': True, 'extract_ema': False, 'config': 'configs/sdxl', 'use_safetensors': True, 'cache_dir': 'C:\\Users\\Owner\\Documents\\Stable Diffusion Models\\huggingface'}
2025-10-10 20:20:54,070 | PC | sd | INFO | textual_inversion | Network load: type=embeddings loaded=89 skipped=1201 time=5.99
2025-10-10 20:20:54,071 | PC | sd | DEBUG | installer | Setting model: component=vae {'name': 'liquid111vae_sdxl9745VAE_for_mmmmilk.safetensors', 'slicing': True, 'tiling': False}
2025-10-10 20:20:54,072 | PC | sd | DEBUG | installer | Setting model: attention="Scaled-Dot-Product"
2025-10-10 20:20:54,077 | PC | sd | DEBUG | model_quant | Load model: post_quant=sdnq
2025-10-10 20:20:54,077 | PC | sd | DEBUG | model_quant | Quantization: type=SDNQ modules=['Model', 'VAE'] dtype=int8 dtype_te=Same as model matmul=False  group_size=0 quant_conv=False matmul_conv=False quantize_with_gpu=True dequantize_fp32=False pre_forward=True
2025-10-10 20:20:55,900 | PC | sd | DEBUG | devices | GC: current={'gpu': 1.15, 'ram': 8.34, 'oom': 0} prev={'gpu': 1.3, 'ram': 8.34} load={'gpu': 7, 'ram': 26} gc={'gpu': 0.15, 'py': 2770} fn=apply_function_to_model:sdnq_quantize_model why=sdnq time=0.28
2025-10-10 20:20:55,902 | PC | sd | DEBUG | model_quant | Quantization: module="unet" type=sdnq mode=post dtype=int8 matmul=False group_size=0 quant_conv=False matmul_conv=False dequantize_fp32=False quantize_with_gpu=True quantization_device=cuda return_device=cpu device_map=default offload_mode=balanced non_blocking=False modules_to_not_convert=['norm'] modules_dtype_dict={}
2025-10-10 20:20:56,156 | PC | sd | DEBUG | devices | GC: current={'gpu': 1.15, 'ram': 8.34, 'oom': 0} prev={'gpu': 1.15, 'ram': 8.34} load={'gpu': 7, 'ram': 26} gc={'gpu': 0.0, 'py': 127} fn=apply_function_to_model:sdnq_quantize_model why=sdnq time=0.25
2025-10-10 20:20:56,157 | PC | sd | DEBUG | model_quant | Quantization: module="vae" type=sdnq mode=post dtype=int8 matmul=False group_size=0 quant_conv=False matmul_conv=False dequantize_fp32=False quantize_with_gpu=True quantization_device=cuda return_device=cpu device_map=default offload_mode=balanced non_blocking=False modules_to_not_convert=[] modules_dtype_dict={}
2025-10-10 20:20:56,159 | PC | sd | INFO | model_quant | Quantization: type=SDNQ time=2.08
2025-10-10 20:20:56,159 | PC | sd | INFO | sd_offload | Offload: type=balanced op=init watermark=0.2-0.6 gpu=3.20-9.60:16.00 cpu=32.000 limit=0.00 always=[] never=[] pre=True
2025-10-10 20:20:56,176 | PC | sd | DEBUG | sd_offload | Module: name=unet cls=UNet2DConditionModel size=2.703 params=2567463684 quant=SDNQ
2025-10-10 20:20:56,178 | PC | sd | DEBUG | sd_offload | Module: name=text_encoder_2 cls=CLIPTextModelWithProjection size=1.302 params=699019520 quant=None
2025-10-10 20:20:56,180 | PC | sd | DEBUG | sd_offload | Module: name=text_encoder cls=CLIPTextModel size=0.234 params=125676288 quant=None
2025-10-10 20:20:56,182 | PC | sd | DEBUG | sd_offload | Module: name=vae cls=AutoencoderKL size=0.154 params=83653863 quant=SDNQ
2025-10-10 20:20:56,182 | PC | sd | INFO | sd_offload | Model class=StableDiffusionXLPipeline modules=4 size=4.393
2025-10-10 20:20:56,183 | PC | sd | DEBUG | json_helpers | Read: file="C:\Users\Owner\sdnext\configs\sdxl\vae\config.json" json=15 bytes=675 time=0.000 fn=apply_vae_config:get_vae_config
2025-10-10 20:20:56,185 | PC | sd | INFO | sd_models | Load model: family=sdxl time={'total': 14.34, 'embeddings': 5.99, 'load': 4.34, 'options': 2.09, 'sdnq': 1.53, 'vae': 0.36} native=1024 memory={'ram': {'total': 31.78, 'used': 8.34, 'free': 23}, 'gpu': {'used': 1.15, 'total': 16.0, 'active': 0.0, 'peak': 0.11, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': 'Load model'}
2025-10-10 20:20:56,188 | PC | sd | DEBUG | script_callbacks | Script init: ['system-info.py:app_started=0.06', 'task_scheduler.py:app_started=0.34']
2025-10-10 20:20:56,189 | PC | sd | INFO | webui | Startup time: total=37.80 checkpoint=12.82 launch=3.95 torch=3.93 loader=3.82 installer=3.82 ui-networks=2.64 libraries=1.29 extensions=0.93 ui-extensions=0.90 gradio=0.81 bnb=0.53 app-started=0.40 ui-img2img=0.34 ui-defaults=0.34 ui-control=0.21 ui-txt2img=0.17 lora=0.11 ui-models=0.11 ui-video=0.11 samplers=0.09 diffusers=0.08 api=0.07 detailer=0.06
2025-10-10 20:20:56,191 | PC | sd | DEBUG | json_helpers | Save: file="C:\Users\Owner\sdnext\config.json" json=27 bytes=1315 time=0.003
2025-10-10 20:20:56,192 | PC | sd | DEBUG | options_handler | Settings: unused=['multiple_tqdm']
2025-10-10 20:21:09,629 | PC | sd | INFO | api | Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0
2025-10-10 20:21:09,693 | PC | sd | INFO | server | UI: ready time=8594
2025-10-10 20:21:09,897 | PC | sd | DEBUG | server | UI: connected
2025-10-10 20:21:26,530 | PC | sd | DEBUG | generation_parameters_copypaste | Prompt parse: type="params" prompt="castle in the clouds, ( gold)
Negative prompt: PDXL_CyberRealistic_Negative_v2_NEG
Steps: 25, Size: 512x512, Sampler: DPM++ 2M, Seed: 1430618317, CFG scale: 6, Batch: 2x1, App: SD.Next, Version: 7c8f42f, Pipeline: StableDiffusionXLPipeline, Operations: txt2img, Model: PDXL CyberRealistic Pony v12.7, Model hash: 69975d352a, VAE: liquid111vae_sdxl9745VAE_for_mmmmilk, Grid: 1x2, Embeddings: PDXL_CyberRealistic_Negative_v2_NEG, Sampler sigma: karras"
2025-10-10 20:21:26,535 | PC | sd | DEBUG | generation_parameters_copypaste | Prompt restore: apply=[{'Prompt': 'castle in the clouds, ( gold)'}, {'Negative prompt': 'PDXL_CyberRealistic_Negative_v2_NEG'}, {'Size-1': 512}, {'Size-2': 512}, {'Sampler': 'DPM++ 2M'}, {'Steps': 25}, {'Batch-1': 2}, {'Batch-2': 1}, {'Seed': 1430618317.0}, {'CFG scale': 6.0}] skip={}
2025-10-10 20:21:59,853 | PC | sd | DEBUG | styles | Apply wildcard: select="Color_Palettes\simplecolors" choice="violet" file="C:\Users\Owner\Documents\Stable Diffusion Models\wildcards\Color_Palettes\simplecolors.txt" choices=42
2025-10-10 20:21:59,854 | PC | sd | DEBUG | styles | Apply wildcards: found=['Color_Palettes\\simplecolors'] missing=[] path="C:\Users\Owner\Documents\Stable Diffusion Models\wildcards" type=file time=0.00 
2025-10-10 20:21:59,914 | PC | sd | DEBUG | styles | Apply wildcard: select="Color_Palettes\simplecolors" choice="red-violet" file="C:\Users\Owner\Documents\Stable Diffusion Models\wildcards\Color_Palettes\simplecolors.txt" choices=42
2025-10-10 20:21:59,915 | PC | sd | DEBUG | styles | Apply wildcards: found=['Color_Palettes\\simplecolors'] missing=[] path="C:\Users\Owner\Documents\Stable Diffusion Models\wildcards" type=file time=0.00 
2025-10-10 20:21:59,929 | PC | sd | DEBUG | processing | Processing: batch=1 total=2 progress=0.50
2025-10-10 20:21:59,932 | PC | sd | DEBUG | sd_samplers | Sampler: "DPM++ 2M" class=DPMSolverMultistepScheduler config={'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'solver_order': 2, 'prediction_type': 'epsilon', 'dynamic_thresholding_ratio': 0.995, 'sample_max_value': 1.0, 'algorithm_type': 'dpmsolver++', 'solver_type': 'midpoint', 'lower_order_final': True, 'use_karras_sigmas': True, 'flow_shift': 1.0, 'final_sigmas_type': 'zero', 'lambda_min_clipped': -inf, 'timestep_spacing': 'linspace', 'steps_offset': 0, 'time_shift_type': 'exponential'}
2025-10-10 20:21:59,941 | PC | sd | INFO | processing_diffusers | Processing modifiers: apply
2025-10-10 20:21:59,965 | PC | sd | DEBUG | prompt_parser_diffusers | Tokenizer: words=52814 file="configs/sdxl\tokenizer\vocab.json"
2025-10-10 20:22:00,927 | PC | sd | INFO | processing_args | Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=1/2x1 set={'prompt_embeds': torch.Size([1, 77, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]), 'negative_prompt_embeds': torch.Size([1, 77, 2048]), 'negative_pooled_prompt_embeds': torch.Size([1, 1280]), 'guidance_scale': 6, 'generator': 'cuda:[1430618317]', 'num_inference_steps': 25, 'eta': 1.0, 'guidance_rescale': 0, 'denoising_end': None, 'output_type': 'latent', 'width': 512, 'height': 512, 'parser': 'native'}
2025-10-10 20:22:06,148 | PC | sd | INFO | processing_diffusers | Processing modifiers: unapply
2025-10-10 20:22:06,350 | PC | sd | DEBUG | installer | Setting decode: component=vae {'slicing': True, 'tiling': False}
2025-10-10 20:22:09,021 | PC | sd | DEBUG | processing_vae | Decode: vae="liquid111vae_sdxl9745VAE_for_mmmmilk" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 64, 64]:cuda:0:torch.bfloat16 time=2.670
2025-10-10 20:22:09,038 | PC | sd | INFO | images | Save: image="outputs\text\02673-2025-10-10-PDXL CyberRealistic Pony v12.7-1430618317.jpg" type=JPEG width=512 height=512 size=69657
2025-10-10 20:22:09,038 | PC | sd | DEBUG | processing | Processing: batch=2 total=2 progress=1.00
2025-10-10 20:22:09,040 | PC | sd | DEBUG | sd_samplers | Sampler: "DPM++ 2M" class=DPMSolverMultistepScheduler config={'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'solver_order': 2, 'prediction_type': 'epsilon', 'dynamic_thresholding_ratio': 0.995, 'sample_max_value': 1.0, 'algorithm_type': 'dpmsolver++', 'solver_type': 'midpoint', 'lower_order_final': True, 'use_karras_sigmas': True, 'flow_shift': 1.0, 'final_sigmas_type': 'zero', 'lambda_min_clipped': -inf, 'timestep_spacing': 'linspace', 'steps_offset': 0, 'time_shift_type': 'exponential'}
2025-10-10 20:22:09,042 | PC | sd | INFO | processing_diffusers | Processing modifiers: apply
2025-10-10 20:22:09,050 | PC | sd | INFO | processing_args | Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=2/2x1 set={'prompt_embeds': torch.Size([1, 77, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]), 'negative_prompt_embeds': torch.Size([1, 77, 2048]), 'negative_pooled_prompt_embeds': torch.Size([1, 1280]), 'guidance_scale': 6, 'generator': 'cuda:[1430618318]', 'num_inference_steps': 25, 'eta': 1.0, 'guidance_rescale': 0, 'denoising_end': None, 'output_type': 'latent', 'width': 512, 'height': 512, 'parser': 'native'}
2025-10-10 20:22:13,371 | PC | sd | INFO | processing_diffusers | Processing modifiers: unapply
2025-10-10 20:22:13,380 | PC | sd | DEBUG | installer | Setting decode: component=vae {'slicing': True, 'tiling': False}
2025-10-10 20:22:14,444 | PC | sd | DEBUG | processing_vae | Decode: vae="liquid111vae_sdxl9745VAE_for_mmmmilk" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 64, 64]:cuda:0:torch.bfloat16 time=1.064
2025-10-10 20:22:14,555 | PC | sd | INFO | images | Save: image="outputs\text\02674-2025-10-10-PDXL CyberRealistic Pony v12.7-1430618318.jpg" type=JPEG width=512 height=512 size=70371
2025-10-10 20:22:14,563 | PC | sd | INFO | images | Save: grid="outputs\grids\02675-2025-10-10-PDXL CyberRealistic Pony v12.7-1430618317.jpg" type=JPEG width=1024 height=512 size=138697
2025-10-10 20:22:14,564 | PC | sd | INFO | processing | Processed: images=3 its=5.13 ops=['txt2img']
2025-10-10 20:22:14,565 | PC | sd | DEBUG | processing | Processed: timers={'total': 16.61, 'pipeline': 10.52, 'decode': 4.04, 'prompt': 0.98, 'move': 0.59, 'preview': 0.2, 'init': 0.14, 'gc': 0.07}
2025-10-10 20:22:14,567 | PC | sd | DEBUG | processing | Processed: memory={'ram': {'total': 31.78, 'used': 6.68, 'free': 25}, 'gpu': {'used': 2.4, 'total': 16.0, 'active': 0.17, 'peak': 9.42, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': ''}
```

### Backend

Diffusers

### Compute

nVidia CUDA

### Interface

Standard

### Branch

Master

### Model

StableDiffusion XL

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
but your log shows that they are changing? `violet` vs `red-violet`

> Apply wildcard: select="Color_Palettes\simplecolors" choice="violet" file="C:\Users\Owner\Documents\Stable Diffusion Models\wildcards\Color_Palettes\simplecolors.txt" choices=42  
> Apply wildcard: select="Color_Palettes\simplecolors" choice="red-violet" file="C:\Users\Owner\Documents\Stable Diffusion Models\wildcards\Color_Palettes\simplecolors.txt" choices=42

**Comment by epsilon7430** [comment]
Yes, however, the two output images and their metadata show only "violet", so something seems to be happening behind the scenes to use only the first wildcard.  Previous tests using other wildcard sets exhibit the same behaviour.  Thanks

**Comment by vladmandic** [comment]
i just tried both batch-size and batch-count and verified image metadata in both ui and by dumping it from file manually  
i still dont see a problem - each image in all cases had a different and correct wildcard

**Comment by epsilon7430** [comment]
Unfortunate - don't know what to say.  Dislike the idea of having to do a full reinstall to see if this solves it, but I guess it might come to that.

**Comment by vladmandic** [comment]
full reinstall for this doesn't make a difference.
i'd suggest to try with default configuration - simply backup your config.json, remove it from sdnext folder and run tests.
when you're done, restore your old config.json

**Comment by epsilon7430** [comment]
I considered an extension conflict and found the issue was caused by sd-dynamic-prompts extension still being installed.  I removed that extensions folder from the extensions directory and native wildcard support behaves normally.

Note: I found I could not simply disable that extension - doing so marks it disabled in config.json but it was still activated on restart (and checked as active in extensions panel).

**Comment by vladmandic** [comment]
i'll check why it cant be disabled via ui, that should work, but i haven't touched that part of the code in ages.
glad you found the root cause.
