### ISSUE TITLE
[Issue]: Using CPU only Torch, Torch reports CUDA not available

### ISSUE THREAD

**Issue by stidgeridoo** [vladmandic/automatic#436]
### Issue Description

Version: 98adfb31 Sun Apr 23 11:50:30 2023 -0400

A fresh install running webui.bat results in the outputs in the title,  I cannot generate images and receive the following error when trying 'RuntimeError: "LayerNormKernelImpl" not implemented for 'Half''

20:45:15-298254 INFO     Version: 98adfb31 Sun Apr 23 11:50:30 2023 -0400
20:45:15-345125 INFO     Using CPU-only Torch

20:46:36-423584 INFO     Torch 2.0.0+cpu
20:46:36-432800 WARNING  Torch repoorts CUDA not available

### Version Platform Description

Version: 98adfb31 Sun Apr 23 11:50:30 2023 -0400

GPU is Nvidia A100 40gb, OS is Win10 22H2.

**Comment by AlUlkesh** [comment]
I've seen this happen, when the pip cache was messed up. Try uninstalling and clearing the cache first. For example like this:
```
venv\Scripts\activate.bat
pip uninstall torch torchvision torchaudio
pip cache purge
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

**Comment by vladmandic** [comment]
can you run `nvidia-smi` and what is the output?
that is standard command for all systems with nvidia drivers installed. if that command is not detected, setup will install cpu-only version of torch.

**Comment by Lone118** [comment]
Same issue but with my 6700 XT.

Tried the suggestion to unsinstall and reinstall torch with no change. Not a pro so I just entered it in cmd but dunno what I am supposed to do with activate.bat.

**Comment by vladmandic** [comment]
> for AMD, setup checks if `rocminfo` is present and available. if you try to run it manually, what do you get? if its not in path, add it to path.

**Comment by Lone118** [comment]
Sorry, I am just an Artist. As far as I know I don´t have Rocm or even know how to run it manually.

**Comment by vladmandic** [comment]
`rocminfo` is utility installed when you install AMD display drivers. just type it in command prompt and see what you get. if it doesn't work, update your drivers.

**Comment by Lone118** [comment]
My Drivers are up to date. Typing Rocminfo in cmd is just telling me that it can´t be found

**Comment by vladmandic** [comment]
@Lone118 you're on Windows? AMD does not have ROCm support for Windows just yet, its being worked on. As such, there is no GPU acceleration for AMD on Windows as of today. So installer installs Torch for CPU.

**Comment by Lone118** [comment]
Yes, I am on Windows. Okay, in that case I am sorry for wasting your time.

I am getting an Error though when I try to generate something. Should I make a new Thread for that?

**Comment by feedxongkhoc** [comment]
i have some issue like this, but i dont have gpu. so CPU-only touch  work for me right but it not . usually just put --no-half in COMMANDLINE_ARGS and everything will be fine, but this time it no working (sorry for my terrible english )
![image](https://user-images.githubusercontent.com/54738326/234089702-9ae1c005-cbdc-4faf-a0ab-960ce86ff6b6.png)

**Comment by vladmandic** [comment]
@Lone118 yes, but please read through AMD thread first - its quite long.

@feedxongkhoc this issue is about specific nvidia gpu not detected, really not sure how is this relevant? i'm stopping providing answers on unrelated questions that hijaack valid issues.

**Comment by feedxongkhoc** [comment]
@vladmandic ok thanks

**Comment by evanerichards** [comment]
For what it's worth, I have this same problem. I'm on a 3090 GPU

```
16:38:16-513535 INFO     Python 3.10.6 on Windows
16:38:16-773604 INFO     Version: dbdef787 Mon Apr 24 14:11:19 2023 -0400
16:38:17-090095 INFO     Latest published version: 20b64aad7b02f717aebd41c3d25cf335d4e0ed43 2023-04-24T20:16:52Z
16:38:17-094096 INFO     nVidia toolkit detected
16:38:17-670939 INFO     Torch 1.12.1+cpu
16:38:17-674939 WARNING  Torch repoorts CUDA not available
```

**Comment by vladmandic** [comment]
@evanerichards

no, its NOT the same problem.

> nVidia toolkit detected
> Torch 1.12.1+cpu

you have gpu correctly detected, but you have wrong torch installed from who knows when.
and its ancient (1.12???).
installer will not force change torch if torch is already present on the system as it assumes user choose it for a reason.
in your case, uninstall torch and then webui will install best possible one automatically.

**Comment by evanerichards** [comment]
> @evanerichards
> no, its NOT the same problem.

Sorry, I'm kind of newb. It seemed like the same problem the OP mentioned.

> in your case, uninstall torch and then webui will install best possible one automatically.
Ok. Thanks!

**Comment by vladmandic** [comment]
@qpl23 thats good to know - that's why i rely on community guidance on that - see #217 
i've added the path as you suggested:
```python
elif shutil.which('rocminfo') is not None or os.path.exists('/opt/rocm/bin/rocminfo'):
```

**Comment by stidgeridoo** [comment]
> can you run `nvidia-smi` and what is the output? that is standard command for all systems with nvidia drivers installed. if that command is not detected, setup will install cpu-only version of torch.

Solved!

nvidia-smi was not detected, so I added C:\Program Files\NVIDIA Corporation\NVSMI to my PATH. Reinstalled and it's now working.

**Comment by vladmandic** [comment]
That's a weird path, but then again, I've never seen A100 on Windows. What drivers are you using?

**Comment by stidgeridoo** [comment]
NVIDIA-SMI 472.50       Driver Version: 472.50       CUDA Version: 11.4
