### ISSUE TITLE
[Issue]: Monitor goes black & PC hardware goes into overdrive after generating 2+ images in a row

### ISSUE THREAD

**Issue by CurseWave** [vladmandic/automatic#4363]
### Issue Description

Hello; thank you for your time. I've searched through issues and didn't find a close match to the behavior. 

In the process of troubleshooting another issue, I deleted my config.json to test with default settings. With this current set-up (minimal changes to default settings), I run into an issue where an image generation will be interrupted; my monitors go black (maybe a display server crash) and my hardware starts spinning at much greater speed than usual (it sounds like a vacuum going off). This state requires a manual shutdown of the PC, there is no feedback of any kind to confirm that the PC is operating as normal but with displays turned off. 

Repro steps: 
1. Enter txt2img minimal prompt for testing (disable all extensions, disable refine, disable detailer)
2. Load SDXL model (I was testing with: https://civitai.com/models/1560668/dutch)
3. Generate multiple images

Observed results: 
PC monitors turn off, computer revs like mad (technical term), with fans spinning much faster than when using any software including SD Next. 

Note: 
- Please find attached logs of app + journalctl output of my system before the event. 

### Version Platform Description

PC information:

[Journalctl_last_Boot.md](https://github.com/user-attachments/files/23371867/Journalctl_last_Boot.md)
[12:07.md](https://github.com/user-attachments/files/23371866/12.07.md)

    Arch Linux
    AMD Ryzen 7 5800X3D 8-Core Processor
    64 GB RAM
    AMD Radeon RX 6950 XT (16384MB)

Software information
    SD Next (latest main version)
    Current branch: master
    Current version: 2025-11-02 hash a0b7f0319

Browser information
    Firefox 
    Version 144.0.2 (64-bit)

### Relevant log output

```shell
Activate python venv: /home/FullMoon/SDNext/venv
Launch: venv/bin/python3
12:07:06-334039 INFO     Starting SD.Next                                                                                                                                                                                            
12:07:06-336256 INFO     Logger: file="/home/FullMoon/SDNext/sdnext.log" level=DEBUG host="LunarRevel" size=77 mode=create                                                                                                           
12:07:06-337052 INFO     Python: version=3.13.0 platform=Linux bin="/home/FullMoon/SDNext/venv/bin/python3" venv="/home/FullMoon/SDNext/venv"                                                                                        
12:07:06-337766 WARNING  Python experimental: 3.13.0                                                                                                                                                                                 
12:07:06-360072 INFO     Version: app=sd.next updated=2025-11-02 hash=a0b7f0319 branch=master url=https://github.com/vladmandic/sdnext/tree/master ui=main                                                                           
12:07:06-591418 INFO     Version: app=sd.next latest=2025-11-02T22:31:27Z hash=a0b7f031 branch=master                                                                                                                                
12:07:06-593241 INFO     Platform: arch=x86_64 cpu= system=Linux release=6.17.7-arch1-1 python=3.13.0 locale=('en_US', 'UTF-8') docker=False                                                                                         
12:07:06-594291 DEBUG    Packages: prefix=venv site=['venv/lib/python3.13/site-packages']                                                                                                                                            
12:07:06-595304 INFO     Args: ['--use-rocm', '--debug']                                                                                                                                                                             
12:07:06-595922 DEBUG    Setting environment tuning                                                                                                                                                                                  
12:07:06-596558 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"                                                                                                                                  
12:07:06-597875 INFO     Verifying torch installation                                                                                                                                                                                
12:07:06-598441 DEBUG    Torch overrides: cuda=False rocm=True ipex=False directml=False openvino=False zluda=False                                                                                                                  
12:07:06-716320 INFO     ROCm: AMD toolkit detected                                                                                                                                                                                  
12:07:06-717164 INFO     ROCm: agents=['gfx1030']                                                                                                                                                                                    
12:07:06-717910 INFO     ROCm: version=6.4, using agent gfx1030                                                                                                                                                                      
12:07:06-718686 INFO     ROCm: HSA_OVERRIDE_GFX_VERSION auto config skipped: device=gfx1030 version=10.3.0                                                                                                                           
12:07:15-291641 INFO     Torch backend: version="2.9.0+rocm6.4" type=ROCm HIP=6.4.43484-123eb5128                                                                                                                                    
12:07:15-294100 INFO     Torch detected: gpu="AMD Radeon Graphics" vram=16368 arch=(10, 3) cores=40                                                                                                                                  
12:07:15-360200 INFO     Install: verifying requirements                                                                                                                                                                             
12:07:15-366503 DEBUG    Timestamp repository update time: Sun Nov  2 17:31:27 2025                                                                                                                                                  
12:07:15-367400 INFO     Startup: standard                                                                                                                                                                                           
12:07:15-367945 INFO     Verifying submodules                                                                                                                                                                                        
12:07:15-540740 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main                                                                                                                                              
12:07:15-552939 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main                                                                                                                                           
12:07:15-564178 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main                                                                                                                       
12:07:15-564851 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / main                                                                                                                                                    
12:07:15-574112 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master                                                                                                                                     
12:07:15-585446 DEBUG    Git detached head detected: folder="wiki" reattach=master                                                                                                                                                   
12:07:15-586243 DEBUG    Git submodule: wiki / master                                                                                                                                                                                
12:07:15-662727 DEBUG    Installed packages: 252                                                                                                                                                                                     
12:07:15-663486 DEBUG    Extensions all: ['sdnext-modernui', 'sd-extension-chainner', 'sd-webui-agent-scheduler', 'sd-extension-system-info', 'Lora', 'stable-diffusion-webui-rembg']                                                
12:07:15-719837 DEBUG    Extension installer: builtin=True file="/home/FullMoon/SDNext/extensions-builtin/sd-webui-agent-scheduler/install.py"                                                                                       
12:07:15-808499 DEBUG    Extension installer: builtin=True file="/home/FullMoon/SDNext/extensions-builtin/stable-diffusion-webui-rembg/install.py"                                                                                   
12:07:15-838927 DEBUG    Extensions all: ['sd-dynamic-prompts']                                                                                                                                                                      
12:07:15-840051 DEBUG    Extension installer: builtin=False file="/home/FullMoon/SDNext/extensions/sd-dynamic-prompts/install.py"                                                                                                    
12:07:15-965227 INFO     Extensions enabled: ['sdnext-modernui', 'sd-extension-chainner', 'sd-webui-agent-scheduler', 'sd-extension-system-info', 'Lora', 'stable-diffusion-webui-rembg', 'sd-dynamic-prompts']                      
12:07:15-994917 INFO     Install: verifying requirements                                                                                                                                                                             
12:07:15-998436 DEBUG    Setup complete without errors: 1762362436                                                                                                                                                                   
12:07:16-000707 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}                                                                                                                                           
12:07:16-001533 INFO     Installer time: total=10.31 torch=8.70 git=0.30 submodules=0.27 latest=0.25 base=0.17 sd-dynamic-prompts=0.13                                                                                               
12:07:16-002466 INFO     Command line args: ['--use-rocm', '--debug'] use_rocm=True args=[]                                                                                                                                          
12:07:16-003175 DEBUG    Env flags: []                                                                                                                                                                                               
12:07:16-003699 DEBUG    Linker flags: preload="None" path=":/home/FullMoon/SDNext/venv/lib/"                                                                                                                                        
12:07:16-004307 DEBUG    Starting module: <module 'webui' from '/home/FullMoon/SDNext/webui.py'>                                                                                                                                     
12:07:23-545478 DEBUG    System: cores=16 affinity=16 threads=8                                                                                                                                                                      
12:07:23-549986 INFO     Torch: torch==2.9.0+rocm6.4 torchvision==0.24.0+rocm6.4                                                                                                                                                     
12:07:23-550673 INFO     Packages: diffusers==0.36.0.dev0 transformers==4.57.1 accelerate==1.11.0 gradio==3.43.2 pydantic==1.10.21 numpy==2.1.2 cv2==4.12.0                                                                          
12:07:24-307021 DEBUG    ONNX: version=1.23.2, available=['AzureExecutionProvider', 'CPUExecutionProvider']                                                                                                                          
12:07:24-369402 DEBUG    State initialized: id=140576135378464                                                                                                                                                                       
12:07:24-371452 INFO     Device detect: memory=16.0 default=balanced                                                                                                                                                                 
12:07:24-376739 DEBUG    Read: file="/home/FullMoon/SDNext/config.json" json=5 bytes=277 time=0.000 fn=<module>:load                                                                                                                 
12:07:24-378073 INFO     Engine: backend=Backend.DIFFUSERS compute=rocm device=cuda attention="Scaled-Dot-Product" mode=no_grad                                                                                                      
12:07:24-379128 DEBUG    Read: file="html/reference.json" json=136 bytes=65095 time=0.000 fn=_call_with_frames_removed:<module>                                                                                                      
12:07:24-380095 DEBUG    Torch attention: type="sdpa" opts=['Flash attention', 'Memory attention', 'Math attention', 'Dynamic attention']                                                                                            
12:07:24-381461 DEBUG    Torch attention installed: flashattn=False sageattention=False                                                                                                                                              
12:07:24-382101 DEBUG    Torch attention status: flash=False flash3=False aiter=False sage=False flex=True npu=False xla=False xformers=False                                                                                        
12:07:27-132264 DEBUG    Triton: pass=True fn=<module>:set_cuda_params time=2.37                                                                                                                                                     
12:07:27-133398 INFO     Torch parameters: backend=rocm device=cuda config=Auto dtype=torch.float16 context=no_grad nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False, True] fp16=pass bf16=fail          
                         triton=pass optimization="Scaled-Dot-Product"                                                                                                                                                               
12:07:27-134658 INFO     Device: device=AMD Radeon Graphics n=1 hip=6.4.43484-123eb5128                                                                                                                                              
12:07:27-233898 DEBUG    Entering start sequence                                                                                                                                                                                     
12:07:27-236470 DEBUG    Initializing                                                                                                                                                                                                
12:07:27-240850 DEBUG    Read: file="metadata.json" json=184 bytes=926779 time=0.004 fn=initialize:init_metadata                                                                                                                     
12:07:27-241798 DEBUG    Read: file="cache.json" json=2 bytes=19245 time=0.000 fn=initialize:init_cache                                                                                                                              
12:07:27-270436 INFO     Available VAEs: path="models/VAE" items=1                                                                                                                                                                   
12:07:27-271255 INFO     Available UNets: path="models/UNET" items=0                                                                                                                                                                 
12:07:27-272036 INFO     Available TEs: path="models/Text-encoder" items=0                                                                                                                                                           
12:07:27-273854 INFO     Available Models: safetensors="models/Stable-diffusion":10 diffusers="models/Diffusers":1 reference=136 items=11 time=0.00                                                                                  
12:07:27-279218 INFO     Available LoRAs: path="models/Lora" items=4 folders=2 time=0.00                                                                                                                                             
12:07:27-284442 INFO     Available Styles: path="models/styles" items=288 time=0.00                                                                                                                                                  
12:07:27-322864 INFO     Available Detailer: path="models/yolo" items=12 downloaded=8                                                                                                                                                
12:07:27-323687 DEBUG    Extensions: disabled=['Lora']                                                                                                                                                                               
12:07:27-324283 INFO     Load extensions                                                                                                                                                                                             
12:07:27-705979 INFO     Extension: script='extensions-builtin/sd-webui-agent-scheduler/scripts/task_scheduler.py' Using sqlite file: extensions-builtin/sd-webui-agent-scheduler/task_scheduler.sqlite3                             
12:07:27-732643 DEBUG    Extensions init time: total=0.41 sd-webui-agent-scheduler=0.28                                                                                                                                              
12:07:28-252008 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2640 time=0.000 fn=__init__:__init__                                                                                                                          
12:07:28-253288 DEBUG    Read: file="extensions-builtin/sd-extension-chainner/models.json" json=25 bytes=2803 time=0.000 fn=__init__:find_scalers                                                                                    
12:07:28-254482 DEBUG    Available chaiNNer: path="models/chaiNNer" defined=25 discovered=0 downloaded=2                                                                                                                             
12:07:28-256663 INFO     Available Upscalers: items=76 downloaded=12 user=0 time=0.52 types=['None', 'Resize', 'Latent', 'AsymmetricVAE', 'WanUpscale', 'DCC', 'VIPS', 'ChaiNNer', 'SeedVR', 'Diffusion', 'ESRGAN', 'SCUNet',        
                         'RealESRGAN', 'AuraSR', 'SwinIR']                                                                                                                                                                           
12:07:28-286382 INFO     Networks: type="video" engines=11 models=54 errors=0 time=0.03                                                                                                                                              
12:07:28-288365 INFO     Huggingface: transfer=rust parallel=True direct=False token="None" cache="models/huggingface" init                                                                                                          
12:07:28-327735 WARNING  Cache location changed: previous="/home/FullMoon/.cache/huggingface/hub" size=189828 MB                                                                                                                     
12:07:28-328543 DEBUG    Huggingface: cache="models/huggingface" size=0 MB                                                                                                                                                           
12:07:28-329185 DEBUG    UI start sequence                                                                                                                                                                                           
12:07:28-331421 INFO     UI locale: name="Auto"                                                                                                                                                                                      
12:07:28-332081 INFO     UI theme: type=Modern name="Default" available=35                                                                                                                                                           
12:07:28-332860 DEBUG    UI theme: css="extensions-builtin/sdnext-modernui/themes/Default.css" base="['base.css', 'timesheet.css']" user="None"                                                                                      
12:07:28-335030 DEBUG    UI initialize: tab=txt2img                                                                                                                                                                                  
12:07:28-371135 DEBUG    Read: file="html/reference.json" json=136 bytes=65095 time=0.000 fn=list_items:list_reference                                                                                                               
12:07:28-376308 DEBUG    Networks: type="reference" items={'total': 136, 'ready': 1, 'hidden': 0, 'experimental': 0, 'base': 87, 'distilled': 17, 'quantized': 15, 'community': 15}                                                  
12:07:28-381586 DEBUG    Networks: type="model" items=145 subfolders=9 tab=txt2img folders=['models/Stable-diffusion', 'models/Reference', '/home/FullMoon/SDNext/models/Stable-diffusion'] list=0.02 thumb=0.00 desc=0.00 info=0.01 
                         workers=12                                                                                                                                                                                                  
12:07:28-384261 DEBUG    Networks: type="lora" items=4 subfolders=1 tab=txt2img folders=['models/Lora'] list=0.01 thumb=0.00 desc=0.00 info=0.00 workers=12                                                                          
12:07:28-392517 DEBUG    Networks: type="style" items=288 subfolders=3 tab=txt2img folders=['models/styles', 'html'] list=0.01 thumb=0.01 desc=0.00 info=0.00 workers=12                                                             
12:07:28-395249 DEBUG    Networks: type="wildcards" items=0 subfolders=1 tab=txt2img folders=['models/wildcards'] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=12                                                                
12:07:28-396614 DEBUG    Networks: type="embedding" items=3 subfolders=1 tab=txt2img folders=['models/embeddings'] list=0.01 thumb=0.01 desc=0.00 info=0.00 workers=12                                                               
12:07:28-398010 DEBUG    Networks: type="vae" items=1 subfolders=1 tab=txt2img folders=['models/VAE'] list=0.01 thumb=0.01 desc=0.00 info=0.00 workers=12                                                                            
12:07:28-399258 DEBUG    Networks: type="history" items=0 subfolders=1 tab=txt2img folders=[] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=12                                                                                    
12:07:28-680346 DEBUG    UI initialize: tab=img2img                                                                                                                                                                                  
12:07:28-962963 DEBUG    UI initialize: tab=control models="models/control"                                                                                                                                                          
12:07:29-210839 DEBUG    Script: fn="extensions-builtin/sd-webui-agent-scheduler/scripts/task_scheduler.py" type=control skip                                                                                                        
12:07:29-211727 DEBUG    Script: fn="extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py" type=control skip                                                                                                                   
12:07:29-485752 DEBUG    UI initialize: tab=video                                                                                                                                                                                    
12:07:29-605669 DEBUG    UI initialize: tab=process                                                                                                                                                                                  
12:07:29-657920 DEBUG    UI initialize: tab=caption                                                                                                                                                                                  
12:07:29-737584 DEBUG    UI initialize: tab=models                                                                                                                                                                                   
12:07:29-818604 DEBUG    UI initialize: tab=gallery                                                                                                                                                                                  
12:07:29-856138 DEBUG    Read: file="ui-config.json" json=6 bytes=874 time=0.000 fn=__init__:read_from_file                                                                                                                          
12:07:29-857275 DEBUG    UI initialize: tab=settings                                                                                                                                                                                 
12:07:30-437013 DEBUG    Settings: sections=25 settings=400/621 quicksettings=1                                                                                                                                                      
12:07:30-492961 DEBUG    UI initialize: tab=info                                                                                                                                                                                     
12:07:30-513847 DEBUG    UI initialize: tab=extensions                                                                                                                                                                               
12:07:30-573599 DEBUG    Extension list: processed=413 installed=6 enabled=5 disabled=1 visible=413 hidden=0                                                                                                                         
12:07:31-313899 DEBUG    Root paths: ['/home/FullMoon/SDNext', 'models']                                                                                                                                                             
12:07:31-410573 INFO     Local URL: http://127.0.0.1:7860/                                                                                                                                                                           
12:07:31-411574 INFO     API docs: http://127.0.0.1:7860/docs                                                                                                                                                                        
12:07:31-412318 INFO     API redocs: http://127.0.0.1:7860/redocs                                                                                                                                                                    
12:07:31-413603 DEBUG    API middleware: [<class 'starlette.middleware.base.BaseHTTPMiddleware'>, <class 'starlette.middleware.gzip.GZipMiddleware'>]                                                                                
12:07:31-414448 DEBUG    API initialize                                                                                                                                                                                              
12:07:31-655751 INFO     [AgentScheduler] Task queue is empty                                                                                                                                                                        
12:07:31-656568 INFO     [AgentScheduler] Registering APIs                                                                                                                                                                           
12:07:31-815968 DEBUG    Scripts setup: time=0.559 ['XYZ Grid:0.061', 'IP Adapters:0.052', 'Prompt enhance:0.033', 'Mixture-of-Diffusers: Tile Control:0.03']                                                                        
12:07:31-817259 DEBUG    Model metadata: file="metadata.json" no changes                                                                                                                                                             
12:07:31-817894 INFO     Model: autoload=True selected="dutch_v30 [00a673d6c2]"                                                                                                                                                      
12:07:31-819271 DEBUG    Model requested: fn=threading.py:run:<lambda>                                                                                                                                                               
12:07:31-820295 DEBUG    Search model: name="dutch_v30 [00a673d6c2]" matched="/home/FullMoon/SDNext/models/Stable-diffusion/dutch_v30.safetensors" type=alias                                                                        
12:07:31-821231 INFO     Load model: select="dutch_v30 [00a673d6c2]"                                                                                                                                                                 
12:07:31-823095 INFO     Autodetect model: detect="Stable Diffusion XL" class=StableDiffusionXLPipeline file="/home/FullMoon/SDNext/models/Stable-diffusion/dutch_v30.safetensors"                                                   
12:07:31-824153 DEBUG    Cache clear                                                                                                                                                                                                 
12:07:32-850260 DEBUG    Setting model: pipeline=StableDiffusionXLPipeline config={'low_cpu_mem_usage': True, 'torch_dtype': torch.float16, 'load_connected_pipeline': True, 'extract_ema': False, 'config': 'configs/sdxl',         
                         'use_safetensors': True, 'cache_dir': 'models/huggingface'}                                                                                                                                                 
12:07:35-409752 INFO     Network load: type=embeddings loaded=3 skipped=0 time=2.55                                                                                                                                                  
12:07:35-410828 DEBUG    Setting model: component=vae {'slicing': True, 'tiling': False}                                                                                                                                             
12:07:35-411562 DEBUG    Setting model: attention="Scaled-Dot-Product"                                                                                                                                                               
12:07:35-419484 INFO     Offload: type=balanced op=init watermark=0.2-0.6 gpu=3.20-9.60:16.00 cpu=63.000 limit=0.00 always=[] never=[] pre=True streams=False                                                                        
12:07:35-437921 DEBUG    Module: name=unet cls=UNet2DConditionModel size=4.782 params=2567463684 quant=None                                                                                                                          
12:07:35-441028 DEBUG    Module: name=text_encoder_2 cls=CLIPTextModelWithProjection size=1.294 params=694810880 quant=None                                                                                                          
12:07:35-443011 DEBUG    Module: name=text_encoder cls=CLIPTextModel size=0.229 params=123151104 quant=None                                                                                                                          
12:07:35-445377 DEBUG    Module: name=vae cls=AutoencoderKL size=0.156 params=83653863 quant=None                                                                                                                                    
12:07:35-446197 INFO     Model class=StableDiffusionXLPipeline modules=4 size=6.462                                                                                                                                                  
12:07:35-448570 INFO     Load model: family=sdxl time={'total': 3.63, 'embeddings': 2.55, 'load': 1.03} native=1024 memory={'ram': {'total': 62.71, 'rss': 4.78, 'used': 9.81, 'free': 44.97, 'avail': 52.9, 'buffers': 0.36,        
                         'cached': 8.28}, 'gpu': {'used': 0.24, 'total': 15.98, 'active': 0.0, 'peak': 0.0, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': 'Load model'}                                                                 
12:07:35-451308 DEBUG    Script init: ['wildcards_tab.py:ui_tabs=0.06', 'system-info.py:app_started=0.09', 'task_scheduler.py:app_started=0.16']                                                                                     
12:07:35-452285 INFO     Startup time: total=49.14 launch=10.55 loader=9.90 installer=9.90 libraries=4.04 checkpoint=3.63 gradio=3.62 torch=2.73 ui-extensions=0.70 bnb=0.66 upscalers=0.53 extensions=0.41 ui-control=0.38          
                         ui-networks=0.31 app-started=0.26 ui-txt2img=0.26 ui-img2img=0.24 ui-defaults=0.18 api=0.14 ui-models=0.12                                                                                                  
12:07:35-455702 DEBUG    Save: file="/home/FullMoon/SDNext/config.json" json=5 bytes=277 time=0.005                                                                                                                                  
12:08:12-650175 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/motd 127.0.0.1 0.0464                                                                                                                                         
12:08:20-502621 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/sd-models 127.0.0.1 0.0023                                                                                                                                    
12:08:21-584192 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/version 127.0.0.1 0.001                                                                                                                                       
12:08:21-711565 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (X11; Linux x86_64; rv:144.0) Gecko/20100101 Firefox/144.0                                                                                    
12:08:21-713475 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/start 127.0.0.1 0.0031                                                                                                                                        
12:08:21-737764 DEBUG    UI: connected                                                                                                                                                                                               
12:08:21-738873 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/version 127.0.0.1 0.002                                                                                                                                       
12:08:22-585073 INFO     UI: ready time=10062                                                                                                                                                                                        
12:08:59-411894 DEBUG    Sampler: "Euler a" class=EulerAncestralDiscreteScheduler config={'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'prediction_type': 'epsilon',     
                         'timestep_spacing': 'linspace', 'steps_offset': 0}                                                                                                                                                          
12:08:59-419684 INFO     Processing modifiers: apply                                                                                                                                                                                 
12:08:59-454249 DEBUG    Tokenizer: words=49526 file="configs/sdxl/tokenizer/vocab.json"                                                                                                                                             
12:09:00-711386 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=1/1x1 set={'prompt_embeds': torch.Size([1, 154, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]), 'negative_prompt_embeds':           
                         torch.Size([1, 154, 2048]), 'negative_pooled_prompt_embeds': torch.Size([1, 1280]), 'guidance_scale': 6, 'generator': 'cuda:[1947590414]', 'num_inference_steps': 20, 'eta': 1.0, 'guidance_rescale': 0,    
                         'denoising_end': None, 'output_type': 'latent', 'width': 960, 'height': 1088, 'parser': 'native'}                                                                                                           
12:09:17-701313 INFO     Processing modifiers: unapply                                                                                                                                                                               

12:09:17-710358 DEBUG    Decode: type="taesd" variant="TAESD 1.3 Mocha Croissant" fn="models/TAESD/taesd_13_decoder_sdxl.pth" layers=3 load                                                                                          
12:09:17-795718 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}                                                                                                                                            
12:09:19-849962 DEBUG    Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 136, 120]:cuda:0 dtype=torch.float16 time=2.054                                                                         
12:09:19-876329 INFO     Save: image="outputs/text/00002-2025-11-05-dutch_v30.jpg" type=JPEG width=960 height=1088 size=148553                                                                                                       
12:09:19-877753 INFO     Processed: images=1 its=0.98 ops=['txt2img']                                                                                                                                                                
12:09:19-878702 DEBUG    Processed: timers={'total': 37.75, 'pipeline': 18.27, 'callback': 10.76, 'onload': 3.13, 'decode': 2.14, 'offload': 1.35, 'prompt': 1.27, 'move': 0.65}                                                     
12:09:19-879852 DEBUG    Processed: memory={'ram': {'total': 62.71, 'rss': 10.67, 'used': 17.08, 'free': 31.55, 'avail': 45.63, 'buffers': 0.36, 'cached': 14.15}, 'gpu': {'used': 1.14, 'total': 15.98, 'active': 0.2, 'peak': 8.17,
                         'retries': 0, 'oom': 0, 'swap': 0}, 'job': ''}                                                                                                                                                              
12:09:35-834068 TRACE    Server: alive=True requests=91 memory=16.71/62.71 status='idle' task='' timestamp=None current='' id='' job=0 jobs=0 total=11 step=0 steps=0 queued=0 uptime=132 elapsed=15.95 eta=None progress=0          
12:11:07-450618 DEBUG    Sampler: "Euler a" class=EulerAncestralDiscreteScheduler config={'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'prediction_type': 'epsilon',     
                         'timestep_spacing': 'linspace', 'steps_offset': 0}                                                                                                                                                          
12:11:07-453028 INFO     Processing modifiers: apply                                                                                                                                                                                 
12:11:07-873846 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=1/1x1 set={'prompt_embeds': torch.Size([1, 154, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]), 'negative_prompt_embeds':           
                         torch.Size([1, 154, 2048]), 'negative_pooled_prompt_embeds': torch.Size([1, 1280]), 'guidance_scale': 6, 'generator': 'cuda:[3282035590]', 'num_inference_steps': 20, 'eta': 1.0, 'guidance_rescale': 0,    
                         'denoising_end': None, 'output_type': 'latent', 'width': 960, 'height': 1088, 'parser': 'native'}                                                                                                           
12:11:22-334428 INFO     Processing modifiers: unapply                                                                                                                                                                               
12:11:22-387826 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}                                                                                                                                            
12:11:23-095263 DEBUG    Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 136, 120]:cuda:0 dtype=torch.float16 time=0.707                                                                         
12:11:23-377011 INFO     Save: image="outputs/text/00003-2025-11-05-dutch_v30.jpg" type=JPEG width=960 height=1088 size=164571                                                                                                       
12:11:23-378465 INFO     Processed: images=1 its=1.26 ops=['txt2img']                                                                                                                                                                
12:11:23-379361 DEBUG    Processed: timers={'total': 28.73, 'pipeline': 14.87, 'callback': 11.16, 'decode': 1.02, 'offload': 0.73, 'prompt': 0.41, 'onload': 0.32, 'move': 0.1}                                                      
12:11:23-380669 DEBUG    Processed: memory={'ram': {'total': 62.71, 'rss': 12.81, 'used': 18.82, 'free': 29.76, 'avail': 43.89, 'buffers': 0.36, 'cached': 14.2}, 'gpu': {'used': 2.51, 'total': 15.98, 'active': 0.2, 'peak': 8.33, 
                         'retries': 0, 'oom': 0, 'swap': 0}, 'job': ''}                                                                                                                                                              
12:11:35-846806 TRACE    Server: alive=True requests=134 memory=18.75/62.71 status='idle' task='' timestamp=None current='' id='' job=0 jobs=0 total=20 step=0 steps=0 queued=0 uptime=252 elapsed=12.46 eta=None progress=0         
12:12:01-404974 DEBUG    Sampler: "Euler a" class=EulerAncestralDiscreteScheduler config={'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'prediction_type': 'epsilon',     
                         'timestep_spacing': 'linspace', 'steps_offset': 0}                                                                                                                                                          
12:12:01-406124 INFO     Processing modifiers: apply                                                                                                                                                                                 
12:12:01-808185 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=1/1x1 set={'prompt_embeds': torch.Size([1, 154, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]), 'negative_prompt_embeds':           
                         torch.Size([1, 154, 2048]), 'negative_pooled_prompt_embeds': torch.Size([1, 1280]), 'guidance_scale': 6, 'generator': 'cuda:[4212401360]', 'num_inference_steps': 20, 'eta': 1.0, 'guidance_rescale': 0,    
                         'denoising_end': None, 'output_type': 'latent', 'width': 960, 'height': 1088, 'parser': 'native'}                                                                                                           
12:12:16-657796 INFO     Processing modifiers: unapply                                                                                                                                                                               
12:12:16-731325 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}                                                                                                                                            
12:12:17-191797 DEBUG    Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 136, 120]:cuda:0 dtype=torch.float16 time=0.460                                                                         
12:12:17-476159 INFO     Save: image="outputs/text/00004-2025-11-05-dutch_v30.jpg" type=JPEG width=960 height=1088 size=157998                                                                                                       
12:12:17-477481 INFO     Processed: images=1 its=1.24 ops=['txt2img']                                                                                                                                                                
12:12:17-478351 DEBUG    Processed: timers={'total': 32.35, 'pipeline': 15.24, 'callback': 10.97, 'preview': 4.0, 'decode': 0.79, 'offload': 0.49, 'prompt': 0.39, 'onload': 0.31}                                                   
12:12:17-479727 DEBUG    Processed: memory={'ram': {'total': 62.71, 'rss': 12.86, 'used': 18.97, 'free': 29.52, 'avail': 43.74, 'buffers': 0.36, 'cached': 14.29}, 'gpu': {'used': 2.57, 'total': 15.98, 'active': 0.2, 'peak': 8.54,
                         'retries': 0, 'oom': 0, 'swap': 0}, 'job': ''}                                                                                                                                                              
12:12:44-019824 DEBUG    Sampler: "Euler a" class=EulerAncestralDiscreteScheduler config={'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'prediction_type': 'epsilon',     
                         'timestep_spacing': 'linspace', 'steps_offset': 0}                                                                                                                                                          
12:12:44-021181 INFO     Processing modifiers: apply                                                                                                                                                                                 
12:12:44-433699 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=1/1x1 set={'prompt_embeds': torch.Size([1, 154, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]), 'negative_prompt_embeds':           
                         torch.Size([1, 154, 2048]), 'negative_pooled_prompt_embeds': torch.Size([1, 1280]), 'guidance_scale': 6, 'generator': 'cuda:[2757103243]', 'num_inference_steps': 20, 'eta': 1.0, 'guidance_rescale': 0,    
                         'denoising_end': None, 'output_type': 'latent', 'width': 960, 'height': 1088, 'parser': 'native'}                                                                                                           
12:12:58-913843 INFO     Processing modifiers: unapply                                                                                                                                                                               
12:12:58-966899 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}                                                                                                                                            
12:12:59-436687 DEBUG    Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 136, 120]:cuda:0 dtype=torch.float16 time=0.470                                                                         
12:12:59-720212 INFO     Save: image="outputs/text/00005-2025-11-05-dutch_v30.jpg" type=JPEG width=960 height=1088 size=169016                                                                                                       
12:12:59-721620 INFO     Processed: images=1 its=1.27 ops=['txt2img']                                                                                                                                                                
12:12:59-722575 DEBUG    Processed: timers={'total': 28.25, 'pipeline': 14.88, 'callback': 11.19, 'decode': 0.78, 'offload': 0.49, 'prompt': 0.4, 'onload': 0.3}                                                                     
12:12:59-723875 DEBUG    Processed: memory={'ram': {'total': 62.71, 'rss': 12.93, 'used': 18.83, 'free': 29.63, 'avail': 43.88, 'buffers': 0.36, 'cached': 14.23}, 'gpu': {'used': 2.59, 'total': 15.98, 'active': 0.2, 'peak': 8.33,
                         'retries': 0, 'oom': 0, 'swap': 0}, 'job': ''}                                                                                                                                                              
12:13:36-210320 TRACE    Server: alive=True requests=203 memory=18.74/62.71 status='idle' task='' timestamp=None current='' id='' job=0 jobs=0 total=38 step=0 steps=0 queued=0 uptime=372 elapsed=36.48 eta=None progress=0
```

### Backend

Diffusers

### Compute

AMD ROCm

### Interface

ModernUI

### Branch

Master

### Model

StableDiffusion XL

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by CurseWave** [comment]
I'm not sure how useful this information is, but sharing an image output with meta data. 

A few notes about image generation: 
- This image was done with refine, detailer and scaled meaningfully. 
- This image took 3,5 minutes to generate, normally I can generate them in 30 seconds with similar data. I'm assuming I have to do some optimization tweaks on my machines.
- I repro'd issue upon starting a new gen after this one image

![Image](https://github.com/user-attachments/assets/8edf49f3-b400-40d9-85c5-bad0fed0534e)

**Comment by vladmandic** [comment]
this looks like a pretty bad behavior from amd gpu driver:

```log
Nov 05 11:20:37 LunarRevel kernel: INFO: task kworker/15:0:111 blocked for more than 122 seconds.
...
Nov 05 12:14:23 LunarRevel parsecd[2837]: radeonsi: error: ../mesa-25.2.6/src/gallium/drivers/radeonsi/radeon_vcn_dec.c:1414 rvcn_dec_dynamic_dpb_t2_message VCN - Can't allocate dpb buffer.
..
Nov 05 12:14:23 LunarRevel kernel: amdgpu 0000:2f:00.0: amdgpu: device lost from bus!
Nov 05 12:14:23 LunarRevel kernel: amdgpu 0000:2f:00.0: amdgpu: SMU: response:0xFFFFFFFF for index:40 param:0x00000000 message:AllowGfxOff?
Nov 05 12:14:23 LunarRevel kernel: amdgpu 0000:2f:00.0: amdgpu: Failed to enable gfxoff!
Nov 05 12:14:24 LunarRevel kernel: snd_hda_intel 0000:2f:00.1: Unable to change power state from D3hot to D0, device inaccessible
Nov 05 12:14:24 LunarRevel kwin_wayland[1007]: Pageflip timed out! This is a bug in the amdgpu kernel driver
Nov 05 12:14:24 LunarRevel kwin_wayland[1007]: Please report this at https://gitlab.freedesktop.org/drm/amd/-/issues
Nov 05 12:14:24 LunarRevel kwin_wayland[1007]: With the output of 'sudo dmesg' and 'journalctl --user-unit plasma-kwin_wayland --boot 0'
```

and yes, gpu basically unregisters itself from the system so your monitor goes blank with no input.
why? seems like there was a 2min timeout on some call. but instead of recovering, driver just dies.

also at the same time, there is 
```log
Nov 05 12:14:23 LunarRevel parsecd[2837]: [hevc @ 0x7fa82d481180] Failed to end picture decode issue: 1 (operation failed).
```
which is not sdnext call, it looks like gpu tried loading some hevc image and failed. not sure if its related, but could be due to very close timestamp.

btw, seems like you have 25.2.6 drivers, try updating?
other than what i just wrote, not much i can help with, this is amd gpu driver problem.

**Comment by vladmandic** [comment]
i've closed the issue as its not sdnext product issue, but feel free to post here and we can continue the thread, just not sure how much i can help.
if it turns out to be sdnext issue, i'll reopen.

**Comment by CurseWave** [comment]
Thanks Vlad, I'll take this to the appropriate platform. I initially thought that maybe sdnext was a trigger for another underlying issue with my set up, I wanted to rule out this theory before moving to the next report platform. I'll make sure to use this thread if new information emerge that involves sdnext.

**Comment by Disty0** [comment]
Do you have another GPU just to get video out?
I don't really know why but my RX 7900 XTX tends to crash often like your GPU for no apparent reason on regular desktop use if i have any monitor attached to it.
If use my Intel ARC A770 for video out, then everything is fine, RX 7900 XTX can achieve weeks to months of uptime without crashing when no monitor is attached to it.
I am using a pci-e riser, that adds some instability as well but not enough to explain why it crashes for no reason.

Also on Arch Linux with Gnome Wayland and Linux kernel 6.17.7-zen1-1-zen.

**Comment by CurseWave** [comment]
> Do you have another GPU just to get video out? I don't really know why but my RX 7900 XTX tends to crash often like your GPU for no apparent reason on regular desktop use if i have any monitor attached to it. If use my Intel ARC A770 for video out, then everything is fine, RX 7900 XTX can achieve weeks to months of uptime without crashing when no monitor is attached to it. I am using a pci-e riser, that adds some instability as well but not enough to explain why it crashes for no reason.
> 
> Also on Arch Linux with Gnome Wayland and Linux kernel 6.17.7-zen1-1-zen.

I think it's some weird interaction between my drivers, my display server and certain collection of apps that require a certain amount of processing power. 

I haven't done a detailed analysis, but I had multiple incidents of my displays crashing but my PC running as normal. These incidents are individually consistent - which is to say, if I start crashing, it will be like this ticket we're discussing. A very specific software triggering the issue when used a certain way. 

For instance, I can't use the "sleep" feature on my PC, it freezes my display seemingly without entering sleep mode. I'll get a PC hang when using ollama CLI for too many prompt or something. 

I've no clue what is going on. I theorize that the issue might because by any and all of the following:
- My recent removal of SWAP partition on my linux disk
- My display power management settings (I've set them to go to sleep after 1 minute of inactivity, I'm not sure how rugged the on/off management of displays really is)
- My display server struggling to jungle certain types of apps at the same time 
- Bad management of drivers (I'm wondering whether I have the best driver packages available for arch linux) 

Sorry I know this isn't very coherent or objective information, this troubleshooting is a bit overwhelming and I've yet to schedule up time to specifically parse all the information available. Just kind off brainstorming/sharing current state of affair on my investigation.

**Comment by vladmandic** [comment]
from a very cursory look, it seems that kernel timeouts on a thread and everything goes down the hill from there as driver never recovers and gpu basically disconnects.
i'd start with search for `amdgpu kworker blocked`, there are several hits that may be onto something.

**Comment by CurseWave** [comment]
Hello @vladmandic  (CC: @Disty0 ), coming back to this thread with a happy ending (knocking on wood). 

I'm sharing information on the off-chance that you guys might encounter another user with similar issues & to consult you to see whether you have fine-tuning suggestions for the fix I found. 

After a lot of troubleshooting with ChatGPT, I found one environment variable that can stabilize my sdnext install ( to my surprise). 

`export HSA_DISABLE_CACHE=1` 

ChatGPT describes this change as: 
> Driver / runtime mitigations (moderate trade-offs)
> Forces ROCm to avoid userptr where possible

Which makes limited sense to me, since my PC doesn't have a `/sys/module/amdgpu/parameters/userptr` file or directory. I'm not sure what is going on with this specific file or if `HSA_DISABLE_CACHE=1` actually does anything in relation to this missing file. 

I've been running some tests and slowly ramping up images production to stress test the fix, but it really looks as though it was the magical bullet. 

TL;DR: I've added `export HSA_DISABLE_CACHE=1` to my script to launch sdnext. I'm open to any insight you might have about how wise it is to use this environment variable.

**Comment by vladmandic** [comment]
thanks for the follow-up.
from what i know, that var disables GPU L2 cache which is perfectly safe, just does have some performance hit.
how much, i don't know, but if you're willing to do the test, you can try running with the var and without it (as much as possible before lock) and compare
