### ISSUE TITLE
[Issue]: NotImplementedError from rocm.py when using venv-installed ROCm wheels

### ISSUE THREAD

**Issue by ryanmeador** [vladmandic/automatic#4529]
### Issue Description

This is the followup to #4423 that @vladmandic requested in https://github.com/vladmandic/sdnext/issues/4526#issuecomment-3707796982

In short, SDNext doesn't like it when the ROCm wheels are installed in the venv on Linux (as opposed to system-wide): it seems to explicitly detect this situation and throws `NotImplementedError` at `rocm.py:53`. (I don't want to install them system-wide because I have different versions for different software.)

To demonstrate exactly what's going on, I did a fresh install. Here are the steps:

1. I initially tried a plain old install:
   `git clone https://github.com/vladmandic/sdnext`
   `python3.13 -m venv venv`
   `./webui.sh --debug --use-rocm`
   **this produces `HIP error: invalid device function`**, as you can see in [this log](https://github.com/user-attachments/files/24426721/sdnext-fresh-install.txt), and no generation is possible
   ```bash
   $ pip list | grep rocm
   pytorch-triton-rocm            3.5.1
   torch                          2.9.1+rocm6.4
   torchvision                    0.24.1+rocm6.4
   ``` 
5. so I decided to try enabling the experimental triton thing:
   `TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1 ./webui.sh --debug --use-rocm --test`
    (it was worth a shot, but produced [no change](https://github.com/user-attachments/files/24426723/sdnext-fresh-install-with-triton.txt))
6. at this point, I decided I needed to install the nightly ROCm wheels from TheRock:
   `pip install --index-url https://rocm.nightlies.amd.com/v2/gfx1151/ "rocm[libraries,devel]"`
   ```bash
   $ pip list | grep rocm
   pytorch-triton-rocm            3.5.1
   rocm                           7.11.0a20260104
   rocm-sdk-core                  7.11.0a20260104
   rocm-sdk-devel                 7.11.0a20260104
   rocm-sdk-libraries-gfx1151     7.11.0a20260104
   torch                          2.9.1+rocm6.4
   torchvision                    0.24.1+rocm6.4
   ``` 
7. `./webui.sh --debug --use-rocm`
   [failure with **NotImplementedError**](https://github.com/user-attachments/files/24426733/sdnext-fresh-install-NotImplementedError.txt) -- I'm pretty sure this is what #4423 was about
8. I worked around the exception by removing the check from rocm.py:
   ```patch
   diff --git a/modules/rocm.py b/modules/rocm.py
   index ca74810d5..910e561bb 100644
   --- a/modules/rocm.py
   +++ b/modules/rocm.py
   @@ -128,11 +128,11 @@ class Agent:
    
    
    def find() -> Union[Environment, None]:
   -    try: # TheRock
   -        import _rocm_sdk_core # pylint: disable=unused-import
   -        return PythonPackageEnvironment()
   -    except ImportError:
   -        pass
    
        # system-wide installation
        hip_path = shutil.which("hipconfig")
   ```
9. `./webui.sh --debug --use-rocm --test`
   [**success**](https://github.com/user-attachments/files/24426770/sdnext-fresh-install-after-modified-rocm.txt)

I am sure there is a purpose to this `PythonPackageEnvironment` check, but I'm unable to see what it is. It looks like SDNext works perfectly fine with it removed (thus it erroneously believes that my venv-installed ROCm is actually system-wide). I'd be happy to open a PR to make this change if you tell me if you'd like to keep what I've done, modify the check in `PythonPackageEnvironment` to allow this scenario, or something else.

### Version Platform Description

Fedora 43 Kinoite Linux (kernel 6.17.12-300.fc43.x86_64)
AMD Ryzen AI Max+ 395 (Strix Halo)
AMD Radeon 8060S
128GB RAM + shared with the iGPU
Python 3.13
Browser: Chrome 143.0.7499.169
SDNext version https://github.com/vladmandic/sdnext/commit/56a8aeaea4d7dce334dd5d127a7f6da72906731d

### Backend

Diffusers

### Compute

AMD ROCm

### Interface

ModernUI

### Branch

Master

### Model

Unspecified

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
cc @lshqqytiger

**Comment by lshqqytiger** [comment]
Even though you installed `rocm` packages, `torch-2.9.1+rocm6.4` will use its own ROCm libraries (located at `site-packages/torch/lib`).
Also, it seems weird to have both ROCm 7 packages and `torch` compiled targetting ROCm 6.
I recommend to install `torch` from same source, or search for `torch` wheels built for gfx1151.
Anyhow, I expect SD.Next no longer rejects `rocm` packages on Linux from commit 91c4aa1ad4e35fb958fadea22df6d26f8b642a0f.

**Comment by ryanmeador** [comment]
I agree it feels weird to have two different versions of ROCm installed, but it fixed the HIP failure, so clearly it has some effect, even though it seems like it should not. At the time I first did this, I attempted to replace SDNext's torch with the one from TheRock, but there wasn't a compatible version available. Now that SDNext has upgraded to 2.9.1, it might be possible. I'll give it a try. I'll also pull down your change and see if that works. Thank you.

**Comment by ryanmeador** [comment]
I pulled your latest dev branch, and I'm happy to say the workaround of editing rocm.py is no longer necessary. Thank you!

I did still have to install my own rocm nightly packages to work around the HIP failures, and with those packages + the ones SDNext installed, I got these errors in the log:
```
22:14:09-413672 ERROR    ROCm initialization failed: No HIP GPUs are available                                                           
22:14:09-414368 WARNING  GPU stats: No HIP GPUs are available                                                                            
22:14:09-414709 DEBUG    Initializing: default modes                                                                                     
22:14:09-415307 DEBUG    Initializing: settings                                                                                          
22:14:09-416312 DEBUG    Triton: pass=False fn=<module>:has_triton time=0.00  
```

So I ended up having to replace the torch and torchvision that SDNext installed. My final working set of packages is:
```
$ pip list | grep rocm
pytorch-triton-rocm            3.5.0+gitfcf723cb.rocm7.9.0rc20251001
rocm                           7.11.0a20260106
rocm-sdk-core                  7.11.0a20260106
rocm-sdk-devel                 7.11.0a20260106
rocm-sdk-libraries-gfx1151     7.11.0a20260106
torch                          2.9.1+rocm7.11.0a20260106
torchvision                    0.24.0+rocm7.11.0a20260106
triton                         3.5.1+rocm7.11.0a20260106
```

I do still see another new error in the log, but it doesn't prevent me from generating.
```
[W106 23:02:14.291948864 Context.cpp:533] Warning: Attempting to use CK on an unsupported architecture! Cannot set backend to CK (function operator())
23:02:14-457903 DEBUG    ROCm: disabled hipBLASLt
```

Generations are at least 10% faster now, probably because I'm using updated ROCm.  Thanks again!
