### ISSUE TITLE
[Issue]: rocblaslt error

### ISSUE THREAD

**Issue by Cixada115** [vladmandic/automatic#4574]
### Issue Description

Post update im getting an error i feel like i have seen before way back. Its a cublasLt error when trying to generate, its looking its looking for TensileLibrary_lazy_gfx1030 which isnt present in HIP 6.2 on windows. Was working fine with the ZLuda extension pre update. 

[message.txt](https://github.com/user-attachments/files/24752808/message.txt)

### Version Platform Description

Windows, AMD-Zluda, RX 6800xt, gfx1030, HIP 6.2

### Relevant log output

```shell
ocblaslt error: Cannot read "C:\\Program Files\\AMD\\ROCm\\6.2\\bin\\hipblaslt\\library\\TensileLibrary_lazy_gfx1030.dat": No error

rocblaslt error: Could not load "C:\\Program Files\\AMD\\ROCm\\6.2\\bin\\hipblaslt\\library\\TensileLibrary_lazy_gfx1030.dat"
15:30:32-897234 ERROR    Prompt parser encode: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling
                         `cublasLtMatmulAlgoGetHeuristic( ltHandle, computeDesc.descriptor(), Adesc.descriptor(),
                         Bdesc.descriptor(), Cdesc.descriptor(), Cdesc.descriptor(), preference.descriptor(), 1,
                         &heuristicResult, &returnedResult)`
15:30:32-917747 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=1/1x1 set={'prompt': 1,
                         'negative_prompt': 1, 'prompt_2': [' leiadg, woman leiagolddg gold bikini armor red loincloth
                         braid leiadressdg '], 'negative_prompt_2': ['low quality, worst quality, lowres, username,
                         sketch, censor, blurry, distorted, bad anatomy, signature, watermark'], 'guidance_scale': 6,
                         'generator': 'cuda:[218170624]', 'num_inference_steps': 20, 'eta': 1.0, 'guidance_rescale': 0,
                         'denoising_end': None, 'output_type': 'latent', 'width': 1024, 'height': 1024, 'parser':
                         'fixed'}
Load network: F:\sdnext\models\Lora\Characters\Leia DALL E-3 IlluLoRA.safetensors ━━━━━━━━━━━━━━━━━━ 0.0/57.4 MB -:--:--
15:30:33-774092 DEBUG    Network load: type=LoRA name="Leia DALL E-3 IlluLoRA" type={'ModuleTypeLora'} keys=986
                         dtypes=[torch.bfloat16] fuse=True:False
Network: type=LoRA action=activate 100% networks=1 modules=['unet'] layers=1930 weights=722 bias=0 backup=None device=c…
15:30:35-529802 INFO     Network load: type=LoRA networks=['Leia DALL E-3 IlluLoRA'] method=native mode=fuse te=[1.0]
                         unet=[[1.0, 1.0, 1.0]] time={'load': 0.87, 'calc': 0.48, 'apply': 1.21, 'activate': 1.74}
15:30:35-562799 ERROR    Processing: step=base args={'prompt': [' leiadg, woman leiagolddg gold bikini armor red
                         loincloth braid leiadressdg '], 'negative_prompt': ['low quality, worst quality, lowres,
                         username, sketch, censor, blurry, distorted, bad anatomy, signature, watermark'], 'prompt_2':
                         [' leiadg, woman leiagolddg gold bikini armor red loincloth braid leiadressdg '],
                         'negative_prompt_2': ['low quality, worst quality, lowres, username, sketch, censor, blurry,
                         distorted, bad anatomy, signature, watermark'], 'guidance_scale': 6, 'generator':
                         [<torch._C.Generator object at 0x000002851B19F9F0>], 'callback_on_step_end': <function
                         diffusers_callback at 0x000002851239B100>, 'callback_on_step_end_tensor_inputs': ['latents',
                         'prompt_embeds', 'add_text_embeds', 'add_time_ids', 'noise_pred'], 'num_inference_steps': 20,
                         'eta': 1.0, 'guidance_rescale': 0, 'denoising_end': None, 'output_type': 'latent', 'width':
                         1024, 'height': 1024} CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling
                         `cublasLtMatmulAlgoGetHeuristic( ltHandle, computeDesc.descriptor(), Adesc.descriptor(),
                         Bdesc.descriptor(), Cdesc.descriptor(), Cdesc.descriptor(), preference.descriptor(), 1,
                         &heuristicResult, &returnedResult)`
15:30:35-565800 ERROR    Processing: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│F:\sdnext\modules\processing_diffusers.py:181 in process_base                                                         │
│                                                                                                                      │
│  180 │   │   │   taskid = shared.state.begin('Inference')                                                            │
│❱ 181 │   │   │   output = shared.sd_model(**base_args)                                                               │
│  182 │   │   │   shared.state.end(taskid)                                                                            │
│                                                                                                                      │
│F:\sdnext\venv\Lib\site-packages\torch\utils\_contextlib.py:116 in decorate_context                                   │
│                                                                                                                      │
│  115 │   │   with ctx_factory():                                                                                     │
│❱ 116 │   │   │   return func(*args, **kwargs)                                                                        │
│  117                                                                                                                 │
│                                                                                                                      │
│F:\sdnext\venv\Lib\site-packages\diffusers\pipelines\stable_diffusion_xl\pipeline_stable_diffusion_xl.py:1080 in __ca │
│                                                                                                                      │
│  1079 │   │   │   negative_pooled_prompt_embeds,                                                                     │
│❱ 1080 │   │   ) = self.encode_prompt(                                                                                │
│  1081 │   │   │   prompt=prompt,                                                                                     │
│                                                                                                                      │
│F:\sdnext\venv\Lib\site-packages\diffusers\pipelines\stable_diffusion_xl\pipeline_stable_diffusion_xl.py:405 in encod │
│                                                                                                                      │
│   404 │   │   │   │                                                                                                  │
│❱  405 │   │   │   │   prompt_embeds = text_encoder(text_input_ids.to(device), output_hidden_states=True)             │
│   406                                                                                                                │
│                                                                                                                      │
│F:\sdnext\venv\Lib\site-packages\torch\nn\modules\module.py:1751 in _wrapped_call_impl                                │
│                                                                                                                      │
│  1750 │   │   else:                                                                                                  │
│❱ 1751 │   │   │   return self._call_impl(*args, **kwargs)                                                            │
│  1752                                                                                                                │
│                                                                                                                      │
│F:\sdnext\venv\Lib\site-packages\torch\nn\modules\module.py:1762 in _call_impl                                        │
│                                                                                                                      │
│  1761 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                        │
│❱ 1762 │   │   │   return forward_call(*args, **kwargs)                                                               │
│  1763                                                                                                                │
│                                                                                                                      │
│F:\sdnext\venv\Lib\site-packages\accelerate\hooks.py:175 in new_forward                                               │
│                                                                                                                      │
│  174 │   │   else:                                                                                                   │
│❱ 175 │   │   │   output = module._old_forward(*args, **kwargs)                                                       │
│  176 │   │   return module._hf_hook.post_forward(module, output)                                                     │
│                                                                                                                      │
│F:\sdnext\venv\Lib\site-packages\transformers\utils\generic.py:918 in wrapper                                         │
│                                                                                                                      │
│   917 │   │   │   return_dict = return_dict_passed                                                                   │
│❱  918 │   │   output = func(self, *args, **kwargs)                                                                   │
│   919 │   │   if not return_dict and not isinstance(output, tuple):                                                  │
│                                                                                                                      │
│                                              ... 10 frames hidden ...                                                │
│                                                                                                                      │
│F:\sdnext\venv\Lib\site-packages\transformers\models\clip\modeling_clip.py:397 in forward                             │
│                                                                                                                      │
│   396 │   │   hidden_states = self.layer_norm1(hidden_states)                                                        │
│❱  397 │   │   hidden_states, attn_weights = self.self_attn(                                                          │
│   398 │   │   │   hidden_states=hidden_states,                                                                       │
│                                                                                                                      │
│F:\sdnext\venv\Lib\site-packages\torch\nn\modules\module.py:1751 in _wrapped_call_impl                                │
│                                                                                                                      │
│  1750 │   │   else:                                                                                                  │
│❱ 1751 │   │   │   return self._call_impl(*args, **kwargs)                                                            │
│  1752                                                                                                                │
│                                                                                                                      │
│F:\sdnext\venv\Lib\site-packages\torch\nn\modules\module.py:1762 in _call_impl                                        │
│                                                                                                                      │
│  1761 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                        │
│❱ 1762 │   │   │   return forward_call(*args, **kwargs)                                                               │
│  1763                                                                                                                │
│                                                                                                                      │
│F:\sdnext\venv\Lib\site-packages\transformers\models\clip\modeling_clip.py:312 in forward                             │
│                                                                                                                      │
│   311 │   │                                                                                                          │
│❱  312 │   │   queries = self.q_proj(hidden_states)                                                                   │
│   313 │   │   keys = self.k_proj(hidden_states)                                                                      │
│                                                                                                                      │
│F:\sdnext\venv\Lib\site-packages\torch\nn\modules\module.py:1751 in _wrapped_call_impl                                │
│                                                                                                                      │
│  1750 │   │   else:                                                                                                  │
│❱ 1751 │   │   │   return self._call_impl(*args, **kwargs)                                                            │
│  1752                                                                                                                │
│                                                                                                                      │
│F:\sdnext\venv\Lib\site-packages\torch\nn\modules\module.py:1762 in _call_impl                                        │
│                                                                                                                      │
│  1761 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                        │
│❱ 1762 │   │   │   return forward_call(*args, **kwargs)                                                               │
│  1763                                                                                                                │
│                                                                                                                      │
│F:\sdnext\modules\sdnq\layers\__init__.py:14 in forward                                                               │
│                                                                                                                      │
│  13 │   def forward(self, *args, **kwargs) -> torch.Tensor:                                                          │
│❱ 14 │   │   return self.forward_func(self, *args, **kwargs)                                                          │
│  15                                                                                                                  │
│                                                                                                                      │
│F:\sdnext\modules\sdnq\layers\linear\forward.py:20 in quantized_linear_forward                                        │
│                                                                                                                      │
│  19 def quantized_linear_forward(self, input: torch.FloatTensor) -> torch.FloatTensor:                               │
│❱ 20 │   return torch.nn.functional.linear(input, self.sdnq_dequantizer(self.weight, self.scale, self.zero_point, sel │
│  21                                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasLtMatmulAlgoGetHeuristic( ltHandle, computeDesc.descriptor(), Adesc.descriptor(), Bdesc.descriptor(), Cdesc.descriptor(), Cdesc.descriptor(), preference.descriptor(), 1, &heuristicResult, &returnedResult)`
```

### Backend

Diffusers

### Compute

ZLUDA

### Interface

Standard

### Branch

Master

### Model

StableDiffusion 1.5/2.1/XL

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
per update on discord, reinstalling hip fixes it?
if issue persists, update here and i'll reopen.

**Comment by Cixada115** [comment]
@vladmandic Pretty sure the problem is the HIP-Extension for zluda. I think it only started working because i flushed out all the hipblaslt stuff from my HIP build, SD was seeing it and trying to move forward with it but there was no tensile lib to use (TensileLibrary_lazy_gfx1030.dat), gfx 1030 isnt compatible with hipblaslt on windows. I was using it for cudnn before but i didn't want to go through the whole extension and try to parse the two resources, as they're all packed in together.

**Comment by vladmandic** [comment]
cc @lshqqytiger

**Comment by lshqqytiger** [comment]
SD.Next checks if `TensileLibrary_lazy_gfx####.dat` exists since the commit 40e366acf727018dfe1ae4b192823b1f8543544d I pushed just before.
Could you confirm whether this commit fixes your rocblaslt error or not?

**Comment by Cixada115** [comment]
Hey sorry i was away from my desk for a while. 
Sorry to confirm the issue is still present in the current build.

**Comment by lshqqytiger** [comment]
Could you upload full log?

**Comment by vladmandic** [comment]
@Cixada115 ping?

**Comment by Cixada115** [comment]
Sorry you can close this, it has been working for a while, think my update was broken the first time around when i tried it. Thank you guys.
