### ISSUE TITLE
[Issue]: Meituan Longcat Image different behaviour between app versions

### ISSUE THREAD

**Issue by alerikaisattera** [vladmandic/automatic#4585]
### Issue Description

In some update, behaviour of Meituan Longcat Image has changed. The outputs now look different and the way model works is changed. For example, setting the model to run 50 steps runs 167 steps, each step taking less time

Version 3ae1018 (old)

<img width="1024" height="1024" alt="Image" src="https://github.com/user-attachments/assets/6c32df8c-38e4-4ce7-a203-eca78794958d" />

Version 02268a4 (new)

<img width="1024" height="1024" alt="Image" src="https://github.com/user-attachments/assets/72ecd075-2fce-4131-aa99-1052c23a482f" />

### Version Platform Description

SD.Next master, Brave, Linux

### Relevant log output

```shell
18:43:12-232894 INFO     Starting SD.Next                                                                                                                                                           
18:43:12-237199 INFO     Logger: file="/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/sdnext.log" level=DEBUG host="aleri-pc" size=75 mode=create                                  
18:43:12-238341 INFO     Python: version=3.12.10 platform=Linux bin="/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/venv/bin/python3"                                              
                         venv="/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/venv"                                                                                                
18:43:12-294880 INFO     Version: app=sd.next updated=2026-01-21 commit=02268a4af branch=master url=https://github.com/vladmandic/sdnext/tree/master kanvas=main ui=dev                             
18:43:12-296231 DEBUG    Branch mismatch: sdnext=master ui=dev                                                                                                                                      
18:43:12-360097 DEBUG    Branch sync failed: sdnext=master ui=main                                                                                                                                  
18:43:12-817194 TRACE    Repository branches: active=master available=['dev', 'master', 'upstream']                                                                                                 
18:43:13-346808 INFO     Version: app=sd.next latest=2026-01-21T16:09:04Z hash=02268a4a branch=master                                                                                               
18:43:13-354492 INFO     Platform: arch=x86_64 cpu= system=Linux release=6.12.62-1-MANJARO python=3.12.10 locale=('en_US', 'UTF-8') docker=False                                                    
18:43:13-355990 DEBUG    Packages: prefix=venv site=['venv/lib/python3.12/site-packages']                                                                                                           
18:43:13-357332 INFO     Args: ['--use-cuda', '--update']                                                                                                                                           
18:43:13-358123 DEBUG    Setting environment tuning                                                                                                                                                 
18:43:13-358954 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"                                                                                                 
18:43:13-360716 INFO     Verifying torch installation                                                                                                                                               
18:43:13-361634 DEBUG    Torch overrides: cuda=True rocm=False ipex=False directml=False openvino=False zluda=False                                                                                 
18:43:13-362872 INFO     CUDA: nVidia toolkit detected                                                                                                                                              
18:43:14-696792 INFO     Torch backend: version="2.8.0+cu128" type=CUDA CUDA=12.8 cuDNN=91002                                                                                                       
18:43:14-712360 INFO     Torch detected: gpu="NVIDIA GeForce RTX 4060 Ti" vram=15946 arch=(8, 9) cores=34                                                                                           
18:43:14-794808 INFO     Install: verifying requirements                                                                                                                                            
18:43:14-800045 INFO     Startup: standard                                                                                                                                                          
18:43:14-800782 INFO     Verifying submodules                                                                                                                                                       
18:43:15-297538 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main                                                                                                             
18:43:15-922332 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main                                                                                                          
18:43:16-551791 DEBUG    Git submodule: extensions-builtin/sdnext-kanvas / main                                                                                                                     
18:43:17-218762 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=dev                                                                                       
18:43:17-219942 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / dev                                                                                                                    
18:43:17-848786 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master                                                                                                    
18:43:18-498134 DEBUG    Git submodule: wiki / master                                                                                                                                               
18:43:19-172588 DEBUG    Installed packages: 263                                                                                                                                                    
18:43:19-173693 DEBUG    Extensions all: ['sdnext-kanvas', 'stable-diffusion-webui-rembg', 'sd-extension-system-info', 'sd-extension-chainner', 'sdnext-modernui']                                  
18:43:19-196120 DEBUG    Git submodule: extensions-builtin/sdnext-kanvas / main                                                                                                                     
18:43:19-887867 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master                                                                                                    
18:43:20-493837 DEBUG    Extension installer: builtin=True file="/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/extensions-builtin/stable-diffusion-webui-rembg/install.py"        
18:43:20-579945 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main                                                                                                          
18:43:21-343104 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main                                                                                                             
18:43:22-115983 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / dev                                                                                                                    
18:43:22-772352 DEBUG    Extensions all: []                                                                                                                                                         
18:43:22-773456 INFO     Extensions enabled: ['sdnext-kanvas', 'stable-diffusion-webui-rembg', 'sd-extension-system-info', 'sd-extension-chainner', 'sdnext-modernui']                              
18:43:22-817061 INFO     Install: verifying requirements                                                                                                                                            
18:43:22-822353 INFO     Updating Wiki                                                                                                                                                              
18:43:22-847381 DEBUG    Git submodule: /run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/wiki / master                                                                               
18:43:23-462931 DEBUG    Setup complete without errors: 1769085803                                                                                                                                  
18:43:23-465263 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}                                                                                                          
18:43:23-466327 INFO     Installer time: total=27.90 git=8.30 update=7.77 submodules=4.31 torch=1.35 latest=1.11 sd-extension-chainner=0.77 sd-extension-system-info=0.76                           
                         stable-diffusion-webui-rembg=0.70 sdnext-kanvas=0.69 sdnext-modernui=0.68 wiki=0.64 branch=0.28 base=0.13                                                                  
18:43:23-468102 INFO     Command line args: ['--use-cuda', '--update'] upgrade=True use_cuda=True args=[]                                                                                           
18:43:23-469248 DEBUG    Flags: sd=['SD_VAE_DEFAULT=true'] ld=['LD_PRELOAD=libtcmalloc.so.4', 'LD_LIBRARY_PATH=:/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/venv/lib/']         
18:43:23-470245 DEBUG    Starting module: <module 'webui' from '/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/webui.py'>                                                          
18:43:23-471664 DEBUG    Initializing: libraries                                                                                                                                                    
18:43:31-938237 DEBUG    System: cores=16 affinity=16 threads=8                                                                                                                                     
18:43:31-942642 INFO     Torch: torch==2.8.0+cu128 torchvision==0.23.0+cu128                                                                                                                        
18:43:31-943569 INFO     Packages: diffusers==0.37.0.dev0 transformers==4.57.5 accelerate==1.12.0 gradio==3.43.2 pydantic==1.10.21 numpy==2.1.2 cv2==4.12.0                                         
18:43:31-955067 DEBUG    Initializing: shared module                                                                                                                                                
18:43:32-003055 DEBUG    Initializing: pipelines                                                                                                                                                    
18:43:32-556792 DEBUG    ONNX: version=1.22.1, available=['AzureExecutionProvider', 'CPUExecutionProvider']                                                                                         
18:43:32-566864 DEBUG    State initialized: id=139642284803472                                                                                                                                      
18:43:32-674626 DEBUG    Initializing: default modes                                                                                                                                                
18:43:32-676510 INFO     Device detect: memory=16.0 default=balanced                                                                                                                                
18:43:32-678045 DEBUG    Initializing: settings                                                                                                                                                     
18:43:32-682014 DEBUG    Read: file="/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/config.json" json=19 bytes=823 time=0.000 fn=__init__:load                                     
18:43:32-684038 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product" mode=no_grad                                                                     
18:43:32-686297 DEBUG    Read: file="html/reference.json" json=100 bytes=50269 time=0.000 fn=_call_with_frames_removed:<module>                                                                     
18:43:32-687500 DEBUG    Initializing: devices                                                                                                                                                      
18:43:32-688277 DEBUG    Torch cuDNN: benchmark=True                                                                                                                                                
18:43:32-689184 DEBUG    Torch attention: type="sdpa" kernels=['Flash', 'Memory', 'Math'] overrides=[]                                                                                              
18:43:32-690675 DEBUG    Torch attention installed: flashattn=False sageattention=False                                                                                                             
18:43:32-691537 DEBUG    Torch attention status: flash=False flash3=False aiter=False sage=False flex=True npu=False xla=False xformers=False                                                       
18:43:34-512851 DEBUG    Triton: pass=True fn=<module>:set_cuda_params time=1.79                                                                                                                    
18:43:34-514130 INFO     Torch parameters: backend=cuda device=cuda config=Auto dtype=torch.bfloat16 context=no_grad nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False,  
                         True] fp16=pass bf16=pass triton=pass optimization="Scaled-Dot-Product"                                                                                                    
18:43:34-528773 DEBUG    Quantization: registered=SDNQ                                                                                                                                              
18:43:34-555459 INFO     Device: device=NVIDIA GeForce RTX 4060 Ti n=1 arch=sm_120 capability=(8, 9) cuda=12.8 cudnn=91002 driver=580.119.02                                                        
18:43:34-670076 DEBUG    Entering start sequence                                                                                                                                                    
18:43:34-671652 DEBUG    Initializing: modules                                                                                                                                                      
18:43:34-672595 DEBUG    Read: file="metadata.json" json=2 bytes=1352 time=0.000 fn=initialize:init_metadata                                                                                        
18:43:34-673753 DEBUG    Read: file="cache.json" json=1 bytes=350 time=0.000 fn=initialize:init_cache                                                                                               
18:43:34-701473 INFO     Available VAEs: path="models/VAE" items=0                                                                                                                                  
18:43:34-702788 INFO     Available UNets: path="models/UNET" items=0                                                                                                                                
18:43:34-703807 INFO     Available TEs: path="models/Text-encoder" items=0                                                                                                                          
18:43:34-705528 INFO     Available Models: safetensors="models/Stable-diffusion":0 diffusers="models/Diffusers":12 reference=100 items=12 time=0.00                                                 
18:43:34-710295 INFO     Available LoRAs: path="models/Lora" items=0 folders=2 time=0.00                                                                                                            
18:43:34-717417 INFO     Available Styles: path="models/styles" items=288 time=0.01                                                                                                                 
18:43:34-749201 INFO     Available Detailer: path="models/yolo" items=14 downloaded=0                                                                                                               
18:43:34-750587 DEBUG    Extensions: disabled=['Lora', 'sd-webui-agent-scheduler']                                                                                                                  
18:43:34-751440 INFO     Load extensions                                                                                                                                                            
18:43:35-040817 DEBUG    Extensions init time: total=0.29 stable-diffusion-webui-rembg=0.17                                                                                                         
18:43:35-478975 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2640 time=0.000 fn=__init__:__init__                                                                                         
18:43:35-480423 DEBUG    Read: file="extensions-builtin/sd-extension-chainner/models.json" json=25 bytes=2803 time=0.000 fn=__init__:find_scalers                                                   
18:43:35-481941 DEBUG    Available chaiNNer: path="models/chaiNNer" defined=25 discovered=0 downloaded=0                                                                                            
18:43:35-483666 INFO     Available Upscalers: items=77 downloaded=1 user=1 time=0.44 types=['None', 'Resize', 'Latent', 'AsymmetricVAE', 'WanUpscale', 'DCC', 'VIPS', 'ChaiNNer', 'Diffusion',      
                         'SwinIR', 'AuraSR', 'SCUNet', 'ESRGAN', 'RealESRGAN', 'SeedVR']                                                                                                            
18:43:35-535683 INFO     Networks: type="video" engines=13 models=71 errors=0 time=0.05                                                                                                             
18:43:35-538292 INFO     Huggingface: transfer=rust parallel=False direct=True token="hf_...rCGg" cache="cache/huggingface/hub" init                                                                
18:43:35-540246 WARNING  Cache location changed: previous="/home/aleri/.cache/huggingface/hub" size=3520 MB                                                                                         
18:43:35-547351 DEBUG    Huggingface: cache="cache/huggingface/hub" size=203113 MB                                                                                                                  
18:43:35-548393 DEBUG    UI start sequence                                                                                                                                                          
18:43:35-549151 DEBUG    UI image support: kanvas=main                                                                                                                                              
18:43:35-552092 INFO     UI locale: name="Auto"                                                                                                                                                     
18:43:35-553056 INFO     UI theme: type=Modern name="Default" available=35                                                                                                                          
18:43:35-554078 DEBUG    UI theme: css="extensions-builtin/sdnext-modernui/themes/Default.css" base="['base.css', 'timesheet.css']" user="None"                                                     
18:43:35-556847 DEBUG    UI initialize: tab=txt2img                                                                                                                                                 
18:43:35-604717 DEBUG    Read: file="html/reference.json" json=100 bytes=50269 time=0.000 fn=list_items:list_reference                                                                              
18:43:35-606284 DEBUG    Read: file="html/reference-quant.json" json=24 bytes=9140 time=0.000 fn=list_items:list_reference                                                                          
18:43:35-607469 DEBUG    Read: file="html/reference-distilled.json" json=20 bytes=9775 time=0.000 fn=list_items:list_reference                                                                      
18:43:35-608629 DEBUG    Read: file="html/reference-community.json" json=15 bytes=5737 time=0.000 fn=list_items:list_reference                                                                      
18:43:35-609754 DEBUG    Read: file="html/reference-cloud.json" json=2 bytes=677 time=0.000 fn=list_items:list_reference                                                                            
18:43:35-618571 DEBUG    Networks: type="reference" {'total': 161, 'ready': 11, 'hidden': 0, 'experimental': 0, 'base': 99, 'quantized': 24, 'community': 15, 'distilled': 19, 'cloud': 2}          
18:43:35-627304 DEBUG    Networks: type="model" items=171 subfolders=8 tab=txt2img folders=['models/Stable-diffusion', 'models/Reference',                                                          
                         '/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/models/Stable-diffusion'] list=0.04 thumb=0.00 desc=0.00 info=0.01 workers=12                             
18:43:35-630037 DEBUG    Networks: type="lora" items=0 subfolders=1 tab=txt2img folders=['models/Lora'] list=0.01 thumb=0.01 desc=0.00 info=0.00 workers=12                                         
18:43:35-639547 DEBUG    Networks: type="style" items=288 subfolders=3 tab=txt2img folders=['models/styles', 'html'] list=0.01 thumb=0.01 desc=0.00 info=0.00 workers=12                            
18:43:35-642727 DEBUG    Networks: type="wildcards" items=0 subfolders=1 tab=txt2img folders=['models/wildcards'] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=12                               
18:43:35-644623 DEBUG    Networks: type="embedding" items=0 subfolders=1 tab=txt2img folders=['models/embeddings'] list=0.01 thumb=0.01 desc=0.00 info=0.00 workers=12                              
18:43:35-646459 DEBUG    Networks: type="vae" items=0 subfolders=1 tab=txt2img folders=['models/VAE'] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=12                                           
18:43:35-648494 DEBUG    Networks: type="history" items=0 subfolders=1 tab=txt2img folders=[] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=12                                                   
18:43:35-976477 DEBUG    UI initialize: tab=img2img                                                                                                                                                 
18:43:36-341775 DEBUG    UI initialize: tab=control models="models/control"                                                                                                                         
18:43:36-980917 DEBUG    UI initialize: tab=video                                                                                                                                                   
18:43:37-134701 DEBUG    UI initialize: tab=process                                                                                                                                                 
18:43:37-205499 DEBUG    UI initialize: tab=caption                                                                                                                                                 
18:43:37-291269 DEBUG    UI initialize: tab=models                                                                                                                                                  
18:43:37-395489 DEBUG    UI initialize: tab=gallery                                                                                                                                                 
18:43:37-452086 DEBUG    Read: file="ui-config.json" json=0 bytes=2 time=0.000 fn=__init__:read_from_file                                                                                           
18:43:37-453312 DEBUG    UI initialize: tab=settings                                                                                                                                                
18:43:38-183848 DEBUG    Settings: sections=23 settings=389/617 quicksettings=1                                                                                                                     
18:43:38-261988 DEBUG    UI initialize: tab=info                                                                                                                                                    
18:43:38-291792 DEBUG    UI initialize: tab=extensions                                                                                                                                              
18:43:38-298367 INFO     Extension List: No information found. Refresh required.                                                                                                                    
18:43:38-396420 DEBUG    Extension list: processed=5 installed=5 enabled=3 disabled=2 visible=5 hidden=0                                                                                            
18:43:38-971172 DEBUG    Root paths: ['/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext', 'models']                                                                                  
18:43:39-097279 INFO     Local URL: http://127.0.0.1:7860/                                                                                                                                          
18:43:39-098231 INFO     API docs: http://127.0.0.1:7860/docs                                                                                                                                       
18:43:39-098953 INFO     API redocs: http://127.0.0.1:7860/redocs                                                                                                                                   
18:43:39-100092 DEBUG    API middleware: [<class 'starlette.middleware.base.BaseHTTPMiddleware'>, <class 'starlette.middleware.gzip.GZipMiddleware'>]                                               
18:43:39-101031 DEBUG    API initialize                                                                                                                                                             
18:43:39-435732 DEBUG    Scripts setup: time=0.631 ['XYZ Grid:0.081', 'IP Adapters:0.067', 'Prompt enhance:0.054', 'Mixture-of-Diffusers: Tile Control:0.039', 'Face: Multiple ID Transfers:0.038'] 
18:43:39-436984 DEBUG    Model metadata: file="metadata.json" no changes                                                                                                                            
18:43:39-437790 INFO     Model: autoload=False selected="Diffusers/black-forest-labs/FLUX.2-klein-4B [5e67da950f]"                                                                                  
18:43:39-439112 DEBUG    Script init: ['system-info.py:app_started=0.13']                                                                                                                           
18:43:39-440189 INFO     Startup time: total=50.24 launch=11.66 loader=11.43 installer=11.42 gradio=4.00 libraries=3.22 torch=3.00 ui-extensions=0.92 diffusers=0.70 ui-defaults=0.46 upscalers=0.44
                         ui-control=0.44 ui-networks=0.43 ui-img2img=0.30 ui-txt2img=0.29 extensions=0.29 cv2=0.22 api=0.21 ui-models=0.14 app-started=0.13                                         
18:43:39-445226 DEBUG    Save: file="/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/config.json" json=19 bytes=823 time=0.005                                                      
18:43:47-779219 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/motd 127.0.0.1 0.1794                                                                                                        
18:44:07-601566 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/sd-models 127.0.0.1 0.0357                                                                                                   
18:44:08-691373 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/version 127.0.0.1 0.0011                                                                                                     
18:44:08-876964 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36                    
18:44:08-879495 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/start 127.0.0.1 0.0051                                                                                                       
18:44:08-933229 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/version 127.0.0.1 0.0101                                                                                                     
18:44:08-935539 DEBUG    UI: connected                                                                                                                                                              
18:44:13-082332 INFO     UI: ready time=26281                                                                                                                                                       
18:44:27-473610 DEBUG    Search model: name="Diffusers/meituan-longcat/LongCat-Image [d2ea50b79a]"                                                                                                  
                         matched="models/Diffusers/models--meituan-longcat--LongCat-Image/snapshots/d2ea50b79a930074c37b9b97ce45e3b2ea8cf4d8" type=alias                                            
18:44:27-476161 INFO     Load model: select="Diffusers/meituan-longcat/LongCat-Image [d2ea50b79a]"                                                                                                  
18:44:27-507821 INFO     Autodetect model: detect="LongCat" class=LongCatImagePipeline                                                                                                              
                         file="models/Diffusers/models--meituan-longcat--LongCat-Image/snapshots/d2ea50b79a930074c37b9b97ce45e3b2ea8cf4d8"                                                          
18:44:27-510201 DEBUG    Cache clear                                                                                                                                                                
18:44:27-535331 DEBUG    Load model: type=LongCat repo="meituan-longcat/LongCat-Image" config={'low_cpu_mem_usage': True, 'torch_dtype': torch.bfloat16, 'load_connected_pipeline': True,           
                         'safety_checker': None, 'requires_safety_checker': False} offload=balanced dtype=torch.bfloat16 args={'low_cpu_mem_usage': True, 'torch_dtype': torch.bfloat16,            
                         'load_connected_pipeline': True, 'safety_checker': None, 'requires_safety_checker': False}                                                                                 
18:44:27-538193 DEBUG    Quantization: module="Model" type=sdnq mode=pre dtype=int8 svd=False dynamic=False group=0 loss=0.01 matmul_dtype=auto matmul_quant=False matmul_conv=False                
                         quant_conv=False fp32=False device=cuda return=cuda use_gpu=True map=default offload=balanced non_blocking=False skip_modules=[] dict={}                                   
18:44:27-540263 DEBUG    Load model: transformer="meituan-longcat/LongCat-Image" cls=LongCatImageTransformer2DModel subfolder=transformer quant="SDNQConfig" loader=default args={'torch_dtype':    
                         torch.bfloat16}                                                                                                                                                            
18:45:39-544590 TRACE    Server: alive=True requests=113 memory=16.49/62.74 status='running' task='Load DiT' timestamp='20260122184427' current='' id='1e560007b90c45e' job=0 jobs=1 total=2 step=0 
                         steps=0 queued=0 uptime=128 elapsed=72.01 eta=None progress=0                                                                                                              
18:46:35-229443 DEBUG    GC: current={'gpu': 1.42, 'ram': 22.33, 'oom': 0} prev={'gpu': 7.42, 'ram': 22.32} load={'gpu': 9, 'ram': 36} gc={'gpu': 6.0, 'py': 7207}                                  
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.42                                                                                                
18:46:35-257798 DEBUG    Quantization: module="TE" type=sdnq mode=pre dtype=int8 svd=False dynamic=False group=0 loss=0.01 matmul_dtype=auto matmul_quant=False matmul_conv=False  quant_conv=False 
                         fp32=False device=cuda return=cuda use_gpu=True map=default offload=balanced non_blocking=False skip_modules=[] dict={}                                                    
18:46:35-259919 DEBUG    Load model: text_encoder="hunyuanvideo-community/HunyuanImage-2.1-Diffusers" cls=Qwen2_5_VLForConditionalGeneration quant="SDNQConfig" loader=default shared=True          
Progress 27.86s/it ███▌            25% 1/4 00:27 01:23 Loading checkpoint shards18:47:39-560400 TRACE    Server: alive=True requests=121 memory=22.49/62.74 status='running' task='Load TE' timestamp='20260122184635' current='' id='9e06b2643bee4bd' job=0 jobs=1 total=3 step=0  
                         steps=0 queued=0 uptime=248 elapsed=64.3 eta=None progress=0                                                                                                               
Progress 29.39s/it ██████████████ 100% 4/4 01:57 00:00 Loading checkpoint shards
18:48:37-453915 DEBUG    GC: current={'gpu': 1.38, 'ram': 29.22, 'oom': 0} prev={'gpu': 8.79, 'ram': 29.23} load={'gpu': 9, 'ram': 47} gc={'gpu': 7.41, 'py': 256}                                  
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.47                                                                                                
Progress  7.20it/s █████████ 100% 6/6 00:00 00:00 Loading pipeline components...
18:48:44-136463 DEBUG    GC: current={'gpu': 1.38, 'ram': 29.41, 'oom': 0} prev={'gpu': 1.38, 'ram': 29.41} load={'gpu': 9, 'ram': 47} gc={'gpu': 0.0, 'py': 131}                                   
                         fn=load_diffuser_force:load_longcat why=load time=0.36                                                                                                                     
18:48:44-138752 DEBUG    Setting model: component=vae {'slicing': True, 'tiling': False}                                                                                                            
18:48:44-139690 DEBUG    Setting model: attention="Scaled-Dot-Product"                                                                                                                              
18:48:44-140654 INFO     Offload: type=balanced op=init watermark=0.2-0.84 gpu=3.20-13.44:16.00 cpu=63.000 limit=0.00 always=[] never=[] pre=True streams=False                                     
18:48:44-159306 DEBUG    Module: name=text_encoder cls=Qwen2_5_VLForConditionalGeneration size=8.749 params=8296860928 quant=QuantizationMethod.SDNQ                                                
18:48:44-166493 DEBUG    Module: name=transformer cls=LongCatImageTransformer2DModel size=5.917 params=6276723776 quant=QuantizationMethod.SDNQ                                                     
18:48:44-170176 DEBUG    Module: name=vae cls=AutoencoderKL size=0.156 params=83819683 quant=None                                                                                                   
18:48:44-171524 INFO     Model class=LongCatImagePipeline modules=3 size=14.822                                                                                                                     
18:48:45-716553 INFO     Load model: family=longcat time={'total': 258.24, 'load': 256.66, 'move': 1.58} native=1024 memory={'ram': {'total': 62.74, 'rss': 39.05, 'used': 29.39, 'free': 0.45,     
                         'avail': 33.36, 'buffers': 0.0, 'cached': 34.44}, 'gpu': {'used': 1.54, 'total': 15.57, 'active': 0.16, 'peak': 7.21, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': ''}       
18:48:45-924637 DEBUG    Save: file="/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/config.json" json=19 bytes=819 time=0.205                                                      
18:49:39-577668 TRACE    Server: alive=True requests=123 memory=29.54/62.74 status='idle' task='' timestamp=None current='' id='' job=0 jobs=0 total=3 step=0 steps=0 queued=0 uptime=368           
                         elapsed=53.86 eta=None progress=0                                                                                                                                          
18:50:22-704615 DEBUG    Pipeline class change: original=LongCatImagePipeline target=LongCatImagePipeline device=cpu fn=control_run:preprocess_image                                                
18:50:22-840153 DEBUG    Pipeline class change: original=LongCatImagePipeline target=LongCatImagePipeline device=cpu fn=process_images_inner:process_diffusers                                      
18:50:22-844370 DEBUG    Sampler: "Default" cls=FlowMatchEulerDiscreteScheduler config={'num_train_timesteps': 1000, 'shift': 3.0, 'use_dynamic_shifting': True, 'base_shift': 0.5, 'max_shift':    
                         1.15, 'base_image_seq_len': 256, 'max_image_seq_len': 4096, 'invert_sigmas': False, 'shift_terminal': None, 'use_karras_sigmas': False, 'use_exponential_sigmas': False,   
                         'use_beta_sigmas': False, 'time_shift_type': 'exponential', 'stochastic_sampling': False}                                                                                  
18:50:23-276644 INFO     Processing modifiers: apply                                                                                                                                                
18:50:23-462109 INFO     Base: pipeline=LongCatImagePipeline task=IMAGE_2_IMAGE batch=1/1x1 set={'prompt': 1, 'negative_prompt': 1, 'guidance_scale': 5, 'generator': 'cuda:[4211501254]',          
                         'num_inference_steps': 167, 'output_type': 'np', 'width': 1024, 'height': 1024, 'parser': 'fixed'}                                                                         
Progress  2.95s/it █▉                                 6% 10/167 00:34 07:43 Base18:51:39-610830 TRACE    Server: alive=True requests=301 memory=32.28/62.74 status='running' task='Inference' timestamp='20260122185023' current='task(t329cjlxf9zi8ld)' id='e566cd0a61be4f2' job=0 
                         jobs=1 total=10 step=0 steps=0 queued=0 uptime=488 elapsed=76.15 eta=None progress=0                                                                                       
Progress  2.77s/it ██████████▏                       32% 53/167 02:34 05:15 Base18:53:39-648716 TRACE    Server: alive=True requests=410 memory=32.33/62.74 status='running' task='Inference' timestamp='20260122185023' current='task(t329cjlxf9zi8ld)' id='e566cd0a61be4f2' job=0 
                         jobs=1 total=10 step=0 steps=0 queued=0 uptime=608 elapsed=196.18 eta=None progress=0                                                                                      
Progress  2.77s/it ██████████████████▌               58% 97/167 04:36 03:13 Base18:55:39-709087 TRACE    Server: alive=True requests=434 memory=32.32/62.74 status='running' task='Inference' timestamp='20260122185023' current='task(t329cjlxf9zi8ld)' id='e566cd0a61be4f2' job=0 
                         jobs=1 total=10 step=0 steps=0 queued=0 uptime=728 elapsed=316.24 eta=None progress=0                                                                                      
Progress  2.87s/it █████████████████████████▊       83% 139/167 06:35 01:20 Base18:57:39-731386 TRACE    Server: alive=True requests=457 memory=32.44/62.74 status='running' task='Inference' timestamp='20260122185023' current='task(t329cjlxf9zi8ld)' id='e566cd0a61be4f2' job=0 
                         jobs=1 total=10 step=0 steps=0 queued=0 uptime=848 elapsed=436.27 eta=None progress=0                                                                                      
Progress  2.85s/it ███████████████████████████████ 100% 167/167 07:55 00:00 Base
18:59:06-493343 INFO     Processing modifiers: unapply                                                                                                                                              
18:59:07-196841 INFO     Save: image="outputs/text/00197-2026-01-22-LongCat-Image.png" type=PNG width=1024 height=1024 size=1423256
```

### Backend

Diffusers

### Compute

nVidia CUDA

### Interface

ModernUI

### Branch

Master

### Model

Other image model

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed.

**Comment by alerikaisattera** [comment]
Still occurs in the latest dev

```
14:44:02-368442 INFO     Starting SD.Next                                                                                                                                                           
14:44:02-372047 INFO     Logger: file="/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/sdnext.log" level=DEBUG host="aleri-pc" size=75 mode=create                                  
14:44:02-373266 INFO     Python: version=3.12.10 platform=Linux bin="/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/venv/bin/python3"                                              
                         venv="/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/venv"                                                                                                
14:44:02-467634 INFO     Version: app=sd.next updated=2026-01-23 commit=69685f198 branch=dev url=https://github.com/vladmandic/sdnext/tree/dev kanvas=main ui=dev                                   
14:44:02-781253 TRACE    Repository branches: active=dev available=['dev', 'master', 'upstream']                                                                                                    
14:44:03-265958 INFO     Version: app=sd.next latest=2026-01-23T08:19:47Z hash=69685f19 branch=dev                                                                                                  
14:44:03-270184 INFO     Platform: arch=x86_64 cpu= system=Linux release=6.12.62-1-MANJARO python=3.12.10 locale=('en_US', 'UTF-8') docker=False                                                    
14:44:03-272863 DEBUG    Packages: prefix=venv site=['venv/lib/python3.12/site-packages']                                                                                                           
14:44:03-275225 INFO     Args: ['--use-cuda', '--update']                                                                                                                                           
14:44:03-276825 DEBUG    Setting environment tuning                                                                                                                                                 
14:44:03-278980 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"                                                                                                 
14:44:03-282361 INFO     Verifying torch installation                                                                                                                                               
14:44:03-283814 DEBUG    Torch overrides: cuda=True rocm=False ipex=False directml=False openvino=False zluda=False                                                                                 
14:44:03-285733 INFO     CUDA: nVidia toolkit detected                                                                                                                                              
14:44:04-699219 INFO     Torch backend: version="2.8.0+cu128" type=CUDA CUDA=12.8 cuDNN=91002                                                                                                       
14:44:04-716653 INFO     Torch detected: gpu="NVIDIA GeForce RTX 4060 Ti" vram=15946 arch=(8, 9) cores=34                                                                                           
14:44:04-718082 INFO     Diffusers update: current=0.37.0.dev0 hash=61f175660a8ac54f1470a74a810e6c38fb4795d5 target=d7a1c31f4f85bae5a9e01cdce49bd7346bd8ccd6                                        
14:44:22-168046 INFO     Install: verifying requirements                                                                                                                                            
14:44:22-173554 INFO     Startup: standard                                                                                                                                                          
14:44:22-174330 INFO     Verifying submodules                                                                                                                                                       
14:44:22-665984 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main                                                                                                             
14:44:23-285997 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main                                                                                                          
14:44:23-912795 DEBUG    Git submodule: extensions-builtin/sdnext-kanvas / main                                                                                                                     
14:44:24-569192 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=dev                                                                                       
14:44:24-570543 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / dev                                                                                                                    
14:44:25-213078 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master                                                                                                    
14:44:25-864772 DEBUG    Git submodule: wiki / master                                                                                                                                               
14:44:26-545002 DEBUG    Installed packages: 263                                                                                                                                                    
14:44:26-546200 DEBUG    Extensions all: ['sdnext-kanvas', 'stable-diffusion-webui-rembg', 'sd-extension-system-info', 'sd-extension-chainner', 'sdnext-modernui']                                  
14:44:26-562557 DEBUG    Git submodule: extensions-builtin/sdnext-kanvas / main                                                                                                                     
14:44:27-209255 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master                                                                                                    
14:44:27-794199 DEBUG    Extension installer: builtin=True file="/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/extensions-builtin/stable-diffusion-webui-rembg/install.py"        
14:44:27-856403 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main                                                                                                          
14:44:28-533184 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main                                                                                                             
14:44:29-244767 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / dev                                                                                                                    
14:44:29-903956 DEBUG    Extensions all: []                                                                                                                                                         
14:44:29-904935 INFO     Extensions enabled: ['sdnext-kanvas', 'stable-diffusion-webui-rembg', 'sd-extension-system-info', 'sd-extension-chainner', 'sdnext-modernui']                              
14:44:29-947644 INFO     Install: verifying requirements                                                                                                                                            
14:44:29-953133 INFO     Updating Wiki                                                                                                                                                              
14:44:29-977629 DEBUG    Git submodule: /run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/wiki / master                                                                               
14:44:30-567190 DEBUG    Setup complete without errors: 1769157871                                                                                                                                  
14:44:30-570620 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}                                                                                                          
14:44:30-572255 INFO     Installer time: total=61.75 diffusers=17.35 pip=17.35 git=8.04 update=7.55 submodules=4.30 torch=1.43 latest=0.89 sd-extension-chainner=0.72 sdnext-modernui=0.68          
                         sd-extension-system-info=0.67 stable-diffusion-webui-rembg=0.65 sdnext-kanvas=0.64 wiki=0.61 branch=0.31 base=0.16 installed=0.12 requirements=0.12                        
14:44:30-575292 INFO     Command line args: ['--use-cuda', '--update'] upgrade=True use_cuda=True args=[]                                                                                           
14:44:30-577358 DEBUG    Flags: sd=['SD_VAE_DEFAULT=true'] ld=['LD_PRELOAD=libtcmalloc.so.4', 'LD_LIBRARY_PATH=:/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/venv/lib/']         
14:44:30-578863 DEBUG    Starting module: <module 'webui' from '/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/webui.py'>                                                          
14:44:30-580781 DEBUG    Initializing: libraries                                                                                                                                                    
14:44:39-162304 DEBUG    System: cores=16 affinity=16 threads=8                                                                                                                                     
14:44:39-166173 INFO     Torch: torch==2.8.0+cu128 torchvision==0.23.0+cu128                                                                                                                        
14:44:39-167076 INFO     Packages: diffusers==0.37.0.dev0 transformers==4.57.5 accelerate==1.12.0 gradio==3.43.2 pydantic==1.10.21 numpy==2.1.2 cv2==4.12.0                                         
14:44:39-176702 DEBUG    Initializing: shared module                                                                                                                                                
14:44:39-226312 DEBUG    Initializing: pipelines                                                                                                                                                    
14:44:39-789801 DEBUG    ONNX: version=1.22.1, available=['AzureExecutionProvider', 'CPUExecutionProvider']                                                                                         
14:44:39-800496 DEBUG    State initialized: id=139680624641904                                                                                                                                      
14:44:39-936297 DEBUG    Initializing: default modes                                                                                                                                                
14:44:39-937414 INFO     Device detect: memory=16.0 default=balanced                                                                                                                                
14:44:39-938955 DEBUG    Initializing: settings                                                                                                                                                     
14:44:39-942857 DEBUG    Read: file="/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/config.json" json=19 bytes=819 time=0.000 fn=__init__:load                                     
14:44:39-944720 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product" mode=no_grad                                                                     
14:44:39-946955 DEBUG    Read: file="html/reference.json" json=100 bytes=50269 time=0.000 fn=_call_with_frames_removed:<module>                                                                     
14:44:39-948066 DEBUG    Initializing: devices                                                                                                                                                      
14:44:39-948821 DEBUG    Torch cuDNN: benchmark=True                                                                                                                                                
14:44:39-949599 DEBUG    Torch attention: type="sdpa" kernels=['Flash', 'Memory', 'Math'] overrides=[]                                                                                              
14:44:39-950921 DEBUG    Torch attention installed: flashattn=False sageattention=False                                                                                                             
14:44:39-951778 DEBUG    Torch attention status: flash=False flash3=False aiter=False sage=False flex=True npu=False xla=False xformers=False                                                       
14:44:41-800677 DEBUG    Triton: pass=True fn=<module>:set_cuda_params time=1.82                                                                                                                    
14:44:41-801962 INFO     Torch parameters: backend=cuda device=cuda config=Auto dtype=torch.bfloat16 context=no_grad nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False,  
                         True] fp16=pass bf16=pass triton=pass optimization="Scaled-Dot-Product"                                                                                                    
14:44:41-817604 DEBUG    Quantization: registered=SDNQ                                                                                                                                              
14:44:41-845261 INFO     Device: device=NVIDIA GeForce RTX 4060 Ti n=1 arch=sm_120 capability=(8, 9) cuda=12.8 cudnn=91002 driver=580.119.02                                                        
14:44:42-286563 DEBUG    Entering start sequence                                                                                                                                                    
14:44:42-288139 DEBUG    Initializing: modules                                                                                                                                                      
14:44:42-289071 DEBUG    Read: file="metadata.json" json=2 bytes=1352 time=0.000 fn=initialize:init_metadata                                                                                        
14:44:42-290194 DEBUG    Read: file="cache.json" json=1 bytes=350 time=0.000 fn=initialize:init_cache                                                                                               
14:44:42-321793 INFO     Available VAEs: path="models/VAE" items=0                                                                                                                                  
14:44:42-323189 INFO     Available UNets: path="models/UNET" items=0                                                                                                                                
14:44:42-324178 INFO     Available TEs: path="models/Text-encoder" items=0                                                                                                                          
14:44:42-326065 INFO     Available Models: safetensors="models/Stable-diffusion":0 diffusers="models/Diffusers":12 reference=100 items=12 time=0.00                                                 
14:44:42-331895 INFO     Available LoRAs: path="models/Lora" items=0 folders=2 time=0.00                                                                                                            
14:44:42-342098 INFO     Available Styles: path="models/styles" items=288 time=0.01                                                                                                                 
14:44:42-377905 INFO     Available Detailer: path="models/yolo" items=14 downloaded=0                                                                                                               
14:44:42-379332 DEBUG    Extensions: disabled=['Lora', 'sd-webui-agent-scheduler']                                                                                                                  
14:44:42-380173 INFO     Load extensions                                                                                                                                                            
14:44:42-685686 DEBUG    Extensions init time: total=0.30 stable-diffusion-webui-rembg=0.17                                                                                                         
14:44:42-852934 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2640 time=0.000 fn=__init__:__init__                                                                                         
14:44:42-854408 DEBUG    Read: file="extensions-builtin/sd-extension-chainner/models.json" json=25 bytes=2803 time=0.000 fn=__init__:find_scalers                                                   
14:44:42-856073 DEBUG    Available chaiNNer: path="models/chaiNNer" defined=25 discovered=0 downloaded=0                                                                                            
14:44:42-857946 INFO     Available Upscalers: items=77 downloaded=1 user=1 time=0.17 types=['None', 'Resize', 'Latent', 'AsymmetricVAE', 'WanUpscale', 'DCC', 'VIPS', 'ChaiNNer', 'Diffusion',      
                         'SwinIR', 'AuraSR', 'SCUNet', 'ESRGAN', 'RealESRGAN', 'SeedVR']                                                                                                            
14:44:42-912521 INFO     Networks: type="video" engines=13 models=71 errors=0 time=0.05                                                                                                             
14:44:42-915142 INFO     Huggingface: transfer=rust parallel=False direct=True token="hf_...rCGg" cache="cache/huggingface/hub" init                                                                
14:44:42-917099 WARNING  Cache location changed: previous="/home/aleri/.cache/huggingface/hub" size=3520 MB                                                                                         
14:44:42-924228 DEBUG    Huggingface: cache="cache/huggingface/hub" size=203113 MB                                                                                                                  
14:44:42-925259 DEBUG    UI start sequence                                                                                                                                                          
14:44:42-926003 DEBUG    UI image support: kanvas=main                                                                                                                                              
14:44:42-929151 INFO     UI locale: name="Auto"                                                                                                                                                     
14:44:42-930106 INFO     UI theme: type=Modern name="Default" available=35                                                                                                                          
14:44:42-931201 DEBUG    UI theme: css="extensions-builtin/sdnext-modernui/themes/Default.css" base="['base.css', 'timesheet.css']" user="None"                                                     
14:44:42-934147 DEBUG    UI initialize: tab=txt2img                                                                                                                                                 
14:44:42-988467 DEBUG    Read: file="html/reference.json" json=100 bytes=50269 time=0.000 fn=list_items:list_reference                                                                              
14:44:42-990075 DEBUG    Read: file="html/reference-quant.json" json=24 bytes=9140 time=0.000 fn=list_items:list_reference                                                                          
14:44:42-991257 DEBUG    Read: file="html/reference-distilled.json" json=20 bytes=9775 time=0.000 fn=list_items:list_reference                                                                      
14:44:42-992416 DEBUG    Read: file="html/reference-community.json" json=15 bytes=5737 time=0.000 fn=list_items:list_reference                                                                      
14:44:42-993517 DEBUG    Read: file="html/reference-cloud.json" json=2 bytes=677 time=0.000 fn=list_items:list_reference                                                                            
14:44:43-002759 DEBUG    Networks: type="reference" {'total': 161, 'ready': 11, 'hidden': 0, 'experimental': 0, 'base': 99, 'quantized': 24, 'community': 15, 'distilled': 19, 'cloud': 2}          
14:44:43-011691 DEBUG    Networks: type="model" items=171 subfolders=8 tab=txt2img folders=['models/Stable-diffusion', 'models/Reference',                                                          
                         '/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/models/Stable-diffusion'] list=0.04 thumb=0.00 desc=0.00 info=0.01 workers=12                             
14:44:43-014909 DEBUG    Networks: type="lora" items=0 subfolders=1 tab=txt2img folders=['models/Lora'] list=0.02 thumb=0.01 desc=0.00 info=0.00 workers=12                                         
14:44:43-024487 DEBUG    Networks: type="style" items=288 subfolders=3 tab=txt2img folders=['models/styles', 'html'] list=0.02 thumb=0.01 desc=0.00 info=0.00 workers=12                            
14:44:43-028015 DEBUG    Networks: type="wildcards" items=0 subfolders=1 tab=txt2img folders=['models/wildcards'] list=0.01 thumb=0.00 desc=0.00 info=0.00 workers=12                               
14:44:43-030363 DEBUG    Networks: type="embedding" items=0 subfolders=1 tab=txt2img folders=['models/embeddings'] list=0.01 thumb=0.01 desc=0.00 info=0.00 workers=12                              
14:44:43-033467 DEBUG    Networks: type="vae" items=0 subfolders=1 tab=txt2img folders=['models/VAE'] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=12                                           
14:44:43-037579 DEBUG    Networks: type="history" items=0 subfolders=1 tab=txt2img folders=[] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=12                                                   
14:44:43-433975 DEBUG    UI initialize: tab=img2img                                                                                                                                                 
14:44:43-869840 DEBUG    UI initialize: tab=control models="models/control"                                                                                                                         
14:44:44-598194 DEBUG    UI initialize: tab=video                                                                                                                                                   
14:44:44-761146 DEBUG    UI initialize: tab=process                                                                                                                                                 
14:44:44-837058 DEBUG    UI initialize: tab=caption                                                                                                                                                 
14:44:44-942698 DEBUG    UI initialize: tab=models                                                                                                                                                  
14:44:45-049589 DEBUG    UI initialize: tab=gallery                                                                                                                                                 
14:44:45-106024 DEBUG    Read: file="ui-config.json" json=0 bytes=2 time=0.000 fn=__init__:read_from_file                                                                                           
14:44:45-107288 DEBUG    UI initialize: tab=settings                                                                                                                                                
14:44:46-142897 DEBUG    Settings: sections=22 settings=374/616 quicksettings=1                                                                                                                     
14:44:46-222115 DEBUG    UI initialize: tab=info                                                                                                                                                    
14:44:46-252813 DEBUG    UI initialize: tab=extensions                                                                                                                                              
14:44:46-259700 INFO     Extension List: No information found. Refresh required.                                                                                                                    
14:44:46-361539 DEBUG    Extension list: processed=5 installed=5 enabled=3 disabled=2 visible=5 hidden=0                                                                                            
14:44:46-625781 DEBUG    Root paths: ['/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext', 'models']                                                                                  
14:44:46-755739 INFO     Local URL: http://127.0.0.1:7860/                                                                                                                                          
14:44:46-756808 INFO     API docs: http://127.0.0.1:7860/docs                                                                                                                                       
14:44:46-757659 INFO     API redocs: http://127.0.0.1:7860/redocs                                                                                                                                   
14:44:46-758933 DEBUG    API middleware: [<class 'starlette.middleware.base.BaseHTTPMiddleware'>, <class 'starlette.middleware.gzip.GZipMiddleware'>]                                               
14:44:46-759915 DEBUG    API initialize                                                                                                                                                             
14:44:47-126809 DEBUG    Scripts setup: time=0.754 ['XYZ Grid:0.101', 'IP Adapters:0.076', 'Prompt enhance:0.059', 'Mixture-of-Diffusers: Tile Control:0.045', 'Face: Multiple ID Transfers:0.044', 
                         'NudeNet:0.03']                                                                                                                                                            
14:44:47-128456 DEBUG    Model metadata: file="metadata.json" no changes                                                                                                                            
14:44:47-129397 INFO     Model: autoload=False selected="Diffusers/meituan-longcat/LongCat-Image [d2ea50b79a]"                                                                                      
14:44:47-130801 DEBUG    Script init: ['system-info.py:app_started=0.14']                                                                                                                           
14:44:47-131634 INFO     Startup time: total=101.85 launch=28.67 loader=28.44 installer=28.43 gradio=3.86 libraries=3.63 torch=3.25 ui-extensions=1.23 diffusers=0.89 ui-control=0.52               
                         ui-networks=0.48 ui-img2img=0.36 ui-txt2img=0.35 extensions=0.30 api=0.23 upscalers=0.17 ui-defaults=0.16 app-started=0.14 ui-models=0.14                                  
14:44:47-136794 DEBUG    Save: file="/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/config.json" json=19 bytes=819 time=0.003                                                      
14:45:10-431150 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/motd 127.0.0.1 0.1162                                                                                                        
14:45:31-121642 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/sd-models 127.0.0.1 0.0042                                                                                                   
14:45:32-212373 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/version 127.0.0.1 0.0012                                                                                                     
14:45:32-433764 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36                    
14:45:32-438546 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/start 127.0.0.1 0.0078                                                                                                       
14:45:32-488212 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/version 127.0.0.1 0.0084                                                                                                     
14:45:32-491737 DEBUG    UI: connected                                                                                                                                                              
14:45:36-606331 INFO     UI: ready time=26804                                                                                                                                                       
14:45:51-434943 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/network/desc 127.0.0.1 0.0021                                                                                                
14:46:03-873765 DEBUG    Search model: name="Diffusers/black-forest-labs/FLUX.2-klein-4B [5e67da950f]"                                                                                              
                         matched="models/Diffusers/models--black-forest-labs--FLUX.2-klein-4B/snapshots/5e67da950fce4a097bc150c22958a05716994cea" type=alias                                        
14:46:03-876360 INFO     Load model: select="Diffusers/black-forest-labs/FLUX.2-klein-4B [5e67da950f]"                                                                                              
14:46:03-880173 INFO     Autodetect model: detect="FLUX2 Klein" class=Flux2KleinPipeline                                                                                                            
                         file="models/Diffusers/models--black-forest-labs--FLUX.2-klein-4B/snapshots/5e67da950fce4a097bc150c22958a05716994cea"                                                      
14:46:03-881523 DEBUG    Cache clear                                                                                                                                                                
14:46:03-925896 DEBUG    Load model: type=Flux2Klein repo="black-forest-labs/FLUX.2-klein-4B" config={'low_cpu_mem_usage': True, 'torch_dtype': torch.bfloat16, 'load_connected_pipeline': True,    
                         'safety_checker': None, 'requires_safety_checker': False} offload=balanced dtype=torch.bfloat16 args={'torch_dtype': torch.bfloat16}                                       
14:46:03-929677 DEBUG    Quantization: module="Model" type=sdnq mode=pre dtype=int8 svd=False dynamic=False group=0 loss=0.01 matmul_dtype=auto matmul_quant=False matmul_conv=False                
                         quant_conv=False fp32=False device=cuda return=cuda use_gpu=True map=default offload=balanced non_blocking=False skip_modules=[] dict={}                                   
14:46:03-933621 DEBUG    Load model: transformer="black-forest-labs/FLUX.2-klein-4B" cls=Flux2Transformer2DModel subfolder=transformer quant="SDNQConfig" loader=default args={'torch_dtype':       
                         torch.bfloat16}                                                                                                                                                            
14:46:47-540727 TRACE    Server: alive=True requests=116 memory=19.25/62.74 status='running' task='Load DiT' timestamp='20260123144603' current='' id='a1acd1bfbec64ef' job=0 jobs=1 total=2 step=0 
                         steps=0 queued=0 uptime=128 elapsed=43.61 eta=None progress=0                                                                                                              
14:47:00-900905 DEBUG    GC: current={'gpu': 1.48, 'ram': 22.67, 'oom': 0} prev={'gpu': 5.32, 'ram': 22.68} load={'gpu': 10, 'ram': 36} gc={'gpu': 3.84, 'py': 496}                                 
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.37                                                                                                
14:47:00-907472 DEBUG    Quantization: module="TE" type=sdnq mode=pre dtype=int8 svd=False dynamic=False group=0 loss=0.01 matmul_dtype=auto matmul_quant=False matmul_conv=False  quant_conv=False 
                         fp32=False device=cuda return=cuda use_gpu=True map=default offload=balanced non_blocking=False skip_modules=[] dict={}                                                    
14:47:00-909396 DEBUG    Load model: text_encoder="Tongyi-MAI/Z-Image-Turbo" cls=Qwen3ForCausalLM quant="SDNQConfig" loader=default shared=True                                                     
Progress 17.31s/it ██████████████ 100% 3/3 00:51 00:00 Loading checkpoint shards
14:47:56-011450 DEBUG    GC: current={'gpu': 1.46, 'ram': 26.19, 'oom': 0} prev={'gpu': 5.21, 'ram': 26.22} load={'gpu': 9, 'ram': 42} gc={'gpu': 3.75, 'py': 357}                                  
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.43                                                                                                
Progress  4.10it/s █████████ 100% 5/5 00:01 00:00 Loading pipeline components...
14:47:58-147268 DEBUG    GC: current={'gpu': 1.47, 'ram': 26.31, 'oom': 0} prev={'gpu': 1.47, 'ram': 26.31} load={'gpu': 9, 'ram': 42} gc={'gpu': 0.0, 'py': 131}                                   
                         fn=load_diffuser_force:load_flux2_klein why=load time=0.37                                                                                                                 
14:47:58-150203 DEBUG    Setting model: component=vae {'slicing': True, 'tiling': False}                                                                                                            
14:47:58-151597 DEBUG    Setting model: attention="Scaled-Dot-Product"                                                                                                                              
14:47:58-153172 INFO     Offload: type=balanced op=init watermark=0.2-0.84 gpu=3.20-13.44:16.00 cpu=63.000 limit=0.00 always=[] never=[] pre=True streams=False                                     
14:47:58-168191 DEBUG    Module: name=text_encoder cls=Qwen3ForCausalLM size=4.112 params=4024495616 quant=QuantizationMethod.SDNQ                                                                  
14:47:58-173180 DEBUG    Module: name=transformer cls=Flux2Transformer2DModel size=3.798 params=3879138816 quant=QuantizationMethod.SDNQ                                                            
14:47:58-177230 DEBUG    Module: name=vae cls=AutoencoderKLFlux2 size=0.157 params=84046115 quant=None                                                                                              
14:47:58-179023 INFO     Model class=Flux2KleinPipeline modules=3 size=8.067                                                                                                                        
14:47:59-782076 INFO     Load model: family=f2 time={'total': 115.9, 'load': 114.27, 'move': 1.63} native=1024 memory={'ram': {'total': 62.74, 'rss': 21.97, 'used': 26.36, 'free': 0.45, 'avail':  
                         36.39, 'buffers': 0.03, 'cached': 37.94}, 'gpu': {'used': 1.66, 'total': 15.57, 'active': 0.16, 'peak': 3.83, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': ''}               
14:47:59-812007 DEBUG    Save: file="/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/config.json" json=19 bytes=823 time=0.022                                                      
14:48:02-089823 DEBUG    Search model: name="Diffusers/meituan-longcat/LongCat-Image [d2ea50b79a]"                                                                                                  
                         matched="models/Diffusers/models--meituan-longcat--LongCat-Image/snapshots/d2ea50b79a930074c37b9b97ce45e3b2ea8cf4d8" type=alias                                            
14:48:02-092612 INFO     Load model: select="Diffusers/meituan-longcat/LongCat-Image [d2ea50b79a]"                                                                                                  
14:48:02-098902 DEBUG    Cache clear                                                                                                                                                                
14:48:02-101240 DEBUG    Current model: {'ram': {'total': 62.74, 'rss': 21.97, 'used': 26.49, 'free': 0.5, 'avail': 36.25, 'buffers': 0.03, 'cached': 37.76}, 'gpu': {'used': 1.64, 'total': 15.57, 
                         'active': 0.16, 'peak': 3.83, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': 'Load model'}                                                                                     
14:48:02-994739 DEBUG    GC: current={'gpu': 1.48, 'ram': 26.49, 'oom': 0} prev={'gpu': 1.64, 'ram': 26.49} load={'gpu': 10, 'ram': 42} gc={'gpu': 0.16, 'py': 638}                                 
                         fn=reload_model_weights:unload_model_weights why=unload time=0.39                                                                                                          
14:48:02-997086 DEBUG    Unload model: {'ram': {'total': 62.74, 'rss': 8.35, 'used': 26.49, 'free': 0.5, 'avail': 36.26, 'buffers': 0.03, 'cached': 37.77}, 'gpu': {'used': 1.48, 'total': 15.57,   
                         'active': 0.0, 'peak': 3.83, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': 'Load model'} fn=<lambda>:reload_model_weights                                                     
14:48:03-034895 INFO     Autodetect model: detect="LongCat" class=LongCatImagePipeline                                                                                                              
                         file="models/Diffusers/models--meituan-longcat--LongCat-Image/snapshots/d2ea50b79a930074c37b9b97ce45e3b2ea8cf4d8"                                                          
14:48:03-036163 DEBUG    Cache clear                                                                                                                                                                
14:48:03-043853 DEBUG    Load model: type=LongCat repo="meituan-longcat/LongCat-Image" config={'low_cpu_mem_usage': True, 'torch_dtype': torch.bfloat16, 'load_connected_pipeline': True,           
                         'safety_checker': None, 'requires_safety_checker': False} offload=balanced dtype=torch.bfloat16 args={'low_cpu_mem_usage': True, 'torch_dtype': torch.bfloat16,            
                         'load_connected_pipeline': True, 'safety_checker': None, 'requires_safety_checker': False}                                                                                 
14:48:03-046423 DEBUG    Quantization: module="Model" type=sdnq mode=pre dtype=int8 svd=False dynamic=False group=0 loss=0.01 matmul_dtype=auto matmul_quant=False matmul_conv=False                
                         quant_conv=False fp32=False device=cuda return=cuda use_gpu=True map=default offload=balanced non_blocking=False skip_modules=[] dict={}                                   
14:48:03-048516 DEBUG    Load model: transformer="meituan-longcat/LongCat-Image" cls=LongCatImageTransformer2DModel subfolder=transformer quant="SDNQConfig" loader=default args={'torch_dtype':    
                         torch.bfloat16}                                                                                                                                                            
14:48:48-169613 TRACE    Server: alive=True requests=141 memory=26.43/62.74 status='running' task='Load DiT' timestamp='20260123144803' current='' id='71298d6e07b84ef' job=0 jobs=1 total=5 step=0 
                         steps=0 queued=0 uptime=249 elapsed=45.12 eta=None progress=0                                                                                                              
14:50:06-115607 DEBUG    GC: current={'gpu': 1.43, 'ram': 26.53, 'oom': 0} prev={'gpu': 7.43, 'ram': 26.58} load={'gpu': 9, 'ram': 42} gc={'gpu': 6.0, 'py': 20950}                                 
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.53                                                                                                
14:50:06-129830 DEBUG    Quantization: module="TE" type=sdnq mode=pre dtype=int8 svd=False dynamic=False group=0 loss=0.01 matmul_dtype=auto matmul_quant=False matmul_conv=False  quant_conv=False 
                         fp32=False device=cuda return=cuda use_gpu=True map=default offload=balanced non_blocking=False skip_modules=[] dict={}                                                    
14:50:06-132454 DEBUG    Load model: text_encoder="hunyuanvideo-community/HunyuanImage-2.1-Diffusers" cls=Qwen2_5_VLForConditionalGeneration quant="SDNQConfig" loader=default shared=True          
Progress 27.84s/it ███▌            25% 1/4 00:27 01:23 Loading checkpoint shards14:50:48-218979 TRACE    Server: alive=True requests=164 memory=26.58/62.74 status='running' task='Load TE' timestamp='20260123145006' current='' id='6b0eff677610468' job=0 jobs=1 total=6 step=0  
                         steps=0 queued=0 uptime=369 elapsed=42.09 eta=None progress=0                                                                                                              
Progress 29.19s/it ██████████████ 100% 4/4 01:56 00:00 Loading checkpoint shards
14:52:07-302881 DEBUG    GC: current={'gpu': 1.44, 'ram': 32.36, 'oom': 0} prev={'gpu': 8.86, 'ram': 32.31} load={'gpu': 9, 'ram': 52} gc={'gpu': 7.42, 'py': 456}                                  
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.47                                                                                                
Progress  7.04it/s █████████ 100% 6/6 00:00 00:00 Loading pipeline components...
14:52:13-824701 DEBUG    GC: current={'gpu': 1.45, 'ram': 32.4, 'oom': 0} prev={'gpu': 1.45, 'ram': 32.41} load={'gpu': 9, 'ram': 52} gc={'gpu': 0.0, 'py': 131} fn=load_diffuser_force:load_longcat
                         why=load time=0.42                                                                                                                                                         
14:52:13-826978 DEBUG    Setting model: component=vae {'slicing': True, 'tiling': False}                                                                                                            
14:52:13-827882 DEBUG    Setting model: attention="Scaled-Dot-Product"                                                                                                                              
14:52:13-828845 INFO     Offload: type=balanced op=init watermark=0.2-0.84 gpu=3.20-13.44:16.00 cpu=63.000 limit=0.00 always=[] never=[] pre=True streams=False                                     
14:52:13-847959 DEBUG    Module: name=text_encoder cls=Qwen2_5_VLForConditionalGeneration size=8.749 params=8296860928 quant=QuantizationMethod.SDNQ                                                
14:52:13-856127 DEBUG    Module: name=transformer cls=LongCatImageTransformer2DModel size=5.917 params=6276723776 quant=QuantizationMethod.SDNQ                                                     
14:52:13-860271 DEBUG    Module: name=vae cls=AutoencoderKL size=0.156 params=83819683 quant=None                                                                                                   
14:52:13-861638 INFO     Model class=LongCatImagePipeline modules=3 size=14.822                                                                                                                     
14:52:15-258015 INFO     Load model: family=longcat time={'total': 252.26, 'load': 250.83, 'move': 1.43} native=1024 memory={'ram': {'total': 62.74, 'rss': 38.7, 'used': 32.44, 'free': 0.56,      
                         'avail': 30.3, 'buffers': 0.0, 'cached': 32.15}, 'gpu': {'used': 1.61, 'total': 15.57, 'active': 0.16, 'peak': 7.21, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': ''}        
14:52:15-278111 DEBUG    Save: file="/run/media/aleri/60b6f25f-f89b-41ea-929b-31bc47e210bc/AI/sdnext/config.json" json=19 bytes=819 time=0.015                                                      
14:52:20-090665 DEBUG    Gallery: type=ws folder="outputs/text" files=198 time=0.033                                                                                                                
14:52:24-916568 DEBUG    Prompt parse: type="current" prompt="a pack of feral wizards caught on a security camera                                                                                   
                         Negative prompt:                                                                                                                                                           
                         Steps: 50, Size: 1024x1024, Seed: 318744544, CFG scale: 6, App: SD.Next, Version: 3ae1018, Pipeline: LongCatImagePipeline, Operations: txt2img, Model: LongCat-Image"      
14:52:24-923514 DEBUG    Prompt restore: apply=[{'Prompt': 'a pack of feral wizards caught on a security camera'}, {'Size-1': 1024}, {'Size-2': 1024}, {'Steps': 50}, {'Seed': 318744544.0}, {'CFG  
                         scale': 6.0}] skip={'Negative prompt': ''}                                                                                                                                 
14:52:29-493091 DEBUG    Pipeline class change: original=LongCatImagePipeline target=LongCatImagePipeline device=cpu fn=process_images_inner:init                                                   
14:52:29-677046 DEBUG    Pipeline class change: original=LongCatImagePipeline target=LongCatImagePipeline device=cpu fn=process_images_inner:process_diffusers                                      
14:52:29-730856 DEBUG    Sampler: "Default" cls=FlowMatchEulerDiscreteScheduler config={'num_train_timesteps': 1000, 'shift': 3.0, 'use_dynamic_shifting': True, 'base_shift': 0.5, 'max_shift':    
                         1.15, 'base_image_seq_len': 256, 'max_image_seq_len': 4096, 'invert_sigmas': False, 'shift_terminal': None, 'use_karras_sigmas': False, 'use_exponential_sigmas': False,   
                         'use_beta_sigmas': False, 'time_shift_type': 'exponential', 'stochastic_sampling': False}                                                                                  
14:52:30-447087 INFO     Processing modifiers: apply                                                                                                                                                
14:52:30-990137 INFO     Base: pipeline=LongCatImagePipeline task=IMAGE_2_IMAGE batch=1/1x1 set={'prompt': 1, 'negative_prompt': 1, 'guidance_scale': 6, 'generator': 'cuda:[318744544]',           
                         'num_inference_steps': 167, 'output_type': 'np', 'width': 1024, 'height': 1024, 'parser': 'fixed'}                                                                         
14:52:48-234292 TRACE    Server: alive=True requests=228 memory=32.44/62.74 status='running' task='Inference' timestamp='20260123145230' current='task(qyzplsyzo5uc1tt)' id='2eb000c971a54a4' job=0 
                         jobs=1 total=12 step=0 steps=0 queued=0 uptime=489 elapsed=17.24 eta=None progress=0                                                                                       
Progress  2.85s/it ██████▋                           21% 35/167 01:44 06:16 Base14:54:48-305994 TRACE    Server: alive=True requests=382 memory=35.16/62.74 status='running' task='Inference' timestamp='20260123145230' current='task(qyzplsyzo5uc1tt)' id='2eb000c971a54a4' job=0 
                         jobs=1 total=12 step=0 steps=0 queued=0 uptime=609 elapsed=137.31 eta=None progress=0                                                                                      
Progress  2.87s/it ██████████████▉                   47% 78/167 03:46 04:15 Base14:56:48-360881 TRACE    Server: alive=True requests=406 memory=35.16/62.74 status='running' task='Inference' timestamp='20260123145230' current='task(qyzplsyzo5uc1tt)' id='2eb000c971a54a4' job=0 
                         jobs=1 total=12 step=0 steps=0 queued=0 uptime=729 elapsed=257.37 eta=None progress=0                                                                                      
Progress  2.80s/it ██████████████████████▎          72% 120/167 05:44 02:11 Base14:58:48-390192 TRACE    Server: alive=True requests=430 memory=35.25/62.74 status='running' task='Inference' timestamp='20260123145230' current='task(qyzplsyzo5uc1tt)' id='2eb000c971a54a4' job=0 
                         jobs=1 total=12 step=0 steps=0 queued=0 uptime=849 elapsed=377.4 eta=None progress=0                                                                                       
Progress  2.86s/it ██████████████████████████████   97% 162/167 07:44 00:14 Base15:00:48-414395 TRACE    Server: alive=True requests=454 memory=34.09/62.74 status='running' task='Inference' timestamp='20260123145230' current='task(qyzplsyzo5uc1tt)' id='2eb000c971a54a4' job=0 
                         jobs=1 total=12 step=0 steps=0 queued=0 uptime=969 elapsed=497.42 eta=None progress=0                                                                                      
Progress  2.86s/it ███████████████████████████████ 100% 167/167 07:57 00:00 Base

```

**Comment by vladmandic** [comment]
ah, i fixed it for detailer/refiner/hires, but not for base. updated.
