### ISSUE TITLE
[ZLUDA] RX 7700 XT: "zluda_get_hip_object not found" and "CUDA error: operation not supported" (ROCm 7.1 / Torch 2.7.1)

### ISSUE THREAD

**Issue by EXtreMe6999** [vladmandic/automatic#4647]
### Issue Description

This is a clean installation. I have completely reinstalled Python, SD.Next, and manually placed the ZLUDA binaries to ensure no legacy conflicts. While the GPU and VRAM are detected correctly, generation fails immediately.

The Problem:

1.  ZLUDA Initialization Error: During startup, I encounter the following error: **ERROR Load ZLUDA: function** **'zluda_get_hip_object' not found.**

2.  Generation Failure: When attempting to generate (using Juggernaut XL), the process crashes with: **RuntimeError: CUDA error: operation not supported pointing to torch.embedding in functional.py:2551.**

_**Attempted Fixes:**_

- Forced full precision (--no-half).
- Manually updated ZLUDA binaries (v3.12.11)
- Reinstall Python (3.12.0)
- Clean SD Next with ZLUDA

**Full console log**
*in txt file* 

[CWindowsSystem32cmd.exe - .webui.bat  --use-zluda --debug --autolaunch.txt](https://github.com/user-attachments/files/25278514/CWindowsSystem32cmd.exe.-.webui.bat.--use-zluda.--debug.--autolaunch.txt)

Errors on screenshoots:

<img width="1115" height="628" alt="Image" src="https://github.com/user-attachments/assets/620e615a-d124-43f9-8eab-d4b5e391511a" />

<img width="1115" height="628" alt="Image" src="https://github.com/user-attachments/assets/210a5d16-f9de-4296-92b2-47690ab73308" />

I am asking for help, have a nice day!

### Version Platform Description

System Information:

- OS: Windows 11

- GPU: AMD Radeon RX 7700 XT (agent: gfx1101)

- VRAM: 12272 MB

- Python Version: 3.12.0

- Browser:  Brave v1.87.186

- Torch Version: 2.7.1+cu118

- ROCm Version: 7.1

- Engine: Juggernaut XL

- SD Backend: SD.Next with ZLUDA

### Relevant log output

```shell
03:16:03-137390 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=True
03:16:03-228281 INFO     ROCm: agents=['gfx1101']
03:16:03-228281 INFO     ROCm: version=7.1, using agent gfx1101
03:16:03-235332 ERROR    Load ZLUDA: function 'zluda_get_hip_object' not found
03:16:03-236337 INFO     ROCm: HSA_OVERRIDE_GFX_VERSION config overridden: device=gfx1101 version=11.0.0
03:16:04-885908 INFO     Torch backend: version="2.7.1+cu118" type=CUDA CUDA=11.8 cuDNN=90100
03:16:04-888457 INFO     Torch detected: gpu="AMD Radeon RX 7700 XT [ZLUDA]" vram=12272 arch=(8, 8) cores=27

RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### Operating system

Windows

### Compute

ZLUDA

### Interface

ModernUI

### Branch

Master

### Model

Other image model

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
cc @lshqqytiger

**Comment by EXtreMe6999** [comment]
### Quick update & a new issue regarding ROCm version detection:

First off, my previous problem was likely my own mistake – I didn't use the newest ZLUDA release and wasn't aware that only the latest one properly supports ROCm 7.1. That part should be sorted out now.

However, I've run into a new, bizarre issue. Just yesterday, SD.Next correctly detected **rocm = 7.1**. 
Today, for some unknown reason, the startup log shows **rocm = 7.2**. 

<img width="1091" height="187" alt="Image" src="https://github.com/user-attachments/assets/91c5882e-6a1d-4c94-8699-e4f337b92fa8" />

I strongly suspect it's pulling the HIP runtime pre-installed with the latest AMD Adrenalin drivers directly from System32.

I tried to force it back to 7.1 and did the following:

- Added the C:\Program Files\AMD\ROCm\7.1\bin directory to the absolute top of my System Path environment variables.

<img width="1164" height="599" alt="Image" src="https://github.com/user-attachments/assets/9beb5772-330b-4591-996f-02f5079c3b5c" />

- Noticed AMD's new naming convention (amdhip64_7.dll), so I created a copy of it and renamed it to standard amdhip64.dll inside the C:\Program Files\AMD\ROCm\7.1\bin folder just to be safe.

<img width="961" height="403" alt="Image" src="https://github.com/user-attachments/assets/572342ea-4b0a-4f9e-bde7-3f7b24ad4241" />

- Ran where amdhip64.dll and where amdhip64_7.dll in CMD. Both correctly prioritize and show the C:\Program Files\AMD\ROCm\7.1\bin path at the very top of the list, ahead of System32.

<img width="511" height="314" alt="Image" src="https://github.com/user-attachments/assets/90b37a52-cfd5-4701-90be-7bf5a0506d20" />

Despite all this, SD.Next still reports **rocm = 7.2** on startup. 
It seems the application is completely ignoring the Windows Path priority.

Does anyone know how to strictly enforce the 7.1 path without having to use DDU to completely nuke the Adrenalin drivers?

Thanks for the CC, @vladmandic . @Ishqqytiger, here is a quick update and a new issue I've run into regarding ROCm version detection.

**Comment by EXtreMe6999** [comment]
**Final Update & Solution:**

I've finally managed to get everything working perfectly, and I wanted to share the solution to close this thread for future users. 
It turns out all the issues were self-inflicted due to my misunderstanding of how Python environments and the ZLUDA/ROCm stack interact.

**The Initial Error (ERROR Load ZLUDA / hipGetDeviceProperties):**
This was caused by using an outdated ZLUDA release. The older versions do not support ROCm 7.1. Updating to the latest release fixed the core compatibility issue.

**The "Ghost" ROCm 7.2 Issue:**
This appeared because I tried "testing" the --rocm and --directml flags when ZLUDA wasn't working. These flags triggered a local download of the native ROCm 7.2 SDK directly into my venv/Lib/site-packages. Since Python prioritizes local site-packages over the system PATH, it was pulling version 7.2 from the venv and ignoring my 7.1 system installation.

**The "Fixes":**
_All my previous attempts—tweaking system PATH variables, renaming amdhip64_7.dll, and copying files—were completely unnecessary and unjustified._

**Conclusion: A clean venv installation using only the --use-zluda flag (avoiding --rocm or --directml) was the real fix. 
I apologize for the noise caused by my lack of knowledge regarding Python library isolation and ROCm dependencies. I’m leaving this thread here as a reference for anyone else who might overcomplicate their setup.**

Thanks again for the support! <3

**Comment by lshqqytiger** [comment]
I'm glad to hear that your issue was resolved. For your information, you can expect a better performance with AMD ROCm backend (`--use-rocm`) than ZLUDA since your card is directly supported by AMD's TheRock project that offers the official ROCm PyTorch release. For more information, please check the wiki pages.
[AMD ROCm](https://github.com/vladmandic/sdnext/wiki/AMD-ROCm)
[ZLUDA](https://github.com/vladmandic/sdnext/wiki/ZLUDA)
