### ISSUE TITLE
[Issue]: ROCm TensileLibrary.dat: No such file or directory for GPU arch: gfx1100

### ISSUE THREAD

**Issue by klausman** [vladmandic/automatic#4737]
### Issue Description

sdnext starts up fine, but as soon as I try to create an image, sdnext crashes with the error in the subject/log below. haveing both `/` and `\` in that path looks like a Windows/Unix path munging issue.

### Version Platform Description

Debian forky (testing).

15:50:16-695599 INFO     Starting SD.Next
15:50:16-697141 INFO     Logger: file="/home/klausman/sdnext/automatic/sdnext.log" level=DEBUG host="carter" size=73 mode=append
15:50:16-697747 INFO     Python: version=3.12.12 platform=Linux bin="/home/klausman/sdnext/automatic/venv/bin/python3" venv="/home/klausman/sdnext/automatic/venv"
15:50:16-699270 INFO     Platform: arch=x86_64 cpu= system=Linux release=7.0.0-rc6 python=3.12.12 locale=('en_US', 'UTF-8') setuptools=69.5.1 docker=False
15:50:16-709008 INFO     Version: app=sd.next updated=2026-04-04 commit=0eb4a98e0 branch=master url=https://github.com/vladmandic/sdnext/tree/master kanvas=main ui=main
15:50:16-766948 TRACE    Repository branches: active=master available=['dev', 'feat/flux2-klein-lora', 'feat/tag-dictionaries', 'fix/sdnq-lora-swap', 'master']
15:50:16-790242 INFO     Version: app=sd.next latest=2026-04-04T09:10:28Z hash=0eb4a98e branch=master
15:50:16-790816 DEBUG    Packages: prefix=venv site=['venv/lib/python3.12/site-packages']
15:50:16-791362 INFO     Args: ['--config', '../config/config.json', '--ui-config', '../config/ui-config.json', '--models-dir', '../models', '--listen', '--insecure', '--use-rocm']
15:50:16-791825 DEBUG    Setting environment tuning
15:50:16-792291 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
15:50:16-793188 INFO     Torch: verifying installation
15:50:16-793572 DEBUG    Torch overrides: cuda=False rocm=True ipex=False directml=False openvino=False zluda=False
15:50:16-823057 INFO     ROCm: agents=['gfx1100']
15:50:16-823511 INFO     ROCm: version=7.1, using agent gfx1100
15:50:17-555689 INFO     Torch backend: {'version': '2.11.0+rocm7.1', 'type': 'rocm', 'hip': '7.1.52802'}
15:50:17-556738 INFO     Torch detected: {'gpu': 'AMD Radeon RX 7900 XTX', 'vram': 24560, 'arch': '11.0 Unknown', 'cores': 48}
15:50:17-571455 INFO     Install: verifying requirements
15:50:17-594817 DEBUG    State: cached=True
15:50:17-595299 INFO     Startup: launch=quick
15:50:17-595729 INFO     Extensions: disabled=[]
15:50:17-596163 INFO     Extensions: path="extensions-builtin" enabled=['sd-extension-chainner', 'sd-extension-system-info', 'sdnext-modernui', 'stable-diffusion-webui-rembg', 'sdnext-kanvas']
15:50:17-596806 INFO     Extensions: path="extensions" enabled=['sdwebui-close-confirmation-dialogue', 'PromptHub', 'enso', 'adetailer', 'sd-webui-prompt-format']

### Relevant log output

```shell
15:50:28-104439 INFO     Network load: type=embeddings loaded=30 skipped=2 time=2.98
15:50:28-105294 DEBUG    Setting model: component=vae {'upcast': True, 'slicing': True, 'tiling': False}
15:50:28-105766 DEBUG    Setting model: attention="Scaled-Dot-Product"
15:50:28-106456 INFO     Offload: type=balanced op=init watermark=0.2-0.8 gpu=4.80-19.20:24.00 cpu=62.000 limit=0.95 always=['T5EncoderModel', 'UMT5EncoderModel'] never=['CLIPTextModel', 'CLIPTextModelWithProjection', 'AutoencoderKL'] pre=True streams=False
15:50:28-119632 DEBUG    Module: name=unet cls=UNet2DConditionModel size=4.782 params=2567463684 quant=None
15:50:28-121806 DEBUG    Module: name=text_encoder_2 cls=CLIPTextModelWithProjection size=1.297 params=696096000 quant=None
15:50:28-123102 DEBUG    Module: name=text_encoder cls=CLIPTextModel size=0.231 params=123922176 quant=None
15:50:28-124547 DEBUG    Module: name=vae cls=AutoencoderKL size=0.156 params=83653863 quant=None
15:50:28-125155 INFO     Model class=StableDiffusionXLPipeline modules=4 size=6.465
15:50:28-126785 INFO     Load model: family=sdxl time={'total': 3.33, 'embeddings': 2.98, 'load': 0.33} native=1024 memory={'ram': {'total': 62.45, 'rss': 2.9, 'used': 7.37, 'free': 22.72, 'avail': 55.09, 'buffers': 0.0, 'cached': 33.3}, 'gpu': {'used': 0.31, 'total': 23.98, 'active': 0.0, 'peak': 0.42, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': 'Load model'}
15:50:28-129042 DEBUG    Script init: ['system-info.py:app_started=0.30', 'enso.py:app_started=0.09']
15:50:28-129686 INFO     Startup time: total=13.43 checkpoint=3.34 libraries=1.68 torch=1.62 launch=1.17 loader=0.97 installer=0.97 ui-networks=0.71 ui-extensions=0.59 gradio=0.39 app-started=0.39 diffusers=0.24 ui-txt2img=0.22 extensions=0.22 ui-control=0.19 ui-img2img=0.15 scans=0.12
15:50:28-135513 DEBUG    Save: file="/home/klausman/sdnext/config/config.json" json=55 bytes=2790 time=0.007
15:50:28-136123 DEBUG    Save: file="/home/klausman/sdnext/automatic/secrets.json" json=3 bytes=203 time=0.000
15:50:29-458756 DEBUG    UI: connected
15:50:44-991755 INFO     Applying HyperTile: unet=128/256
15:50:44-996939 DEBUG    Sampler: "Default" cls=EulerAncestralDiscreteScheduler config={'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'trained_betas': None, 'prediction_type': 'epsilon', 'timestep_spacing': 'trailing', 'steps_offset': 1, 'rescale_betas_zero_snr': False, 'interpolation_type': 'linear', 'use_karras_sigmas': False, 'clip_sample': False, 'sample_max_value': 1.0, 'set_alpha_to_one': False, 'skip_prk_steps': True}
15:50:45-001742 INFO     Processing modifiers: apply
15:50:45-021281 DEBUG    Tokenizer: words=50530 file="configs/sdxl/tokenizer/vocab.json"

rocBLAS error: Cannot read /home/klausman/sdnext/automatic/venv\Lib\site-packages\_rocm_sdk_devel\bin\rocblas\library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1100
 List of available TensileLibrary Files :

rocBLAS error: Could not initialize Tensile host:
filesystem error: directory iterator cannot open directory: No such file or directory [/home/klausman/sdnext/automatic/venv\Lib\site-packages\_rocm_sdk_devel\bin\rocblas\library]
/home/klausman/bin/run-sdn.sh: line 10: 103881 Aborted                    systemd-run --user --scope -p MemoryMax=50G -p MemoryHigh=60G -p MemorySwapMax=55G ./webui.sh --config ../config/config.json --ui-config ../config/ui-config.json --models-dir ../models --listen --insecure --use-rocm "$@"
```

### Operating system

Linux

### Compute

AMD ROCm

### Interface

ModernUI

### Branch

Master

### Model

Unspecified

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by klausman** [comment]
Updating the system ROCm to 7.2.1 and remaking the venv does not make a noticable differnce.

**Comment by klausman** [comment]
Reverting to c9e21a51db77512832462bf8c051754b5527b443 (keeping ROCm 7.2.1, remaking the venv) still works fine.

**Comment by vladmandic** [comment]
mixed `/` and `\` dont make a difference, this is most likely due to rocm install itself and unfortunately, it keeps happening since exact combination changes from torch build to build, amd needs to stabilize rocm builds before we can make total sense out of it. in the meantime, its a lot of manual trial and error for each new version.

**Comment by Ma-ryan** [comment]
> mixed `/` and `\` dont make a difference, this is most likely due to rocm install itself and unfortunately, it keeps happening since exact combination changes from torch build to build, amd needs to stabilize rocm builds before we can make total sense out of it. in the meantime, its a lot of manual trial and error for each new version.

On Linux it definitely makes a difference. Linux is strictly POSIX-compliant. On Linux, a backslash `\` is an escape character or a literal part of a file name. To Linux, `/venv\Lib\site-packages` isn't a folder path; it's asking the OS to look for a literal directory named exactly `venv\Lib\site-packages`.

While Python's pathlib tries to abstract this away, when that malformed string gets passed down to a compiled, low-level C++ library like AMD's rocBLAS, the C++ code asks the Linux kernel for that path, the kernel says "that doesn't exist," and it triggers that hard crash. It is a classic Windows-centric oversight.

**Comment by resonantsky** [comment]
There is a simple fix for this. Look in SD.Next UI for "Extras" and then "ROCm: Advanced Config"

There are two paths at the top, these should equal the 

`full of path of your\lib\site-packages\_rocm_sdk_libraries_gfx103X_dgpu\bin\`  for the system db path 
`full of path of your\lib\site-packages\_rocm_sdk_libraries_gfx103X_dgpu\bin\rocblas\library` for the tensile path 

gfx103x_gpu is in my case, look in your \lib\site-packages for your exact folder name...

The incorrect appended url for linux has been fixed and pushed as well as a fix for the now locked _rocm_sdk_devel folder that was previously configured.

<img width="958" height="1488" alt="Image" src="https://github.com/user-attachments/assets/aa15d91c-0b54-4953-9cb8-c0da92665526" />

**Comment by vladmandic** [comment]
fix from @resonantsky is merged, as it should resolve the problem im closing the issue. if issue persists, please report here with the new log and i'll reopen.

**Comment by Ma-ryan** [comment]
The merge did not fix the issue unfortunately.

I checked the Linux ROCm 7.2 wheel contents. The files are located (for my python version) at `venv/lib/python3.11/site-packages/torch/lib/rocblas/library/`.

Furthermore, ROCm now uses lazy loading (e.g. `TensileLibrary_lazy_gfx1201.dat`), not a monolithic `TensileLibrary.dat`. The error message only complains about `TensileLibrary.dat` because the directory iterator fails completely on the malformed `//bin` path, triggering a generic fallback error.

The solution: On Linux, PyTorch's native `librocblas.so` already knows how to find its own library folder. Setting `ROCBLAS_TENSILE_LIBPATH` manually in the SD.Next code is overwriting PyTorch's correct internal paths and causing the crash. The script should only attempt to set `ROCBLAS_TENSILE_LIBPATH` on Windows, and bypass this logic entirely for Linux users.

**Comment by Brli** [comment]
applied fix in dev branch leads to
```
rocBLAS error: Cannot read /opt/sdnext/venv/lib/python3.11/site-packages/_rocm_sdk_libraries_gfx120X_all/bin/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1201
 List of available TensileLibrary Files :

rocBLAS error: Could not initialize Tensile host:
filesystem error: directory iterator cannot open directory: No such file or directory [/opt/sdnext/venv/lib/python3.11/site-packages/_rocm_sdk_libraries_gfx120X_all/bin/rocblas/library]
```

which doesn't fix the real issue, of which there is no `(..)/site-packages/_rocm_sdk_libraries_gfx120X_all/bin/rocblas/library` generated in the initial phases.

**Comment by resonantsky** [comment]
> applied fix in dev branch leads to
> 
> ```
> rocBLAS error: Cannot read /opt/sdnext/venv/lib/python3.11/site-packages/_rocm_sdk_libraries_gfx120X_all/bin/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1201
>  List of available TensileLibrary Files :
> 
> rocBLAS error: Could not initialize Tensile host:
> filesystem error: directory iterator cannot open directory: No such file or directory [/opt/sdnext/venv/lib/python3.11/site-packages/_rocm_sdk_libraries_gfx120X_all/bin/rocblas/library]
> ```
> 
> which doesn't fix the real issue, of which there is no `(..)/site-packages/_rocm_sdk_libraries_gfx120X_all/bin/rocblas/library` generated in the initial phases.

Sorry, previous remark of mine deleted as was factually incorrect... the issue is the /bin/ in the folder...

I downloaded and checked `rocm_sdk_libraries_gfx120x_all-7.9.0rc20251008-py3-none-linux_x86_64.whl` and in the wheel was -> `_rocm_sdk_libraries_gfx120X_all\lib\rocblas\library` and found the files - but they are not in *bin*, they are in *lib*

If you change \bin\ to \lib\ you will be fine and the issue will be resolved.

On Windows the files are in \bin\... in Linux they are in \lib\

Thanks AMD... yeah, just change \bin\ and \lib\ between windows and linux versions because portability!

**Comment by vladmandic** [comment]
@resonantsky can we handle that automatically?

**Comment by Brli** [comment]
Still, the `TensileLibrary.dat` is deprecated, iirc the file now is
prefixed with something with `lazyload` and `gfxXXX` remark

resonantsky ***@***.***> 於 2026年4月10日 週五 下午7:51 寫道：

**Comment by resonantsky** [comment]
> [@resonantsky](https://github.com/resonantsky) can we handle that automatically?

Yeah I need to push another fix where linux installer autodetects \lib\ instead of \bin\...

**Comment by resonantsky** [comment]
> Still, the `TensileLibrary.dat` is deprecated, iirc the file now is
> prefixed with something with `lazyload` and `gfxXXX` remark
> 
> resonantsky ***@***.***> 於 2026年4月10日 週五 下午7:51 寫道：
> […](#)

I don't know... I see the same in my rocblas folder on windows, TensileLibrary_lazy... 

I see the libraries read during rocBLAS benchmarks, else those signatures are just a row of zeros...

**Comment by resonantsky** [comment]
> [@resonantsky](https://github.com/resonantsky) can we handle that automatically?

PR is up for this... 

https://github.com/vladmandic/sdnext/pull/4746

**Comment by resonantsky** [comment]
> > Still, the `TensileLibrary.dat` is deprecated, iirc the file now is
> > prefixed with something with `lazyload` and `gfxXXX` remark
> > resonantsky _**@**_.***> 於 2026年4月10日 週五 下午7:51 寫道：
> > […](#)
> 
> I don't know... I see the same in my rocblas folder on windows, TensileLibrary_lazy...
> 
> I see the libraries read during rocBLAS benchmarks, else those signatures are just a row of zeros...

But also, in the linux wheel there is a \share\ folder containing all of the KernDBs and models... if you get traceback / errors about `gfx908.tn.model` and the like... please post it here, this is different from windows, where there is a \bin\ folder only

It could be that the \share\ folder must also be added as system path for those... please let me know if you see any other errors.

**Comment by vladmandic** [comment]
ok, i hope this is now resolved with latest merges? if not, report here and i'll reopen.

**Comment by resonantsky** [comment]
> ok, i hope this is now resolved with latest merges? if not, report here and i'll reopen.

I am not sure to be honest because of these issues with file permissions and automatic extracting when pip installing... 

I am also not sure if these are errors at the vendor, in terms of mistakes in packaging, or if these are by design and even though certain files are shipped and not unpacked, is it that they are not unpacked because they are not meant to be used? 

Take for instance https://github.com/vladmandic/sdnext/issues/4666 this issue where the guy says "the files are simply absent"... no, they are not absent, they are present but not unpacked, or, left in folders not referenced by the DLLs... and copying/pointing to these files does solve the issues with fallback and ai heuristics... no matter if the files are gfx908 on a gfx1030, these are methods/models... so, I'm still on the fence with this issue being solved or not... Are we dealing with by-design functional changes to ROCm or are these mistakes at the vendor... Time will tell. 

I know for myself that I am still using folder pointers to ensure MIOpen.dll or Rocblas.dll find their necessary libraries or models, because otherwise those errors return, where a particular process needs to reference a particular model, kernel, or the like.

It is the following files that are still stuck in the now locked/not unpacked `_rocm_sdk_devel\bin\` (on windows) that are referenced by the MIOpen.dll but not present in the `_rocm_sdk_libraries[gfx]\bin\` on installation... I have solved this issue by extracting these files into the currently used `_rocm_sdk_libraries[gfx]\bin\` folder and I have no issues with these files not being found or MIOpen.dll debug trace about it.

- gfx908.tn.model
- gfx908_ConvAsm1x1U_decoder.ktn.model
- gfx908_ConvAsm1x1U_encoder.ktn.model
- gfx908_ConvAsm1x1U_metadata.ktn.model
- gfx908_metadata.tn.model
- gfx90a.tn.model
- gfx90a_ConvHipIgemmGroupFwdXdlops_decoder.ktn.model
- gfx90a_ConvHipIgemmGroupFwdXdlops_encoder.ktn.model
- gfx90a_ConvHipIgemmGroupFwdXdlops_metadata.ktn.model
- gfx90a_ConvHipIgemmGroupXdlops_decoder.ktn.model
- gfx90a_ConvHipIgemmGroupXdlops_encoder.ktn.model
- gfx90a_ConvHipIgemmGroupXdlops_metadata.ktn.model
- gfx90a_metadata.tn.model
- gfx942.tn.model
- gfx942_3d.tn.model
- gfx942_3d_metadata.tn.model
- gfx942_ConvHipIgemmGroupBwdXdlops_decoder.ktn.model
- gfx942_ConvHipIgemmGroupBwdXdlops_encoder.ktn.model
- gfx942_ConvHipIgemmGroupBwdXdlops_metadata.ktn.model
- gfx942_ConvHipIgemmGroupFwdXdlops_decoder.ktn.model
- gfx942_ConvHipIgemmGroupFwdXdlops_encoder.ktn.model
- gfx942_ConvHipIgemmGroupFwdXdlops_metadata.ktn.model
- gfx942_ConvHipIgemmGroupWrwXdlops_decoder.ktn.model
- gfx942_ConvHipIgemmGroupWrwXdlops_encoder.ktn.model
- gfx942_ConvHipIgemmGroupWrwXdlops_metadata.ktn.model
- gfx942_ConvHipIgemmGroupXdlops_decoder.ktn.model
- gfx942_ConvHipIgemmGroupXdlops_encoder.ktn.model
- gfx942_ConvHipIgemmGroupXdlops_metadata.ktn.model
- gfx942_ConvHipImplicitGemm3DGroupBwdXdlops_input_encoder.tn.model
- gfx942_ConvHipImplicitGemm3DGroupBwdXdlops_kernel_config_encoder.tn.model
- gfx942_ConvHipImplicitGemm3DGroupBwdXdlops_metadata.tn.model
- gfx942_ConvHipImplicitGemm3DGroupFwdXdlops_input_encoder.tn.model
- gfx942_ConvHipImplicitGemm3DGroupFwdXdlops_kernel_config_encoder.tn.model
- gfx942_ConvHipImplicitGemm3DGroupFwdXdlops_metadata.tn.model
- gfx942_ConvHipImplicitGemm3DGroupWrwXdlops_input_encoder.tn.model
- gfx942_ConvHipImplicitGemm3DGroupWrwXdlops_kernel_config_encoder.tn.model
- gfx942_ConvHipImplicitGemm3DGroupWrwXdlops_metadata.tn.model
- gfx942_metadata.tn.model
- gfx950_3d.tn.model
- gfx950_3d_metadata.tn.model
- gfx950_ConvHipIgemmGroupBwdXdlops_decoder.ktn.model
- gfx950_ConvHipIgemmGroupBwdXdlops_encoder.ktn.model
- gfx950_ConvHipIgemmGroupBwdXdlops_metadata.ktn.model
- gfx950_ConvHipIgemmGroupFwdXdlops_decoder.ktn.model
- gfx950_ConvHipIgemmGroupFwdXdlops_encoder.ktn.model
- gfx950_ConvHipIgemmGroupFwdXdlops_metadata.ktn.model
- gfx950_ConvHipIgemmGroupWrwXdlops_decoder.ktn.model
- gfx950_ConvHipIgemmGroupWrwXdlops_encoder.ktn.model
- gfx950_ConvHipIgemmGroupWrwXdlops_metadata.ktn.model
- gfx950_ConvHipIgemmGroupXdlops_decoder.ktn.model
- gfx950_ConvHipIgemmGroupXdlops_encoder.ktn.model
- gfx950_ConvHipIgemmGroupXdlops_metadata.ktn.model
- gfx950_ConvHipImplicitGemm3DGroupBwdXdlops_input_encoder.tn.model
- gfx950_ConvHipImplicitGemm3DGroupBwdXdlops_kernel_config_encoder.tn.model
- gfx950_ConvHipImplicitGemm3DGroupBwdXdlops_metadata.tn.model
- gfx950_ConvHipImplicitGemm3DGroupFwdXdlops_input_encoder.tn.model
- gfx950_ConvHipImplicitGemm3DGroupFwdXdlops_kernel_config_encoder.tn.model
- gfx950_ConvHipImplicitGemm3DGroupFwdXdlops_metadata.tn.model
- gfx950_ConvHipImplicitGemm3DGroupWrwXdlops_input_encoder.tn.model
- gfx950_ConvHipImplicitGemm3DGroupWrwXdlops_kernel_config_encoder.tn.model
- gfx950_ConvHipImplicitGemm3DGroupWrwXdlops_metadata.tn.model

There are other files than these that are referenced by MIOpen.dll that are not in this list, kernel DBs mostly, but according to some associated with amd devs... this is by design on GFX1100 and above.
