### ISSUE TITLE
[Issue]: HiDream I1 Full AttributeError: 'list' object has no attribute 'device'

### ISSUE THREAD

**Issue by liutyi** [vladmandic/automatic#4744]
### Issue Description

Generate for HiDream not work with error on UI

'list' object has no attribute 'device'
Time: 3.88s | post 3.62 prompt 3.62 te 3.62 | GPU 59336 MB 46% | RAM 66.83 GB 53%

and in the log

### Version Platform Description

latest dev in docker ipex.

### Relevant log output

```shell
23:34:35-824533 DEBUG    Setting model: component=vae {'slicing': True,
                         'tiling': False}
23:34:35-826247 DEBUG    Setting model: attention="Scaled-Dot-Product"
23:34:35-826748 WARNING  Setting model: offload=none type=HiDreamImagePipeline
                         large model
23:34:36-872969 DEBUG    GC: current={'gpu': 57.74, 'ram': 65.15, 'oom': 0}
                         prev={'gpu': 57.74, 'ram': 65.15} load={'gpu': 46,
                         'ram': 52} gc={'gpu': 0.0, 'py': 8568}
                         fn=reload_model_weights:load_diffuser why=load
                         time=0.34
23:34:36-875526 INFO     Load model: family=h1 time={'total': 79.2, 'load':
                         78.49, 'move': 0.71} native=1024 memory={'ram':
                         {'total': 125.32, 'rss': 4.44, 'used': 65.15, 'free':
                         26.04, 'avail': 60.16, 'buffers': 0.03, 'cached':
                         93.64}, 'gpu': {'used': 57.74, 'total': 125.32,
                         'active': 57.53, 'peak': 57.53, 'retries': 0, 'oom': 0,
                         'swap': 0}, 'job': ''}
23:34:36-880172 DEBUG    Script init: ['task_scheduler.py:app_started=0.17']
23:34:36-880772 INFO     Startup time: total=96.69 checkpoint=79.55 launch=3.59
                         loader=2.98 installer=2.98 libraries=2.78 torch=1.91
                         gradio=0.48 ui-control=0.37 ui-extensions=0.31
                         extensions=0.31 ui-networks=0.24 diffusers=0.20
                         app-started=0.17 scans=0.14 ui-img2img=0.11
23:34:36-883507 DEBUG    Save: file="/mnt/data/config.json" json=16 bytes=759
                         time=0.004
23:34:36-884434 DEBUG    Save: file="/mnt/data/secrets.json" json=5 bytes=321
                         time=0.000
23:34:41-880106 DEBUG    Search model:
                         name="Diffusers/HiDream-ai/HiDream-I1-Full
                         [8ccbbfb270]"
                         matched="/mnt/models/Diffusers/models--HiDream-ai--HiDr
                         eam-I1-Full/snapshots/8ccbbfb270ccdae26d6bb0081df67dc81
                         e4033bf" type=alias
23:34:41-889574 DEBUG    Analyzed: model="Diffusers/HiDream-ai/HiDream-I1-Full"
                         type=h1 class=HiDreamImagePipeline size=0
                         mtime="2026-04-08 17:35:52" modules=[name="vae"
                         cls=AutoencoderKL config=True device=xpu:0
                         dtype=torch.bfloat16 params=83819683 modules=241,
                         name="text_encoder" cls=CLIPTextModelWithProjection
                         config=True device=xpu:0 dtype=torch.bfloat16
                         params=123781632 modules=153, name="text_encoder_2"
                         cls=CLIPTextModelWithProjection config=True
                         device=xpu:0 dtype=torch.bfloat16 params=694840320
                         modules=393, name="text_encoder_3" cls=T5EncoderModel
                         config=True device=xpu:0 dtype=torch.bfloat16
                         params=4762310656 modules=464, name="text_encoder_4"
                         cls=LlamaForCausalLM config=True device=xpu:0
                         dtype=torch.bfloat16 params=8030261248 modules=423,
                         name="tokenizer" cls=CLIPTokenizer config=False,
                         name="tokenizer_2" cls=CLIPTokenizer config=False,
                         name="tokenizer_3" cls=T5Tokenizer config=False,
                         name="tokenizer_4" cls=TokenizersBackend config=False,
                         name="scheduler" cls=UniPCMultistepScheduler
                         config=True, name="transformer"
                         cls=HiDreamImageTransformer2DModel config=True
                         device=xpu:0 dtype=torch.bfloat16 params=17105733184
                         modules=2090]
23:34:46-847126 TRACE    VAE: cls=HiDreamImagePipeline scale=8 patch=1
23:34:46-851962 DEBUG    Sampler: "Default" cls=UniPCMultistepScheduler
                         config={'num_train_timesteps': 1000, 'beta_start':
                         0.0001, 'beta_end': 0.02, 'beta_schedule': 'linear',
                         'trained_betas': None, 'solver_order': 2,
                         'prediction_type': 'flow_prediction', 'thresholding':
                         False, 'dynamic_thresholding_ratio': 0.995,
                         'sample_max_value': 1.0, 'predict_x0': True,
                         'solver_type': 'bh2', 'lower_order_final': True,
                         'disable_corrector': [], 'solver_p': None,
                         'use_karras_sigmas': False, 'use_exponential_sigmas':
                         False, 'use_beta_sigmas': False, 'use_flow_sigmas':
                         True, 'flow_shift': 3.0, 'timestep_spacing':
                         'linspace', 'steps_offset': 0, 'final_sigmas_type':
                         'zero', 'rescale_betas_zero_snr': False,
                         'use_dynamic_shifting': False, 'time_shift_type':
                         'exponential', 'sigma_min': None, 'sigma_max': None,
                         'shift_terminal': None}
23:34:46-857443 INFO     Processing modifiers: apply
23:34:46-865527 DEBUG    Encode: prompt="A serene mountain range shrouded in
                         soft morning fog, rendered in delicate layers with
                         subtle gradients of light blue tones - ranging from
                         pale sky-blue at the peaks to deeper cerulean near the
                         valleys. Mist curls gently around jagged ridges and
                         hidden forested slopes, creating ethereal depth. The
                         scene is bathed in diffused dawn light filtering
                         through low-hanging clouds, casting quiet shadows and
                         luminous highlights across snow-dusted summits and
                         mossy rock faces. Minimalist composition emphasizes
                         tranquility; distant peaks fade into atmospheric haze,
                         evoking solitude and calm. Mood: peaceful, dreamlike,
                         untouched nature. Style: minimalist realism with
                         painterly texture and muted palette." hijack=True
23:34:50-485305 ERROR    Exception: 'list' object has no attribute 'device'
23:34:50-486164 ERROR    Arguments: args=('task(r5xmb2llrn295nw)', '', 'A serene
                         mountain range shrouded in soft morning fog, rendered
                         in delicate layers with subtle gradients of light blue
                         tones - ranging from pale sky-blue at the peaks to
                         deeper cerulean near the valleys. Mist curls gently
                         around jagged ridges and hidden forested slopes,
                         creating ethereal depth. The scene is bathed in
                         diffused dawn light filtering through low-hanging
                         clouds, casting quiet shadows and luminous highlights
                         across snow-dusted summits and mossy rock faces.
                         Minimalist composition emphasizes tranquility; distant
                         peaks fade into atmospheric haze, evoking solitude and
                         calm. Mood: peaceful, dreamlike, untouched nature.
                         Style: minimalist realism with painterly texture and
                         muted palette.', '', [], 50, 0, 108, 'Full', False,
                         False, False, '', '', 10, 0.3, 1024, 1, 1, 'Default',
                         4, 0, 0, 1, 5, 6, 0, 0, 0.5, 1, 1, 20260408.0, -1.0, 0,
                         0, 0, 1024, 1024, False, 0.3, 1, 1, 'Add with forward',
                         'None', False, 20, 0, 0, 20, 0, '', '', 0, 0, 0, 0,
                         False, 4, 0.95, False, 0.6, 1, '#000000', 0, True, 0,
                         0, 0, 0, 1, 0, 6500, 0, 0, 0, 0, 8, '#000000',
                         '#ffffff', 0.5, 0, 0, None, 1, [], 0, 1, False, 'None',
                         'None', 'None', 'None', 0.5, 0.5, 0.5, 0.5, None, None,
                         None, None, False, False, False, False, 0, 0, 0, 0, 1,
                         1, 1, 1, None, None, None, None, False, '', False,
                         False, False, False, True, False, 0.2, 3, [],
                         'pixelate', '', 'eng', 'latn', '', 'A serene mountain
                         range shrouded in soft morning fog, rendered in
                         delicate layers with subtle gradients of light blue
                         tones - ranging from pale sky-blue at the peaks to
                         deeper cerulean near the valleys. Mist curls gently
                         around jagged ridges and hidden forested slopes,
                         creating ethereal depth. The scene is bathed in
                         diffused dawn light filtering through low-hanging
                         clouds, casting quiet shadows and luminous highlights
                         across snow-dusted summits and mossy rock faces.
                         Minimalist composition emphasizes tranquility; distant
                         peaks fade into atmospheric haze, evoking solitude and
                         calm. Mood: peaceful, dreamlike, untouched nature.
                         Style: minimalist realism with painterly texture and
                         muted palette.', None, False, 'google/gemma-3-4b-it
                         \uf06e', '', '', '', 1024, True, 0.7, 1.2, 0, 0, False,
                         True, True, '', False, False, False, 0, '', [], 0, '',
                         [], 0, '', [], False, True, False, True, False, False,
                         False, False, 0, False, 'MP4/MP4V', 2, True, 1, 0, 1,
                         -0.5, 0, 'constant', 1, 'constant', 1, '', '', False,
                         '', '', '-1', 0, 0, '', 0, False, 0, 'None', 2, 0, 0,
                         '', '', '', 0.5, True, True, False, True, True, False,
                         '0.6, 0.4, 1.1, 1.2', '10, 20, 0.8', False, '', 0.5, 5,
                         None, '', 0.5, 5, None, True, 'jet', 3, 1, 1, 0.8, 8,
                         64, True, 'None', [], 'ReSwapper 256 0.2', False,
                         'FaceID Base', True, True, 1, 1, 1, 0.5, True,
                         'PhotoMaker v2', '', 1, 0.5, True, 2, True, 1, 35,
                         True, 1, 0.75, True, 2, 0.75, False, 3, 0.75, False, 4,
                         0.75, 0.65, True, False, 1, 1, 1, 'aes_stage2', None,
                         None, 1, 0, 1, 3.5, 1, False, True, 0.5, 600.0, 1.0, 2,
                         0.5, 'Linear', False, 1, 1, 0.5, 0.5, 1, 1, 128, 128,
                         '', '', '', '', '', '', '', '', '', '', '', '', '', '',
                         '', '', 'OpenGVLab/InternVL-14B-224px', 20, False,
                         False, 'positive', 'comma', 0, False, False, '', [],
                         0.8, 20, 'dpmpp_sde', 'v2', False, True, 'v1.1',
                         'None', '', 1, '', 'None', 1, '7,8,9', 1, 0.01, 0.2,
                         None, '', False, ['attention', 'adain_queries',
                         'adain_keys'], 1, 0, 0, True, 10, 'None', 16, 'None',
                         1, True, 'MP4/MP4V', 2, True, 1, 0, True, 'none', 3, 4,
                         0.25, 0.25, 'None', True, 0, 'MP4/MP4V', 2, True, 1, 0,
                         0, '', [], 0, '', [], 0, '', [], False, True, False,
                         True, False, False, False, False, 0, False, 'MP4/MP4V',
                         2, True, 1, 0) kwargs={}
23:34:50-490242 CRITICAL gradio call: AttributeError
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│/app/modules/call_queue.py:42 in f                                            │
│                                                                              │
│  41             try:                                                         │
│❱ 42                 res = func(*args, **kwargs)                              │
│  43                 progress.record_results(id_task, res)                    │
│                                                                              │
│/app/modules/txt2img.py:118 in txt2img                                        │
│                                                                              │
│  117     if processed is None:                                               │
│❱ 118         processed = processing.process_images(p)                        │
│  119     processed = scripts_manager.scripts_txt2img.after(p, processed, *ar │
│                                                                              │
│/app/modules/processing.py:231 in process_images                              │
│                                                                              │
│  230             with context_hypertile_vae(p), context_hypertile_unet(p):   │
│❱ 231                 results = process_images_inner(p)                       │
│  232                                                                         │
│                                                                              │
│/app/modules/processing.py:497 in process_images_inner                        │
│                                                                              │
│  496                 from modules.processing_diffusers import process_diffus │
│❱ 497                 samples = process_diffusers(p)                          │
│  498             timer.process.record('process')                             │
│                                                                              │
│/app/modules/processing_diffusers.py:599 in process_diffusers                 │
│                                                                              │
│  598     if 'base' not in p.skip:                                            │
│❱ 599         output = process_base(p)                                        │
│  600     else:                                                               │
│                                                                              │
│/app/modules/processing_diffusers.py:150 in process_base                      │
│                                                                              │
│  149         desc = 'Detail'                                                 │
│❱ 150     base_args = set_pipeline_args(                                      │
│  151         p=p,                                                            │
│                                                                              │
│/app/modules/processing_args.py:212 in set_pipeline_args                      │
│                                                                              │
│  211                                                                         │
│❱ 212     prompt_attention, args = set_prompt(p, args, possible, cls, prompt_ │
│  213                                                                         │
│                                                                              │
│/app/modules/processing_prompt.py:128 in set_prompt                           │
│                                                                              │
│  127                 prompt_attention = 'fixed'                              │
│❱ 128             elif prompt_embeds.device == torch.device('meta'):          │
│  129                 log.warning('Prompt parser encode: embeds on meta devic │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'list' object has no attribute 'device'
```

### Operating system

Linux

### Compute

Intel IPEX

### Interface

Standard

### Branch

Dev

### Model

Other image model

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
should be fixed now.

**Comment by liutyi** [comment]
this error gone but now

![Image](https://github.com/user-attachments/assets/4671fe73-d7f9-4e54-84b3-36b1fb83ae4b)

single image

![Image](https://github.com/user-attachments/assets/6ec953b0-f7b5-4623-ad10-f7e5b6b9d539)

**Comment by vladmandic** [comment]
log?

**Comment by liutyi** [comment]
may clean reinstall on dev, re-download model and execute with Generate in modernui if needed. just will take some time

from standard ui fork with scheduler logs looks like that:
```
2026-04-09 07:04:00,001 | f44410854219 | sd | TRACE | sd_vae | VAE: cls=HiDreamImagePipeline scale=8 patch=1
2026-04-09 07:04:00,001 | f44410854219 | sd | DEBUG | processing_vae | Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 16, 128, 128]:xpu:0 dtype=torch.bfloat16 time=1.514
2026-04-09 07:04:00,275 | f44410854219 | sd | DEBUG | processing_vae | Profile: VAE decode: 1.79
2026-04-09 07:04:00,299 | f44410854219 | sd | INFO | save | Save: image="/mnt/data/outputs/text/2026-04-09-02056-HiDream-I1-Full-1024x1024-Seed20260408-CFG5-AG0-STEP50.jpg" type=JPEG width=1024 height=1024 size=599383
2026-04-09 07:04:00,300 | f44410854219 | sd | INFO | processing | Processed: images=1 its=0.06 ops=['txt2img']
2026-04-09 07:04:00,301 | f44410854219 | sd | DEBUG | processing | Processed: timers={'total': 828.73, 'pipeline': 822.81, 'decode': 2.41, 'te': 1.34, 'vae': 1.21, 'preview': 0.61, 'gc': 0.3}
2026-04-09 07:04:00,302 | f44410854219 | sd | DEBUG | processing | Processed: memory={'ram': {'total': 125.32, 'rss': 5.96, 'used': 69.75, 'free': 19.96, 'avail': 55.57, 'buffers': 0.04, 'cached': 98.75}, 'gpu': {'used': 61.23, 'total': 125.32, 'active': 57.54, 'peak': 59.42, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': ''}
2026-04-09 07:04:00,307 | f44410854219 | sd | INFO | task_runner | [AgentScheduler] Total pending tasks: 10
2026-04-09 07:04:00,308 | f44410854219 | sd | INFO | task_runner | [AgentScheduler] Executing task task(di1ga2xyltk2jfs)
2026-04-09 07:04:00,309 | f44410854219 | sd | TRACE | sd_vae | VAE: cls=HiDreamImagePipeline scale=8 patch=1
2026-04-09 07:04:00,311 | f44410854219 | sd | DEBUG | sd_samplers | Sampler: "Default" cls=UniPCMultistepScheduler config={'num_train_timesteps': 1000, 'beta_start': 0.0001, 'beta_end': 0.02, 'beta_schedule': 'linear', 'trained_betas': None, 'solver_order': 2, 'prediction_type': 'flow_prediction', 'thresholding': False, 'dynamic_thresholding_ratio': 0.995, 'sample_max_value': 1.0, 'predict_x0': True, 'solver_type': 'bh2', 'lower_order_final': True, 'disable_corrector': [], 'solver_p': None, 'use_karras_sigmas': False, 'use_exponential_sigmas': False, 'use_beta_sigmas': False, 'use_flow_sigmas': True, 'flow_shift': 3.0, 'timestep_spacing': 'linspace', 'steps_offset': 0, 'final_sigmas_type': 'zero', 'rescale_betas_zero_snr': False, 'use_dynamic_shifting': False, 'time_shift_type': 'exponential', 'sigma_min': None, 'sigma_max': None, 'shift_terminal': None}
2026-04-09 07:04:00,312 | f44410854219 | sd | INFO | processing_diffusers | Processing modifiers: apply
2026-04-09 07:04:00,313 | f44410854219 | sd | TRACE | sd_vae | VAE: cls=HiDreamImagePipeline scale=8 patch=1
2026-04-09 07:04:00,313 | f44410854219 | sd | INFO | processing_args | Base: pipeline=HiDreamImagePipeline task=TEXT_2_IMAGE batch=1/1x1 set={'prompt': 1, 'negative_prompt': 1, 'prompt_2': ['loft bedroom with panoramic window'], 'negative_prompt_2': [''], 'guidance_scale': 5, 'generator': 'xpu:[20260408]', 'num_inference_steps': 50, 'output_type': 'latent', 'width': 1024, 'height': 1024, 'parser': 'fixed'}
2026-04-09 07:04:00,319 | f44410854219 | sd | DEBUG | sd_hijack_te | Encode: prompt="['loft bedroom with panoramic window']" hijack=True
2026-04-09 07:05:58,342 | f44410854219 | sd | TRACE | launch | Server: alive=True requests=1227 memory=69.77/125.32 status='idle' task='' timestamp=None current='task(di1ga2xyltk2jfs)' id='' job=0 jobs=0 total=346 step=7 steps=0 queued=0 uptime=24691 elapsed=116.69 eta=None progress=0
2026-04-09 07:07:58,361 | f44410854219 | sd | TRACE | launch | Server: alive=True requests=1227 memory=69.77/125.32 status='idle' task='' timestamp=None current='task(di1ga2xyltk2jfs)' id='' job=0 jobs=0 total=346 step=14 steps=0 queued=0 uptime=24811 elapsed=236.71 eta=None progress=0
2026-04-09 07:09:58,380 | f44410854219 | sd | TRACE | launch | Server: alive=True requests=1227 memory=69.77/125.32 status='idle' task='' timestamp=None current='task(di1ga2xyltk2jfs)' id='' job=0 jobs=0 total=346 step=21 steps=0 queued=0 uptime=24931 elapsed=356.73 eta=None progress=0
2026-04-09 07:11:58,398 | f44410854219 | sd | TRACE | launch | Server: alive=True requests=1227 memory=69.77/125.32 status='idle' task='' timestamp=None current='task(di1ga2xyltk2jfs)' id='' job=0 jobs=0 total=346 step=29 steps=0 queued=0 uptime=25051 elapsed=476.75 eta=None progress=0
2026-04-09 07:13:58,417 | f44410854219 | sd | TRACE | launch | Server: alive=True requests=1227 memory=69.77/125.32 status='idle' task='' timestamp=None current='task(di1ga2xyltk2jfs)' id='' job=0 jobs=0 total=346 step=36 steps=0 queued=0 uptime=25171 elapsed=596.77 eta=None progress=0
2026-04-09 07:15:58,437 | f44410854219 | sd | TRACE | launch | Server: alive=True requests=1227 memory=69.77/125.32 status='idle' task='' timestamp=None current='task(di1ga2xyltk2jfs)' id='' job=0 jobs=0 total=346 step=43 steps=0 queued=0 uptime=25291 elapsed=716.79 eta=None progress=0
2026-04-09 07:17:41,471 | f44410854219 | sd | INFO | processing_diffusers | Processing modifiers: unapply
2026-04-09 07:17:42,368 | f44410854219 | sd | DEBUG | devices | GC: current={'gpu': 57.76, 'ram': 69.77, 'oom': 0} prev={'gpu': 61.26, 'ram': 69.77} load={'gpu': 46, 'ram': 56} gc={'gpu': 3.5, 'py': 1146} fn=vae_decode:full_vae_decode why=force time=0.30
2026-04-09 07:17:42,370 | f44410854219 | sd | DEBUG | logger | Setting decode: component=vae {'slicing': True, 'tiling': False}
2026-04-09 07:17:42,371 | f44410854219 | sd | TRACE | processing_vae | VAE config: FrozenDict({'in_channels': 3, 'out_channels': 3, 'down_block_types': ['DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D'], 'up_block_types': ['UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D'], 'block_out_channels': [128, 256, 512, 512], 'layers_per_block': 2, 'act_fn': 'silu', 'latent_channels': 16, 'norm_num_groups': 32, 'sample_size': 1024, 'scaling_factor': 0.3611, 'shift_factor': 0.1159, 'latents_mean': None, 'latents_std': None, 'force_upcast': True, 'use_quant_conv': False, 'use_post_quant_conv': False, 'mid_block_add_attention': True, '_class_name': 'AutoencoderKL', '_diffusers_version': '0.30.0.dev0', '_name_or_path': '/mnt/models/Diffusers/models--HiDream-ai--HiDream-I1-Full/snapshots/8ccbbfb270ccdae26d6bb0081df67dc81e4033bf/vae'})
2026-04-09 07:17:43,580 | f44410854219 | sd | DEBUG | sd_hijack_vae | Decode: vae=AutoencoderKL dtype=torch.bfloat16 latents=[1, 16, 128, 128]:xpu:0 decoded=[1, 3, 1024, 1024] slicing=True tiling=False time=1.207
2026-04-09 07:17:43,582 | f44410854219 | sd | TRACE | processing_vae | VAE memory: defaultdict(<class 'int'>, {'free': 68810469376, 'total': 134558281728, 'used': 65747812352, 'active': 3228, 'active_peak': 63799680512, 'reserved': 65747812352, 'reserved_peak': 65747812352, 'retries': -1, 'oom': -1})
2026-04-09 07:17:43,582 | f44410854219 | sd | TRACE | sd_vae | VAE: cls=HiDreamImagePipeline scale=8 patch=1
2026-04-09 07:17:43,583 | f44410854219 | sd | DEBUG | processing_vae | Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 16, 128, 128]:xpu:0 dtype=torch.bfloat16 time=1.514
2026-04-09 07:17:43,857 | f44410854219 | sd | DEBUG | processing_vae | Profile: VAE decode: 1.79
2026-04-09 07:17:43,882 | f44410854219 | sd | INFO | save | Save: image="/mnt/data/outputs/text/2026-04-09-02057-HiDream-I1-Full-1024x1024-Seed20260408-CFG5-AG0-STEP50.jpg" type=JPEG width=1024 height=1024 size=597455
2026-04-09 07:17:43,883 | f44410854219 | sd | INFO | processing | Processed: images=1 its=0.06 ops=['txt2img']

```

**Comment by liutyi** [comment]
hmm.. ok.. looks like it is something wrong on my side..
![Image](https://github.com/user-attachments/assets/0ccf84ad-11a1-4f0e-955d-6af479f5f9dd)

```
Launch: /mnt/python/venv/bin/python3
13:21:18-053621 INFO     Starting SD.Next
13:21:18-054902 INFO     Logger: file="/app/sdnext.log" level=DEBUG
                         host="fd85ac8639df" size=32741 mode=append
13:21:18-055399 INFO     Python: version=3.12.3 platform=Linux
                         bin="/mnt/python/venv/bin/python3"
                         venv="/mnt/python/venv"
13:21:18-056711 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux
                         release=6.17.0-20-generic python=3.12.3 locale=('C',
                         'UTF-8') setuptools=69.5.1 docker=True
13:21:18-065110 INFO     Version: app=sd.next updated=2026-04-09
                         commit=f1d2888f1 branch=dev
                         url=https://github.com/vladmandic/sdnext/tree/dev
                         kanvas=main ui=main

```
