### ISSUE TITLE
[Issue]: rocBLAS error

### ISSUE THREAD

**Issue by Matt541753** [vladmandic/automatic#4757]
### Issue Description

I tried the dev version, had some minor issues and went back to the master version, then I got the following error message and image generation isn't possible anymore (before I switched to the dev version everything worked fine with the master version). I reinstalled SD Next and get still the same error message:

"rocBLAS error: Cannot read C:\SDNext\sdnext\venv\Lib\site-packages\_rocm_sdk_devel\bin\rocblas\library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1200
 List of available TensileLibrary Files :

rocBLAS error: Could not initialize Tensile host:
directory_iterator::directory_iterator: Das System kann den angegebenen Pfad nicht finden.: "C:\SDNext\sdnext\venv\Lib\site-packages\_rocm_sdk_devel\bin\rocblas\library"

When starting SD Next it seems for me with my limited knowledge that everything should be fine with my gpu:

02:08:33-421317 INFO     Starting SD.Next
02:08:33-424765 INFO     Logger: file="C:\SDNext\sdnext\sdnext.log" level=DEBUG host="DESKTOP-EHPEPIN" size=83
                         mode=append
02:08:33-427775 INFO     Python: version=3.12.0 platform=Windows bin="C:\SDNext\sdnext\venv\Scripts\python.exe"
                         venv="C:\SDNext\sdnext\venv"
02:08:33-456209 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-11-10.0.26100-SP0 python=3.12.0 locale=('German_Switzerland', '1252')
                         setuptools=69.5.1 docker=False
02:08:33-874994 INFO     Version: app=sd.next updated=2026-04-04 commit=0eb4a98e0 branch=master
                         url=https://github.com/vladmandic/sdnext/tree/master kanvas=main ui=main
02:08:34-615169 TRACE    Repository branches: active=master available=['dev', 'feat/civitai-base-models',
                         'fix/sdnq-lora-swap', 'master']
02:08:35-034075 INFO     Version: app=sd.next latest=2026-04-04T09:10:28Z hash=0eb4a98e branch=master
02:08:35-037282 DEBUG    Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
02:08:35-040283 INFO     Args: ['--use-rocm']
02:08:35-041283 DEBUG    Setting environment tuning
02:08:35-042281 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
02:08:35-045798 INFO     Torch: verifying installation
02:08:35-046798 DEBUG    Torch overrides: cuda=False rocm=True ipex=False directml=False openvino=False zluda=False
02:08:35-418724 INFO     ROCm: agents=['gfx1200']
02:08:35-421727 INFO     ROCm: version=7.2, using agent gfx1200
02:08:35-424252 INFO     Python: version=3.12.0 platform=Windows bin="C:\SDNext\sdnext\venv\Scripts\python.exe"
                         venv="C:\SDNext\sdnext\venv"
02:08:53-059101 INFO     Torch backend: {'version': '2.11.0+rocm7.13.0a20260413', 'type': 'rocm', 'hip': '7.2.0'}
02:08:53-062100 INFO     Torch detected: {'gpu': 'AMD Radeon RX 9060 XT', 'vram': 16304, 'arch': '12.0 Unknown',
                         'cores': 16}
02:08:53-284851 INFO     Install: verifying requirements
02:08:53-446233 DEBUG    State: cached=True
02:08:53-447233 INFO     Startup: launch=quick
02:08:53-449235 INFO     Extensions: disabled=[]
02:08:53-450235 INFO     Extensions: path="extensions-builtin" enabled=['sd-extension-chainner',
                         'sd-extension-system-info', 'sdnext-kanvas', 'sdnext-modernui']
02:08:53-454279 INFO     Extensions: path="extensions" enabled=[]
02:08:53-458272 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
02:08:53-460271 INFO     Installer time: total=21.15 torch=18.02 latest=1.58 version=0.41 amd=0.31 git=0.27 files=0.21
                       

What could be the problem? Thanks for your help :)

### Relevant log output

```shell

```

### Operating system

Windows

### Compute

AMD ROCm

### Interface

ModernUI

### Branch

Master

### Model

StableDiffusion 1.5/2.1/XL

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
cc @resonantsky

**Comment by resonantsky** [comment]
Hi @Matt541753 

The solution is fairly straightforward, find the "Extras" panel on the left on the SD.Next modern UI. There you will an ROCM: Advanced Configuration script, note the two paths at the top of the settings area, You have two options, one is to clear those paths and leave them empty, or you can change them to the location of the missing libraries, See my screenshot, it will give you the correct *full* path you need to use to find those libraries, it will be a little different from yours because I have a gfx1030, but you should have no trouble locating these in  your venv, look for `_rocm_libraries` at the top of your venv.

<img width="1294" height="1494" alt="Image" src="https://github.com/user-attachments/assets/0fad1f40-4331-4a7f-8147-2f033497073d" />

`venv\Lib\site-packages\_rocm_sdk_libraries_gfx103X_dgpu\bin\`

`venv\Lib\site-packages\_rocm_sdk_libraries_gfx103X_dgpu\bin\rocblas\library`

It is important to note `_rocm_sdk_libraries` and not the `_rocm_sdk_devel` folder that was used until the folder was locked by AMD developers, Many files are still in that folder, so you may still have file not found issues, these arise out of MIOpen not being able to locate `_rocm_sdk_devel` 

`_rocm_sdk_devel` is not missing, it has been locked as not to unpack automatically by AMD, but you still downloaded it when you installed rocm, you will find it at the bottom of the venv, without the underscore `rocm_sdk_devel` in there is a `_devel.tar`, an archive containing `_rocm_sdk_devel` folder with all the files required, I suggest that you unpack this to `_rocm_sdk_devel` at the top of the venv alongside the other two _rocm folders.

This issue is a remnant of the script configuration seeking the `_rocm_devel_sdk` folder, again, first attempt to clear the folder setting there, leaving it empty and click "Apply" at the top.

Restarting SD.Next will clear this issue, if you still have issues resolving files no worries, let me know and we can extract and point to the necessary files.

**Comment by nktice** [comment]
With version 2026-04-04 
I've the same problem, but on Ubuntu Linux, I get this error : 
```
rocBLAS error: Cannot read /home/n/sdnext/venv\Lib\site-packages\_rocm_sdk_devel\bin\rocblas\library/TensileLibrary.dat: Illegal seek for GPU arch : gfx1100
 List of available TensileLibrary Files : 

rocBLAS error: Could not initialize Tensile host:
filesystem error: directory iterator cannot open directory: No such file or directory [/home/n/sdnext/venv\Lib\site-packages\_rocm_sdk_devel\bin\rocblas\library]
./sdnext.sh: line 4: 23357 Aborted                    (core dumped) ./webui.sh --debug --models-dir ~/models
```
The interfaces says that it's for Windows systems... what about Linux?  
For one thing I have gfx1151 not gfx1100 on this system....  ( gfx1151 is correctly detected at the start of the console log ) 
Note backslashes - Linux uses forward slash, so that will not work.  
I saw post above offering a solution... and checked those settings - in that interface the paths use forward slashes 
Path starts with Lib but the file is named lib ... I tried fixing the paths but got this : 
```
rocBLAS error: Cannot read /home/n/sdnext/venv/lib/site-packages/_rocm_sdk_devel/bin/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1100
 List of available TensileLibrary Files : 

rocBLAS error: Could not initialize Tensile host:
filesystem error: directory iterator cannot open directory: No such file or directory [/home/n/sdnext/venv/lib/site-packages/_rocm_sdk_devel/bin/rocblas/library]
./sdnext.sh: line 4: 26942 Aborted                    (core dumped) ./webui.sh --debug --models-dir ~/models
```
So I tried again, but by leaving the paths blank, apply then restart. 
Eventually I was able to get it to make images as one would expect.

**Comment by Matt541753** [comment]
@resonantsky : Thank you very very much :) 

I was thinking that I try the very simple way first and leave both paths empty, and now everything is working as it should. Anyway I'm very glad that SD Next works properly with ROCm, the speed is at least 3 to 4 times faster than with other image generators I've tried before. Around 1.10it/s at 1024x1024 with Cyberrealistic XL for example is really nice with my gpu :)

**Comment by nktice** [comment]
I would recommend making the default settings for those values blank, so out of the box default config does not crash for common users.
