### ISSUE TITLE
[Issue]: VAE failed to validate on some SDXL models

### ISSUE THREAD

**Issue by ProfessionalMisunderstanding** [vladmandic/automatic#4759]
### Issue Description

Yesterday I managed to generate 3 images in a row in a resolution of 2048 by 2048, but today every picture gives errors. The Nova Mobian XL and Nova Reality XL models give errors, while the Nova MLP XL works fine in this resolution

13:50:24-189248 INFO     Starting SD.Next
13:50:24-193248 INFO     Logger: file="D:\sdnext rocm\sdnext\sdnext.log" level=DEBUG host="DESKTOP-KJDNSM" size=83
                         mode=append
13:50:24-197249 INFO     Python: version=3.12.7 platform=Windows bin="D:\sdnext rocm\sdnext\venv\Scripts\python.exe"
                         venv="D:\sdnext rocm\sdnext\venv"
13:50:24-202247 WARNING  Python: path="D:\sdnext rocm\sdnext\venv\Scripts\python.exe" contains spaces which may cause
                         issues
13:50:24-221248 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.12.7 locale=('Russian_Russia', '1251')
                         setuptools=69.5.1 docker=False
13:50:24-446706 INFO     Version: app=sd.next updated=2026-04-04 commit=0eb4a98e0 branch=master
                         url=https://github.com/vladmandic/sdnext/tree/master kanvas=main ui=main
13:50:25-177250 TRACE    Repository branches: active=master available=['dev', 'feat/civitai-base-models',
                         'fix/sdnq-lora-swap', 'master']
13:50:25-605395 INFO     Version: app=sd.next latest=2026-04-04T09:10:28Z hash=0eb4a98e branch=master
13:50:25-607397 DEBUG    Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
13:50:25-609397 INFO     Args: ['--use-rocm', '--theme', 'modern/default']
13:50:25-610395 DEBUG    Setting environment tuning
13:50:25-612397 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
13:50:25-615396 INFO     Torch: verifying installation
13:50:25-616396 DEBUG    Torch overrides: cuda=False rocm=True ipex=False directml=False openvino=False zluda=False
sdnext: Unknown command line argument 'rocm\sdnext\venv\Lib\site-packages\_rocm_sdk_core\lib\llvm\bin\offload-arch.exe'.  Try: 'D:\sdnext --help'
13:50:26-445010 INFO     ROCm: agents=['gfx1031']
13:50:26-448009 INFO     ROCm: version=7.2, using agent gfx1031
13:50:26-449009 INFO     Python: version=3.12.7 platform=Windows bin="D:\sdnext rocm\sdnext\venv\Scripts\python.exe"
                         venv="D:\sdnext rocm\sdnext\venv"
13:50:26-455008 WARNING  Python: path="D:\sdnext rocm\sdnext\venv\Scripts\python.exe" contains spaces which may cause
                         issues
13:50:26-456009 INFO     ROCm: HSA_OVERRIDE_GFX_VERSION config overridden: device=gfx1031 version=10.3.0
13:50:47-331570 INFO     Torch backend: {'version': '2.10.0+rocm7.12.0a20260218', 'type': 'rocm', 'hip': '7.2.0'}
13:50:47-335570 INFO     Torch detected: {'gpu': 'AMD Radeon RX 6700 XT', 'vram': 12272, 'arch': '10.3 Unknown',
                         'cores': 20}
13:50:47-482733 INFO     Install: verifying requirements
13:50:47-588064 DEBUG    State: cached=True
13:50:47-589063 INFO     StartuD: launch=quick
13:50:47-590063 INFO     Extensions: disabled=[]
13:50:47-591063 INFO     Extensions: path="extensions-builtin" enabled=['sd-extension-chainner',
                         'sd-extension-system-info', 'sdnext-kanvas', 'sdnext-modernui',
                         'stable-diffusion-webui-rembg']
13:50:47-598063 INFO     Extensions: path="extensions" enabled=[]
13:50:47-604063 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
13:50:47-605062 INFO     Installer time: total=24.20 torch=21.72 latest=1.38 version=0.22 base=0.20 amd=0.18 git=0.17
                         files=0.14
13:50:47-609063 INFO     Command line args: ['--use-rocm', '--theme', 'modern/default'] use_rocm=True
                         theme=modern/default args=[]
13:50:47-612063 DEBUG    Flags: sd=[] ld=[]
13:50:47-613063 DEBUG    Starting module: <module 'webui' from 'D:\\sdnext rocm\\sdnext\\webui.py'>
13:50:47-616064 DEBUG    Initializing: libraries
13:50:49-165975 WARNING  Loader: torch is not built with distributed support
13:51:00-766215 INFO     Torch: torch==2.10.0+rocm7.12.0a20260218 torchvision==0.25.0+rocm7.12.0a20260218
13:51:00-770216 INFO     Packages: diffusers==0.38.0.dev0 transformers==5.5.0.dev0 accelerate==1.13.0 gradio==3.43.2
                         pydantic==2.12.5 numpy==2.1.2 cv2==4.12.0
13:51:00-785215 DEBUG    Initializing: shared module
13:51:00-902328 DEBUG    Initializing: pipelines
13:51:01-994227 DEBUG    State initialized: id=2383157668864
13:51:02-073227 DEBUG    ROCm: agents=[<modules.rocm.Agent object at 0x0000022ADF4D54C0>]
13:51:02-075225 DEBUG    ROCm: selected=[<modules.rocm.Agent object at 0x0000022ADF4D54C0>]
13:51:02-077225 WARNING  ROCm: hipBLASLt unavailable agent=gfx1031
13:51:02-332699 DEBUG    Initializing: default modes
13:51:02-333698 INFO     Device detect: memory=12.0 default=balanced optimization=medvram
13:51:02-335697 DEBUG    Initializing: settings
13:51:02-352719 DEBUG    Read: file="D:\sdnext rocm\sdnext\config.json" json=27 bytes=1152 time=0.000 fn=__init__:load
13:51:02-355716 DEBUG    Read: file="D:\sdnext rocm\sdnext\secrets.json" json=2 bytes=142 time=0.000 fn=__init__:load
13:51:02-357717 DEBUG    Initializing: backend
13:51:02-358717 INFO     Engine: backend=Backend.DIFFUSERS compute=rocm device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
13:51:02-364716 DEBUG    Read: file="data\reference.json" json=102 bytes=52147 time=0.001
                         fn=_call_with_frames_removed:<module>
13:51:02-367718 DEBUG    Initializing: devices
13:51:02-376716 DEBUG    Torch cuDNN: enabled=False
13:51:02-378718 DEBUG    Torch attention: type="sdpa" kernels=['Flash', 'Memory', 'Math'] overrides=['Sage attention']
13:51:02-401716 DEBUG    Torch attention: type="Sage attention" backend=auto
13:51:02-404717 DEBUG    Torch attention installed: flashattn=False sageattention=1.0.6
13:51:02-406718 DEBUG    Torch attention status: flash=False flash3=False aiter=False sage=False flex=True npu=False
                         xla=False xformers=False
13:51:04-476597 DEBUG    Triton: pass=True version=3.6.0 fn=<module>:set_cuda_params time=2.01
13:51:04-479598 INFO     Torch parameters: backend=rocm device=cuda config=FP16 dtype=torch.float16 context=no_grad
                         nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False, False] fp16=pass
                         bf16=fail triton=pass optimization="Scaled-Dot-Product"
13:51:04-483597 DEBUG    Quantization: registered=SDNQ
13:51:04-485599 INFO     Device: device=AMD Radeon RX 6700 XT n=1 hip=7.2.0
13:51:04-678598 INFO     API: limit=300 strategy=SlidingWindowCounterRateLimiter backend=MemoryStorage
13:51:04-681598 DEBUG    Entering start sequence
13:51:04-684597 DEBUG    Initializing: modules
13:51:04-695597 DEBUG    Read: file="data\metadata.json" json=47 bytes=2013202 time=0.010 fn=initialize:init_metadata
13:51:04-699597 DEBUG    Read: file="data\cache.json" json=2 bytes=2663 time=0.000 fn=initialize:init_cache
13:51:04-777599 INFO     Available UNets: path="models\UNET" items=0
13:51:04-779601 INFO     Available TEs: path="models\Text-encoder" items=0
13:51:04-780599 INFO     Available VAEs: path="models\VAE" items=0
13:51:04-785602 INFO     Available Models: safetensors="D:\Neural Network Models\Paint\SDXL\Nova Models":8
                         diffusers="models\Diffusers":0 reference=102 items=8 time=0.01
13:51:04-791599 DEBUG    Model metadata: file="data\metadata.json" no changes
13:51:04-804598 INFO     Available LoRAs: path="D:\Neural Network Models\Paint\SDXL\Lora" items=26 folders=2 time=0.01
13:51:05-015600 DEBUG    Read: file="data\upscalers.json" json=4 bytes=2672 time=0.001 fn=__init__:__init__
13:51:05-079600 INFO     Available Upscalers: items=57 downloaded=0 user=0 time=0.30 types=['None', 'Resize', 'Latent',
                         'AsymmetricVAE', 'WanUpscale', 'DCC', 'VIPS', 'HQX', 'ICBI', 'Spandrel', 'AuraSR', 'ESRGAN',
                         'RealESRGAN', 'SCUNet', 'Diffusion', 'SeedVR', 'SwinIR']
13:51:05-099600 INFO     Available Styles: path="models\styles" items=288 time=0.02
13:51:05-102601 INFO     Available Detailer: path="models\yolo" items=10 downloaded=0
13:51:05-104600 DEBUG    Extensions: disabled=['stable-diffusion-webui-rembg']
13:51:05-105603 INFO     Load extensions
13:51:05-286997 DEBUG    Extensions init time: total=0.18
13:51:05-296997 INFO     Huggingface: transfer=rust parallel=True direct=False token="None" cache="models\huggingface"
                         init
13:51:05-314996 WARNING  Cache location changed: previous="C:\Users\User\.cache\huggingface\hub" size=586 MB
13:51:05-319996 DEBUG    Huggingface: cache="models\huggingface" size=0 MB
13:51:05-321996 DEBUG    Temp folder: path="C:\Users\User\AppData\Local\Temp\gradio"
13:51:05-338996 DEBUG    UI start sequence
13:51:05-339995 DEBUG    UI image support: kanvas=main
13:51:05-348996 INFO     UI locale: name="en: English"
13:51:05-349996 INFO     UI theme: type=Modern name="Default" available=39
13:51:05-352999 DEBUG    UI theme: css="extensions-builtin\sdnext-modernui\themes\Default.css" base="['base.css',
                         'timesheet.css']" user="None"
13:51:05-357995 DEBUG    UI initialize: tab=txt2img
13:51:05-388997 DEBUG    Read: file="data\reference.json" json=102 bytes=52147 time=0.000 fn=list_items:list_reference
13:51:05-394998 DEBUG    Read: file="data\reference-quant.json" json=24 bytes=9379 time=0.001
                         fn=list_items:list_reference
13:51:05-398998 DEBUG    Read: file="data\reference-distilled.json" json=22 bytes=11089 time=0.001
                         fn=list_items:list_reference
13:51:05-402998 DEBUG    Read: file="data\reference-community.json" json=21 bytes=8764 time=0.001
                         fn=list_items:list_reference
13:51:05-406996 DEBUG    Read: file="data\reference-cloud.json" json=3 bytes=1102 time=0.000
                         fn=list_items:list_reference
13:51:05-410996 DEBUG    Read: file="data\reference-nunchaku.json" json=18 bytes=7581 time=0.001
                         fn=list_items:list_reference
13:51:05-437000 DEBUG    Networks: type="reference" {'total': 190, 'ready': 0, 'hidden': 18, 'experimental': 0, 'base':
                         102, 'quantized': 24, 'community': 21, 'distilled': 20, 'cloud': 3}
13:51:05-447996 DEBUG    Networks: type="model" items=178 subfolders=9 tab=txt2img folders=['D:\\Neural Network
                         Models\\Paint\\SDXL\\Nova Models', 'models\\Reference', 'D:\\sdnext
                         rocm\\sdnext\\models\\Stable-diffusion'] list=0.07 thumb=0.00 desc=0.00 info=0.00 workers=12
13:51:05-453997 DEBUG    Networks: type="lora" items=26 subfolders=1 tab=txt2img folders=['D:\\Neural Network
                         Models\\Paint\\SDXL\\Lora'] list=0.02 thumb=0.01 desc=0.00 info=0.01 workers=12
13:51:05-459998 DEBUG    Networks: type="unet/dit" items=0 subfolders=1 tab=txt2img folders=['models\\UNET'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=12
13:51:05-471996 DEBUG    Networks: type="style" items=288 subfolders=3 tab=txt2img folders=['models\\styles', 'html']
                         list=0.02 thumb=0.00 desc=0.00 info=0.00 workers=12
13:51:05-476995 DEBUG    Networks: type="wildcards" items=0 subfolders=1 tab=txt2img folders=['models\\wildcards']
                         list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=12
13:51:05-480996 DEBUG    Networks: type="embedding" items=0 subfolders=1 tab=txt2img folders=['models\\embeddings']
                         list=0.01 thumb=0.00 desc=0.00 info=0.00 workers=12
13:51:05-486998 DEBUG    Networks: type="vae" items=0 subfolders=1 tab=txt2img folders=['models\\VAE'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=12
13:51:05-490996 DEBUG    Networks: type="history" items=0 subfolders=1 tab=txt2img folders=[] list=0.00 thumb=0.00
                         desc=0.00 info=0.00 workers=12
13:51:05-692127 DEBUG    ROCm load_config: path=D:\sdnext rocm\sdnext\data\rocm.json existed=False items=61
13:51:05-859124 DEBUG    UI initialize: tab=img2img
13:51:06-379388 DEBUG    UI initialize: tab=control models="models\control"
13:51:06-588387 DEBUG    Script: fn="extensions-builtin\sd-extension-system-info\scripts\system-info.py" type=control
                         skip
13:51:06-794514 DEBUG    UI initialize: tab=video
13:51:06-899183 INFO     Networks: type="video" engines=13 models=79 errors=0 time=0.08
13:51:07-003182 DEBUG    UI initialize: tab=process
13:51:07-058182 DEBUG    UI initialize: tab=caption
13:51:07-118182 DEBUG    UI initialize: tab=models
13:51:07-209182 DEBUG    UI initialize: tab=gallery
13:51:07-268184 DEBUG    Read: file="ui-config.json" json=13 bytes=902 time=0.006 fn=__init__:read_from_file
13:51:07-270183 DEBUG    UI initialize: tab=settings
13:51:07-343415 DEBUG    ONNX: version=1.24.3, available=['AzureExecutionProvider', 'CPUExecutionProvider']
13:51:07-714643 DEBUG    Settings: sections=23 settings=366/600 quicksettings=1
13:51:07-784643 DEBUG    UI initialize: tab=info
13:51:07-812644 DEBUG    UI initialize: tab=extensions
13:51:07-816643 INFO     Extension list: No information found - refresh required
13:51:08-247643 DEBUG    Extension list: processed=3 installed=3 enabled=2 disabled=1 visible=3 hidden=0
13:51:08-752596 DEBUG    Root paths: ['D:\\sdnext rocm\\sdnext']
13:51:08-867597 INFO     Local URL: httD://127.0.0.1:7860/
13:51:08-869599 INFO     API docs: httD://127.0.0.1:7860/docs
13:51:08-869599 INFO     API redocs: httD://127.0.0.1:7860/redocs
13:51:08-872597 DEBUG    API middleware: [<class 'starlette.middleware.base.BaseHTTPMiddleware'>, <class
                         'starlette.middleware.gzip.GZipMiddleware'>]
13:51:08-874598 DEBUG    API initialize
13:51:09-065063 DEBUG    Scripts setuD: time=0.426 ['Windows ROCm: Advanced Config:0.075']
13:51:09-067063 INFO     Model: autoload=True selected="novaMobianXL_v10 [e28c650622]"
13:51:09-071063 DEBUG    Model requested: fn=threading.py:run:<lambda>
13:51:09-072061 DEBUG    Search model: name="novaMobianXL_v10 [e28c650622]" matched="D:\Neural Network
                         Models\Paint\SDXL\Nova Models\novaMobianXL_v10.safetensors" type=alias
13:51:09-075063 INFO     Load model: select="novaMobianXL_v10 [e28c650622]"
13:51:09-079063 INFO     Autodetect model: detect="Stable Diffusion XL" class=StableDiffusionXLPipeline file="D:\Neural
                         Network Models\Paint\SDXL\Nova Models\novaMobianXL_v10.safetensors"
13:51:09-103063 DEBUG    Cache clear
Progress  5.00it/s █████████ 100% 7/7 00:01 00:00 Loading pipeline components...
13:51:10-845368 DEBUG    Setting model: pipeline=StableDiffusionXLPipeline config={'low_cpu_mem_usage': True,
                         'torch_dtype': torch.float16, 'load_connected_pipeline': True, 'extract_ema': False, 'config':
                         'configs/sdxl', 'use_safetensors': True, 'cache_dir': 'models\\huggingface'}
13:51:10-858367 INFO     Network load: type=embeddings loaded=0 skipped=0 time=0.00
13:51:10-859370 DEBUG    Setting model: component=vae {'slicing': True, 'tiling': False}
13:51:10-862370 DEBUG    Setting model: attention="Scaled-Dot-Product"
13:51:10-863370 INFO     Offload: type=balanced op=init watermark=0-0.6 gpu=0.00-7.20:12.00 cpu=32.000 limit=0.00
                         always=[] never=[] pre=True streams=False
13:51:10-899367 DEBUG    Module: name=unet cls=UNet2DConditionModel size=4.782 params=2567463684 quant=None
13:51:10-909368 DEBUG    Module: name=text_encoder_2 cls=CLIPTextModelWithProjection size=1.294 params=694659840
                         quant=None
13:51:10-916368 DEBUG    Module: name=text_encoder cls=CLIPTextModel size=0.229 params=123060480 quant=None
13:51:10-925367 DEBUG    Module: name=vae cls=AutoencoderKL size=0.156 params=83653863 quant=None
13:51:10-928369 INFO     Model class=StableDiffusionXLPipeline modules=4 size=6.461
13:51:10-934367 INFO     Load model: family=sdxl time={'total': 1.85, 'load': 1.78} native=1024 memory={'ram':
                         {'total': 31.87, 'rss': 2.48, 'used': 6.32, 'free': 25.55, 'avail': 25.55, 'buffers': 0,
                         'cached': 0}, 'gpu': {'used': 0.18, 'total': 11.98, 'active': 0.0, 'peak': 0.0, 'retries': 0,
                         'oom': 0, 'swap': 0}, 'job': 'Load model'}
13:51:10-946370 DEBUG    Script init: ['system-info.py:app_started=0.08']
13:51:10-948368 DEBUG    Save: file="D:\sdnext rocm\sdnext\config.json" json=27 bytes=1122 time=0.002
13:51:10-949368 INFO     Startup time: total=94.59 launch=24.27 loader=23.76 installer=23.75 torch=6.96 libraries=4.74
                         gradio=3.67 checkpoint=1.88 diffusers=1.47 ui-extensions=0.97 ui-img2img=0.46 ui-networks=0.40
                         ui-txt2img=0.33 scans=0.31 ui-control=0.28 extensions=0.18 ui-video=0.16 ui-defaults=0.11
                         api=0.11
13:51:10-952368 DEBUG    Save: file="D:\sdnext rocm\sdnext\secrets.json" json=2 bytes=139 time=0.001
13:51:13-627678 INFO     API user=None code=200 http/1.1 GET / 127.0.0.1 0.4573
13:51:14-259284 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/motd 127.0.0.1 0.085
13:51:17-215714 INFO     API user=None code=200 http/1.1 GET /info 127.0.0.1 3.2354
13:51:20-177678 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/sd-models 127.0.0.1 0.001
13:51:21-664977 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/browser/folders 127.0.0.1 0.003
13:51:21-781977 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64)
                         AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36
13:51:21-787977 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/start 127.0.0.1 0.008
13:51:21-808977 DEBUG    UI: connected
13:51:23-237315 INFO     UI: ready time=9199
13:51:24-061460 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/status 127.0.0.1 0.001
13:51:43-380359 INFO     Applying HyperTile: vae=128/128
13:51:43-396361 DEBUG    Sampler: "Euler a" class=EulerAncestralDiscreteScheduler config={'num_train_timesteps': 1000,
                         'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'prediction_type':
                         'epsilon', 'timestep_spacing': 'linspace', 'steps_offset': 0}
13:51:43-418361 INFO     Processing modifiers: apply
13:51:43-451358 DEBUG    Tokenizer: words=49408 file="configs/sdxl\tokenizer\vocab.json"
13:51:48-043131 DEBUG    Model move: device=cuda class=CLIPTextModelWithProjection accelerate=True
                         fn=get_weighted_text_embeddings:prepare_embedding_providers time=3.62
13:51:51-003748 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=1/1x1 set={'prompt_embeds':
                         torch.Size([1, 154, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]),
                         'negative_prompt_embeds': torch.Size([1, 154, 2048]), 'negative_pooled_prompt_embeds':
                         torch.Size([1, 1280]), 'guidance_scale': 4.5, 'generator': 'cuda:[3197733508]',
                         'num_inference_steps': 40, 'eta': 1.0, 'guidance_rescale': 0, 'denoising_end': None,
                         'output_type': 'latent', 'width': 2048, 'height': 2048, 'parser': 'native'}
Progress ?it/s                                              0% 0/40 00:00 ? Base ⣻  Sage Attention·INT8·2c·0.0s                                                                                          ⢿  Sage Attention·INT8·2c·0.0s                                                                                          ⡿  Sage Attention·INT8·66c·0.1s                                                                                         ⣟  Sage Attention·INT8·119c·0.1s       Progress 37.19s/it ▊                                    2% 1/40 00:37 24:10 Base ⣯  Sage Attention·INT8·2c·0.0s                                                                                          ⣷  Sage Attention·INT8·65c·0.1s                                                                                         ⣾  Sage Attention·INT8·132c·0.1s       Progress 19.30s/it █▋                                   5% 2/40 00:43 12:13 Base ⣽  Sage Attention·INT8·2c·0.0s                                                                                          ⣻  Sage Attention·INT8·64c·0.1s                                                                                         ⢿  Sage Attention·INT8·131c·0.1s       Progress 13.66s/it ██▌                                  8% 3/40 00:50 08:25 Base ⡿  Sage Attention·INT8·2c·0.0s                                                                                          ⣟  Sage Attention·INT8·60c·0.1s                                                                                         ⣯  Sage Attention·INT8·129c·0.1s       Progress 11.03s/it ███▍                                10% 4/40 00:57 06:37 Base ⣷  Sage Attention·INT8·2c·0.0s                                                                                          ⣾  Sage Attention·INT8·60c·0.1s                                                                                         ⣽  Sage Attention·INT8·129c·0.1s       Progress  9.52s/it ████▎                               12% 5/40 01:04 05:33 Base ⣻  Sage Attention·INT8·2c·0.0s                                                                                          ⢿  Sage Attention·INT8·65c·0.1s                                                                                         ⡿  Sage Attention·INT8·133c·0.1s       Progress  8.63s/it █████                               15% 6/40 01:11 04:53 Base ⣟  Sage Attention·INT8·2c·0.0s                                                                                          ⣯  Sage Attention·INT8·65c·0.1s                                                                                         ⣷  Sage Attention·INT8·133c·0.1s       Progress  8.10s/it █████▉                              18% 7/40 01:18 04:27 Base ⣾  Sage Attention·INT8·2c·0.0s                                                                                          ⣽  Sage Attention·INT8·66c·0.1s                                                                                         ⣻  Sage Attention·INT8·133c·0.1s       Progress  7.70s/it ██████▊                             20% 8/40 01:25 04:06 Base ⢿  Sage Attention·INT8·2c·0.0s                                                                                          ⡿  Sage Attention·INT8·65c·0.1s                                                                                         ⣟  Sage Attention·INT8·132c·0.1s       Progress  7.44s/it ███████▋                            22% 9/40 01:32 03:50 Base ⣯  Sage Attention·INT8·2c·0.0s                                                                                          ⣷  Sage Attention·INT8·65c·0.1s                                                                                         ⣾  Sage Attention·INT8·132c·0.1s       
13:53:28-500704 DEBUG    Decode: type="taesd" variant="TAESD 1.3 Mocha Croissant"
                         fn="models\TAESD\taesd_13_decoder_sdxl.pth" layers=3 load
Progress  7.32s/it ████████▎                          25% 10/40 01:39 03:39 Base ⣽  Sage Attention·INT8·2c·0.0s                                                                                          ⣻  Sage Attention·INT8·65c·0.1s                                                                                         ⢿  Sage Attention·INT8·127c·0.1s       Progress  7.19s/it █████████                          28% 11/40 01:46 03:28 Base ⡿  Sage Attention·INT8·2c·0.0s                                                                                          ⣟  Sage Attention·INT8·65c·0.1s                                                                                         ⣯  Sage Attention·INT8·129c·0.1s       Progress  7.09s/it █████████▉                         30% 12/40 01:53 03:18 Base ⣷  Sage Attention·INT8·2c·0.0s                                                                                          ⣾  Sage Attention·INT8·63c·0.1s                                                                                         ⣽  Sage Attention·INT8·127c·0.1s       Progress  7.07s/it ██████████▋                        32% 13/40 02:00 03:10 Base ⣻  Sage Attention·INT8·2c·0.0s                                                                                          ⢿  Sage Attention·INT8·64c·0.1s                                                                                         ⡿  Sage Attention·INT8·127c·0.1s       Progress  7.04s/it ███████████▌                       35% 14/40 02:07 03:03 Base ⣟  Sage Attention·INT8·2c·0.0s                                                                                          ⣯  Sage Attention·INT8·67c·0.1s                                                                                         ⣷  Sage Attention·INT8·133c·0.1s       Progress  6.98s/it ████████████▍                      38% 15/40 02:14 02:54 Base ⣾  Sage Attention·INT8·2c·0.0s                                                                                          ⣽  Sage Attention·INT8·66c·0.1s                                                                                         ⣻  Sage Attention·INT8·130c·0.1s       Progress  6.86s/it █████████████▏                     40% 16/40 02:20 02:44 Base ⢿  Sage Attention·INT8·2c·0.0s                                                                                          ⡿  Sage Attention·INT8·67c·0.1s                                                                                         ⣟  Sage Attention·INT8·133c·0.1s       Progress  6.64s/it ██████████████                     42% 17/40 02:26 02:32 Base ⣯  Sage Attention·INT8·2c·0.0s                                                                                          ⣷  Sage Attention·INT8·70c·0.1s                                                                                         ⣾  Sage Attention·INT8·138c·0.1s       Progress  6.45s/it ██████████████▊                    45% 18/40 02:32 02:21 Base ⣽  Sage Attention·INT8·2c·0.0s                                                                                          ⣻  Sage Attention·INT8·70c·0.1s                                                                                         ⢿  Sage Attention·INT8·139c·0.1s       Progress  6.33s/it ███████████████▋                   48% 19/40 02:38 02:13 Base ⡿  Sage Attention·INT8·2c·0.0s                                                                                          ⣟  Sage Attention·INT8·69c·0.1s                                                                                         ⣯  Sage Attention·INT8·129c·0.1s       Progress  6.24s/it ████████████████▌                  50% 20/40 02:44 02:04 Base ⣷  Sage Attention·INT8·2c·0.0s                                                                                          ⣾  Sage Attention·INT8·67c·0.1s                                                                                         ⣽  Sage Attention·INT8·134c·0.1s       Progress  6.23s/it █████████████████▎                 52% 21/40 02:51 01:58 Base ⣻  Sage Attention·INT8·2c·0.0s                                                                                          ⢿  Sage Attention·INT8·68c·0.1s                                                                                         ⡿  Sage Attention·INT8·133c·0.1s       Progress  6.16s/it ██████████████████▏                55% 22/40 02:57 01:50 Base ⣟  Sage Attention·INT8·2c·0.0s                                                                                          ⣯  Sage Attention·INT8·69c·0.1s                                                                                         ⣷  Sage Attention·INT8·136c·0.1s       Progress  6.14s/it ██████████████████▉                57% 23/40 03:03 01:44 Base ⣾  Sage Attention·INT8·2c·0.0s                                                                                          ⣽  Sage Attention·INT8·65c·0.1s                                                                                         ⣻  Sage Attention·INT8·133c·0.1s       Progress  6.14s/it ███████████████████▊               60% 24/40 03:09 01:38 Base ⢿  Sage Attention·INT8·2c·0.0s                                                                                          ⡿  Sage Attention·INT8·69c·0.1s                                                                                         ⣟  Sage Attention·INT8·137c·0.1s       Progress  6.13s/it ████████████████████▋              62% 25/40 03:15 01:31 Base ⣯  Sage Attention·INT8·2c·0.0s                                                                                          ⣷  Sage Attention·INT8·66c·0.1s                                                                                         ⣾  Sage Attention·INT8·132c·0.1s       Progress  6.11s/it █████████████████████▍             65% 26/40 03:21 01:25 Base ⣽  Sage Attention·INT8·2c·0.0s                                                                                          ⣻  Sage Attention·INT8·68c·0.1s                                                                                         ⢿  Sage Attention·INT8·134c·0.1s       Progress  6.11s/it ██████████████████████▎            68% 27/40 03:27 01:19 Base ⡿  Sage Attention·INT8·2c·0.0s                                                                                          ⣟  Sage Attention·INT8·64c·0.1s                                                                                         ⣯  Sage Attention·INT8·131c·0.1s       Progress  6.12s/it ███████████████████████            70% 28/40 03:33 01:13 Base ⣷  Sage Attention·INT8·2c·0.0s                                                                                          ⣾  Sage Attention·INT8·65c·0.1s                                                                                         ⣽  Sage Attention·INT8·131c·0.1s       Progress  6.09s/it ███████████████████████▉           72% 29/40 03:39 01:06 Base ⣻  Sage Attention·INT8·2c·0.0s                                                                                          ⢿  Sage Attention·INT8·63c·0.1s                                                                                         ⡿  Sage Attention·INT8·130c·0.1s       Progress  6.05s/it ████████████████████████▊          75% 30/40 03:45 01:00 Base ⣟  Sage Attention·INT8·2c·0.0s                                                                                          ⣯  Sage Attention·INT8·65c·0.1s                                                                                         ⣷  Sage Attention·INT8·132c·0.1s       Progress  6.04s/it █████████████████████████▌         78% 31/40 03:51 00:54 Base ⣾  Sage Attention·INT8·2c·0.0s                                                                                          ⣽  Sage Attention·INT8·63c·0.1s                                                                                         ⣻  Sage Attention·INT8·131c·0.1s       Progress  6.05s/it ██████████████████████████▍        80% 32/40 03:57 00:48 Base ⢿  Sage Attention·INT8·2c·0.0s                                                                                          ⡿  Sage Attention·INT8·65c·0.1s                                                                                         ⣟  Sage Attention·INT8·130c·0.1s       Progress  6.04s/it ███████████████████████████▏       82% 33/40 04:03 00:42 Base ⣯  Sage Attention·INT8·2c·0.0s                                                                                          ⣷  Sage Attention·INT8·65c·0.1s                                                                                         ⣾  Sage Attention·INT8·132c·0.1s       Progress  6.08s/it ████████████████████████████       85% 34/40 04:09 00:36 Base ⣽  Sage Attention·INT8·2c·0.0s                                                                                          ⣻  Sage Attention·INT8·61c·0.1s                                                                                         ⢿  Sage Attention·INT8·129c·0.1s       Progress  6.10s/it ████████████████████████████▉      88% 35/40 04:16 00:30 Base ⡿  Sage Attention·INT8·2c·0.0s                                                                                          ⣟  Sage Attention·INT8·65c·0.1s                                                                                         ⣯  Sage Attention·INT8·131c·0.1s       Progress  6.10s/it █████████████████████████████▋     90% 36/40 04:22 00:24 Base ⣷  Sage Attention·INT8·2c·0.0s                                                                                          ⣾  Sage Attention·INT8·64c·0.1s                                                                                         ⣽  Sage Attention·INT8·129c·0.1s       Progress  6.12s/it ██████████████████████████████▌    92% 37/40 04:28 00:18 Base ⣻  Sage Attention·INT8·2c·0.0s                                                                                          ⢿  Sage Attention·INT8·63c·0.1s                                                                                         ⡿  Sage Attention·INT8·128c·0.1s       Progress  6.12s/it ███████████████████████████████▎   95% 38/40 04:34 00:12 Base ⣟  Sage Attention·INT8·2c·0.0s                                                                                          ⣯  Sage Attention·INT8·64c·0.1s                                                                                         ⣷  Sage Attention·INT8·132c·0.1s       Progress  6.11s/it ████████████████████████████████▏  98% 39/40 04:40 00:06 Base ⣾  Sage Attention·INT8·2c·0.0s                                                                                          ⣽  Sage Attention·INT8·65c·0.1s                                                                                         ⣻  Sage Attention·INT8·131c·0.1s       Progress  7.16s/it █████████████████████████████████ 100% 40/40 04:46 00:00 Base
13:56:37-946405 DEBUG    GC: current={'gpu': 5.51, 'ram': 15.26, 'oom': 0} prev={'gpu': 10.03, 'ram': 15.26}
                         load={'gpu': 46, 'ram': 48} gc={'gpu': 4.52, 'py': 2640} fn=process_base:end why=threshold
                         time=0.36
13:56:37-955406 INFO     Processing modifiers: unapply
13:56:38-006406 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}
13:57:11-397856 TRACE    Server: alive=True requests=336 memory=31.87/31.87 status='running' task='VAE Decode'
                         timestamp='20260414135638' current='task(devqqaf48ukigse)' id='8b79e5aec7a9441' job=0 jobs=1
                         total=10 step=0 steps=0 queued=0 uptime=371 elapsed=33.32 eta=None progress=0
13:57:38-763337 DEBUG    Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 256,
                         256]:cuda:0 dtype=torch.float16 time=60.753
13:57:49-187097 DEBUG    GC: current={'gpu': 11.98, 'ram': 5.03, 'oom': 0} prev={'gpu': 11.98, 'ram': 13.54}
                         load={'gpu': 100, 'ram': 16} gc={'gpu': 0.0, 'py': 650} fn=process_decode:vae_decode
                         why=threshold time=1.03
13:57:49-607326 DEBUG    GC: current={'gpu': 11.98, 'ram': 4.95, 'oom': 0} prev={'gpu': 11.98, 'ram': 5.03}
                         load={'gpu': 100, 'ram': 16} gc={'gpu': 0.0, 'py': 127} fn=vae_decode:end why=threshold
                         time=0.41
13:57:49-756326 ERROR    Decode: sample=(2048, 2048, 3) invalid=12582912 dtype=float32 vae=torch.float16 upcast=False
                         failed to validate
13:57:49-760326 INFO     Decode: set upcast=True and attempt to retry operation
13:57:50-201577 DEBUG    GC: current={'gpu': 11.98, 'ram': 4.89, 'oom': 0} prev={'gpu': 11.98, 'ram': 4.92}
                         load={'gpu': 100, 'ram': 15} gc={'gpu': 0.0, 'py': 127} fn=atomically_save_image:begin
                         why=threshold time=0.36

### Relevant log output

```shell

```

### Operating system

Windows

### Compute

AMD ROCm

### Interface

ModernUI

### Branch

Master

### Model

StableDiffusion 1.5/2.1/XL

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
you're running in fp16 precision because your gpu failed bf16 test (sdnext tests gpu capabilities and precision on start)
and many models are simply not safe to run in fp16 precision as they have numerical overflows.
and this is especially common for sdxl models that still use original vae and do not pack newer fixed vae.
download and manually override vae to use fp16 fixed sdxl vae.

also, sage attention is fast, but it takes a lot of shortcuts - so yes, it can also result in quite a lot of numerical instabilities.
plus you also have hypertile - which can also result in additional instabilities.

**Comment by ProfessionalMisunderstanding** [comment]
> you're running in fp16 precision because your gpu failed bf16 test (sdnext tests gpu capabilities and precision on start) and many models are simply not safe to run in fp16 precision as they have numerical overflows. and this is especially common for sdxl models that still use original vae and do not pack newer fixed vae. download and manually override vae to use fp16 fixed sdxl vae.
> 
> also, sage attention is fast, but it takes a lot of shortcuts - so yes, it can also result in quite a lot of numerical instabilities. plus you also have hypertile - which can also result in additional instabilities.

How do I know if the patched VAE is enabled and it won't affect the generation result?

**Comment by ProfessionalMisunderstanding** [comment]
This does not help, the error "ValueError: Cannot generate a cpu tensor from a generator of type cuda." is returned. I download it from here https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/tree/main. "sdxl.vae.safetensors" gives the same error, and the other two give the one above

**Comment by ProfessionalMisunderstanding** [comment]
I tried to turn on BF16, but it gave the same error (failed to validate), and FP32 gave the error "HIP out of memory"

**Comment by ProfessionalMisunderstanding** [comment]
Turning off the "Hypertile VAE" did not help

**Comment by ProfessionalMisunderstanding** [comment]
@vladmandic What is the fastest parameter compared to "Sage attention"? They don't all have a description of what they are like. And is it possible to fix Sage attention?

**Comment by vladmandic** [comment]
there is no single fastest or it would have been enabled for all by default.
and there is no fixing sage - its not broken, its just not numerically stable exactly because its fast.

and no, you cant just "i'll run bf16" if your gpu is not compatible with bf16.

in general, for troubleshooting you need to reduce number of variables.
meaning, if we're dealing with failed-to-validate lets disable sage, hypertile, reduce resolution to normal, etc. - everything.
- if there is no longer a problem, then you know its in one of those items.
- if its still a problem, then apply vae-fix and upload new log.
- if its still a problem, run in fp32 and and upload new log
...

**Comment by ProfessionalMisunderstanding** [comment]
> there is no single fastest or it would have been enabled for all by default. and there is no fixing sage - its not broken, its just not numerically stable exactly because its fast.
> 
> and no, you cant just "i'll run bf16" if your gpu is not compatible with bf16.
> 
> in general, for troubleshooting you need to reduce number of variables. meaning, if we're dealing with failed-to-validate lets disable sage, hypertile, reduce resolution to normal, etc. - everything.
> 
> * if there is no longer a problem, then you know its in one of those items.
> * if its still a problem, then apply vae-fix and upload new log.
> * if its still a problem, run in fp32 and and upload new log
>   ...

I turned on Triton Attention and everything works fine with it, but the load on the graphics card is twice as high and the speed is twice as bad

**Comment by vladmandic** [comment]
meaning you switched from sage to triton attention?
yes, lets less optimized than sage, but i cannot fix sage to work on your gpu.

**Comment by ProfessionalMisunderstanding** [comment]
> meaning you switched from sage to triton attention? yes, lets less optimized than sage, but i cannot fix sage to work on your gpu.

And it works, but not in such a high resolution. What can I try to do to make it work in hires? Can I upgrade the Rocm wheels? I'm using wheels from February of this year

**Comment by vladmandic** [comment]
i doubt newer wheels would make a big change.
but there are tons of rocm tweaks and tbh i'm not a rocm expert - best to ask in rocm channel in our discord, there are quite a lot conversations on optimizations. and new extras -> script -> advanced rocm has tons of options.

**Comment by ProfessionalMisunderstanding** [comment]
> i doubt newer wheels would make a big change. but there are tons of rocm tweaks and tbh i'm not a rocm expert - best to ask in rocm channel in our discord, there are quite a lot conversations on optimizations. and new extras -> script -> advanced rocm has tons of options.

I'll definitely ask you when you finaly figure out this problem

<img width="1325" height="500" alt="Image" src="https://github.com/user-attachments/assets/04781f19-237e-4546-b9b4-fd871794ee81" />

**Comment by ProfessionalMisunderstanding** [comment]
> i doubt newer wheels would make a big change. but there are tons of rocm tweaks and tbh i'm not a rocm expert - best to ask in rocm channel in our discord, there are quite a lot conversations on optimizations. and new extras -> script -> advanced rocm has tons of options.

And there are no such settings here, or am I looking at the wrong place?

<img width="188" height="677" alt="Image" src="https://github.com/user-attachments/assets/b9398100-c3cc-40c8-808e-3aa1bedf0abc" />
<img width="189" height="413" alt="Image" src="https://github.com/user-attachments/assets/207aa501-9ff9-476c-9daf-214453c52665" />

**Comment by vladmandic** [comment]
> I'll definitely ask you when you finaly figure out this problem

I'll have a chat with him, this is not ok.
when something like this happens, please do flag it to me.

> And there are no such settings here, or am I looking at the wrong place?

Left panel -> Extras -> Scripts -> ROCm Advanced

**Comment by ProfessionalMisunderstanding** [comment]
> > I'll definitely ask you when you finaly figure out this problem
> 
> I'll have a chat with him, this is not ok. when something like this happens, please do flag it to me.
> 
> > And there are no such settings here, or am I looking at the wrong place?
> 
> Left panel -> Extras -> Scripts -> ROCm Advanced

I tried to report this by adding you as a friend, since I was banned from the server, but you still did not accept the request

**Comment by vladmandic** [comment]
> I tried to report this by adding you as a friend, since I was banned from the server, but you still did not accept the request

which username? i dont look at friend requests often as there are thousands of users

**Comment by ProfessionalMisunderstanding** [comment]
> > I tried to report this by adding you as a friend, since I was banned from the server, but you still did not accept the request
> 
> which username? i dont look at friend requests often as there are thousands of users

Hello, I found out here that Sage Attention is not only now unable to generate 2048 by 2048, but also lower resolutions that used to work fine, such as 1024 by 1536, that is, the problem is not in the type of attention and models, as I understand it, but in the program. And I have a question, how can I install Flash attention?
