### ISSUE TITLE
[Issue]: OpenVINO Black output image when used with SDNQ

### ISSUE THREAD

**Issue by ak-sangal** [vladmandic/automatic#4764]
### Issue Description

when I use sdxl Tubo model as SDNQ quantization i got blank output image, processing show image is generating but output image is totally black image as screenshort

i got below errror 
21:01:31-084825 ERROR    Decode: sample=(768, 768, 3) invalid=1769472 dtype=float32 vae=torch.float32 upcast=True failed to validate

<img width="1713" height="1436" alt="Image" src="https://github.com/user-attachments/assets/e2174906-6406-4b8f-b926-da27a467f952" />

### Version Platform Description

windows 11 processor i7 1355U, iGPU- intel irisx 16GB RAM, SDNEXT with OPENVINO.

### Relevant log output

```shell
20:46:39-587993 INFO     Autodetect model: detect="Stable Diffusion XL" class=StableDiffusionXLPipeline
                         file="models\Diffusers\models--stabilityai--sdxl-turbo\snapshots\71153311d3dbb46851df1931d3ca6e
                         939de83304"
20:46:39-589993 DEBUG    Cache clear
Loading weights: 100%|█████████████████████████████████████████████████████████████| 517/517 [00:00<00:00, 3957.06it/s]
Loading weights: 100%|█████████████████████████████████████████████████████████████| 196/196 [00:00<00:00, 4139.69it/s]
Progress  4.28it/s █████████ 100% 7/7 00:01 00:00 Loading pipeline components...               | 0/196 [00:00<?, ?it/s]
20:46:41-228852 INFO     Network load: type=embeddings loaded=0 skipped=0 time=0.00
20:46:41-231335 DEBUG    Setting model: component=vae {'slicing': True, 'tiling': False}
20:46:41-231835 DEBUG    Setting model: attention="Scaled-Dot-Product"
20:46:41-232835 DEBUG    Load model: post_quant=sdnq
20:46:41-233335 DEBUG    Quantization: type=SDNQ modules=['Model', 'TE', 'LLM'] dtype=int8 dtype_te=Same as model
                         offload=none pre_forward=True
20:47:06-163699 TRACE    Server: alive=True requests=328 memory=10.31/15.71 status='running' task='Load model'
                         timestamp='20260414204639' current='' id='d977cfa4bae3453' job=0 jobs=1 total=4 step=0 steps=0
                         queued=0 uptime=770 elapsed=26.91 eta=None progress=0
20:47:23-059492 DEBUG    GC: current={'gpu': 0, 'ram': 14.94, 'oom': 0} prev={'gpu': 0, 'ram': 14.71} load={'gpu': 0,
                         'ram': 95} gc={'gpu': 0, 'py': 4155} fn=apply_function_to_model:sdnq_quantize_model why=sdnq
                         time=0.55
20:47:23-061941 DEBUG    Quantization: module="unet" type=sdnq mode=post dtype=int8 matmul_dtype=auto matmul=False
                         svd=False dynamic=False:group=0:rank=32:steps=8:loss=-1e-08 matmul_conv=False quant_conv=False
                         quant_embedding=False fp32=True gpu=True device=cpu return=cpu map=default non_blocking=False
                         modules_skip=[] modules_dtype={}
20:47:24-048469 DEBUG    GC: current={'gpu': 0, 'ram': 15.36, 'oom': 0} prev={'gpu': 0, 'ram': 15.33} load={'gpu': 0,
                         'ram': 98} gc={'gpu': 0, 'py': 0} fn=apply_function_to_model:sdnq_quantize_model why=sdnq
                         time=0.31
20:47:24-050967 DEBUG    Quantization: module="text_encoder" type=sdnq mode=post dtype=int8 matmul_dtype=auto
                         matmul=False svd=False dynamic=False:group=0:rank=32:steps=8:loss=-1e-08 matmul_conv=False
                         quant_conv=False quant_embedding=False fp32=True gpu=True device=cpu return=cpu map=default
                         non_blocking=False modules_skip=[] modules_dtype={}
20:47:29-013047 DEBUG    GC: current={'gpu': 0, 'ram': 15.41, 'oom': 0} prev={'gpu': 0, 'ram': 15.4} load={'gpu': 0,
                         'ram': 98} gc={'gpu': 0, 'py': 104} fn=apply_function_to_model:sdnq_quantize_model why=sdnq
                         time=0.30
20:47:29-015047 DEBUG    Quantization: module="text_encoder_2" type=sdnq mode=post dtype=int8 matmul_dtype=auto
                         matmul=False svd=False dynamic=False:group=0:rank=32:steps=8:loss=-1e-08 matmul_conv=False
                         quant_conv=False quant_embedding=False fp32=True gpu=True device=cpu return=cpu map=default
                         non_blocking=False modules_skip=[] modules_dtype={}
20:47:29-016963 INFO     Quantization: type=SDNQ time=47.78
20:47:29-018080 DEBUG    Setting model: offload=none limit=0.0
20:47:29-023081 INFO     Model compile: pipeline=StableDiffusionXLPipeline mode=default backend=openvino_fx options=[]
                         compile=['Model', 'VAE', 'Upscaler', 'Control']
20:47:29-027147 DEBUG    Model compile: task=torch backends=['cudagraphs', 'inductor', 'openvino', 'openvino_fx',
                         'openxla', 'tvm']
20:47:29-099211 INFO     Model compile: task=torch time=0.07
20:47:29-348257 DEBUG    GC: current={'gpu': 0, 'ram': 15.31, 'oom': 0} prev={'gpu': 0, 'ram': 15.4} load={'gpu': 0,
                         'ram': 97} gc={'gpu': 0, 'py': 20} fn=reload_model_weights:load_diffuser why=load time=0.24
20:47:29-350468 INFO     Load model: family=sdxl time={'total': 96.13, 'options': 47.79, 'sdnq': 46.61, 'load': 1.64}
                         native=1024 memory={'ram': {'total': 15.71, 'rss': 11.39, 'used': 15.31, 'free': 0.4, 'avail':
                         0.4, 'buffers': 0, 'cached': 0}, 'gpu': {'total': 0, 'used': 0, 'error': 'Torch not compiled
                         with CUDA enabled', 'swap': 0}, 'job': 'Load model'}
20:47:29-365716 DEBUG    Save: file="F:\sdnext\config.json" json=15 bytes=663 time=0.009
20:47:29-372716 DEBUG    Save: file="F:\sdnext\secrets.json" json=2 bytes=139 time=0.003
20:48:30-584138 DEBUG    Sampler: "Default" cls=EulerAncestralDiscreteScheduler config={'num_train_timesteps': 1000,
                         'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'trained_betas':
                         None, 'prediction_type': 'epsilon', 'timestep_spacing': 'trailing', 'steps_offset': 1,
                         'rescale_betas_zero_snr': False, 'clip_sample': False, 'interpolation_type': 'linear',
                         'sample_max_value': 1.0, 'set_alpha_to_one': False, 'skip_prk_steps': True}
20:48:30-689639 INFO     Processing modifiers: apply
20:48:30-799018 DEBUG    Tokenizer: words=49408
                         file="models\Diffusers\models--stabilityai--sdxl-turbo\snapshots\71153311d3dbb46851df1931d3ca6e
                         939de83304\tokenizer\vocab.json"
20:48:37-432170 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=1/1x1 set={'prompt_embeds':
                         torch.Size([1, 231, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]),
                         'negative_prompt_embeds': torch.Size([1, 231, 2048]), 'negative_pooled_prompt_embeds':
                         torch.Size([1, 1280]), 'guidance_scale': 1.5, 'generator': 'cpu:[1187174725]',
                         'num_inference_steps': 8, 'eta': 1.0, 'guidance_rescale': 0, 'denoising_end': None,
                         'output_type': 'latent', 'width': 768, 'height': 768, 'parser': 'native'}
Progress ?it/s                                               0% 0/8 00:00 ? Base20:49:06-678071 TRACE    Server: alive=True requests=419 memory=15.63/15.71 status='running' task='Inference'
                         timestamp='20260414204837' current='task(xv0dydj6ykcq9u1)' id='5f5124a7a54a4b4' job=0 jobs=1
                         total=11 step=0 steps=0 queued=0 uptime=890 elapsed=29.24 eta=None progress=0
20:49:50-418842 DEBUG    OpenVINO compile: device=AUTO backend=openvino_fx hints={} file="None"
Progress 107.57s/it ████▎                               12% 1/8 01:47 12:33 Base
20:50:25-466444 DEBUG    Decode: type="taesd" variant="TAESD 1.3 Mocha Croissant"
                         fn="models\TAESD\taesd_13_decoder_sdxl.pth" layers=3 load
Progress 19.70s/it ███████████████████████████████████ 100% 8/8 02:37 00:00 Base
20:51:15-125495 INFO     Processing modifiers: unapply
20:51:16-381532 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}
20:51:38-168124 DEBUG    OpenVINO compile: device=AUTO backend=openvino_fx hints={} file="None"
20:51:57-507895 DEBUG    Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 96, 96]:cpu
                         dtype=torch.float32 time=41.127
20:51:57-652868 INFO     Save: image="outputs\text\00176-2026-04-14-sdxl-turbo.jpg" type=JPEG width=768 height=768
                         size=130181
20:51:57-666368 INFO     Processed: images=1 its=0.04 ops=['txt2img']
20:51:57-669868 DEBUG    Processed: timers={'total': 229.4, 'pipeline': 164.38, 'decode': 42.39, 'preview': 15.62,
                         'prompt': 6.57, 'pre': 0.16, 'post': 0.15}
20:51:57-672868 DEBUG    Processed: memory={'ram': {'total': 15.71, 'rss': 8.96, 'used': 12.95, 'free': 2.76, 'avail':
                         2.76, 'buffers': 0, 'cached': 0}, 'gpu': {'total': 0, 'used': 0, 'error': 'Torch not compiled
                         with CUDA enabled', 'swap': 0}, 'job': ''}
20:52:14-189903 DEBUG    Processing: batch=1 total=3 progress=0.33
20:52:14-254887 DEBUG    Sampler: "DPM++ 2M" class=DPMSolverMultistepScheduler config={'num_train_timesteps': 1000,
                         'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'solver_order': 2,
                         'prediction_type': 'epsilon', 'dynamic_thresholding_ratio': 0.995, 'sample_max_value': 1.0,
                         'algorithm_type': 'dpmsolver++', 'solver_type': 'midpoint', 'lower_order_final': True,
                         'flow_shift': 1.0, 'final_sigmas_type': 'zero', 'lambda_min_clipped': -inf, 'timestep_spacing':
                         'linspace', 'steps_offset': 0, 'time_shift_type': 'exponential'}
20:52:14-262390 INFO     Processing modifiers: apply
20:52:14-309400 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=1/3x1 set={'prompt_embeds':
                         torch.Size([1, 231, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]),
                         'negative_prompt_embeds': torch.Size([1, 231, 2048]), 'negative_pooled_prompt_embeds':
                         torch.Size([1, 1280]), 'guidance_scale': 1.5, 'generator': 'cpu:[2197390677]',
                         'num_inference_steps': 8, 'eta': 1.0, 'guidance_rescale': 0, 'denoising_end': None,
                         'output_type': 'latent', 'width': 768, 'height': 768, 'parser': 'native'}
Progress ?it/s                                               0% 0/8 00:00 ? Base20:53:06-808822 TRACE    Server: alive=True requests=866 memory=15.5/15.71 status='running' task='Inference'
                         timestamp='20260414205214' current='task(1edkm2ejbm4sel6)' id='91139d1034f745b' job=0 jobs=1
                         total=20 step=0 steps=0 queued=0 uptime=1130 elapsed=52.49 eta=None progress=0
20:53:26-778957 DEBUG    OpenVINO compile: device=AUTO backend=openvino_fx hints={} file="None"
Progress 19.87s/it ███████████████████████████████████ 100% 8/8 02:38 00:00 Base
20:54:53-462958 INFO     Processing modifiers: unapply
20:54:54-797973 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}
20:54:58-066171 DEBUG    Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 96, 96]:cpu
                         dtype=torch.float32 time=3.270
20:54:58-162672 ERROR    Decode: sample=(768, 768, 3) invalid=1769472 dtype=float32 vae=torch.float32 upcast=True failed
                         to validate
20:54:58-236180 INFO     Save: image="outputs\text\00177-2026-04-14-sdxl-turbo.jpg" type=JPEG width=768 height=768
                         size=6000
20:54:58-242682 DEBUG    Processing: batch=2 total=3 progress=0.67
20:54:58-305200 DEBUG    Sampler: "DPM++ 2M" class=DPMSolverMultistepScheduler config={'num_train_timesteps': 1000,
                         'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'solver_order': 2,
                         'prediction_type': 'epsilon', 'dynamic_thresholding_ratio': 0.995, 'sample_max_value': 1.0,
                         'algorithm_type': 'dpmsolver++', 'solver_type': 'midpoint', 'lower_order_final': True,
                         'flow_shift': 1.0, 'final_sigmas_type': 'zero', 'lambda_min_clipped': -inf, 'timestep_spacing':
                         'linspace', 'steps_offset': 0, 'time_shift_type': 'exponential'}
20:54:58-314198 INFO     Processing modifiers: apply
20:54:58-377611 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=2/3x1 set={'prompt_embeds':
                         torch.Size([1, 231, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]),
                         'negative_prompt_embeds': torch.Size([1, 231, 2048]), 'negative_pooled_prompt_embeds':
                         torch.Size([1, 1280]), 'guidance_scale': 1.5, 'generator': 'cpu:[2197390678]',
                         'num_inference_steps': 8, 'eta': 1.0, 'guidance_rescale': 0, 'denoising_end': None,
                         'output_type': 'latent', 'width': 768, 'height': 768, 'parser': 'native'}
Progress  5.11s/it ███████████████████████████████████ 100% 8/8 00:40 00:00 Base
20:55:39-411384 INFO     Processing modifiers: unapply
20:55:40-651915 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}
20:55:43-224153 DEBUG    Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 96, 96]:cpu
                         dtype=torch.float32 time=2.572
20:55:43-247285 ERROR    Decode: sample=(768, 768, 3) invalid=1769472 dtype=float32 vae=torch.float32 upcast=True failed
                         to validate
20:55:43-278785 INFO     Save: image="outputs\text\00178-2026-04-14-sdxl-turbo.jpg" type=JPEG width=768 height=768
                         size=6000
20:55:43-282292 DEBUG    Processing: batch=3 total=3 progress=1.00
20:55:43-286288 DEBUG    Sampler: "DPM++ 2M" class=DPMSolverMultistepScheduler config={'num_train_timesteps': 1000,
                         'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'solver_order': 2,
                         'prediction_type': 'epsilon', 'dynamic_thresholding_ratio': 0.995, 'sample_max_value': 1.0,
                         'algorithm_type': 'dpmsolver++', 'solver_type': 'midpoint', 'lower_order_final': True,
                         'flow_shift': 1.0, 'final_sigmas_type': 'zero', 'lambda_min_clipped': -inf, 'timestep_spacing':
                         'linspace', 'steps_offset': 0, 'time_shift_type': 'exponential'}
20:55:43-289285 INFO     Processing modifiers: apply
20:55:43-301286 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=3/3x1 set={'prompt_embeds':
                         torch.Size([1, 231, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]),
                         'negative_prompt_embeds': torch.Size([1, 231, 2048]), 'negative_pooled_prompt_embeds':
                         torch.Size([1, 1280]), 'guidance_scale': 1.5, 'generator': 'cpu:[2197390679]',
                         'num_inference_steps': 8, 'eta': 1.0, 'guidance_rescale': 0, 'denoising_end': None,
                         'output_type': 'latent', 'width': 768, 'height': 768, 'parser': 'native'}
Progress  5.12s/it ███████████████████████████████████ 100% 8/8 00:40 00:00 Base
20:56:24-270252 INFO     Processing modifiers: unapply
20:56:25-549292 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}
20:56:28-165500 DEBUG    Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 96, 96]:cpu
                         dtype=torch.float32 time=2.616
20:56:28-192515 ERROR    Decode: sample=(768, 768, 3) invalid=1769472 dtype=float32 vae=torch.float32 upcast=True failed
                         to validate
20:56:28-221523 INFO     Save: image="outputs\text\00179-2026-04-14-sdxl-turbo.jpg" type=JPEG width=768 height=768
                         size=6000
20:56:28-252522 INFO     Save: grid="outputs\grids\00180-2026-04-14-sdxl-turbo.jpg" type=JPEG width=2304 height=768
                         size=12910
20:56:28-259021 INFO     Processed: images=4 its=0.13 ops=['txt2img']
20:56:28-262520 DEBUG    Processed: timers={'total': 298.56, 'pipeline': 241.23, 'preview': 44.34, 'decode': 12.22,
                         'post': 0.42, 'prepare': 0.14, 'validate': 0.12}
20:56:28-267021 DEBUG    Processed: memory={'ram': {'total': 15.71, 'rss': 10.47, 'used': 14.88, 'free': 0.82, 'avail':
                         0.82, 'buffers': 0, 'cached': 0}, 'gpu': {'total': 0, 'used': 0, 'error': 'Torch not compiled
                         with CUDA enabled', 'swap': 0}, 'job': ''}
20:57:07-428980 TRACE    Server: alive=True requests=1224 memory=14.84/15.71 status='idle' task='' timestamp=None
                         current='' id='' job=0 jobs=0 total=35 step=0 steps=0 queued=0 uptime=1371 elapsed=39.14
                         eta=None progress=0
20:57:22-441998 DEBUG    Processing: batch=1 total=3 progress=0.33
20:57:22-476000 DEBUG    Sampler: "Default" cls=EulerAncestralDiscreteScheduler config={'num_train_timesteps': 1000,
                         'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'trained_betas':
                         None, 'prediction_type': 'epsilon', 'timestep_spacing': 'trailing', 'steps_offset': 1,
                         'rescale_betas_zero_snr': False, 'clip_sample': False, 'interpolation_type': 'linear',
                         'sample_max_value': 1.0, 'set_alpha_to_one': False, 'skip_prk_steps': True}
20:57:22-479999 INFO     Processing modifiers: apply
20:57:22-496998 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=1/3x1 set={'prompt_embeds':
                         torch.Size([1, 231, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]),
                         'negative_prompt_embeds': torch.Size([1, 231, 2048]), 'negative_pooled_prompt_embeds':
                         torch.Size([1, 1280]), 'guidance_scale': 1.5, 'generator': 'cpu:[653020349]',
                         'num_inference_steps': 8, 'eta': 1.0, 'guidance_rescale': 0, 'denoising_end': None,
                         'output_type': 'latent', 'width': 768, 'height': 768, 'parser': 'native'}
Progress  5.73s/it ███████████████████████████████████ 100% 8/8 00:45 00:00 Base
20:58:08-352395 INFO     Processing modifiers: unapply
20:58:09-567504 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}
20:58:12-161081 DEBUG    Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 96, 96]:cpu
                         dtype=torch.float32 time=2.594
20:58:12-187003 ERROR    Decode: sample=(768, 768, 3) invalid=1769472 dtype=float32 vae=torch.float32 upcast=True failed
                         to validate
20:58:12-211503 INFO     Save: image="outputs\text\00181-2026-04-14-sdxl-turbo.jpg" type=JPEG width=768 height=768
                         size=5968
20:58:12-215003 DEBUG    Processing: batch=2 total=3 progress=0.67
20:58:12-219004 DEBUG    Sampler: "Default" cls=EulerAncestralDiscreteScheduler config={'num_train_timesteps': 1000,
                         'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'trained_betas':
                         None, 'prediction_type': 'epsilon', 'timestep_spacing': 'trailing', 'steps_offset': 1,
                         'rescale_betas_zero_snr': False, 'clip_sample': False, 'interpolation_type': 'linear',
                         'sample_max_value': 1.0, 'set_alpha_to_one': False, 'skip_prk_steps': True}
20:58:12-222004 INFO     Processing modifiers: apply
20:58:12-237504 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=2/3x1 set={'prompt_embeds':
                         torch.Size([1, 231, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]),
                         'negative_prompt_embeds': torch.Size([1, 231, 2048]), 'negative_pooled_prompt_embeds':
                         torch.Size([1, 1280]), 'guidance_scale': 1.5, 'generator': 'cpu:[653020350]',
                         'num_inference_steps': 8, 'eta': 1.0, 'guidance_rescale': 0, 'denoising_end': None,
                         'output_type': 'latent', 'width': 768, 'height': 768, 'parser': 'native'}
Progress  5.15s/it ███████████████████████████████████ 100% 8/8 00:41 00:00 Base
20:58:53-487312 INFO     Processing modifiers: unapply
20:58:54-707850 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}
20:58:57-382845 DEBUG    Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 96, 96]:cpu
                         dtype=torch.float32 time=2.675
20:58:57-414933 ERROR    Decode: sample=(768, 768, 3) invalid=1769472 dtype=float32 vae=torch.float32 upcast=True failed
                         to validate
20:58:57-450433 INFO     Save: image="outputs\text\00182-2026-04-14-sdxl-turbo.jpg" type=JPEG width=768 height=768
                         size=5968
20:58:57-452936 DEBUG    Processing: batch=3 total=3 progress=1.00
20:58:57-456933 DEBUG    Sampler: "Default" cls=EulerAncestralDiscreteScheduler config={'num_train_timesteps': 1000,
                         'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'trained_betas':
                         None, 'prediction_type': 'epsilon', 'timestep_spacing': 'trailing', 'steps_offset': 1,
                         'rescale_betas_zero_snr': False, 'clip_sample': False, 'interpolation_type': 'linear',
                         'sample_max_value': 1.0, 'set_alpha_to_one': False, 'skip_prk_steps': True}
20:58:57-460934 INFO     Processing modifiers: apply
20:58:57-477436 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=3/3x1 set={'prompt_embeds':
                         torch.Size([1, 231, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]),
                         'negative_prompt_embeds': torch.Size([1, 231, 2048]), 'negative_pooled_prompt_embeds':
                         torch.Size([1, 1280]), 'guidance_scale': 1.5, 'generator': 'cpu:[653020351]',
                         'num_inference_steps': 8, 'eta': 1.0, 'guidance_rescale': 0, 'denoising_end': None,
                         'output_type': 'latent', 'width': 768, 'height': 768, 'parser': 'native'}
Progress  5.15s/it ███████████████████████████████████ 100% 8/8 00:41 00:00 Base
20:59:38-662566 INFO     Processing modifiers: unapply
20:59:39-917591 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}
20:59:42-523163 DEBUG    Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 96, 96]:cpu
                         dtype=torch.float32 time=2.606
20:59:42-550915 ERROR    Decode: sample=(768, 768, 3) invalid=1769472 dtype=float32 vae=torch.float32 upcast=True failed
                         to validate
20:59:42-578926 INFO     Save: image="outputs\text\00183-2026-04-14-sdxl-turbo.jpg" type=JPEG width=768 height=768
                         size=5968
20:59:42-608926 INFO     Save: grid="outputs\grids\00184-2026-04-14-sdxl-turbo.jpg" type=JPEG width=2304 height=768
                         size=12878
20:59:42-613426 INFO     Processed: images=4 its=0.23 ops=['txt2img']
20:59:42-616425 DEBUG    Processed: timers={'total': 182.77, 'pipeline': 128.31, 'preview': 42.5, 'decode': 11.54,
                         'post': 0.23}
20:59:42-619925 DEBUG    Processed: memory={'ram': {'total': 15.71, 'rss': 10.34, 'used': 14.92, 'free': 0.79, 'avail':
                         0.79, 'buffers': 0, 'cached': 0}, 'gpu': {'total': 0, 'used': 0, 'error': 'Torch not compiled
                         with CUDA enabled', 'swap': 0}, 'job': ''}
20:59:57-429024 INFO     Settings: changed=1 ['openvino_accuracy']
20:59:57-438025 DEBUG    Save: file="F:\sdnext\config.json" json=16 bytes=698 time=0.009
20:59:57-467007 DEBUG    Save: file="F:\sdnext\secrets.json" json=2 bytes=139 time=0.005
21:00:01-481709 DEBUG    Processing: batch=1 total=3 progress=0.33
21:00:01-485209 DEBUG    Sampler: "Default" cls=EulerAncestralDiscreteScheduler config={'num_train_timesteps': 1000,
                         'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'trained_betas':
                         None, 'prediction_type': 'epsilon', 'timestep_spacing': 'trailing', 'steps_offset': 1,
                         'rescale_betas_zero_snr': False, 'clip_sample': False, 'interpolation_type': 'linear',
                         'sample_max_value': 1.0, 'set_alpha_to_one': False, 'skip_prk_steps': True}
21:00:01-487709 INFO     Processing modifiers: apply
21:00:01-504208 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=1/3x1 set={'prompt_embeds':
                         torch.Size([1, 231, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]),
                         'negative_prompt_embeds': torch.Size([1, 231, 2048]), 'negative_pooled_prompt_embeds':
                         torch.Size([1, 1280]), 'guidance_scale': 1.5, 'generator': 'cpu:[874770478]',
                         'num_inference_steps': 8, 'eta': 1.0, 'guidance_rescale': 0, 'denoising_end': None,
                         'output_type': 'latent', 'width': 768, 'height': 768, 'parser': 'native'}
Progress  5.15s/it ███████████████████████████████████ 100% 8/8 00:41 00:00 Base
21:00:42-737987 INFO     Processing modifiers: unapply
21:00:43-971550 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}
21:00:46-623651 DEBUG    Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 96, 96]:cpu
                         dtype=torch.float32 time=2.652
21:00:46-653748 ERROR    Decode: sample=(768, 768, 3) invalid=1769472 dtype=float32 vae=torch.float32 upcast=True failed
                         to validate
21:00:46-679750 INFO     Save: image="outputs\text\00185-2026-04-14-sdxl-turbo.jpg" type=JPEG width=768 height=768
                         size=5968
21:00:46-684249 DEBUG    Processing: batch=2 total=3 progress=0.67
21:00:46-689249 DEBUG    Sampler: "Default" cls=EulerAncestralDiscreteScheduler config={'num_train_timesteps': 1000,
                         'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'trained_betas':
                         None, 'prediction_type': 'epsilon', 'timestep_spacing': 'trailing', 'steps_offset': 1,
                         'rescale_betas_zero_snr': False, 'clip_sample': False, 'interpolation_type': 'linear',
                         'sample_max_value': 1.0, 'set_alpha_to_one': False, 'skip_prk_steps': True}
21:00:46-693249 INFO     Processing modifiers: apply
21:00:46-705749 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=2/3x1 set={'prompt_embeds':
                         torch.Size([1, 231, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]),
                         'negative_prompt_embeds': torch.Size([1, 231, 2048]), 'negative_pooled_prompt_embeds':
                         torch.Size([1, 1280]), 'guidance_scale': 1.5, 'generator': 'cpu:[874770479]',
                         'num_inference_steps': 8, 'eta': 1.0, 'guidance_rescale': 0, 'denoising_end': None,
                         'output_type': 'latent', 'width': 768, 'height': 768, 'parser': 'native'}
Progress  5.05s/it ███████████████████████████████████ 100% 8/8 00:40 00:00 Base
21:01:27-089739 INFO     Processing modifiers: unapply
21:01:28-351805 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}
21:01:31-052588 DEBUG    Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 96, 96]:cpu
                         dtype=torch.float32 time=2.701
21:01:31-084825 ERROR    Decode: sample=(768, 768, 3) invalid=1769472 dtype=float32 vae=torch.float32 upcast=True failed
                         to validate
21:01:31-109329 INFO     Save: image="outputs\text\00186-2026-04-14-sdxl-turbo.jpg" type=JPEG width=768 height=768
                         size=5968
21:01:31-113830 DEBUG    Processing: batch=3 total=3 progress=1.00
21:01:31-117326 DEBUG    Sampler: "Default" cls=EulerAncestralDiscreteScheduler config={'num_train_timesteps': 1000,
                         'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'trained_betas':
                         None, 'prediction_type': 'epsilon', 'timestep_spacing': 'trailing', 'steps_offset': 1,
                         'rescale_betas_zero_snr': False, 'clip_sample': False, 'interpolation_type': 'linear',
                         'sample_max_value': 1.0, 'set_alpha_to_one': False, 'skip_prk_steps': True}
21:01:31-120325 INFO     Processing modifiers: apply
21:01:31-138328 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=3/3x1 set={'prompt_embeds':
                         torch.Size([1, 231, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]),
                         'negative_prompt_embeds': torch.Size([1, 231, 2048]), 'negative_pooled_prompt_embeds':
                         torch.Size([1, 1280]), 'guidance_scale': 1.5, 'generator': 'cpu:[874770480]',
                         'num_inference_steps': 8, 'eta': 1.0, 'guidance_rescale': 0, 'denoising_end': None,
                         'output_type': 'latent', 'width': 768, 'height': 768, 'parser': 'native'}
Progress  4.89s/it ███████████████████████████████████ 100% 8/8 00:39 00:00 Base
21:02:10-315913 INFO     Processing modifiers: unapply
21:02:11-542922 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}
21:02:14-175659 DEBUG    Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 96, 96]:cpu
                         dtype=torch.float32 time=2.633
21:02:14-202645 ERROR    Decode: sample=(768, 768, 3) invalid=1769472 dtype=float32 vae=torch.float32 upcast=True failed
                         to validate
21:02:14-229646 INFO     Save: image="outputs\text\00187-2026-04-14-sdxl-turbo.jpg" type=JPEG width=768 height=768
                         size=5968
21:02:14-248147 INFO     Save: grid="outputs\grids\00188-2026-04-14-sdxl-turbo.jpg" type=JPEG width=2304 height=768
                         size=12878
21:02:14-251647 INFO     Processed: images=4 its=0.24 ops=['txt2img']
21:02:14-252647 DEBUG    Processed: timers={'total': 153.28, 'pipeline': 120.81, 'preview': 20.42, 'decode': 11.69,
                         'post': 0.22}
21:02:14-257153 DEBUG    Processed: memory={'ram': {'total': 15.71, 'rss': 10.25, 'used': 15.24, 'free': 0.47, 'avail':
                         0.47, 'buffers': 0, 'cached': 0}, 'gpu': {'total': 0, 'used': 0, 'error': 'Torch not compiled
                         with CUDA enabled', 'swap': 0}, 'job': ''}
21:03:07-716251 TRACE    Server: alive=True requests=1659 memory=15.23/15.71 status='idle' task='' timestamp=None
                         current='' id='' job=0 jobs=0 total=80 step=0 steps=0 queued=0 uptime=1731 elapsed=53.45
                         eta=None progress=0
21:05:07-817862 TRACE    Server: alive=True requests=1680 memory=15.29/15.71 status='idle' task='' timestamp=None
                         current='' id='' job=0 jobs=0 total=80 step=0 steps=0 queued=0 uptime=1851 elapsed=173.55
                         eta=None progress=0
21:07:07-945167 TRACE    Server: alive=True requests=1694 memory=15.0/15.71 status='idle' task='' timestamp=None
                         current='' id='' job=0 jobs=0 total=80 step=0 steps=0 queued=0 uptime=1971 elapsed=293.68
                         eta=None progress=0
21:09:08-051558 TRACE    Server: alive=True requests=1696 memory=14.99/15.71 status='idle' task='' timestamp=None
                         current='' id='' job=0 jobs=0 total=80 step=0 steps=0 queued=0 uptime=2092 elapsed=413.79
                         eta=None progress=0
21:11:08-126185 TRACE    Server: alive=True requests=1710 memory=15.01/15.71 status='idle' task='' timestamp=None
                         current='' id='' job=0 jobs=0 total=80 step=0 steps=0 queued=0 uptime=2212 elapsed=533.86
                         eta=None progress=0
```

### Operating system

Windows

### Compute

OpenVINO

### Interface

Standard

### Branch

Dev

### Model

StableDiffusion 1.5/2.1/XL

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by Disty0** [comment]
Does it even work without SDNQ? Because SDXL VAE doesn't support FP16 either. Use the FP16 Fixed VAE for SDXL or disable OpenVINO on the VAE.

**Comment by ak-sangal** [comment]
<img width="1690" height="1589" alt="Image" src="https://github.com/user-attachments/assets/f3f1461c-4484-4999-b7e7-92aa68b5f5f7" />

i attached screenshot tell me which setting i choose

**Comment by ak-sangal** [comment]
choosing F32  will create extra load on iGPU

**Comment by Disty0** [comment]
Disable SDNQ and try with just OpenVINO. Issue here is SDXL VAE dosn't support FP16, it has nothing to do with SDNQ. You have to manually use the FP16 Fixed VAE for SDXL if the model you are using has the normal SDXL VAE instead of the FP16 Fixed one. Or disable OpenVINO for the VAE so it will run at FP32.

**Comment by ak-sangal** [comment]
Without sdnq quantization sdxl model can't run in my laptop only sd 1.5 run

**Comment by Disty0** [comment]
I said to disable SDNQ to remove that variable from the issue. Anyhow, you have to use the FP16 Fixed VAE for SDXL if the SDXL model you are using uses the original / default SDXL VAE that doesn't work with FP16 and you have an old GPU that doesn't support BF16 or using OpenVINO  (also doesn't support BF16). Original SDXL VAE only works with BF16 or FP32 and produces black output image with FP16.

Use this VAE for SDXL if you want to keep using FP16 instead of FP32: https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/blob/main/sdxl_vae.safetensors

**Comment by ak-sangal** [comment]
Ok i try

**Comment by vladmandic** [comment]
any updates?

**Comment by ak-sangal** [comment]
I will try today

**Comment by vladmandic** [comment]
closing the issue for the moment as no feedback received in 1month. 
but i would like to know if issue is resolved or not - if feedback is provided and issue persists, i'll reopen.

**Comment by ak-sangal** [comment]
Ok
