### ISSUE TITLE
[Issue]: ROCm is incorrectly installed on Windows

### ISSUE THREAD

**Issue by MegaDanX12** [vladmandic/automatic#4774]
### Issue Description

The app starts fine but when attempting to generate an image (with any model), the following appears on the console:

rocBLAS error: Cannot read H:\AI\sdnext_new\venv\Lib\site-packages\_rocm_sdk_devel\bin\rocblas\library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1201

Immediately after SD.Next crashes.

I looked in that path and I found a devel.tar archive which seemed to contain the required files, I unpacked it but the error remains.

Another look in that path made me discover that the required file (TensileLibrary.dat) does not exist even after unpacking.

### Version Platform Description

10:24:17-608060 INFO     Starting SD.Next
10:24:17-609563 INFO     Logger: file="H:\AI\sdnext_new\sdnext.log" level=DEBUG host="MEGADANX-PC" size=79 mode=append
10:24:17-610567 INFO     Python: version=3.12.10 platform=Windows bin="H:\AI\sdnext_new\venv\Scripts\Python.exe"
                         venv="H:\AI\sdnext_new\venv"
10:24:17-646250 INFO     Platform: arch=AMD64 cpu=AMD64 Family 26 Model 68 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-11-10.0.26200-SP0 python=3.12.10 locale=('Italian_Italy', '932')
                         setuptools=69.5.1 docker=False
10:24:17-902815 INFO     Version: app=sd.next updated=2026-04-04 commit=0eb4a98e0 branch=master
                         url=https://github.com/vladmandic/sdnext/tree/master kanvas=main ui=main
10:24:18-401190 TRACE    Repository branches: active=master available=['dev', 'feat/ltx-tab-unification',
                         'fix/sdnq-lora-swap', 'master']
10:24:18-604090 INFO     Version: app=sd.next latest=2026-04-04T09:10:28Z hash=0eb4a98e branch=master
10:24:18-605091 DEBUG    Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
10:24:18-606089 INFO     Args: ['--debug', '--use-rocm']
10:24:18-607090 DEBUG    Setting environment tuning
10:24:18-607090 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
10:24:18-609596 INFO     Torch: verifying installation
10:24:18-609596 DEBUG    Torch overrides: cuda=False rocm=True ipex=False directml=False openvino=False zluda=False
10:24:18-726152 INFO     ROCm: agents=['gfx1201']
10:24:18-728148 INFO     ROCm: version=7.2, using agent gfx1201
10:24:18-729151 INFO     Python: version=3.12.10 platform=Windows bin="H:\AI\sdnext_new\venv\Scripts\Python.exe"
                         venv="H:\AI\sdnext_new\venv"
10:24:46-626496 INFO     Torch backend: {'version': '2.10.0+rocm7.13.0a20260403', 'type': 'rocm', 'hip': '7.2.0'}
10:24:46-644244 INFO     Torch detected: {'gpu': 'AMD Radeon RX 9070', 'vram': 16304, 'arch': '12.0 Unknown', 'cores':
                         28}
10:24:46-804534 WARNING  Modified files: ['mimalloc-redirect.dll', 'mimalloc.dll']

### Relevant log output

```shell
rocBLAS error: Cannot read H:\AI\sdnext_new\venv\Lib\site-packages\_rocm_sdk_devel\bin\rocblas\library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1201
 List of available TensileLibrary Files :

rocBLAS error: Could not initialize Tensile host:
directory_iterator::directory_iterator: The system cannot find the path specified.: "H:\AI\sdnext_new\venv\Lib\site-packages\_rocm_sdk_devel\bin\rocblas\library"
```

### Operating system

Windows

### Compute

AMD ROCm

### Interface

ModernUI

### Branch

Master

### Model

StableDiffusion 1.5/2.1/XL

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
cc @resonantsky

**Comment by resonantsky** [comment]
> ### Issue Description
> The app starts fine but when attempting to generate an image (with any model), the following appears on the console:
> 
> rocBLAS error: Cannot read H:\AI\sdnext_new\venv\Lib\site-packages_rocm_sdk_devel\bin\rocblas\library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1201
> 
> Immediately after SD.Next crashes.
> 
> I looked in that path and I found a devel.tar archive which seemed to contain the required files, I unpacked it but the error remains.
> 
> Another look in that path made me discover that the required file (TensileLibrary.dat) does not exist even after unpacking.

If you have chosen to unpack _devel.tar there a few things to realize, this tar file has been locked so when you extract it should be done with administrator privileges, if you used 7z, winrar or whatever, need to run these as admin to properly unpack _devel.tar

If you have can confirm that _devel.tar has been extracted by admin and the paths to folders `H:\AI\sdnext_new\venv\Lib\site-packages\_rocm_sdk_devel\bin\rocblas\library` & `H:\AI\sdnext_new\venv\Lib\site-packages\_rocm_sdk_devel\bin\` then you should have no issues... either the extraction went badly or the path has an error there with `site-packages_rocm_sdk_devel` which should be `site-packages\_rocm_sdk_devel`

If you have correctly unpacked the file then there will be many files in `\rocblas\library` 

However, you should note that those files should already be present in a `_rocm_sdk_libraries[gfx card]` - another folder next to `_rocm_sdk_devel` in venv... 

check under "Extras" for the ROCm: Advanced configuration script and see which paths you have noted there...

**Comment by MegaDanX12** [comment]
I fully reinstalled SD.Next and now the problem is gone.

There was no problem with generation.

Most probably I incorrectly extracted the .tar file.

**Comment by resonantsky** [comment]
> I fully reinstalled SD.Next and now the problem is gone.
> 
> There was no problem with generation.
> 
> Most probably I incorrectly extracted the .tar file.

Good, I was going to suggest that a full install would solve this issue, yeah the .tar file was locked by AMD for some time, but they have corrected that lock and now it is extracting as expected, in latest rocm versions...
