### ISSUE TITLE
[Issue]: ROCm RuntimeError: miopenStatusInternalError on RX 7800 XT

### ISSUE THREAD

**Issue by yaizawa2e** [vladmandic/automatic#4803]
## Environment setup:
I am using the official Dockerfile for ROCm and have already set the following environment variables to ensure compatibility with my RX 7800 XT (gfx1101):
- `HSA_OVERRIDE_GFX_VERSION=11.0.0`
- `MIOPEN_DEBUG_DISABLE_CUDNN_OPPORTUNISTIC_CONVS=1`

## The Problem:
Despite these settings, the debug logs show that MIOpen is still attempting to load a metadata model for a different architecture:
```
Unable to load file: /mnt/python/venv\Lib\site-packages\_rocm_sdk_devel\bin\/gfx908_metadata.tn.model
```
It seems the system is ignoring the override or the heuristics engine is hardcoded to seek **gfx908 (Instinct MI100)** metadata in this specific container environment.

### Version Platform Description

- **OS:** Ubuntu Linux 24.04.4 LTS
- **Docker Version:** 29.4.1
- **GPU:**
   - **eGPU:** AMD Radeon RX 7800 XT (gfx1101)
   - **iGPU:** AMD Radeon Vega 8 (gfx902)
- **Backend:** ROCm (PyTorch with ROCm support)
- **Model:** Stable Diffusion v1-5 (FP16)
- **SD.next Version:** 2026-04-04 (0eb4a98e0)
- **Browser**: Microsoft Edge 147.0.3912.72

### Relevant log output

```shell
Cloning into '.'...
Create python venv
Activate python venv: /mnt/python/venv
Launch: /mnt/python/venv/bin/python3
15:50:15-717102 INFO     Starting SD.Next
15:50:15-720888 INFO     Logger: file="/app/sdnext.log" level=DEBUG
                         host="d9c158d86137" size=79 mode=append
15:50:15-722553 INFO     Python: version=3.12.3 platform=Linux
                         bin="/mnt/python/venv/bin/python3"
                         venv="/mnt/python/venv"
15:50:15-728238 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux
                         release=6.8.0-110-generic python=3.12.3 locale=('C',
                         'UTF-8') setuptools=69.5.1 docker=True
15:50:15-793328 INFO     Version: app=sd.next updated=2026-04-04
                         commit=0eb4a98e0 branch=master
                         url=https://github.com/vladmandic/sdnext/tree/master
                         kanvas=main ui=main
15:50:16-565079 TRACE    Repository branches: active=master available=['dev',
                         'feat/rife-upgrade', 'fix/sdnq-svd-dynamic-loop',
                         'master']
15:50:16-905261 INFO     Version: app=sd.next latest=2026-04-04T09:10:28Z
                         hash=0eb4a98e branch=master
15:50:16-907068 DEBUG    Packages: prefix=../mnt/python/venv
                         site=['../mnt/python/venv/lib/python3.12/site-packages'
                         ]
15:50:16-908573 INFO     Args: ['-f', '--use-rocm', '--uv', '--listen',
                         '--debug', '--api-log', '--log', 'sdnext.log']
15:50:16-910340 DEBUG    Setting environment tuning
15:50:16-911553 DEBUG    Torch allocator:
                         "garbage_collection_threshold:0.80,max_split_size_mb:51
                         2"
15:50:16-913119 DEBUG    Install: package="uv" install required
15:50:19-986092 DEBUG    Install: package="gradio" install required
15:50:29-536705 INFO     Torch: verifying installation
15:50:29-538149 DEBUG    Torch overrides: cuda=False rocm=True ipex=False
                         directml=False openvino=False zluda=False
15:50:29-665517 INFO     ROCm: agents=['gfx1100', 'gfx1100']
15:50:29-668293 INFO     ROCm: version=6.3, using agent gfx1100
15:50:29-670715 INFO     ROCm: HSA_OVERRIDE_GFX_VERSION auto config skipped:
                         device=gfx1100 version=11.0.0
15:50:29-675330 DEBUG    Install: package="torch" install required
15:50:29-679713 INFO     Install: package="torch" cmd="torch==2.9.1+rocm6.3
                         torchvision==0.24.1+rocm6.3 --index-url
                         https://download.pytorch.org/whl/rocm6.3" download and
                         install in progress...
15:50:29-690757 DEBUG    Install: package="torch" install required
15:50:29-694988 DEBUG    Install: package="torchvision" install required
15:52:49-041118 INFO     Torch backend: {'version': '2.9.1+rocm6.3', 'type':
                         'rocm', 'hip': '6.3.42134-a9a80e791'}
15:52:49-043635 INFO     Torch detected: {'gpu': 'AMD Radeon RX 7800 XT',
                         'vram': 16368, 'arch': '11.0 Unknown', 'cores': 30}
15:52:49-046854 DEBUG    Install: package="onnx" install required
15:52:53-863462 DEBUG    Install: package="onnxruntime" install required
15:52:54-874728 INFO     Install: package="transformers"
                         commit=2dba8e0495974930af02274d75bd182d22cc1686
15:53:54-949242 INFO     Install: package="diffusers"
                         commit=0325ca4c5938a7e300f3e3b9ee7ec85f52d01bb5
15:54:18-524253 INFO     Install: verifying requirements
15:54:18-532351 DEBUG    Install: package="wheel" install required
15:54:19-311343 DEBUG    Install: package="filetype" install required
15:54:19-647900 DEBUG    Install: package="future" install required
15:54:20-136025 DEBUG    Install: package="GitPython" install required
15:54:20-544340 DEBUG    Install: package="lark" install required
15:54:21-365419 DEBUG    Install: package="piexif" install required
15:54:21-798630 DEBUG    Install: package="toml" install required
15:54:22-161288 DEBUG    Install: package="voluptuous" install required
15:54:22-621820 DEBUG    Install: package="fasteners" install required
15:54:23-038044 DEBUG    Install: package="limits" install required
15:54:23-793560 DEBUG    Install: package="orjson" install required
15:54:24-243902 DEBUG    Install: package="ftfy" install required
15:54:24-629350 DEBUG    Install: package="peft" install required
15:54:25-500368 DEBUG    Install: package="einops" install required
15:54:25-899604 WARNING  Install: package="huggingface_hub" installed=1.12.0
                         required=1.8.0 version mismatch
15:54:27-128975 DEBUG    Install: package="pandas" install required
15:54:28-335160 WARNING  Install: package="protobuf" installed=7.34.1
                         required=6.33.5 version mismatch
15:54:28-797151 DEBUG    Install: package="pytorch_lightning" install required
15:54:29-992432 WARNING  Install: package="urllib3" installed=2.6.3
                         required=1.26.19 version mismatch
15:54:30-381670 DEBUG    Install: package="timm" install required
15:54:31-211848 DEBUG    Install: package="sentencepiece" install required
15:54:31-681421 DEBUG    Install: package="ruff" install required
15:54:32-403235 DEBUG    Install: package="pylint" install required
15:54:32-909159 DEBUG    Install: package="pre-commit" install required
15:54:33-801871 DEBUG    Install: package="compel" install required
15:54:44-205486 INFO     Startup: launch=full
15:54:44-206788 INFO     Verifying submodules
15:55:15-114756 DEBUG    Git detached head detected:
                         folder="extensions-builtin/sd-extension-chainner"
                         reattach=main
15:55:15-117891 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner
                         / main
15:55:15-178204 DEBUG    Git detached head detected:
                         folder="extensions-builtin/sd-extension-system-info"
                         reattach=main
15:55:15-181416 DEBUG    Git submodule:
                         extensions-builtin/sd-extension-system-info / main
15:55:15-238372 DEBUG    Git detached head detected:
                         folder="extensions-builtin/sdnext-kanvas" reattach=main
15:55:15-241317 DEBUG    Git submodule: extensions-builtin/sdnext-kanvas / main
15:55:15-338540 DEBUG    Git detached head detected:
                         folder="extensions-builtin/sdnext-modernui"
                         reattach=main
15:55:15-340567 DEBUG    Git submodule: extensions-builtin/sdnext-modernui /
                         main
15:55:15-414974 DEBUG    Git detached head detected: folder="wiki"
                         reattach=master
15:55:15-417928 DEBUG    Git submodule: wiki / master
15:55:15-633625 DEBUG    Installed packages: 137
15:55:15-635008 DEBUG    Extensions all: ['sdnext-kanvas',
                         'sd-extension-system-info', 'sd-extension-chainner',
                         'sdnext-modernui']
15:55:16-159032 DEBUG    Extensions all: []
15:55:16-160354 INFO     Extensions enabled: ['sdnext-kanvas',
                         'sd-extension-system-info', 'sd-extension-chainner',
                         'sdnext-modernui']
15:55:16-162926 INFO     Install: verifying requirements
15:55:16-208061 DEBUG    Setup complete without errors: 1777305316
15:55:16-229905 DEBUG    State: file="/app/data/installer.json"
15:55:16-236249 DEBUG    Extension preload: {'extensions-builtin': 0.0,
                         '/mnt/data/extensions': 0.0}
15:55:16-238119 INFO     Installer time: total=754.22 pip=253.92 install=170.50
                         torch=139.51 transformers=60.08 git=31.31
                         submodules=31.26 requirements=25.73 diffusers=23.51
                         base=9.96 onnx=5.82 latest=1.18 branch=0.38
                         installed=0.32 sdnext-kanvas=0.13
                         sd-extension-system-info=0.13 sdnext-modernui=0.13
                         sd-extension-chainner=0.13
15:55:16-241341 INFO     Command line args: ['-f', '--use-rocm', '--uv',
                         '--listen', '--debug', '--api-log', '--log',
                         'sdnext.log'] use_rocm=True listen=True log=sdnext.log
                         args=[] f=True uv=True
15:55:16-243330 DEBUG    Flags: sd=['SD_DOCKER=true', 'SD_DATADIR=/mnt/data',
                         'SD_MODELSDIR=/mnt/models']
                         ld=['LD_PRELOAD=libjemalloc.so.2',
                         'LD_LIBRARY_PATH=:/mnt/python/venv/lib/']
15:55:16-245054 DEBUG    Starting module: <module 'webui' from '/app/webui.py'>
15:55:16-254928 DEBUG    Initializing: libraries
15:55:21-867046 DEBUG    System: cores=8 affinity=8 threads=4
15:55:40-215961 INFO     Torch: torch==2.9.1+rocm6.3 torchvision==0.24.1+rocm6.3
15:55:40-223134 INFO     Packages: diffusers==0.38.0.dev0
                         transformers==5.5.0.dev0 accelerate==1.13.0
                         gradio==3.43.2 pydantic==2.12.5 numpy==2.1.2
                         cv2==4.12.0
15:55:40-270269 DEBUG    Initializing: shared module
15:55:40-647534 DEBUG    Initializing: pipelines
15:55:41-563246 DEBUG    State initialized: id=136058044332608
15:55:41-565478 DEBUG    ROCm: hipBLASLt unavailable agent=gfx1100
15:55:41-569260 DEBUG    Initializing: default modes
15:55:41-571053 INFO     Device detect: memory=16.0 default=balanced
15:55:41-573126 DEBUG    Initializing: settings
15:55:41-620191 INFO     Device detect: memory=16.0 default=balanced
15:55:41-633038 DEBUG    Read: file="/mnt/data/config.json" json=13 bytes=709
                         time=0.000 fn=__init__:load
15:55:41-635040 DEBUG    Read: file="/mnt/data/secrets.json" json=2 bytes=139
                         time=0.000 fn=__init__:load
15:55:41-637403 DEBUG    Initializing: backend
15:55:41-638519 INFO     Engine: backend=Backend.DIFFUSERS compute=rocm
                         device=cuda attention="Scaled-Dot-Product" mode=no_grad
15:55:41-649602 DEBUG    Read: file="data/reference.json" json=102 bytes=51268
                         time=0.000 fn=_call_with_frames_removed:<module>
15:55:41-651120 DEBUG    Initializing: devices
15:55:41-652185 DEBUG    Torch attention: type="sdpa" kernels=['Flash',
                         'Memory', 'Math'] overrides=[]
15:55:41-653778 DEBUG    Torch attention installed: flashattn=False
                         sageattention=False
15:55:41-654957 DEBUG    Torch attention status: flash=False flash3=False
                         aiter=False sage=False flex=True npu=False xla=False
                         xformers=False
15:55:50-019027 DEBUG    Triton: pass=True version=3.5.1
                         fn=<module>:set_cuda_params time=7.77
15:55:50-022169 INFO     Torch parameters: backend=rocm device=cuda config=Auto
                         dtype=torch.bfloat16 context=no_grad nohalf=False
                         nohalfvae=False upcast=False deterministic=False
                         tunable=[False, True] fp16=pass bf16=pass triton=pass
                         optimization="Scaled-Dot-Product"
15:55:50-026234 DEBUG    Quantization: registered=SDNQ
15:55:50-028377 INFO     Device: device=AMD Radeon RX 7800 XT n=1
                         hip=6.3.42134-a9a80e791
15:55:50-867625 INFO     API: limit=300 strategy=SlidingWindowCounterRateLimiter
                         backend=MemoryStorage
15:55:50-871352 DEBUG    Entering start sequence
15:55:50-873357 INFO     Base path: data="/mnt/data"
15:55:50-875383 INFO     Base path: models="/mnt/models"
15:55:50-878398 DEBUG    Initializing: modules
15:55:50-881214 DEBUG    Read: file="/mnt/data/data/metadata.json" json=2
                         bytes=147 time=0.000 fn=initialize:init_metadata
15:55:50-884322 DEBUG    Read: file="/mnt/data/data/cache.json" json=1 bytes=354
                         time=0.000 fn=initialize:init_cache
15:55:51-130284 INFO     Available VAEs: path="/mnt/models/VAE" items=0
15:55:51-133938 INFO     Available TEs: path="/mnt/models/Text-encoder" items=0
15:55:51-140578 INFO     Available UNets: path="/mnt/models/UNET" items=0
15:55:51-156223 INFO     Available Models:
                         safetensors="/mnt/models/Stable-diffusion":2
                         diffusers="/mnt/models/Diffusers":1 reference=102
                         items=3 time=0.02
15:55:51-159855 DEBUG    Model metadata: file="/mnt/data/data/metadata.json" no
                         changes
15:55:51-291518 INFO     Available LoRAs: path="/mnt/models/Lora" items=0
                         folders=2 time=0.00
15:55:53-205382 DEBUG    Read: file="data/upscalers.json" json=4 bytes=2640
                         time=0.000 fn=__init__:__init__
15:55:53-209563 DEBUG    Install: package="addict" install required
15:55:53-724332 DEBUG    Install: package="yapf" install required
15:55:59-085393 INFO     Available Upscalers: items=57 downloaded=0 user=0
                         time=7.95 types=['None', 'Resize', 'Latent',
                         'AsymmetricVAE', 'WanUpscale', 'DCC', 'VIPS', 'HQX',
                         'ICBI', 'Spandrel', 'RealESRGAN', 'AuraSR', 'ESRGAN',
                         'SCUNet', 'SwinIR', 'Diffusion', 'SeedVR']
15:55:59-105469 INFO     Available Styles: path="/mnt/models/styles" items=288
                         time=0.01
15:55:59-121229 INFO     Available Detailer: path="/mnt/models/yolo" items=10
                         downloaded=0
15:55:59-123139 DEBUG    Extensions: disabled=[]
15:55:59-124682 INFO     Load extensions
15:56:00-472595 DEBUG    Extensions init time: total=1.35
                         sd-extension-chainner=0.34 regional_prompting.py=0.29
15:56:00-528872 DEBUG    Install: package="hf_transfer" install required
15:56:01-142337 INFO     Huggingface: transfer=rust parallel=True direct=False
                         token="None" cache="/mnt/models/huggingface" init
15:56:01-151760 DEBUG    Huggingface: cache="/mnt/models/huggingface" size=1 MB
15:56:01-154995 DEBUG    Temp folder: path="/tmp/gradio"
15:56:01-158674 DEBUG    UI start sequence
15:56:01-162461 DEBUG    UI image support: kanvas=main
15:56:01-175564 INFO     UI locale: name="Auto"
15:56:01-181361 INFO     UI theme: type=Modern name="Default" available=39
15:56:01-185407 DEBUG    UI theme:
                         css="extensions-builtin/sdnext-modernui/themes/Default.
                         css" base="['base.css', 'timesheet.css']" user="None"
15:56:01-211261 DEBUG    UI initialize: tab=txt2img
15:56:01-379970 DEBUG    Read: file="data/reference.json" json=102 bytes=51268
                         time=0.005 fn=list_items:list_reference
15:56:01-387566 DEBUG    Read: file="data/reference-quant.json" json=24
                         bytes=9140 time=0.000 fn=list_items:list_reference
15:56:01-395797 DEBUG    Read: file="data/reference-distilled.json" json=22
                         bytes=10885 time=0.000 fn=list_items:list_reference
15:56:01-399960 DEBUG    Read: file="data/reference-community.json" json=21
                         bytes=8581 time=0.000 fn=list_items:list_reference
15:56:01-404123 DEBUG    Read: file="data/reference-cloud.json" json=3
                         bytes=1079 time=0.000 fn=list_items:list_reference
15:56:01-408531 DEBUG    Read: file="data/reference-nunchaku.json" json=18
                         bytes=7372 time=0.000 fn=list_items:list_reference
15:56:01-431354 DEBUG    Networks: type="reference" {'total': 190, 'ready': 2,
                         'hidden': 18, 'experimental': 0, 'base': 102,
                         'quantized': 24, 'community': 21, 'distilled': 20,
                         'cloud': 3}
15:56:01-449635 DEBUG    Networks: type="model" items=173 subfolders=9
                         tab=txt2img folders=['/mnt/models/Stable-diffusion',
                         'models/Reference', '/mnt/models/Stable-diffusion']
                         list=0.10 thumb=0.01 desc=0.00 info=0.00 workers=12
15:56:01-457350 DEBUG    Networks: type="lora" items=0 subfolders=1 tab=txt2img
                         folders=['/mnt/models/Lora'] list=0.01 thumb=0.00
                         desc=0.00 info=0.00 workers=12
15:56:01-463712 DEBUG    Networks: type="unet/dit" items=0 subfolders=1
                         tab=txt2img folders=['/mnt/models/UNET'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=12
15:56:01-499970 DEBUG    Networks: type="style" items=288 subfolders=3
                         tab=txt2img folders=['/mnt/models/styles', 'html']
                         list=0.04 thumb=0.00 desc=0.00 info=0.00 workers=12
15:56:01-508443 DEBUG    Networks: type="wildcards" items=0 subfolders=1
                         tab=txt2img folders=['/mnt/models/wildcards'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=12
15:56:01-514868 DEBUG    Networks: type="embedding" items=0 subfolders=1
                         tab=txt2img folders=['/mnt/models/embeddings']
                         list=0.01 thumb=0.01 desc=0.00 info=0.00 workers=12
15:56:01-524319 DEBUG    Networks: type="vae" items=0 subfolders=1 tab=txt2img
                         folders=['/mnt/models/VAE'] list=0.00 thumb=0.00
                         desc=0.00 info=0.00 workers=12
15:56:01-529313 DEBUG    Networks: type="history" items=0 subfolders=1
                         tab=txt2img folders=[] list=0.00 thumb=0.00 desc=0.00
                         info=0.00 workers=12
15:56:02-421376 DEBUG    ROCm load_config: path=/app/data/rocm.json
                         existed=False items=61
15:56:02-963178 DEBUG    UI initialize: tab=img2img
15:56:03-972581 DEBUG    UI initialize: tab=control models="/mnt/models/control"
15:56:06-108739 DEBUG    UI initialize: tab=video
15:56:06-298885 INFO     Networks: type="video" engines=13 models=79 errors=0
                         time=0.08
15:56:06-640965 DEBUG    UI initialize: tab=process
15:56:06-854276 DEBUG    UI initialize: tab=caption
15:56:07-179381 DEBUG    UI initialize: tab=models
15:56:07-598213 DEBUG    UI initialize: tab=gallery
15:56:07-788712 DEBUG    Read: file="/mnt/data/ui-config.json" json=0 bytes=2
                         time=0.000 fn=__init__:read_from_file
15:56:07-790995 DEBUG    UI initialize: tab=settings
15:56:08-078470 DEBUG    ONNX: version=1.25.0,
                         available=['AzureExecutionProvider',
                         'CPUExecutionProvider']
15:56:10-493821 DEBUG    Settings: sections=23 settings=366/600 quicksettings=1
15:56:10-675852 DEBUG    UI initialize: tab=info
15:56:10-770585 DEBUG    UI initialize: tab=extensions
15:56:10-787461 INFO     Extension list: No information found - refresh required
15:56:10-895197 DEBUG    Extension list: processed=2 installed=2 enabled=2
                         disabled=0 visible=2 hidden=0
15:56:11-379876 DEBUG    Root paths: ['/app', '/mnt/data', '/mnt/models']
15:56:12-247542 INFO     Local URL: http://localhost:7860/
15:56:12-248860 WARNING  Public URL: enabled without authentication
15:56:12-250070 INFO     External URL: http://172.17.0.2:7860
15:56:12-458174 INFO     Public URL: http://xxx.xxx.xxx.xxx:7860
15:56:12-459707 INFO     API docs: http://localhost:7860/docs
15:56:12-461100 INFO     API redocs: http://localhost:7860/redocs
15:56:12-466919 DEBUG    API middleware: [<class
                         'starlette.middleware.base.BaseHTTPMiddleware'>, <class
                         'starlette.middleware.gzip.GZipMiddleware'>]
15:56:12-469123 DEBUG    API initialize
15:56:13-151452 DEBUG    Scripts setup: time=2.286 ['Prompt enhance:0.528',
                         'Windows ROCm: Advanced Config:0.219', 'IP
                         Adapters:0.184', 'Mixture-of-Diffusers: Tile
                         Control:0.105', 'Face: Multiple ID Transfers:0.102',
                         'XYZ Grid:0.099', 'XYZ Grid Script:0.094', 'CeeTeeDees
                         I2I folder batch inference:0.085', 'NudeNet:0.079',
                         'FreeScale: Tuning-Free Scale Fusion:0.053']
15:56:13-153377 INFO     Model: autoload=True selected="v1-5-pruned-fp16-emaonly
                         [92954befdb]"
15:56:13-155708 DEBUG    Model requested: fn=threading.py:run:<lambda>
15:56:13-157439 DEBUG    Search model: name="v1-5-pruned-fp16-emaonly
                         [92954befdb]"
                         matched="/mnt/models/Stable-diffusion/v1-5-pruned-fp16-
                         emaonly.safetensors" type=alias
15:56:13-158990 INFO     Load model: select="v1-5-pruned-fp16-emaonly
                         [92954befdb]"
15:56:13-161675 INFO     Autodetect model: detect="Stable Diffusion 1.5"
                         class=StableDiffusionPipeline
                         file="/mnt/models/Stable-diffusion/v1-5-pruned-fp16-ema
                         only.safetensors"
15:56:13-267426 DEBUG    Cache clear
Progress 45953.53it/s █████████████████ 100% 11/11 00:00 00:00 Fetching 11 files
Progress  1.69it/s █████████ 100% 6/6 00:03 00:00 Loading pipeline components...
15:56:17-371715 DEBUG    Setting model: pipeline=StableDiffusionPipeline
                         config={'low_cpu_mem_usage': True, 'torch_dtype':
                         torch.bfloat16, 'load_connected_pipeline': True,
                         'extract_ema': False, 'use_safetensors': True,
                         'cache_dir': '/mnt/models/huggingface'}
15:56:17-379136 INFO     Network load: type=embeddings loaded=0 skipped=0
                         time=0.00
15:56:17-380622 DEBUG    Setting model: component=vae {'slicing': True,
                         'tiling': False}
15:56:17-381770 DEBUG    Setting model: attention="Scaled-Dot-Product"
15:56:17-383347 INFO     Offload: type=balanced op=init watermark=0.2-0.6
                         gpu=3.20-9.60:16.00 cpu=60.000 limit=0.00 always=[]
                         never=[] pre=True streams=False
15:56:17-410325 DEBUG    Module: name=unet cls=UNet2DConditionModel size=1.601
                         params=859520964 quant=None
15:56:17-416499 DEBUG    Module: name=text_encoder cls=CLIPTextModel size=0.229
                         params=123060480 quant=None
15:56:17-425672 DEBUG    Module: name=vae cls=AutoencoderKL size=0.156
                         params=83653863 quant=None
15:56:17-429256 INFO     Model class=StableDiffusionPipeline modules=3
                         size=1.986
15:56:17-439180 INFO     Load model: family=sd time={'total': 4.28, 'load':
                         4.22} native=512 memory={'ram': {'total': 59.78, 'rss':
                         4.19, 'used': 11.69, 'free': 1.8, 'avail': 48.1,
                         'buffers': 0.69, 'cached': 46.7}, 'gpu': {'used': 0.35,
                         'total': 15.98, 'active': 0.0, 'peak': 0.0, 'retries':
                         0, 'oom': 0, 'swap': 0}, 'job': 'Load model'}
15:56:17-448834 DEBUG    Script init: ['system-info.py:app_started=0.30']
15:56:17-451787 INFO     Startup time: total=992.93 launch=311.84 loader=310.59
                         installer=310.58 torch=15.99 libraries=13.02 scans=7.97
                         gradio=4.52 checkpoint=4.30 ui-extensions=3.09
                         ui-control=1.63 ui-txt2img=1.36 extensions=1.35
                         ui-networks=1.21 diffusers=0.88 ui-img2img=0.84
                         cleanup=0.63 ui-models=0.52 ui-video=0.39 api=0.38
                         app-started=0.30 ui-defaults=0.29 samplers=0.26
                         ui-extras=0.21 ui-gallery=0.19 ui-caption=0.19
                         ui-info=0.11
15:56:17-461751 DEBUG    Save: file="/mnt/data/config.json" json=13 bytes=709
                         time=0.014
15:56:17-466078 WARNING  Restart is recommended due to packages updates...
15:56:17-470470 DEBUG    Save: file="/mnt/data/secrets.json" json=2 bytes=139
                         time=0.000
15:57:03-191340 DEBUG    UI: connected
15:58:09-329816 INFO     API user=None code=200 http/1.1 GET / 192.168.40.12
                         1.2135
15:58:12-634912 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/motd
                         192.168.40.12 0.1021
15:58:17-796809 TRACE    Server: alive=True requests=73 memory=10.76/59.78
                         status='idle' task='' timestamp=None current='' id=''
                         job=0 jobs=0 total=2 step=0 steps=0 queued=0 uptime=157
                         elapsed=120.33 eta=None progress=0
15:58:18-708167 INFO     API user=None code=200 http/1.1 GET /info 192.168.40.12
                         6.8917
15:58:31-248006 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/sd-models
                         192.168.40.12 0.0077
15:58:31-626595 INFO     API user=None code=200 http/1.1 GET
                         /sdapi/v1/browser/folders 192.168.40.12 0.0045
15:58:31-756415 INFO     Browser session: user=None client=192.168.40.12
                         agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64)
                         AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0
                         Safari/537.36 Edg/147.0.0.0
15:58:31-770672 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/start
                         192.168.40.12 0.0228
15:58:31-789769 DEBUG    UI: connected
15:58:33-662069 INFO     UI: ready time=21879
15:58:34-251118 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/status
                         192.168.40.12 0.0025
15:59:02-751836 DEBUG    Sampler: "Default" cls=EulerAncestralDiscreteScheduler
                         config={'num_train_timesteps': 1000, 'beta_start':
                         0.00085, 'beta_end': 0.012, 'beta_schedule':
                         'scaled_linear', 'trained_betas': None,
                         'prediction_type': 'epsilon', 'timestep_spacing':
                         'linspace', 'steps_offset': 1,
                         'rescale_betas_zero_snr': False, 'skip_prk_steps':
                         True, 'set_alpha_to_one': False, 'clip_sample': False}
15:59:02-856101 INFO     Processing modifiers: apply
15:59:02-895358 DEBUG    Tokenizer: words=49408
                         file="/mnt/models/huggingface/models--stable-diffusion-
                         v1-5--stable-diffusion-v1-5/snapshots/451f4fe16113bff5a
                         5d2269ed5ad43b0592e9a14/tokenizer/vocab.json"
15:59:04-178088 INFO     Base: pipeline=StableDiffusionPipeline
                         task=TEXT_2_IMAGE batch=1/1x1 set={'prompt_embeds':
                         torch.Size([1, 77, 768]), 'negative_prompt_embeds':
                         torch.Size([1, 77, 768]), 'guidance_scale': 6,
                         'generator': 'cuda:[3082395459]',
                         'num_inference_steps': 20, 'eta': 1.0,
                         'guidance_rescale': 0, 'output_type': 'latent',
                         'width': 1024, 'height': 1024, 'parser': 'native'}
Progress ?it/s                                              0% 0/20 00:00 ? BaseMIOpen Error: /long_pathname_so_that_rpms_can_package_the_debug_info/src/MLOpen/src/conv/heuristics/ai_heuristics.cpp:39: Unable to load file: /mnt/python/venv\Lib\site-packages\_rocm_sdk_devel\bin\/gfx908_metadata.tn.model
Progress ?it/s                                              0% 0/20 00:02 ? Base
15:59:06-928195 ERROR    Processing: step=base args={'prompt_embeds':
                         'cuda:0:torch.bfloat16:torch.Size([1, 77, 768])',
                         'negative_prompt_embeds':
                         'cuda:0:torch.bfloat16:torch.Size([1, 77, 768])',
                         'guidance_scale': 6, 'generator': [<torch._C.Generator
                         object at 0x7bba0bd02d90>], 'callback_on_step_end':
                         <function diffusers_callback at 0x7bba0e1789a0>,
                         'callback_on_step_end_tensor_inputs': ['latents',
                         'prompt_embeds', 'negative_prompt_embeds',
                         'noise_pred'], 'num_inference_steps': 20, 'eta': 1.0,
                         'guidance_rescale': 0, 'output_type': 'latent',
                         'width': 1024, 'height': 1024}
                         miopenStatusInternalError
15:59:06-931534 CRITICAL Processing: RuntimeError
lqqqqqqqqqqqqqqqqqqqqq Traceback (most recent call last) qqqqqqqqqqqqqqqqqqqqqqk
x/app/modules/processing_diffusers.py:187 in process_base                      x
x                                                                              x
x  186             taskid = shared.state.begin('Inference')                    x
x❱ 187             output = shared.sd_model(**base_args)                       x
x  188             shared.state.end(taskid)                                    x
x                                                                              x
x/mnt/python/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py:120  x
x                                                                              x
x  119         with ctx_factory():                                             x
x❱ 120             return func(*args, **kwargs)                                x
x  121                                                                         x
x                                                                              x
x/mnt/python/venv/lib/python3.12/site-packages/diffusers/pipelines/stable_diff x
x                                                                              x
x  1041                 # predict the noise residual                           x
x❱ 1042                 noise_pred = self.unet(                                x
x  1043                     latent_model_input,                                x
x                                                                              x
x/mnt/python/venv/lib/python3.12/site-packages/torch/nn/modules/module.py:1775 x
x                                                                              x
x  1774         else:                                                          x
x❱ 1775             return self._call_impl(*args, **kwargs)                    x
x  1776                                                                        x
x                                                                              x
x/mnt/python/venv/lib/python3.12/site-packages/torch/nn/modules/module.py:1786 x
x                                                                              x
x  1785                 or _global_forward_hooks or _global_forward_pre_hooks) x
x❱ 1786             return forward_call(*args, **kwargs)                       x
x  1787                                                                        x
x                                                                              x
x/mnt/python/venv/lib/python3.12/site-packages/accelerate/hooks.py:192 in new_ x
x                                                                              x
x  191         else:                                                           x
x❱ 192             output = module._old_forward(*args, **kwargs)               x
x  193         return module._hf_hook.post_forward(module, output)             x
x                                                                              x
x/mnt/python/venv/lib/python3.12/site-packages/diffusers/utils/peft_utils.py:3 x
x                                                                              x
x  314                 # Execute the forward pass                              x
x❱ 315                 result = forward_fn(self, *args, **kwargs)              x
x  316                 return result                                           x
x                                                                              x
x/mnt/python/venv/lib/python3.12/site-packages/diffusers/models/unets/unet_2d_ x
x                                                                              x
x  1109         # 2. pre-process                                               x
x❱ 1110         sample = self.conv_in(sample)                                  x
x  1111                                                                        x
x                                                                              x
x/mnt/python/venv/lib/python3.12/site-packages/torch/nn/modules/module.py:1775 x
x                                                                              x
x  1774         else:                                                          x
x❱ 1775             return self._call_impl(*args, **kwargs)                    x
x  1776                                                                        x
x                                                                              x
x/mnt/python/venv/lib/python3.12/site-packages/torch/nn/modules/module.py:1786 x
x                                                                              x
x  1785                 or _global_forward_hooks or _global_forward_pre_hooks) x
x❱ 1786             return forward_call(*args, **kwargs)                       x
x  1787                                                                        x
x                                                                              x
x/mnt/python/venv/lib/python3.12/site-packages/accelerate/hooks.py:192 in new_ x
x                                                                              x
x  191         else:                                                           x
x❱ 192             output = module._old_forward(*args, **kwargs)               x
x  193         return module._hf_hook.post_forward(module, output)             x
x                                                                              x
x/mnt/python/venv/lib/python3.12/site-packages/torch/nn/modules/conv.py:548 in x
x                                                                              x
x   547     def forward(self, input: Tensor) -> Tensor:                        x
x❱  548         return self._conv_forward(input, self.weight, self.bias)       x
x   549                                                                        x
x                                                                              x
x/mnt/python/venv/lib/python3.12/site-packages/torch/nn/modules/conv.py:543 in x
x                                                                              x
x   542             )                                                          x
x❱  543         return F.conv2d(                                               x
x   544             input, weight, bias, self.stride, self.padding, self.dilat x
mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj
RuntimeError: miopenStatusInternalError
15:59:08-245276 DEBUG    Search model: name='v1-5-pruned-fp16-emaonly
                         [92954befdb]'
                         matched='/mnt/models/Stable-diffusion/v1-5-pruned-fp16-
                         emaonly.safetensors' type=alias
15:59:08-261349 DEBUG    Analyzed: model='v1-5-pruned-fp16-emaonly' type=sd
                         class=StableDiffusionPipeline size=2132650708
                         mtime='2026-04-27 13:53:36' modules=[name='vae'
                         cls=AutoencoderKL config=True device=cpu
                         dtype=torch.bfloat16 params=83653863 modules=243,
                         name='text_encoder' cls=CLIPTextModel config=True
                         device=cuda:0 dtype=torch.bfloat16 params=123060480
                         modules=152, name='tokenizer' cls=CLIPTokenizer
                         config=False, name='unet' cls=UNet2DConditionModel
                         config=True device=cuda:0 dtype=torch.bfloat16
                         params=859520964 modules=709, name='scheduler'
                         cls=EulerAncestralDiscreteScheduler config=True,
                         name='safety_checker' cls=NoneType config=False,
                         name='feature_extractor' cls=CLIPImageProcessor
                         config=False, name='image_encoder' cls=NoneType
                         config=False, name='requires_safety_checker' cls=bool
                         config=False]
15:59:08-266448 INFO     Processing modifiers: unapply
15:59:08-271851 DEBUG    Process: batch=1/1 interrupted
15:59:08-274150 INFO     Processed: images=0 its=0.00 ops=['txt2img']
15:59:08-275480 DEBUG    Processed: timers={'total': 9.92, 'post': 5.4,
                         'onload': 2.57, 'prompt': 1.3, 'move': 0.47, 'pre':
                         0.11}
15:59:08-277541 DEBUG    Processed: memory={'ram': {'total': 59.78, 'rss': 4.32,
                         'used': 10.64, 'free': 2.84, 'avail': 49.15, 'buffers':
                         0.69, 'cached': 46.7}, 'gpu': {'used': 2.45, 'total':
                         15.98, 'active': 1.93, 'peak': 1.95, 'retries': 0,
                         'oom': 0, 'swap': 0}, 'job': ''}
16:00:17-859215 TRACE    Server: alive=True requests=365 memory=10.87/59.78
                         status='interrupted' task='' timestamp=None current=''
                         id='' job=0 jobs=0 total=10 step=0 steps=0 queued=0
                         uptime=278 elapsed=69.58 eta=None progress=0
```

### Operating system

Linux

### Compute

AMD ROCm

### Interface

Standard

### Branch

Master

### Model

Unspecified

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
when you say official rocm docker image, which one exactly?
setting hsa override env variable is no longer needed for a while now for any recent gpus.
somehow, you end up with torch==2.9.1 which is for rocm world pretty old as rocm updates are nearly daily.
can you try without docker?
also, you have amd gpu and igpu, you may need to set torch visible devices env variable.

**Comment by yaizawa2e** [comment]
I used [this](https://github.com/vladmandic/sdnext/blob/dev/configs/Dockerfile.rocm) Dockerfile.

**Comment by yaizawa2e** [comment]
Thank you for your suggestions.

I tried running it outside of Docker, and I can confirm it is now working correctly, even without setting `ROCM_VISIBLE_DEVICES`.

While setting it up according to the instructions, I realized that SD.next is very well-designed to avoid cluttering the host environment (e.g., by automatically managing VENV within the startup scripts). I now feel that there is little merit in using Docker given how cleanly the native installation handles dependencies.

**Comment by vladmandic** [comment]
thanks.
we'll publish an update to docker receipe shortly so its also updated.
