### ISSUE TITLE
[Issue]: Segmentation fault on launch

### ISSUE THREAD

**Issue by limejet** [vladmandic/automatic#913]
### Issue Description

Hi, i'm unable to run this out of the box due to the python runtime segfaulting right after launch. I can't really find anything in the logs that gives a hint to why this happens, but considering the general tone of discussions here i'm assuming it's related to the 7900XTX GPU.

First few runs crashed for me due to dependencies failing to install properly, but that fixes itself with subsequent runs (until the segfault happens).

Before generating this log, i attempted to remove warnings by fixing stuff that caused warnings in the logs (like installing `image-reward`) , but the segfault has been there from the start.
```
11:37:35-924601 INFO     Starting SD.Next
11:37:35-928788 INFO     Python 3.10.10 on Linux
11:37:35-935447 DEBUG    Git 2.40.1
11:37:35-940989 INFO     Version: a2485cf7 Fri May 12 21:12:24 2023 -0400
11:37:36-363543 INFO     Setting environment tuning
11:37:36-365224 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False
11:37:36-366920 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True
11:37:36-368736 INFO     AMD ROCm toolkit detected
11:37:36-499528 DEBUG    Package version found: torch 2.0.0+rocm5.4.2
11:37:36-501108 DEBUG    Package version found: torchvision 0.15.1+rocm5.4.2
11:37:36-501966 DEBUG    Package version found: torchaudio 2.0.1+rocm5.4.2
11:37:37-605840 INFO     Torch 2.0.0+rocm5.4.2
11:37:39-445761 INFO     Torch backend: AMD ROCm HIP 5.4.22803-474e8620
11:37:39-447383 INFO     Torch detected GPU: AMD Radeon RX 7900 XTX VRAM 24560 Arch (10, 3) Cores 48
11:37:39-448456 DEBUG    Package version found: tensorflow 2.12.0
11:37:39-449208 INFO     Verifying requirements
11:37:39-450005 DEBUG    Package version found: addict 2.4.0
11:37:39-450819 DEBUG    Package version found: aenum 3.1.12
11:37:39-451614 DEBUG    Package version found: aiohttp 3.8.4
11:37:39-452411 DEBUG    Package version found: anyio 3.6.2
11:37:39-453214 DEBUG    Package version found: appdirs 1.4.4
11:37:39-454084 DEBUG    Package version found: astunparse 1.6.3
11:37:39-454904 DEBUG    Package version found: bitsandbytes 0.38.1
11:37:39-455717 DEBUG    Package version found: blendmodes 2022
11:37:39-456495 DEBUG    Package version found: clean-fid 0.1.35
11:37:39-457306 DEBUG    Package version found: easydev 0.12.1
11:37:39-458107 DEBUG    Package version found: extcolors 1.0.0
11:37:39-458897 DEBUG    Package version found: facexlib 0.3.0
11:37:39-459690 DEBUG    Package version found: filetype 1.2.0
11:37:39-460489 DEBUG    Package version found: font-roboto 0.0.1
11:37:39-461287 DEBUG    Package version found: fonts 0.0.3
11:37:39-462064 DEBUG    Package version found: future 0.18.2
11:37:39-462869 DEBUG    Package version found: gdown 4.7.1
11:37:39-463721 DEBUG    Package version found: gfpgan 1.3.8
11:37:39-464603 DEBUG    Package version found: GitPython 3.1.31
11:37:39-465567 DEBUG    Package version found: httpcore 0.17.0
11:37:39-466659 DEBUG    Package version found: inflection 0.5.1
11:37:39-467737 DEBUG    Package version found: jsonmerge 1.9.0
11:37:39-468796 DEBUG    Package version found: kornia 0.6.12
11:37:39-469686 DEBUG    Package version found: lark 1.1.5
11:37:39-470552 DEBUG    Package version found: lmdb 1.4.1
11:37:39-471397 DEBUG    Package version found: lpips 0.1.4
11:37:39-472237 DEBUG    Package version found: numpy 1.23.5
11:37:39-473089 DEBUG    Package version found: omegaconf 2.3.0
11:37:39-473951 DEBUG    Package version found: open-clip-torch 2.19.0
11:37:39-474819 DEBUG    Package version found: opencv-contrib-python 4.7.0.72
11:37:39-475681 DEBUG    Package version found: piexif 1.1.3
11:37:39-476538 DEBUG    Package version found: Pillow 9.4.0
11:37:39-477394 DEBUG    Package version found: psutil 5.9.4
11:37:39-478230 DEBUG    Package version found: pyyaml 6.0
11:37:39-479052 DEBUG    Package version found: realesrgan 0.3.0
11:37:39-479911 DEBUG    Package version found: resize-right 0.0.2
11:37:39-480783 DEBUG    Package version found: rich 13.3.3
11:37:39-481734 DEBUG    Package version found: safetensors 0.3.1
11:37:39-482820 DEBUG    Package version found: scipy 1.10.1
11:37:39-483873 DEBUG    Package version found: tb_nightly 2.14.0a20230511
11:37:39-484960 DEBUG    Package version found: toml 0.10.2
11:37:39-486006 DEBUG    Package version found: torchdiffeq 0.2.3
11:37:39-486911 DEBUG    Package version found: torchsde 0.2.5
11:37:39-487771 DEBUG    Package version found: voluptuous 0.13.1
11:37:39-488622 DEBUG    Package version found: yapf 0.32.0
11:37:39-489482 DEBUG    Package version found: scikit-image 0.20.0
11:37:39-490332 DEBUG    Package version found: basicsr 1.4.2
11:37:39-491189 DEBUG    Package version found: requests 2.30.0
11:37:39-492090 DEBUG    Package version found: tqdm 4.65.0
11:37:39-492947 DEBUG    Package version found: accelerate 0.18.0
11:37:39-493799 DEBUG    Package version found: opencv-python 4.7.0.72
11:37:39-494651 DEBUG    Package version found: diffusers 0.16.1
11:37:39-495506 DEBUG    Package version found: einops 0.4.1
11:37:39-496350 DEBUG    Package version found: gradio 3.29.0
11:37:39-497199 DEBUG    Package version found: numexpr 2.8.4
11:37:39-498044 DEBUG    Package version found: pandas 1.5.3
11:37:39-498895 DEBUG    Package version found: protobuf 3.20.3
11:37:39-499747 DEBUG    Package version found: pytorch_lightning 1.9.4
11:37:39-500630 DEBUG    Package version found: transformers 4.26.1
11:37:39-501506 DEBUG    Package version found: timm 0.6.13
11:37:39-502344 DEBUG    Package version found: tomesd 0.1.2
11:37:39-503188 DEBUG    Package version found: urllib3 1.26.15
11:37:39-504052 DEBUG    Package version found: onnxruntime 1.14.0
11:37:39-511737 DEBUG    Repository update time: Sat May 13 03:12:24 2023
11:37:39-513035 DEBUG    Previous setup time: Sat May 13 11:16:41 2023
11:37:39-514167 DEBUG    Extension version: Sat May 13 11:13:18 2023 ~/src/stable-diffusion/automatic/extensions-builtin:sd-dynamic-thresholding
11:37:39-515093 DEBUG    Extension version: Thu May 11 21:39:58 2023 ~/src/stable-diffusion/automatic/extensions-builtin:prompt-bracket-checker
11:37:39-515946 DEBUG    Extension version: Sat May 13 11:13:18 2023 ~/src/stable-diffusion/automatic/extensions-builtin:a1111-sd-webui-lycoris
11:37:39-516787 DEBUG    Extension version: Sat May 13 11:13:18 2023 ~/src/stable-diffusion/automatic/extensions-builtin:Lora
11:37:39-517724 DEBUG    Extension version: Sat May 13 11:13:18 2023 ~/src/stable-diffusion/automatic/extensions-builtin:multidiffusion-upscaler-for-automatic1111
11:37:39-518783 DEBUG    Extension version: Sat May 13 11:13:19 2023 ~/src/stable-diffusion/automatic/extensions-builtin:sd-extension-system-info
11:37:39-519820 DEBUG    Extension version: Sat May 13 11:13:19 2023 ~/src/stable-diffusion/automatic/extensions-builtin:sd-webui-model-converter
11:37:39-520844 DEBUG    Extension version: Sat May 13 11:13:19 2023 ~/src/stable-diffusion/automatic/extensions-builtin:sd-extension-steps-animation
11:37:39-521787 DEBUG    Extension version: Sat May 13 11:13:18 2023 ~/src/stable-diffusion/automatic/extensions-builtin:LDSR
11:37:39-522653 DEBUG    Extension version: Sat May 13 11:13:37 2023 ~/src/stable-diffusion/automatic/extensions-builtin:SwinIR
11:37:39-523546 DEBUG    Extension version: Sat May 13 11:13:18 2023 ~/src/stable-diffusion/automatic/extensions-builtin:clip-interrogator-ext
11:37:39-524490 DEBUG    Extension version: Sat May 13 11:13:19 2023 ~/src/stable-diffusion/automatic/extensions-builtin:sd-extension-aesthetic-scorer
11:37:39-525405 DEBUG    Extension version: Sat May 13 11:13:19 2023 ~/src/stable-diffusion/automatic/extensions-builtin:seed_travel
11:37:39-526294 DEBUG    Extension version: Sat May 13 11:13:38 2023 ~/src/stable-diffusion/automatic/extensions-builtin:stable-diffusion-webui-images-browser
11:37:39-527290 DEBUG    Extension version: Sat May 13 11:16:23 2023 ~/src/stable-diffusion/automatic/extensions-builtin:sd-webui-controlnet
11:37:39-528187 DEBUG    Extension version: Sat May 13 11:13:37 2023 ~/src/stable-diffusion/automatic/extensions-builtin:ScuNET
11:37:39-529068 DEBUG    Extension version: Sat May 13 11:13:19 2023 ~/src/stable-diffusion/automatic/extensions-builtin:stable-diffusion-webui-rembg
11:37:39-529946 DEBUG    Latest extensions time: Sat May 13 11:16:23 2023
11:37:39-530738 DEBUG    Timestamps: version:1683940344 setup:1683969401 extension:1683969383
11:37:39-531676 INFO     No changes detected: Quick launch active
11:37:39-533039 INFO     Running extension preloading
11:37:39-533820 INFO     Server arguments: ['--debug']
11:37:39-534598 DEBUG    Starting WebUI
11:37:39-542383 DEBUG    Memory used: 0.54 total: 62.72 Collected 0
No module 'xformers'. Proceeding without it.
11:37:43-623627 INFO     Libraries loaded
11:37:43-626932 DEBUG    Entering WebUI
11:37:43-627594 DEBUG    Entering StartUI
11:37:43-628342 DEBUG    Entering Initialize
11:37:43-669341 INFO     Available models: ~/src/stable-diffusion/automatic/models/Stable-diffusion 35
ControlNet v1.1.152
ControlNet v1.1.152
11:37:46-188174 INFO     Loading UI theme: black-orange
11:37:46-190237 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/javascript/aspectRatioOverlay.js
11:37:46-191036 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/javascript/contextMenus.js
11:37:46-191769 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/javascript/dragdrop.js
11:37:46-192481 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/javascript/edit-attention.js
11:37:46-193192 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/javascript/extensions.js
11:37:46-193908 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/javascript/extraNetworks.js
11:37:46-194613 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/javascript/generationParams.js
11:37:46-195315 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/javascript/hints.js
11:37:46-196014 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/javascript/hires_fix.js
11:37:46-196726 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/javascript/imageMaskFix.js
11:37:46-197435 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/javascript/imageParams.js
11:37:46-198126 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/javascript/imageviewer.js
11:37:46-198822 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/javascript/notification.js
11:37:46-199516 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/javascript/progressbar.js
11:37:46-200209 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/javascript/textualInversion.js
11:37:46-200910 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/javascript/ui.js
11:37:46-201623 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/extensions-builtin/multidiffusion-upscaler-for-automatic1111/javascript/bboxHint.js
11:37:46-202370 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/extensions-builtin/prompt-bracket-checker/javascript/prompt-bracket-checker.js
11:37:46-203093 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/extensions-builtin/sd-extension-system-info/javascript/system-info.js
11:37:46-203803 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/extensions-builtin/sd-webui-controlnet/javascript/hints.js
11:37:46-204535 DEBUG    Loading JS script: ~/src/stable-diffusion/automatic/extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js
11:37:46-205528 DEBUG    Adding stylesheet: javascript/style.css
11:37:46-206302 DEBUG    Adding stylesheet: ~/src/stable-diffusion/automatic/extensions-builtin/stable-diffusion-webui-images-browser/style.css
11:37:46-207028 DEBUG    Adding stylesheet: ~/src/stable-diffusion/automatic/javascript/black-orange.css
11:37:47-206896 DEBUG    Extensions list failed to load: ~/src/stable-diffusion/automatic/html/extensions.json
11:37:47-291451 DEBUG    Extensions manager: refresh list search= sort=default
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
11:37:47-566151 INFO     Local URL: http://127.0.0.1:7860/
11:37:47-567936 INFO     API Docs: http://127.0.0.1:7860/docs
11:37:47-569208 DEBUG    Gradio registered functions: 978
11:37:47-570571 INFO     Initializing middleware
11:37:47-915987 DEBUG    gc: {'ram': {'used': 1.33, 'total': 62.72}, 'gpu': {'used': 0.0, 'total': 23.98}, 'retries': 0, 'oom': 0}
11:37:47-917268 DEBUG    Load model: info=False dict=False
[W Module.cpp:1149] Warning: cuDNN Benchmark limit is not supported in MIOpen and will have no effect. (function operator())
fish: Job 1, 'python launch.py --debug' terminated by signal SIGSEGV (Address boundary error)
```

### Version Platform Description

Automatic version: a2485cf7 Fri May 12 21:12:24 2023 -0400

The crash occurs before i ever have the chance to actually open the UI, so browser version isn't really relevant.

System information (from `inxi -SCGmz`, irrelevant info like dram timings and stuff removed)
```
System:
  Kernel: 6.1.26-1-MANJARO arch: x86_64
    Distro: Manjaro Linux
Memory:
  System RAM: available: 62.72 GiB
CPU:
  Info: 8-core model: AMD Ryzen 7 2700X
Graphics:
  Device-1: AMD Navi 31 [Radeon RX 7900 XT/7900 XTX] driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 21.1.8 with: Xwayland v: 23.1.1 driver: X:
    loaded: amdgpu unloaded: modesetting,radeon dri: radeonsi gpu: amdgpu
  API: OpenGL v: 4.6 Mesa 23.0.3 renderer: AMD Radeon RX 7900 XTX (gfx1100
    LLVM 15.0.7 DRM 3.49 6.1.26-1-MANJARO)
```

**Comment by vladmandic** [comment]
anything in `/var/logs` or `dmesg -kuT` output (run immediately after segfault as that prints kernel ring bufffer)?
also, please attach output of `ulimit -a`.

**Comment by limejet** [comment]
Yeah the syslog has a stack trace. Looks like the HIP library installed along with torch is crashing.
```
kernel: amdgpu: Failed to pin bo. ret -1
kernel: amdgpu: Failed to map wptr bo to GART
kernel: amdgpu: Failed to pin bo. ret -1
kernel: amdgpu: Failed to map wptr bo to GART
kernel: amdgpu: Failed to pin bo. ret -1
kernel: amdgpu: Failed to map wptr bo to GART
kernel: amdgpu: Failed to pin bo. ret -1
kernel: amdgpu: Failed to map wptr bo to GART
kernel: amdgpu: Failed to pin bo. ret -1
kernel: amdgpu: Failed to map wptr bo to GART
kernel: amdgpu: Failed to pin bo. ret -1
kernel: amdgpu: Failed to map wptr bo to GART
kernel: amdgpu: Failed to pin bo. ret -1
kernel: amdgpu: Failed to map wptr bo to GART
kernel: amdgpu: Failed to pin bo. ret -1
kernel: amdgpu: Failed to map wptr bo to GART
kernel: amdgpu: Failed to pin bo. ret -1
kernel: amdgpu: Failed to map wptr bo to GART
audit[40923]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj=unconfined pid=40923 comm="python3" exe="/usr/bin/python3.10" sig=11 res=1
kernel: python3[40923]: segfault at 100 ip 00007f2711b2d282 sp 00007fffa29a1530 error 4 in libamdhip64.so[7f2711a00000+3f3000] likely on CPU 9 (core 1, socket 0)
kernel: Code: 00 00 00 00 e8 9f 95 ff ff 48 8d 74 24 20 31 d2 4c 89 f7 48 89 c5 48 c7 44 24 20 00 00 00 00 e8 84 95 ff ff 48 85 c0 48 89 c3 <49> 8b 94 24 00 01 00 00 0f 95 c0 48 85 ed 0f 85 a2 01 00 00 84 c0

<some auditing messages removed>

kernel: audit: type=1130 audit(1683980823.944:459): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-coredump@21-41036-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
(sd-parse-elf)[41040]: Could not parse number of program headers from core file: invalid `Elf' handle
<above line repeated x 74>
systemd-coredump[41037]: [🡕] Process 40923 (python3) of user 1000 dumped core.
                         Module ~/.local/lib/python3.10/site-packages/numba/np/ufunc/tbbpool.cpython-310-x86_64-linux-gnu.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/numba/np/ufunc/tbbpool.cpython-310-x86_64-linux-gnu.so
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libgfortran-91cc3cb1.so.3.0.0 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libgfortran-91cc3cb1.so.3.0.0
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libcrypto-47343492.so.1.1 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libcrypto-47343492.so.1.1
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libopenblas-r0-f650aae0.3.3.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libopenblas-r0-f650aae0.3.3.so
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libQt5Core-39545cc7.so.5.15.0 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libQt5Core-39545cc7.so.5.15.0
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libQt5Gui-48e93776.so.5.15.0 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libQt5Gui-48e93776.so.5.15.0
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libavcodec-16a334ab.so.59.37.100 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libavcodec-16a334ab.so.59.37.100
                         Module ~/.local/lib/python3.10/site-packages/cv2/cv2.abi3.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/cv2/cv2.abi3.so
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libvpx-e95aadfe.so.7.1.0 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libvpx-e95aadfe.so.7.1.0
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libQt5Widgets-e69d94fb.so.5.15.0 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libQt5Widgets-e69d94fb.so.5.15.0
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libavutil-82c407cb.so.57.28.100 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libavutil-82c407cb.so.57.28.100
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libavformat-e0b1067c.so.59.27.100 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libavformat-e0b1067c.so.59.27.100
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libssl-16e42f2f.so.1.1 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libssl-16e42f2f.so.1.1
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libpcre-9513aab5.so.1.2.0 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libpcre-9513aab5.so.1.2.0
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libQt5Test-c38a5234.so.5.15.0 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libQt5Test-c38a5234.so.5.15.0
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libselinux-0922c95c.so.1 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libselinux-0922c95c.so.1
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libswscale-9b504c0d.so.6.7.100 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libswscale-9b504c0d.so.6.7.100
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libkeyutils-dfe70bd6.so.1.5 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libkeyutils-dfe70bd6.so.1.5
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libpng16-57e5e0a0.so.16.37.0 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libpng16-57e5e0a0.so.16.37.0
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libkrb5support-d0bcff84.so.0.1 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libkrb5support-d0bcff84.so.0.1
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libk5crypto-b1f99d5c.so.3.1 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libk5crypto-b1f99d5c.so.3.1
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libcom_err-2abe824b.so.2.1 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libcom_err-2abe824b.so.2.1
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libkrb5-fcafa220.so.3.3 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libkrb5-fcafa220.so.3.3
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libgssapi_krb5-497db0c6.so.2.2 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libgssapi_krb5-497db0c6.so.2.2
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libcrypto-d3570994.so.1.0.2k without build-id.
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libcrypto-d3570994.so.1.0.2k
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libssl-cd1d6220.so.1.0.2k without build-id.
                         Module ~/.local/lib/python3.10/site-packages/tokenizers.libs/libssl-cd1d6220.so.1.0.2k
                         Module ~/.local/lib/python3.10/site-packages/tokenizers/tokenizers.cpython-310-x86_64-linux-gnu.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/tokenizers/tokenizers.cpython-310-x86_64-linux-gnu.so
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libswresample-d02fa90a.so.4.7.100 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/opencv_contrib_python.libs/libswresample-d02fa90a.so.4.7.100
                         Module ~/.local/lib/python3.10/site-packages/torchvision.libs/libdrm_amdgpu.fdca4e9c.so.1 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torchvision.libs/libdrm_amdgpu.fdca4e9c.so.1
                         Module ~/.local/lib/python3.10/site-packages/torchvision.libs/libamd_comgr.9b21a3b1.so.2 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torchvision.libs/libamd_comgr.9b21a3b1.so.2
                         Module ~/.local/lib/python3.10/site-packages/torchvision.libs/libelf.778b3e34.so.1 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torchvision.libs/libelf.778b3e34.so.1
                         Module ~/.local/lib/python3.10/site-packages/torchvision.libs/libhsa-runtime64.2f88ea9b.so.1 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torchvision.libs/libhsa-runtime64.2f88ea9b.so.1
                         Module ~/.local/lib/python3.10/site-packages/torchvision.libs/libamdhip64.2d48d65f.so.5 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torchvision.libs/libamdhip64.2d48d65f.so.5
                         Module ~/.local/lib/python3.10/site-packages/numpy.libs/libquadmath-96973f99.so.0.0.0 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/numpy.libs/libquadmath-96973f99.so.0.0.0
                         Module ~/.local/lib/python3.10/site-packages/numpy.libs/libgfortran-040039e1.so.5.0.0 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/numpy.libs/libgfortran-040039e1.so.5.0.0
                         Module ~/.local/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-742d56dc.3.20.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-742d56dc.3.20.so
                         Module ~/.local/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libnvfuser_codegen.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libnvfuser_codegen.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocsolver.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocsolver.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libhiprtc.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libhiprtc.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocfft-device-3.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocfft-device-3.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocfft-device-2.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocfft-device-2.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocfft-device-1.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocfft-device-1.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocfft-device-0.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocfft-device-0.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libelf.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libelf.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libtinfo.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libtinfo.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libhipblas.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libhipblas.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocsparse.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocsparse.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocrand.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocrand.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocfft.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocfft.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libhsa-runtime64.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libhsa-runtime64.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libamd_comgr.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libamd_comgr.so
                         Module ~/.local/lib/python3.10/site-packages/torchvision.libs/libpng16.7f72a3c5.so.16 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torchvision.libs/libpng16.7f72a3c5.so.16
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libmagma.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libmagma.so
                         Module ~/.local/lib/python3.10/site-packages/torchvision.libs/libz.55464d6f.so.1 without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torchvision.libs/libz.55464d6f.so.1
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librccl.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librccl.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libhipsparse.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libhipsparse.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libroctracer64.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libroctracer64.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libnuma.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libnuma.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocblas.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/librocblas.so
                         Module ~/.local/lib/python3.10/site-packages/torchvision/image.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torchvision/image.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libMIOpen.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libMIOpen.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libamdhip64.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libamdhip64.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libtorch_hip.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libtorch_hip.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so
                         Module ~/.local/lib/python3.10/site-packages/numpy/linalg/_umath_linalg.cpython-310-x86_64-linux-gnu.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/numpy/linalg/_umath_linalg.cpython-310-x86_64-linux-gnu.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libtorch_python.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libtorch_python.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libhipfft.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libhipfft.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libgomp.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libgomp.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libc10.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libc10.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libc10_hip.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libc10_hip.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libcaffe2_nvrtc.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libdrm_amdgpu.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libdrm_amdgpu.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libhiprand.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libhiprand.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libshm.so without build-id.
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libshm.so
                         Module ~/.local/lib/python3.10/site-packages/torch/lib/libtorch_global_deps.so without build-id.
                         Stack trace of thread 40923:
                         #0  0x00007f2711b2d282 n/a (~/.local/lib/python3.10/site-packages/torch/lib/libamdhip64.so + 0x12d282)
                         ELF object binary architecture: AMD x86-64

```

ulimit output:
```
Maximum size of core files created                              (kB, -c) unlimited
Maximum size of a process’s data segment                        (kB, -d) unlimited
Control of maximum nice priority                                    (-e) 0
Maximum size of files created by the shell                      (kB, -f) unlimited
Maximum number of pending signals                                   (-i) 256849
Maximum size that may be locked into memory                     (kB, -l) 8192
Maximum resident set size                                       (kB, -m) unlimited
Maximum number of open file descriptors                             (-n) 1024
Maximum bytes in POSIX message queues                           (kB, -q) 800
Maximum realtime scheduling priority                                (-r) 0
Maximum stack size                                              (kB, -s) 8192
Maximum amount of CPU time in seconds                      (seconds, -t) unlimited
Maximum number of processes available to current user               (-u) 256849
Maximum amount of virtual memory available to each process      (kB, -v) unlimited
Maximum contiguous realtime CPU time                                (-y) unlimited
```

**Comment by vladmandic** [comment]
segfault happens inside `libamdhip64.so`

btw, i'm not AMD expert, but i believe that 7900XTX is RDNA3 GPU and that generation is only semi-supproted by AMD ROCm.
you can try playing with value for `HSA_OVERRIDE_GFX_VERSION` in `installer.py`, i cannot tell you which values to try - perhaps someone else can chime in or goole around?

AMD has announced that upcoming ROCm 5.5 will have full ROCm support, but that is not available yet (I hope AMD puts more effort into ROCm like nVidia is doing with CUDA).

other than this, I'm not sure if i can help anymore.

**Comment by limejet** [comment]
ROCm 5.5 has been proper released for about two weeks now, actually! It's just that pytorch hasn't caught up yet, although apparently they're working on it: [pytorch/issues/100625](https://github.com/pytorch/pytorch/issues/100625) 

Manually compiling pytorch does seem to produce something that works, unfortunately this process takes about two hours on my 2700x and the resulting binary package uses a naming convention that breaks version checks (at least in automatic1111, which always assumes version numbers to be base-10 integers). 

I've been testing out [evshiron/rocm_lab](https://github.com/evshiron/rocm_lab), which packages a fork of this repo in a container and runs it with torch compiled for rocm5.5, and it seems to work rather well, with a sizeable speed-up. The downside is of course that the fork doesn't keep up to date with upstream, and that the "one-click install" nature of these sorts of web ui's make it hard to fix issues when running in a container.

But in that case i know it's just a waiting game at this point. I'll continue tweaking the container approach in the mean time. Thanks for the response.

**Comment by vladmandic** [comment]
version check i can fix - can you get me output of `import torch; print(torch.__version__)` using that build?
btw, as soon as torch20+rocm55 have been published, ping and i'll try to integrate it asap.

**Comment by limejet** [comment]
Unfortunately i don't have the build left, but i did fix it myself at the time. I dug up what i remembered. The file that errored out was part of CodeFormer's yolov5face/face_detector.py when it tries to load torchvision, which was also rebuilt for newer versions of ROCm. The problem was that the version was `2.0.0a0+<git hash>` , and the version check is like `map(int, version.split("+")[0].split(".")) > (1,9,0)`. 

I removed the conversion part and replaced the int tuple with a string tuple, but there's probably a library that does it in a more robust way. Anyway, don't really know if that's on you to fix, seems like a codeformer problem.

**Comment by vladmandic** [comment]
i'm aware of the codeformer bugging out and for torch nighly builds there is already a regex in place to modify version string.
i just need exact torch+rocm version string so i can modify regex to include that.

```python
if ".dev" in torch.__version__ or "+git" in torch.__version__:
    torch.__long_version__ = torch.__version__
    torch.__version__ = re.search(r'[\d.]+[\d]', torch.__version__).group(0)
```

**Comment by limejet** [comment]
Oh, that's going to be harder since i don't have the exact setup. The thing i remember for sure was that the torch version _started_ with `2.0.0a0`, but whether the rocm version was tacked on as `5.5.0` or `rocm5.5.0` or even `rocm5.5.0-release` (these are all formats i've encountered while looking for a working library) i can't remember and can't check anymore. I have no history to go through as it was all done in containers that have since been deleted for space-saving reasons.
