### ISSUE TITLE
[Issue]: Cannot launch because of HSA_STATUS_ERROR_MEMORY_APERTURE_VIOLATION (Ubuntu+ROCm environment)

### ISSUE THREAD

**Issue by cyatarow** [vladmandic/automatic#922]
### Issue Description
I'm trying to use this fork for the first time, but I can't launch it at all.
The terminal log:

```
Create and activate python venv
Launching launch.py...
02:15:36-991490 INFO     Starting SD.Next                                                                                       
02:15:37-002209 INFO     Python 3.10.6 on Linux                                                                                 
02:15:37-032836 INFO     Version: a6522709 Sat May 13 12:26:00 2023 -0400                                                       
02:15:37-684946 INFO     Latest published version: c46f0dbdeb27dac2f17f19b119a43a094076d1b7 2023-05-13T16:55:50Z                
02:15:37-688596 INFO     Setting environment tuning                                                                             
02:15:37-691747 INFO     AMD ROCm toolkit detected                                                                              
02:15:43-008440 INFO     Torch 2.0.0+rocm5.4.2                                                                                  
02:15:46-181858 INFO     Torch backend: AMD ROCm HIP 5.4.22803-474e8620                                                         
02:15:46-197535 INFO     Torch detected GPU: AMD Radeon RX 5500 XT VRAM 8176 Arch (10, 3) Cores 11                              
02:15:46-199514 INFO     Verifying requirements                                                                                 
02:15:46-593826 INFO     Running setup                                                                                          
02:15:46-597339 INFO     Installing packages                                                                                    
02:15:46-600621 INFO     Installing repositories                                                                                
02:15:46-628381 INFO     Installing submodules                                                                                  
02:15:54-620866 INFO     Updating submodules                                                                                    
02:17:13-141076 INFO     Extensions enabled: ['sd-extension-system-info', 'LDSR', 'sd-extension-steps-animation',               
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'stable-diffusion-webui-rembg',            
                         'sd-webui-model-converter', 'clip-interrogator-ext', 'multidiffusion-upscaler-for-automatic1111',      
                         'sd-webui-controlnet', 'prompt-bracket-checker', 'Lora', 'SwinIR', 'seed_travel',                      
                         'a1111-sd-webui-lycoris', 'stable-diffusion-webui-images-browser', 'ScuNET']                           
02:17:13-142274 INFO     Updating Wiki                                                                                          
02:17:13-721543 INFO     Running extension preloading                                                                           
02:17:13-724467 INFO     Server arguments: []                                                                                   
No module 'xformers'. Proceeding without it.
02:17:16-488067 INFO     Libraries loaded                                                                                       
02:17:16-493974 INFO     Available models: /home/sd-amd/automatic/models/Stable-diffusion 1                                     
ControlNet v1.1.159
ControlNet v1.1.159
Image Browser: ImageReward is not installed, cannot be used.
02:17:17-707802 INFO     Loading UI theme: black-orange                                                                         
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
02:17:18-888609 INFO     Local URL: http://127.0.0.1:7860/                                                                      
02:17:18-891379 INFO     API Docs: http://127.0.0.1:7860/docs                                                                   
02:17:18-893942 INFO     Initializing middleware                                                                                
02:17:19-202406 WARNING  Default checkpoint not found: model.ckpt                                                               
02:17:19-203104 WARNING  Loading fallback checkpoint: v1-5-pruned-emaonly.safetensors                                           
[W Module.cpp:1149] Warning: cuDNN Benchmark limit is not supported in MIOpen and will have no effect. (function operator())
:0:rocdevice.cpp            :2673: 1585589027 us: 5640 : [tid:0x7f1dca477640] Device::callbackQueue aborting with error : HSA_STATUS_ERROR_MEMORY_APERTURE_VIOLATION: The agent attempted to access memory beyond the largest legal address. code: 0x29
```

### Version Platform Description

OS: Ubuntu 22.04.2 x64
GPU: Radeon RX 5500 XT 8GB
Version: a6522709 Sat May 13 12:26:00 2023 -0400
Browser: Firefox 102.11.0esr

**Comment by vladmandic** [comment]
AMD ROCm is really dumb when it comes to detecting its own GPUs,
You may need to set `HSA_OVERRIDE_GFX_VERSION` environment variable.
Default this repo sets is `HSA_OVERRIDE_GFX_VERSION=10.3.0` which is reported as ok for RDNA2 cards, but you may need a different string.

other than that, not much i can do.

**Comment by cyatarow** [comment]
I tried `export HSA_OVERRIDE_GFX_VERSION="9.0.0"` and was able to enter the WebUI.
However, I got a different error and cannot generate an image.

```
Create and activate python venv
Launching launch.py...
08:45:20-512024 INFO     Starting SD.Next                                                                                       
08:45:20-522935 INFO     Python 3.10.6 on Linux                                                                                 
08:45:20-537096 INFO     Version: a6522709 Sat May 13 12:26:00 2023 -0400                                                       
08:45:21-099703 INFO     Latest published version: 926b8666cdfca5f7ee3bbb3fb216b5eee5326d22 2023-05-13T20:42:01Z                
08:45:21-103294 INFO     Setting environment tuning                                                                             
08:45:21-106432 INFO     AMD ROCm toolkit detected                                                                              
08:45:22-007027 INFO     Torch 2.0.0+rocm5.4.2                                                                                  
08:45:22-442535 INFO     Torch backend: AMD ROCm HIP 5.4.22803-474e8620                                                         
08:45:22-443662 INFO     Torch detected GPU: AMD Radeon RX 5500 XT VRAM 8176 Arch (9, 0) Cores 22                               
08:45:22-444654 INFO     Verifying requirements                                                                                 
08:45:23-480080 INFO     No changes detected: Quick launch active                                                               
08:45:23-481123 INFO     Running extension preloading                                                                           
08:45:23-481700 INFO     Server arguments: []                                                                                   
No module 'xformers'. Proceeding without it.
08:45:28-263037 INFO     Libraries loaded                                                                                       
08:45:28-267730 INFO     Available models: /home/sd-amd/automatic/models/Stable-diffusion 1                                     
ControlNet v1.1.159
ControlNet v1.1.159
Image Browser: ImageReward is not installed, cannot be used.
08:45:29-453713 INFO     Loading UI theme: black-orange                                                                         
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
08:46:17-771882 INFO     Local URL: http://127.0.0.1:7860/                                                                      
08:46:17-773633 INFO     API Docs: http://127.0.0.1:7860/docs                                                                   
08:46:17-775252 INFO     Initializing middleware                                                                                
[W Module.cpp:1149] Warning: cuDNN Benchmark limit is not supported in MIOpen and will have no effect. (function operator())
```

After entering the WebUI:
```
08:47:46-547615 WARNING  Model not loaded                                                                                       
08:47:46-713656 WARNING  No result returned from function                                                                       
Traceback (most recent call last):
  File "/home/sd-amd/automatic/venv/lib/python3.10/site-packages/gradio/routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/sd-amd/automatic/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "/home/sd-amd/automatic/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/sd-amd/automatic/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/sd-amd/automatic/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/sd-amd/automatic/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/sd-amd/automatic/modules/call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "/home/sd-amd/automatic/modules/ui.py", line 211, in update_token_counter
    token_count, max_length = max([model_hijack.get_prompt_lengths(prompt) for prompt in prompts], key=lambda args: args[0])
  File "/home/sd-amd/automatic/modules/ui.py", line 211, in <listcomp>
    token_count, max_length = max([model_hijack.get_prompt_lengths(prompt) for prompt in prompts], key=lambda args: args[0])
  File "/home/sd-amd/automatic/modules/sd_hijack.py", line 240, in get_prompt_lengths
    _, token_count = self.clip.process_texts([text])
AttributeError: 'NoneType' object has no attribute 'process_texts'
```

**Comment by vladmandic** [comment]
that seems like you have the wrong clip package.
can you do:

> venv\Scripts\activate
> pip show clip

**Comment by cyatarow** [comment]
Here is the result of `source venv/bin/activate` -> `pip show clip`.

```
Name: clip
Version: 1.0
Summary: UNKNOWN
Home-page: UNKNOWN
Author: OpenAI
Author-email: 
License: UNKNOWN
Location: /home/sd-amd/automatic/venv/lib/python3.10/site-packages
Requires: ftfy, regex, torch, torchvision, tqdm
Required-by:
```

**Comment by vladmandic** [comment]
actually, just saw this:
> 08:47:46-547615 WARNING  Model not loaded                                                                                       
> 08:47:46-713656 WARNING  No result returned from function  

you're trying to use generate before model has completed loading.
ui is not going to work until `Model load finished` is printed on console.

**Comment by cyatarow** [comment]
> ui is not going to work until Model load finished is printed on console.
When will it show up? I waited for several minutes but it didn't.

**Comment by vladmandic** [comment]
depends on what's your storage. if this is the first time model is loaded, then its most likely calculating its hash.
on my system, thats ~30sec.

you can run `webui --debug` so it will show more information in the console log.

for example, this is starting from your last line (`Initializing middleware`):
```log
11:31:20-360935 INFO     Initializing middleware
11:31:20-397672 DEBUG    Load model: info=False dict=False
11:31:20-479790 DEBUG    Torch FP16 test passed
11:31:20-480510 DEBUG    Desired Torch parameters: dtype=FP16 no-half=False no-half-vae=False upscast=False
11:31:20-481163 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
Loading weights: models/v1-5-pruned-emaonly.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/4.3 GB -:--:--
11:31:20-593392 DEBUG    Model dict loaded: {'ram': {'used': 1.56, 'total': 27.41}, 'gpu': {'used': 1.02, 'total': 12.0}, 'retries': 0, 'oom': 0}
11:31:20-600574 DEBUG    Model config loaded: {'ram': {'used': 1.56, 'total': 27.41}, 'gpu': {'used': 1.02, 'total': 12.0}, 'retries': 0, 'oom': 0}
11:31:20-601336 DEBUG    Model config: {'linear_start': 0.00085, 'linear_end': 0.012, 'num_timesteps_cond': 1, 'log_every_t': 200, 'timesteps': 1000, 'first_stage_key': 'jpg', 'cond_stage_key': 'txt', 'image_size': 64, 'channels': 4, 'cond_stage_trainable': False, 'conditioning_key': 'crossattn', 'monitor': 'val/loss_simple_ema',
                         'scale_factor': 0.18215, 'use_ema': False, 'scheduler_config': {'target': 'ldm.lr_scheduler.LambdaLinearScheduler', 'params': {'warm_up_steps': [10000], 'cycle_lengths': [10000000000000], 'f_start': [1e-06], 'f_max': [1.0], 'f_min': [1.0]}}, 'unet_config': {'target':
                         'ldm.modules.diffusionmodules.openaimodel.UNetModel', 'params': {'image_size': 32, 'in_channels': 4, 'out_channels': 4, 'model_channels': 320, 'attention_resolutions': [4, 2, 1], 'num_res_blocks': 2, 'channel_mult': [1, 2, 4, 4], 'num_heads': 8, 'use_spatial_transformer': True, 'transformer_depth': 1,
                         'context_dim': 768, 'use_checkpoint': True, 'legacy': False}}, 'first_stage_config': {'target': 'ldm.models.autoencoder.AutoencoderKL', 'params': {'embed_dim': 4, 'monitor': 'val/rec_loss', 'ddconfig': {'double_z': True, 'z_channels': 4, 'resolution': 256, 'in_channels': 3, 'out_ch': 3, 'ch': 128, 'ch_mult': [1,
                         2, 4, 4], 'num_res_blocks': 2, 'attn_resolutions': [], 'dropout': 0.0}, 'lossconfig': {'target': 'torch.nn.Identity'}}}, 'cond_stage_config': {'target': 'ldm.modules.encoders.modules.FrozenCLIPEmbedder'}}
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
11:31:20-847945 INFO     Model created from config: /home/vlado/dev/automatic/configs/v1-inference.yaml
11:31:20-849066 DEBUG    Model weights loading: {'ram': {'used': 2.56, 'total': 27.41}, 'gpu': {'used': 1.02, 'total': 12.0}, 'retries': 0, 'oom': 0}
11:31:21-522678 DEBUG    Model weights loaded: {'ram': {'used': 8.3, 'total': 27.41}, 'gpu': {'used': 1.02, 'total': 12.0}, 'retries': 0, 'oom': 0}
11:31:21-827457 DEBUG    Model weights moved: {'ram': {'used': 7.8, 'total': 27.41}, 'gpu': {'used': 3.05, 'total': 12.0}, 'retries': 0, 'oom': 0}
11:31:21-831654 INFO     Applying scaled dot product cross attention optimization
11:31:21-851329 INFO     Embeddings loaded: 6 ['badprompts', 'charturner', 'easynegative', 'planit', 'ti-mia', 'ti-vlado']
11:31:21-854908 INFO     Model loaded in 1.5s (load=0.2s create=0.2s apply=0.5s vae=0.2s move=0.3s)
11:31:21-855870 INFO     Model load finished: {'ram': {'used': 7.81, 'total': 27.41}, 'gpu': {'used': 3.05, 'total': 12.0}, 'retries': 0, 'oom': 0}
11:31:21-888815 DEBUG    Reload model weights skip
11:31:21-889765 INFO     Startup time: 17.8s (torch=2.4s gradio=0.9s libraries=0.2s models=2.6s codeformer=0.1s scripts=1.5s vae=0.1s opts onchange=0.1s ui=6.3s start=2.2s checkpoint=1.5s)
11:31:21-890674 INFO     Memory used: 3.84 total: 27.41
11:31:29-899961 DEBUG    Server alive: True Memory used: 3.84 total: 27.41
```

**Comment by cyatarow** [comment]
```
00:35:57-235516 INFO     Initializing middleware                                                                                
00:35:57-550458 DEBUG    gc: {'ram': {'used': 1.24, 'total': 23.17}, 'gpu': {'used': 0.0, 'total': 7.98}, 'retries': 0, 'oom':  
                         0}                                                                                                     
00:35:57-551413 DEBUG    Load model: info=False dict=False                                                                      
[W Module.cpp:1149] Warning: cuDNN Benchmark limit is not supported in MIOpen and will have no effect. (function operator())
```
New lines won't appear from this line.

**Comment by vladmandic** [comment]
thats hanging before even starting to load model.
i've added extra debug messages, if you can update the repo and retry?

**Comment by vladmandic** [comment]
that's hanging even before model load.
i've added extra debug messages and one change, can you try to update the repo and retry?

**Comment by cyatarow** [comment]
```
01:56:42-548106 INFO     Initializing middleware                                                
01:56:42-868613 DEBUG    gc: {'ram': {'used': 1.26, 'total': 23.17}, 'gpu': {'used': 0.0,       
                         'total': 7.98}, 'retries': 0, 'oom': 0}                                
01:56:42-869547 DEBUG    Load model: info=False dict=False                                      
01:56:42-870098 WARNING  Default checkpoint not found: model.ckpt                               
01:56:42-870539 WARNING  Loading fallback checkpoint: v1-5-pruned-emaonly.safetensors           
01:56:42-871049 DEBUG    Select checkpoint: v1-5-pruned-emaonly.safetensors                     
01:56:42-871521 DEBUG    Verifying Torch settings  
```

After updating, the debug message has changed, but new lines STILL won't appear.

**Comment by vladmandic** [comment]
its hanging running a trivial torch operation to determine which settings can be used. it appears that rocm may be loading now without errors, but its even worse - its completely hanging. so `HSA_OVERRIDE_GFX_VERSION=9.0.0` is baaad.

**Comment by cyatarow** [comment]
Actually, I deleted and reinstalled the repo, so `HSA_OVERRIDE_GFX_VERSION=9.0.0` is not set.
However, I encountered this hanging issue.

Maybe my ubuntu environment is broken?

**Comment by cyatarow** [comment]
By the way, AUTOMATIC1111's WebUI also switched to torch 2.0.0 this month, but AMD GPUs were excluded.
Could this have something to do with my issue?

**Comment by vladmandic** [comment]
no, this is not about ubuntu broken, this is clearly about rocm. unfortunately, not much i can do since i don't have that gpu.
and no, a1111 changes are separate.

**Comment by cyatarow** [comment]
I got it.
A1111's WebUI works fine with my RX 5500 XT, so maybe your repo is not compatible with RX 5000 series.
Thank you for your support.

**Comment by vladmandic** [comment]
which steps you do to use your card on a1111?
a1111 does not install torch+rocm by default at all, it has to be done manually.

if you tell me which steps you do there, i can perhaps make it work here.

**Comment by cyatarow** [comment]
A1111 can install torch+rocm automatically, so you don't need to do the manual install.
See -> https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs#automatic-installation

**Comment by vladmandic** [comment]
that's not automatic, you just sent me a link to MANUAL step - exactly what I asked.
> TORCH_COMMAND='pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/rocm5.1.1' python launch.py --precision full --no-half

you can try that here as well.

remove existing torch:
> pip uninstall torch torchvision

specify which torch you want to use (not there is no pip install at the beginning of line):
> TORCH_COMMAND='torch torchvision --extra-index-url https://download.pytorch.org/whl/rocm5.1.1' python launch.py --precision full --no-half
> webui

btw, that is really OLD rocm 5.1.1 - yes, maybe that works with your GPU. clearly newer 5.4.2 that I recommend doesn't.

**Comment by cyatarow** [comment]
> (As of [1/15/23](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/6709) you can just run webui-user.sh and pytorch+rocm should be automatically installed for you.)
> 1. Install Python 3.10.6
> 2. git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
> 3. Place stable diffusion checkpoint (model.ckpt) in the models/Stable-diffusion directory
> 4. For many AMD gpus you MUST Add --precision full --no-half to COMMANDLINE_ARGS= in webui-user.sh to avoid black squares or crashing.*
> 5. Run webui.sh
> 
> *Certain cards like the Radeon RX 6000 Series and the RX 500 Series will function normally without the option --precision full --no-half, saving plenty of vram. (noted [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5468).)

Isn't this instruction automatic?

**Comment by vladmandic** [comment]
if you have to set env variable TORCH_COMMAND to specific torch version manually and add command flags in order to work, no i don't consider that automatic anymore. but that's nitpicking - i asked what are the steps and you provided info. now you can try equivalent here.

the major difference is that A1111 is still recommending ROCm 5.1.1 from 04/2022 while this repo automatically installs ROCm 5.4.2 12/2022 (and I'll upgrade to ROCm 5.5 as soon as its available to support latest AMD GPUs).
should newer ROCm be compatible with older? yes, it should. but ROCm is pretty buggy in general and AMD is not giving it nearly enough attention.

**Comment by cyatarow** [comment]
I'm sorry. The steps to use A1111 I did are as follows:

1. `git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui`
2. Downloaded and placed a model file(.safetensors) in the model directory
3. Just ran webui.sh (in my case, I didn't need to put arguments in `COMMANDLINE_ARGS`)
4. Generated images and got no black squares

**Comment by vladmandic** [comment]
if you did not set `TORCH_COMMAND`, then A1111 installed `torch` for CPU, not for ROCm. so i'm pretty sure that at one point or another you did that. and now its already installed and it works because it was previously done. but can we not argue about that?

if the goal is to get rocm working, i can try to help (and i've provided som info about that). if you want to persuade me how a1111 works, no point.

**Comment by vladmandic** [comment]
yes, arc support was added recently.
i'm primarily devloping on cuda, but several collaborators maintain other code. rocm was community effort, no actual lead, but arc support has an actual maintainer.
